
SELECT ANO_REPASSE_CONVIVENCIA_IDOSO FROM [TB_PROGRAMA_PROJETO_PARCELAS] WHERE ID = 314 AND ANO_REPASSE_CONVIVENCIA_IDOSO = 17
UPDATE [TB_PROGRAMA_PROJETO_PARCELAS] SET ANO_REPASSE_CONVIVENCIA_IDOSO = 2017 WHERE ID = 314 AND ANO_REPASSE_CONVIVENCIA_IDOSO = 17

SELECT ANO_REPASSE_CONVIVENCIA_IDOSO FROM [TB_PROGRAMA_PROJETO_PARCELAS] WHERE ID = 5027 AND ANO_REPASSE_CONVIVENCIA_IDOSO = 13
UPDATE [TB_PROGRAMA_PROJETO_PARCELAS] SET ANO_REPASSE_CONVIVENCIA_IDOSO = 2013 WHERE ID = 5027 AND ANO_REPASSE_CONVIVENCIA_IDOSO = 13

SELECT ANO_REPASSE_CONVIVENCIA_IDOSO FROM [TB_PROGRAMA_PROJETO_PARCELAS] WHERE ID = 132  AND ANO_REPASSE_CONVIVENCIA_IDOSO = 15
UPDATE [TB_PROGRAMA_PROJETO_PARCELAS] SET ANO_REPASSE_CONVIVENCIA_IDOSO = 2015 WHERE ID = 132 AND ANO_REPASSE_CONVIVENCIA_IDOSO = 15

SELECT ANO_REPASSE_CONVIVENCIA_IDOSO FROM [TB_PROGRAMA_PROJETO_PARCELAS] WHERE ID = 4811 AND ANO_REPASSE_CONVIVENCIA_IDOSO = 17
UPDATE [TB_PROGRAMA_PROJETO_PARCELAS] SET ANO_REPASSE_CONVIVENCIA_IDOSO = 2017 WHERE ID = 4811 AND ANO_REPASSE_CONVIVENCIA_IDOSO = 17
