		ALTER TABLE TB_PREFEITURA_EXERCICIO_BLOQUEIO_DESBLOQUEIO NOCHECK CONSTRAINT FK_TB_PREFEITURA_EXERCICIO_BLOQUEIO_DESBLOQUEIO_TB_REF_RECURSO
		IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'TB_PREFEITURA_EXERCICIO_BLOQUEIO_DESBLOQUEIO')
		BEGIN
	
			--###############################--###############################--###############################--###############################
			-- Bloco III REDE DIRETA Reprogramacao 
			--############################### TB_RECURSO
			IF NOT EXISTS(SELECT 1 FROM TB_PREFEITURA_EXERCICIO_BLOQUEIO_DESBLOQUEIO	WHERE EXERCICIO = 2018 AND ID_REF_BLOQUEIO = 1019) -- Bloco III REDE DIRETA Reprogramacao
			BEGIN
				INSERT INTO [dbo].[TB_PREFEITURA_EXERCICIO_BLOQUEIO_DESBLOQUEIO]
						   ([ID_PREFEITURA]
						   ,[EXERCICIO]
						   ,[DESBLOQUEADO]
						   ,[ID_REF_BLOQUEIO])
				SELECT 
				PREF.ID as ID_PREFEITURA
				, 2018 as EXERCICIO
				, 0 as DESBLOQUEADO 
				, 1019 as ID_REF_BLOQUEIO -- Bloco III REDE DIRETA Reprogramacao 2018
				FROM TB_PREFEITURA PREF
			END

			IF NOT EXISTS(SELECT 1 FROM TB_PREFEITURA_EXERCICIO_BLOQUEIO_DESBLOQUEIO	WHERE EXERCICIO = 2019 AND ID_REF_BLOQUEIO = 1019)
			BEGIN
				INSERT INTO [dbo].[TB_PREFEITURA_EXERCICIO_BLOQUEIO_DESBLOQUEIO]
						   ([ID_PREFEITURA]
						   ,[EXERCICIO]
						   ,[DESBLOQUEADO]
						   ,[ID_REF_BLOQUEIO])
				SELECT 
				PREF.ID as ID_PREFEITURA
				, 2019 as EXERCICIO
				, 1 as DESBLOQUEADO 
				, 1019 as ID_REF_BLOQUEIO -- Bloco III REDE DIRETA Reprogramacao 2019
				FROM TB_PREFEITURA PREF
			END
		END

		IF EXISTS (SELECT 1 FROM sys.tables WHERE name = 'TB_PREFEITURA_EXERCICIO_BLOQUEIO_DESBLOQUEIO')
		BEGIN
	
			--###############################--###############################--###############################--###############################
			-- Bloco III REDE INDIRETA Reprogramacao 
			--############################### TB_RECURSO
			IF NOT EXISTS(SELECT 1 FROM TB_PREFEITURA_EXERCICIO_BLOQUEIO_DESBLOQUEIO	WHERE EXERCICIO = 2018 AND ID_REF_BLOQUEIO = 1020) -- Bloco III REDE INDIRETA Reprogramacao 2018
			BEGIN
				INSERT INTO [dbo].[TB_PREFEITURA_EXERCICIO_BLOQUEIO_DESBLOQUEIO]
						   ([ID_PREFEITURA]
						   ,[EXERCICIO]
						   ,[DESBLOQUEADO]
						   ,[ID_REF_BLOQUEIO])
				SELECT 
				PREF.ID as ID_PREFEITURA
				, 2018 as EXERCICIO
				, 0 as DESBLOQUEADO 
				, 1020 as ID_REF_BLOQUEIO -- Bloco III REDE INDIRETA Reprogramacao 2018
				FROM TB_PREFEITURA PREF
			END

			IF NOT EXISTS(SELECT 1 FROM TB_PREFEITURA_EXERCICIO_BLOQUEIO_DESBLOQUEIO	WHERE EXERCICIO = 2019 AND ID_REF_BLOQUEIO = 1020)
			BEGIN
				INSERT INTO [dbo].[TB_PREFEITURA_EXERCICIO_BLOQUEIO_DESBLOQUEIO]
						   ([ID_PREFEITURA]
						   ,[EXERCICIO]
						   ,[DESBLOQUEADO]
						   ,[ID_REF_BLOQUEIO])
				SELECT 
				PREF.ID as ID_PREFEITURA
				, 2019 as EXERCICIO
				, 1 as DESBLOQUEADO 
				, 1020 as ID_REF_BLOQUEIO -- Bloco III REDE INDIRETA Reprogramacao 2019
				FROM TB_PREFEITURA PREF
			END
		END

		
SELECT ANO_REPASSE_CONVIVENCIA_IDOSO FROM [TB_PROGRAMA_PROJETO_PARCELAS] WHERE ID = 314 AND ANO_REPASSE_CONVIVENCIA_IDOSO = 17
UPDATE [TB_PROGRAMA_PROJETO_PARCELAS] SET ANO_REPASSE_CONVIVENCIA_IDOSO = 2017 WHERE ID = 314 AND ANO_REPASSE_CONVIVENCIA_IDOSO = 17

SELECT ANO_REPASSE_CONVIVENCIA_IDOSO FROM [TB_PROGRAMA_PROJETO_PARCELAS] WHERE ID = 5027 AND ANO_REPASSE_CONVIVENCIA_IDOSO = 13
UPDATE [TB_PROGRAMA_PROJETO_PARCELAS] SET ANO_REPASSE_CONVIVENCIA_IDOSO = 2013 WHERE ID = 5027 AND ANO_REPASSE_CONVIVENCIA_IDOSO = 13

SELECT ANO_REPASSE_CONVIVENCIA_IDOSO FROM [TB_PROGRAMA_PROJETO_PARCELAS] WHERE ID = 132  AND ANO_REPASSE_CONVIVENCIA_IDOSO = 15
UPDATE [TB_PROGRAMA_PROJETO_PARCELAS] SET ANO_REPASSE_CONVIVENCIA_IDOSO = 2015 WHERE ID = 132 AND ANO_REPASSE_CONVIVENCIA_IDOSO = 15

SELECT ANO_REPASSE_CONVIVENCIA_IDOSO FROM [TB_PROGRAMA_PROJETO_PARCELAS] WHERE ID = 4811 AND ANO_REPASSE_CONVIVENCIA_IDOSO = 17
UPDATE [TB_PROGRAMA_PROJETO_PARCELAS] SET ANO_REPASSE_CONVIVENCIA_IDOSO = 2017 WHERE ID = 4811 AND ANO_REPASSE_CONVIVENCIA_IDOSO = 17
