IF(COL_LENGTH('TB_PREFEITURA_SITUACAO_QUADRO', 'EXERCICIO') IS NULL)
	BEGIN
		ALTER TABLE TB_PREFEITURA_SITUACAO_QUADRO ADD EXERCICIO int null
		EXEC('UPDATE TB_PREFEITURA_SITUACAO_QUADRO SET EXERCICIO = 2018')
		EXEC(
			'INSERT INTO TB_PREFEITURA_SITUACAO_QUADRO 
			(
				  ID_PREFEITURA
				, ID_SITUACAO_QUADRO
				, ID_RECURSO
				, EXERCICIO
			)
			SELECT 
				  ID_PREFEITURA
				, ID_SITUACAO_QUADRO
				, ID_RECURSO
				, 2019
			FROM TB_PREFEITURA_SITUACAO_QUADRO'
		)
	END
GO

