//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seds.PMAS.QUADRIENAL.UI.Web {
    
    
    public partial class VHistorico {
        
        /// <summary>
        /// pnlConsulta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel pnlConsulta;
        
        /// <summary>
        /// lblData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblData;
        
        /// <summary>
        /// lblSituacao control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSituacao;
        
        /// <summary>
        /// lblResponsavel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblResponsavel;
        
        /// <summary>
        /// trParecerDrads control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl trParecerDrads;
        
        /// <summary>
        /// lblParecerDrads control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblParecerDrads;
        
        /// <summary>
        /// lblTituloTipoParecer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTituloTipoParecer;
        
        /// <summary>
        /// lblDescricao control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDescricao;
        
        /// <summary>
        /// trValoresCofinanciamento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow trValoresCofinanciamento;
        
        /// <summary>
        /// lblProtecaoSocialBasica control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialBasica;
        
        /// <summary>
        /// lblProtecaoSocialBasicaReprogramado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialBasicaReprogramado;
        
        /// <summary>
        /// lblProtecaoSocialBasicaDemandas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialBasicaDemandas;
        
        /// <summary>
        /// lblProtecaoSocialBasicaReprogramadoDemandas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialBasicaReprogramadoDemandas;
        
        /// <summary>
        /// lblTotalProtecaoSocialBasica control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalProtecaoSocialBasica;
        
        /// <summary>
        /// lblProtecaoSocialEspecial control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialEspecial;
        
        /// <summary>
        /// lblProtecaoSocialEspecialReprogramado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialEspecialReprogramado;
        
        /// <summary>
        /// lblProtecaoSocialEspecialDemandas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialEspecialDemandas;
        
        /// <summary>
        /// lblProtecaoSocialEspecialReprogramadoDemandas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialEspecialReprogramadoDemandas;
        
        /// <summary>
        /// lblTotalProtecaoSocialEspecial control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalProtecaoSocialEspecial;
        
        /// <summary>
        /// lblLiberdadeAssistida control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLiberdadeAssistida;
        
        /// <summary>
        /// lblLiberdadeAssistidaReprogramado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLiberdadeAssistidaReprogramado;
        
        /// <summary>
        /// lblLiberdadeAssistidaDemandas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLiberdadeAssistidaDemandas;
        
        /// <summary>
        /// lblLiberdadeAssistidaReprogramadoDemandas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLiberdadeAssistidaReprogramadoDemandas;
        
        /// <summary>
        /// lblTotalLiberdadeAssistida control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalLiberdadeAssistida;
        
        /// <summary>
        /// lblCREAS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCREAS;
        
        /// <summary>
        /// lblCREASReprogramado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCREASReprogramado;
        
        /// <summary>
        /// lblCREASDemandas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCREASDemandas;
        
        /// <summary>
        /// lblCREASReprogramadoDemandas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCREASReprogramadoDemandas;
        
        /// <summary>
        /// lblTotalCREAS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalCREAS;
        
        /// <summary>
        /// lblSaoPauloSolidario control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSaoPauloSolidario;
        
        /// <summary>
        /// lblSaoPauloSolidarioReprogramado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSaoPauloSolidarioReprogramado;
        
        /// <summary>
        /// lblSaoPauloSolidarioDemandas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSaoPauloSolidarioDemandas;
        
        /// <summary>
        /// lblSaoPauloSolidarioReprogramadoDemandas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSaoPauloSolidarioReprogramadoDemandas;
        
        /// <summary>
        /// lblTotalSaoPauloSolidario control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalSaoPauloSolidario;
        
        /// <summary>
        /// lblTotalCofinanciamento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalCofinanciamento;
        
        /// <summary>
        /// lblTotalReprogramacao control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalReprogramacao;
        
        /// <summary>
        /// lblTotalDemandas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalDemandas;
        
        /// <summary>
        /// lblTotalReprogramadoDemandas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalReprogramadoDemandas;
        
        /// <summary>
        /// lblTotalRecursos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalRecursos;
        
        /// <summary>
        /// trValoresCofinanciamentoExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow trValoresCofinanciamentoExercicio2;
        
        /// <summary>
        /// lblProtecaoSocialBasicaExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialBasicaExercicio2;
        
        /// <summary>
        /// lblProtecaoSocialBasicaReprogramadoExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialBasicaReprogramadoExercicio2;
        
        /// <summary>
        /// lblProtecaoSocialBasicaDemandasExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialBasicaDemandasExercicio2;
        
        /// <summary>
        /// lblProtecaoSocialBasicaReprogramadoDemandasExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialBasicaReprogramadoDemandasExercicio2;
        
        /// <summary>
        /// lblTotalProtecaoSocialBasicaExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalProtecaoSocialBasicaExercicio2;
        
        /// <summary>
        /// lblProtecaoSocialEspecialExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialEspecialExercicio2;
        
        /// <summary>
        /// lblProtecaoSocialEspecialReprogramadoExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialEspecialReprogramadoExercicio2;
        
        /// <summary>
        /// lblProtecaoSocialEspecialDemandasExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialEspecialDemandasExercicio2;
        
        /// <summary>
        /// lblProtecaoSocialEspecialReprogramadoDemandasExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialEspecialReprogramadoDemandasExercicio2;
        
        /// <summary>
        /// lblTotalProtecaoSocialEspecialExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalProtecaoSocialEspecialExercicio2;
        
        /// <summary>
        /// lblLiberdadeAssistidaExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLiberdadeAssistidaExercicio2;
        
        /// <summary>
        /// lblLiberdadeAssistidaReprogramadoExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLiberdadeAssistidaReprogramadoExercicio2;
        
        /// <summary>
        /// lblLiberdadeAssistidaDemandasExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLiberdadeAssistidaDemandasExercicio2;
        
        /// <summary>
        /// lblLiberdadeAssistidaReprogramadoDemandasExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLiberdadeAssistidaReprogramadoDemandasExercicio2;
        
        /// <summary>
        /// lblTotalLiberdadeAssistidaExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalLiberdadeAssistidaExercicio2;
        
        /// <summary>
        /// lblCREASExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCREASExercicio2;
        
        /// <summary>
        /// lblCREASReprogramadoExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCREASReprogramadoExercicio2;
        
        /// <summary>
        /// lblCREASDemandasExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCREASDemandasExercicio2;
        
        /// <summary>
        /// lblCREASReprogramadoDemandasExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCREASReprogramadoDemandasExercicio2;
        
        /// <summary>
        /// lblTotalCREASExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalCREASExercicio2;
        
        /// <summary>
        /// lblSaoPauloSolidarioExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSaoPauloSolidarioExercicio2;
        
        /// <summary>
        /// lblSaoPauloSolidarioReprogramadoExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSaoPauloSolidarioReprogramadoExercicio2;
        
        /// <summary>
        /// lblSaoPauloSolidarioDemandasExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSaoPauloSolidarioDemandasExercicio2;
        
        /// <summary>
        /// lblSaoPauloSolidarioReprogramadoDemandasExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSaoPauloSolidarioReprogramadoDemandasExercicio2;
        
        /// <summary>
        /// lblTotalSaoPauloSolidarioExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalSaoPauloSolidarioExercicio2;
        
        /// <summary>
        /// lblTotalCofinanciamentoExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalCofinanciamentoExercicio2;
        
        /// <summary>
        /// lblTotalReprogramacaoExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalReprogramacaoExercicio2;
        
        /// <summary>
        /// lblTotalDemandasExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalDemandasExercicio2;
        
        /// <summary>
        /// lblTotalReprogramadoDemandasExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalReprogramadoDemandasExercicio2;
        
        /// <summary>
        /// lblTotalRecursosExercicio2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalRecursosExercicio2;
        
        /// <summary>
        /// trValoresCofinanciamentoExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow trValoresCofinanciamentoExercicio3;
        
        /// <summary>
        /// lblProtecaoSocialBasicaExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialBasicaExercicio3;
        
        /// <summary>
        /// lblProtecaoSocialBasicaReprogramadoExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialBasicaReprogramadoExercicio3;
        
        /// <summary>
        /// lblProtecaoSocialBasicaDemandasExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialBasicaDemandasExercicio3;
        
        /// <summary>
        /// lblProtecaoSocialBasicaReprogramadoDemandasExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialBasicaReprogramadoDemandasExercicio3;
        
        /// <summary>
        /// lblTotalProtecaoSocialBasicaExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalProtecaoSocialBasicaExercicio3;
        
        /// <summary>
        /// lblProtecaoSocialEspecialExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialEspecialExercicio3;
        
        /// <summary>
        /// lblProtecaoSocialEspecialReprogramadoExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialEspecialReprogramadoExercicio3;
        
        /// <summary>
        /// lblProtecaoSocialEspecialDemandasExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialEspecialDemandasExercicio3;
        
        /// <summary>
        /// lblProtecaoSocialEspecialReprogramadoDemandasExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialEspecialReprogramadoDemandasExercicio3;
        
        /// <summary>
        /// lblTotalProtecaoSocialEspecialExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalProtecaoSocialEspecialExercicio3;
        
        /// <summary>
        /// lblLiberdadeAssistidaExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLiberdadeAssistidaExercicio3;
        
        /// <summary>
        /// lblLiberdadeAssistidaReprogramadoExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLiberdadeAssistidaReprogramadoExercicio3;
        
        /// <summary>
        /// lblLiberdadeAssistidaDemandasExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLiberdadeAssistidaDemandasExercicio3;
        
        /// <summary>
        /// lblLiberdadeAssistidaReprogramadoDemandasExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLiberdadeAssistidaReprogramadoDemandasExercicio3;
        
        /// <summary>
        /// lblTotalLiberdadeAssistidaExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalLiberdadeAssistidaExercicio3;
        
        /// <summary>
        /// lblCREASExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCREASExercicio3;
        
        /// <summary>
        /// lblCREASReprogramadoExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCREASReprogramadoExercicio3;
        
        /// <summary>
        /// lblCREASDemandasExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCREASDemandasExercicio3;
        
        /// <summary>
        /// lblCREASReprogramadoDemandasExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCREASReprogramadoDemandasExercicio3;
        
        /// <summary>
        /// lblTotalCREASExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalCREASExercicio3;
        
        /// <summary>
        /// lblSaoPauloSolidarioExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSaoPauloSolidarioExercicio3;
        
        /// <summary>
        /// lblSaoPauloSolidarioReprogramadoExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSaoPauloSolidarioReprogramadoExercicio3;
        
        /// <summary>
        /// lblSaoPauloSolidarioDemandasExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSaoPauloSolidarioDemandasExercicio3;
        
        /// <summary>
        /// lblSaoPauloSolidarioReprogramadoDemandasExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSaoPauloSolidarioReprogramadoDemandasExercicio3;
        
        /// <summary>
        /// lblTotalSaoPauloSolidarioExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalSaoPauloSolidarioExercicio3;
        
        /// <summary>
        /// lblTotalCofinanciamentoExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalCofinanciamentoExercicio3;
        
        /// <summary>
        /// lblTotalReprogramacaoExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalReprogramacaoExercicio3;
        
        /// <summary>
        /// lblTotalDemandasExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalDemandasExercicio3;
        
        /// <summary>
        /// lblTotalReprogramadoDemandasExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalReprogramadoDemandasExercicio3;
        
        /// <summary>
        /// lblTotalRecursosExercicio3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalRecursosExercicio3;
        
        /// <summary>
        /// trValoresCofinanciamentoExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow trValoresCofinanciamentoExercicio4;
        
        /// <summary>
        /// lblProtecaoSocialBasicaExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialBasicaExercicio4;
        
        /// <summary>
        /// lblProtecaoSocialBasicaReprogramadoExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialBasicaReprogramadoExercicio4;
        
        /// <summary>
        /// lblProtecaoSocialBasicaDemandasExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialBasicaDemandasExercicio4;
        
        /// <summary>
        /// lblProtecaoSocialBasicaReprogramadoDemandasExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialBasicaReprogramadoDemandasExercicio4;
        
        /// <summary>
        /// lblTotalProtecaoSocialBasicaExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalProtecaoSocialBasicaExercicio4;
        
        /// <summary>
        /// lblProtecaoSocialEspecialExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialEspecialExercicio4;
        
        /// <summary>
        /// lblProtecaoSocialEspecialReprogramadoExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialEspecialReprogramadoExercicio4;
        
        /// <summary>
        /// lblProtecaoSocialEspecialDemandasExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialEspecialDemandasExercicio4;
        
        /// <summary>
        /// lblProtecaoSocialEspecialReprogramadoDemandasExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblProtecaoSocialEspecialReprogramadoDemandasExercicio4;
        
        /// <summary>
        /// lblTotalProtecaoSocialEspecialExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalProtecaoSocialEspecialExercicio4;
        
        /// <summary>
        /// lblLiberdadeAssistidaExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLiberdadeAssistidaExercicio4;
        
        /// <summary>
        /// lblLiberdadeAssistidaReprogramadoExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLiberdadeAssistidaReprogramadoExercicio4;
        
        /// <summary>
        /// lblLiberdadeAssistidaDemandasExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLiberdadeAssistidaDemandasExercicio4;
        
        /// <summary>
        /// lblLiberdadeAssistidaReprogramadoDemandasExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLiberdadeAssistidaReprogramadoDemandasExercicio4;
        
        /// <summary>
        /// lblTotalLiberdadeAssistidaExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalLiberdadeAssistidaExercicio4;
        
        /// <summary>
        /// lblCREASExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCREASExercicio4;
        
        /// <summary>
        /// lblCREASReprogramadoExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCREASReprogramadoExercicio4;
        
        /// <summary>
        /// lblCREASDemandasExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCREASDemandasExercicio4;
        
        /// <summary>
        /// lblCREASReprogramadoDemandasExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCREASReprogramadoDemandasExercicio4;
        
        /// <summary>
        /// lblTotalCREASExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalCREASExercicio4;
        
        /// <summary>
        /// lblSaoPauloSolidarioExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSaoPauloSolidarioExercicio4;
        
        /// <summary>
        /// lblSaoPauloSolidarioReprogramadoExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSaoPauloSolidarioReprogramadoExercicio4;
        
        /// <summary>
        /// lblSaoPauloSolidarioDemandasExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSaoPauloSolidarioDemandasExercicio4;
        
        /// <summary>
        /// lblSaoPauloSolidarioReprogramadoDemandasExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSaoPauloSolidarioReprogramadoDemandasExercicio4;
        
        /// <summary>
        /// lblTotalSaoPauloSolidarioExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalSaoPauloSolidarioExercicio4;
        
        /// <summary>
        /// lblTotalCofinanciamentoExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalCofinanciamentoExercicio4;
        
        /// <summary>
        /// lblTotalReprogramacaoExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalReprogramacaoExercicio4;
        
        /// <summary>
        /// lblTotalDemandasExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalDemandasExercicio4;
        
        /// <summary>
        /// lblTotalReprogramadoDemandasExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalReprogramadoDemandasExercicio4;
        
        /// <summary>
        /// lblTotalRecursosExercicio4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalRecursosExercicio4;
        
        /// <summary>
        /// btnVoltar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnVoltar;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Seds.PMAS.QUADRIENAL.UI.Web.SiteMaster Master {
            get {
                return ((Seds.PMAS.QUADRIENAL.UI.Web.SiteMaster)(base.Master));
            }
        }
    }
}
