USE [Dbpmas_quadrienal_PRODUCAO_OUTUBRO_2018]
GO

/****** Object:  StoredProcedure [dbo].[PR_PREVISAO_ORCAMENTARIA]    Script Date: 24/10/2018 18:23:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[PR_PREVISAO_ORCAMENTARIA]
@ID_PREFEITURA  INT 
AS
SELECT P.ID AS ID_TIPO_PROTECAO, 
P.NOME AS PROTECAO_SOCIAL,
COALESCE(SUM(T.REDE_PUBLICA_MUNICIPAL),0) AS REDE_PUBLICA_MUNICIPAL,
COALESCE(SUM(T.REDE_PUBLICA_ESTADUAL),0) AS REDE_PUBLICA_ESTADUAL,
COALESCE(SUM(T.REDE_PUBLICA_FEDERAL),0) AS REDE_PUBLICA_FEDERAL,
COALESCE(SUM(T.REDE_PUBLICA_ESTADUALIZADO),0) AS REDE_PUBLICA_ESTADUALIZADO,
COALESCE(SUM(T.REDE_PRIVADA_MUNICIPAL),0) AS REDE_PRIVADA_MUNICIPAL,
COALESCE(SUM(T.REDE_PRIVADA_ESTADUAL),0) AS REDE_PRIVADA_ESTADUAL,
COALESCE(SUM(T.REDE_PRIVADA_FEDERAL),0) AS REDE_PRIVADA_FEDERAL,
COALESCE(SUM(T.PRIVADO),0) AS PRIVADO,
COALESCE(SUM(T.REDE_PRIVADA_ESTADUALIZADO),0) AS REDE_PRIVADA_ESTADUALIZADO
FROM TB_TIPO_PROTECAO P
LEFT JOIN (
	SELECT T.ID_TIPO_PROTECAO,
	 P.NOME AS PROTECAO_SOCIAL, 
	 SUM(s1.VALOR_MUNICIPAL_ASSISTENCIA + s1.VALOR_MUNICIPAL_FMDCA + s1.VALOR_MUNICIPAL_FMI) AS REDE_PUBLICA_MUNICIPAL, 
	 SUM(s1.VALOR_ESTADUAL_ASSISTENCIA + s1.VALOR_ESTADUAL_FEDCA + s1.VALOR_ESTADUAL_FEI) AS REDE_PUBLICA_ESTADUAL,
	 SUM(s1.VALOR_FEDERAL_ASSISTENCIA + s1.VALOR_FEDERAL_FNDCA + s1.VALOR_FEDERAL_FNI) AS REDE_PUBLICA_FEDERAL,
	 --SUM(s.VALOR_ESTADUALIZADO) AS REDE_PUBLICA_ESTADUALIZADO,
	 0.0 AS REDE_PUBLICA_ESTADUALIZADO,
	 0.0 AS REDE_PRIVADA_MUNICIPAL,
	 0.0 AS REDE_PRIVADA_ESTADUAL,
	 0.0 AS REDE_PRIVADA_FEDERAL,
	 0.0 AS PRIVADO,
	 0.0 AS REDE_PRIVADA_ESTADUALIZADO	 
	 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP S
	 INNER JOIN  TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_CENTRO_POP S1
			ON(S.ID = S1.ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP AND S1.EXERCICIO = 2018)
	 INNER JOIN TB_UNIDADE_PUBLICA UP (NOLOCK) ON (UP.ID_PREFEITURA = @ID_PREFEITURA) --brunov
	 INNER JOIN TB_CENTRO_POP L ON(L.ID = S.ID_CENTRO_POP AND L.ID_UNIDADE_PUBLICA = UP.ID) --brunov
	 --INNER JOIN TB_CENTRO_POP L ON(L.ID = S.ID_CENTRO_POP AND L.ID_PREFEITURA = @ID_PREFEITURA) --original	 
	 INNER JOIN TB_USUARIO_TIPO_SERVICO U ON(U.ID = S.ID_USUARIO_TIPO_SERVICO)
	 INNER JOIN TB_TIPO_SERVICO T ON(T.ID = U.ID_TIPO_SERVICO)
	 INNER JOIN TB_TIPO_PROTECAO P ON(P.ID = T.ID_TIPO_PROTECAO)
	 GROUP BY T.ID_TIPO_PROTECAO,P.NOME 

	 UNION ALL

	 SELECT T.ID_TIPO_PROTECAO,
	 P.NOME AS PROTECAO_SOCIAL, 
	 SUM(S1.VALOR_MUNICIPAL_ASSISTENCIA + S1.VALOR_MUNICIPAL_FMDCA + S1.VALOR_MUNICIPAL_FMI) AS REDE_PUBLICA_MUNICIPAL, 
	 SUM(S1.VALOR_ESTADUAL_ASSISTENCIA + S1.VALOR_ESTADUAL_FEDCA + S1.VALOR_ESTADUAL_FEI) AS REDE_PUBLICA_ESTADUAL,
	 SUM(S1.VALOR_FEDERAL_ASSISTENCIA + S1.VALOR_FEDERAL_FNDCA + S1.VALOR_FEDERAL_FNI) AS REDE_PUBLICA_FEDERAL,
	 --SUM(S.VALOR_ESTADUALIZADO) AS REDE_PUBLICA_ESTADUALIZADO,
	 0.0 AS REDE_PUBLICA_ESTADUALIZADO,
	 0.0 AS REDE_PRIVADA_MUNICIPAL,
	 0.0 AS REDE_PRIVADA_ESTADUAL,
	 0.0 AS REDE_PRIVADA_FEDERAL,
	 0.0 AS PRIVADO,
	 0.0 AS REDE_PRIVADA_ESTADUALIZADO
	 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS S
	 INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_CRAS S1 
		ON(S.ID = S1.ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS AND S1.EXERCICIO = 2018)
	 INNER JOIN TB_UNIDADE_PUBLICA UP (NOLOCK) ON (UP.ID_PREFEITURA = @ID_PREFEITURA) --brunov
	 INNER JOIN TB_CRAS L ON(L.ID = S.ID_CRAS AND L.ID_UNIDADE_PUBLICA = UP.ID) --brunov
	 --INNER JOIN TB_CRAS L ON(L.ID = S.ID_CRAS AND L.ID_PREFEITURA = @ID_PREFEITURA) --original
	 INNER JOIN TB_USUARIO_TIPO_SERVICO U ON(U.ID = S.ID_USUARIO_TIPO_SERVICO)
	 INNER JOIN TB_TIPO_SERVICO T ON(T.ID = U.ID_TIPO_SERVICO)
	 INNER JOIN TB_TIPO_PROTECAO P ON(P.ID = T.ID_TIPO_PROTECAO)
	 GROUP BY T.ID_TIPO_PROTECAO,P.NOME 

	 UNION ALL

	 SELECT T.ID_TIPO_PROTECAO,
	 P.NOME AS PROTECAO_SOCIAL, 
	 SUM(S1.VALOR_MUNICIPAL_ASSISTENCIA + S1.VALOR_MUNICIPAL_FMDCA + S1.VALOR_MUNICIPAL_FMI) AS REDE_PUBLICA_MUNICIPAL, 
	 SUM(S1.VALOR_ESTADUAL_ASSISTENCIA + S1.VALOR_ESTADUAL_FEDCA + S1.VALOR_ESTADUAL_FEI) AS REDE_PUBLICA_ESTADUAL,
	 SUM(S1.VALOR_FEDERAL_ASSISTENCIA + S1.VALOR_FEDERAL_FNDCA + S1.VALOR_FEDERAL_FNI) AS REDE_PUBLICA_FEDERAL,
	 --SUM(S.VALOR_ESTADUALIZADO) AS REDE_PUBLICA_ESTADUALIZADO,
	 0.0 AS REDE_PUBLICA_ESTADUALIZADO,
	 0.0 AS REDE_PRIVADA_MUNICIPAL,
	 0.0 AS REDE_PRIVADA_ESTADUAL,
	 0.0 AS REDE_PRIVADA_FEDERAL,
	 0.0 AS PRIVADO,
	 0.0 AS REDE_PRIVADA_ESTADUALIZADO
	 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS S
	 INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_CREAS S1 
		ON(S.ID = S1.ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS AND S1.EXERCICIO = 2018)
	 INNER JOIN TB_UNIDADE_PUBLICA UP (NOLOCK) ON (UP.ID_PREFEITURA = @ID_PREFEITURA) --brunov
	 INNER JOIN TB_CREAS L ON(L.ID = S.ID_CREAS AND L.ID_UNIDADE_PUBLICA = UP.ID) --brunov
	 --INNER JOIN TB_CREAS L ON(L.ID = S.ID_CREAS AND L.ID_PREFEITURA = @ID_PREFEITURA) --original
	 INNER JOIN TB_USUARIO_TIPO_SERVICO U ON(U.ID = S.ID_USUARIO_TIPO_SERVICO)
	 INNER JOIN TB_TIPO_SERVICO T ON(T.ID = U.ID_TIPO_SERVICO)
	 INNER JOIN TB_TIPO_PROTECAO P ON(P.ID = T.ID_TIPO_PROTECAO)
	 GROUP BY T.ID_TIPO_PROTECAO,P.NOME 
	 
	 UNION ALL

	 SELECT T.ID_TIPO_PROTECAO,
	 P.NOME AS PROTECAO_SOCIAL, 
	 SUM(S1.VALOR_MUNICIPAL_ASSISTENCIA + S1.VALOR_MUNICIPAL_FMDCA + S1.VALOR_MUNICIPAL_FMI) AS REDE_PUBLICA_MUNICIPAL, 
	 SUM(S1.VALOR_ESTADUAL_ASSISTENCIA +  S1.VALOR_ESTADUAL_FEDCA + S1.VALOR_ESTADUAL_FEI) AS REDE_PUBLICA_ESTADUAL,
	 SUM(S1.VALOR_FEDERAL_ASSISTENCIA + S1.VALOR_FEDERAL_FNDCA + VALOR_FEDERAL_FNI) AS REDE_PUBLICA_FEDERAL,
	 --SUM(S.VALOR_ESTADUALIZADO) AS REDE_PUBLICA_ESTADUALIZADO,
	 0.0 AS REDE_PUBLICA_ESTADUALIZADO,
	 0.0 AS REDE_PRIVADA_MUNICIPAL,
	 0.0 AS REDE_PRIVADA_ESTADUAL,
	 0.0 AS REDE_PRIVADA_FEDERAL,
	 0.0 AS PRIVADO,
	 0.0 AS REDE_PRIVADA_ESTADUALIZADO
	 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO S
	 INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_PUBLICO S1 
		ON(S.ID = S1.ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO AND S1.EXERCICIO = 2018)
	 INNER JOIN TB_LOCAL_EXECUCAO_PUBLICO E ON(E.ID = S.ID_LOCAL_EXECUCAO_PUBLICO)
	 INNER JOIN TB_UNIDADE_PUBLICA L ON(L.ID = E.ID_UNIDADE_PUBLICA AND L.ID_PREFEITURA = @ID_PREFEITURA)
	 INNER JOIN TB_USUARIO_TIPO_SERVICO U ON(U.ID = S.ID_USUARIO_TIPO_SERVICO)
	 INNER JOIN TB_TIPO_SERVICO T ON(T.ID = U.ID_TIPO_SERVICO)
	 INNER JOIN TB_TIPO_PROTECAO P ON(P.ID = T.ID_TIPO_PROTECAO)
	 GROUP BY T.ID_TIPO_PROTECAO,P.NOME 
	 
	 UNION ALL

	 SELECT T.ID_TIPO_PROTECAO,
	 P.NOME AS PROTECAO_SOCIAL, 	 
	 0.0 AS REDE_PUBLICA_MUNICIPAL,
	 0.0 AS REDE_PUBLICA_ESTADUAL,
	 0.0 AS REDE_PUBLICA_FEDERAL,
	 0 AS REDE_PUBLICA_ESTADUALIZADO,
	 SUM(S1.VALOR_MUNICIPAL_ASSISTENCIA + S1.VALOR_MUNICIPAL_FMDCA + S1.VALOR_MUNICIPAL_FMI) AS REDE_PRIVADA_MUNICIPAL, 
	 SUM(S1.VALOR_ESTADUAL_ASSISTENCIA + S1.VALOR_ESTADUAL_FEDCA + S1.VALOR_ESTADUAL_FEI) AS REDE_PRIVADA_ESTADUAL,	 
	 SUM(S1.VALOR_FEDERAL_ASSISTENCIA + S1.VALOR_FEDERAL_FNDCA + S1.VALOR_FEDERAL_FNI) AS REDE_PRIVADA_FEDERAL,	 
	 SUM(S1.VALOR_RECURSO_EXCLUSIVO_SERVICO) AS PRIVADO,
	 --SUM(S.VALOR_ESTADUALIZADO) AS REDE_PRIVADA_ESTADUALIZADO
	 SUM(S1.VALOR_ESTADUALIZADO) AS REDE_PRIVADA_ESTADUALIZADO
	 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO S
	 INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_PRIVADO S1 
		ON(S.ID = S1.ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO AND S1.EXERCICIO = 2018)
	 INNER JOIN TB_LOCAL_EXECUCAO_PRIVADO E ON(E.ID = S.ID_LOCAL_EXECUCAO_PRIVADO)
	 INNER JOIN TB_UNIDADE_PRIVADA L ON(L.ID = E.ID_UNIDADE_PRIVADA AND L.ID_PREFEITURA = @ID_PREFEITURA)
	 INNER JOIN TB_USUARIO_TIPO_SERVICO U ON(U.ID = S.ID_USUARIO_TIPO_SERVICO)
	 INNER JOIN TB_TIPO_SERVICO T ON(T.ID = U.ID_TIPO_SERVICO)
	 INNER JOIN TB_TIPO_PROTECAO P ON(P.ID = T.ID_TIPO_PROTECAO)
	 GROUP BY T.ID_TIPO_PROTECAO,P.NOME

	 UNION ALL

	 SELECT 1 AS ID_TIPO_PROTECAO,
	 'Básica' AS PROTECAO_SOCIAL, 	 
	 0.0 AS REDE_PUBLICA_MUNICIPAL,
	 isnull(AP.VALOR_FEAS, 0.0) AS REDE_PUBLICA_ESTADUAL,
	 0.0 AS REDE_PUBLICA_FEDERAL,
	 0 AS REDE_PUBLICA_ESTADUALIZADO,
	 0.0 AS REDE_PRIVADA_MUNICIPAL, 
	 0.0 AS REDE_PRIVADA_ESTADUAL,	 
	 0.0 AS REDE_PRIVADA_FEDERAL,	 
	 0.0 AS PRIVADO,
	 0.0 AS REDE_PRIVADA_ESTADUALIZADO
	 FROM TB_PREFEITURA_ACAO_PLANEJAMENTO AP
	 WHERE AP.ID_PREFEITURA = @ID_PREFEITURA AND AP.ID_ACAO_PLANEJAMENTO = 26
 ) T ON(T.ID_TIPO_PROTECAO = P.ID) WHERE ID_TIPO_PROTECAO NOT IN(4,5)
 GROUP BY P.ID, P.NOME 
 ORDER BY P.ID





GO


