USE [Dbpmas_quadrienal_PRODUCAO_OUTUBRO_2018]
GO

/****** Object:  StoredProcedure [dbo].[PR_INDICE_GESTAO_DESCENTRALIZADA_2016]    Script Date: 14/11/2018 12:43:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [dbo].[PR_INDICE_GESTAO_DESCENTRALIZADA_2016]
@ID_PREFEITURA INT
AS
	SELECT ID,ID_PREFEITURA,IGD_PBF, IGD_PBF_VALOR_MENSAL
	, IGD_SUAS
	, IGD_SUAS_VALOR_MENSAL
	, NULL AS COMENTARIOS_EXECUCAO_FINANCEIRA, NULL 
	AS COMENTARIOS_LEI_ORCAMENTARIA  
	, 2017 as EXERCICIO
	FROM DBPMAS2017.DBO.TB_INDICE_GESTAO_DESCENTRALIZADA 
	WHERE ID_PREFEITURA = @ID_PREFEITURA

GO


