USE [Dbpmas_quadrienal]
GO

ALTER VIEW [dbo].[VW_LOCAIS_EXECUCAO]
AS
SELECT 
P.ID AS ID_PREFEITURA,
M.ID AS ID_MUNICIPIO,
M.ID_DRADS,
M.NOME AS MUNICIPIO,
D.NOME AS DRADS,
COALESCE(M.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
D.ID_MACRO_REGIAO,
P.ID_NIVEL_GESTAO,
(CASE WHEN P.POPULACAO <= 20000 THEN 1
   WHEN   P.POPULACAO <= 50000 THEN 2
   WHEN   P.POPULACAO <= 100000 THEN 3
   WHEN   P.POPULACAO <= 900000 THEN 4
   ELSE 5
END) AS ID_PORTE,
'Rede direta' AS TIPO_UNIDADE,
1 AS ID_TIPO_UNIDADE,
UN.ID AS CODIGO_UNIDADE,
isnull(L.ID_DISTRITOS_SAO_PAULO,0) AS ID_DISTRITOS_SAO_PAULO,
DS.NOME AS DISTRITOS_SAO_PAULO,
UN.RAZAO_SOCIAL AS UNIDADE_RESPONSAVEL,
dbo.FORMATAR_CNPJ(UN.CNPJ) AS CNPJ,
L.ID AS ID_LOCAL,
L.NOME AS LOCAL_EXECUCAO,
L.TECNICO_RESPONSAVEL AS TECNICO_RESPONSAVEL_COORDENADOR,
(RTRIM(L.LOGRADOURO) + ', ' + L.NUMERO + (CASE WHEN L.COMPLEMENTO IS NOT NULL AND L.COMPLEMENTO <> ' ' THEN ' - ' + L.COMPLEMENTO ELSE '' END)) AS ENDERECO,
RTRIM(L.BAIRRO) AS BAIRRO,
dbo.FORMATAR_CEP(L.CEP) AS CEP,
L.CIDADE AS CIDADE,
CASE 
	WHEN L.TELEFONE = '' OR L.TELEFONE IS NULL THEN '' 
	ELSE DBO.FORMATAR_TELEFONE(L.TELEFONE)
	END AS TELEFONE,
CASE
	WHEN L.CELULAR= '' OR L.CELULAR IS NULL THEN ''
	ELSE DBO.FORMATAR_CELULAR(L.CELULAR) 
	END AS CELULAR,
L.EMAIL AS EMAIL,
U.ID_TIPO_SERVICO,
U.ID AS ID_USUARIO_TIPO_SERVICO,
S.ID_TIPO_PROTECAO,
S.NAO_TIPIFICADO,
(CASE WHEN R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL AND  R.DESCRICAO_NAO_TIPIFICADO <> '' AND TP.ID <> 3 AND S.NAO_TIPIFICADO IS NOT NULL  THEN  'Serviço não tipificado - ' + S.NOME + ' - ' + R.DESCRICAO_NAO_TIPIFICADO 
		WHEN TP.ID = 3 AND R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL THEN 'Serviço não tipificado - ' + R.DESCRICAO_NAO_TIPIFICADO 
		WHEN S.NAO_TIPIFICADO IS NOT NULL THEN 'Servico não tipificado - ' + S.NOME 
		ELSE S.NOME END)  AS TIPO_SERVICO
FROM TB_PREFEITURA P
INNER JOIN DBSEDS.DBO.TB_MUNICIPIOS M ON(M.ID = P.ID_MUNICIPIO)
INNER JOIN DBSEDS.DBO.TB_DRADS D ON (D.ID = M.ID_DRADS)
INNER JOIN TB_UNIDADE_PUBLICA UN ON(UN.ID_PREFEITURA = P.ID)
INNER JOIN TB_LOCAL_EXECUCAO_PUBLICO L ON(UN.ID = L.ID_UNIDADE_PUBLICA)
LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO R ON(R.ID_LOCAL_EXECUCAO_PUBLICO = L.ID)
LEFT JOIN TB_USUARIO_TIPO_SERVICO U ON (R.ID_USUARIO_TIPO_SERVICO = U.ID)
LEFT JOIN TB_TIPO_SERVICO AS S ON (U.ID_TIPO_SERVICO = S.ID)
INNER JOIN TB_TIPO_PROTECAO TP ON(TP.ID = S.ID_TIPO_PROTECAO)
LEFT JOIN TB_DISTRITOS_SAO_PAULO DS ON (DS.ID = L.ID_DISTRITOS_SAO_PAULO)
WHERE L.DESATIVADO = 0

UNION ALL

SELECT 
P.ID AS ID_PREFEITURA,
M.ID AS ID_MUNICIPIO,
M.ID_DRADS,
M.NOME AS MUNICIPIO,
D.NOME AS DRADS,
COALESCE(M.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
D.ID_MACRO_REGIAO,
P.ID_NIVEL_GESTAO,
(CASE WHEN P.POPULACAO <= 20000 THEN 1
   WHEN   P.POPULACAO <= 50000 THEN 2
   WHEN   P.POPULACAO <= 100000 THEN 3
   WHEN   P.POPULACAO <= 900000 THEN 4
   ELSE 5
END) AS ID_PORTE,
'Rede indireta' AS TIPO_UNIDADE,
2 AS ID_TIPO_UNIDADE,
UN.ID AS CODIGO_UNIDADE,
isnull(L.ID_DISTRITOS_SAO_PAULO,0) AS ID_DISTRITOS_SAO_PAULO,
DS.NOME AS DISTRITOS_SAO_PAULO,
UN.RAZAO_SOCIAL AS UNIDADE_RESPONSAVEL,
dbo.FORMATAR_CNPJ(UN.CNPJ) AS CNPJ,
L.ID AS ID_LOCAL,
L.NOME AS LOCAL_EXECUCAO,
L.TECNICO_RESPONSAVEL AS TECNICO_RESPONSAVEL_COORDENADOR,
(RTRIM(L.LOGRADOURO) + ', ' + L.NUMERO + (CASE WHEN L.COMPLEMENTO IS NOT NULL AND L.COMPLEMENTO <> ' ' THEN ' - ' + L.COMPLEMENTO ELSE '' END)) AS ENDERECO,
RTRIM(L.BAIRRO) AS BAIRRO,
dbo.FORMATAR_CEP(L.CEP) AS CEP,
L.CIDADE AS CIDADE,
CASE 
	WHEN L.TELEFONE = '' OR L.TELEFONE IS NULL THEN '' 
	ELSE DBO.FORMATAR_TELEFONE(L.TELEFONE)
	END AS TELEFONE,
CASE
	WHEN L.CELULAR= '' OR L.CELULAR IS NULL THEN ''
	ELSE DBO.FORMATAR_CELULAR(L.CELULAR) 
	END AS CELULAR,
L.EMAIL AS EMAIL,
U.ID_TIPO_SERVICO,
U.ID AS ID_USUARIO_TIPO_SERVICO,
S.ID_TIPO_PROTECAO,
S.NAO_TIPIFICADO,
(CASE WHEN R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL AND  R.DESCRICAO_NAO_TIPIFICADO <> '' AND TP.ID <> 3 AND S.NAO_TIPIFICADO IS NOT NULL  THEN  'Serviço não tipificado - ' + S.NOME + ' - ' + R.DESCRICAO_NAO_TIPIFICADO 
		WHEN TP.ID = 3 AND R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL THEN 'Serviço não tipificado - ' + R.DESCRICAO_NAO_TIPIFICADO 
		WHEN S.NAO_TIPIFICADO IS NOT NULL THEN 'Servico não tipificado - ' + S.NOME 
		ELSE S.NOME END)  AS TIPO_SERVICO
FROM TB_PREFEITURA P
INNER JOIN DBSEDS.DBO.TB_MUNICIPIOS M ON(M.ID = P.ID_MUNICIPIO)
INNER JOIN DBSEDS.DBO.TB_DRADS D ON (D.ID = M.ID_DRADS)
INNER JOIN TB_UNIDADE_PRIVADA UN ON(UN.ID_PREFEITURA = P.ID)
INNER JOIN TB_LOCAL_EXECUCAO_PRIVADO L ON(UN.ID = L.ID_UNIDADE_PRIVADA)
LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO R ON(R.ID_LOCAL_EXECUCAO_PRIVADO = L.ID)
LEFT JOIN TB_USUARIO_TIPO_SERVICO U ON (R.ID_USUARIO_TIPO_SERVICO = U.ID)
LEFT JOIN TB_TIPO_SERVICO AS S ON (U.ID_TIPO_SERVICO = S.ID)
INNER JOIN TB_TIPO_PROTECAO TP ON(TP.ID = S.ID_TIPO_PROTECAO)
LEFT JOIN TB_DISTRITOS_SAO_PAULO DS ON (DS.ID = L.ID_DISTRITOS_SAO_PAULO)
WHERE L.DESATIVADO = 0

UNION ALL

SELECT 
P.ID AS ID_PREFEITURA,
M.ID AS ID_MUNICIPIO,
M.ID_DRADS,
M.NOME AS MUNICIPIO,
D.NOME AS DRADS,
COALESCE(M.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
D.ID_MACRO_REGIAO,
P.ID_NIVEL_GESTAO,
(CASE WHEN P.POPULACAO <= 20000 THEN 1
   WHEN   P.POPULACAO <= 50000 THEN 2
   WHEN   P.POPULACAO <= 100000 THEN 3
   WHEN   P.POPULACAO <= 900000 THEN 4
   ELSE 5
END) AS ID_PORTE,
'Rede direta' AS TIPO_UNIDADE,
3 AS ID_TIPO_UNIDADE,
C.ID AS CODIGO_UNIDADE,
isnull(C.ID_DISTRITOS_SAO_PAULO,0) AS ID_DISTRITOS_SAO_PAULO,
DS.NOME AS DISTRITOS_SAO_PAULO,
UP.RAZAO_SOCIAL AS UNIDADE_RESPONSAVEL,
dbo.FORMATAR_CNPJ(UP.CNPJ) AS CNPJ,
C.ID AS ID_LOCAL,
C.NOME AS LOCAL_EXECUCAO,
C.COORDENADOR AS TECNICO_RESPONSAVEL_COORDENADOR,
(RTRIM(C.LOGRADOURO) + ', ' + C.NUMERO + (CASE WHEN C.COMPLEMENTO IS NOT NULL AND C.COMPLEMENTO <> ' ' THEN ' - ' + C.COMPLEMENTO ELSE '' END)) AS ENDERECO,
RTRIM(C.BAIRRO) AS BAIRRO,
dbo.FORMATAR_CEP(C.CEP) AS CEP,
C.CIDADE AS CIDADE,
CASE 
	WHEN C.TELEFONE = '' OR C.TELEFONE IS NULL THEN '' 
	ELSE DBO.FORMATAR_TELEFONE(C.TELEFONE)
	END AS TELEFONE,
CASE
	WHEN C.CELULAR= '' OR C.CELULAR IS NULL THEN ''
	ELSE DBO.FORMATAR_CELULAR(C.CELULAR) 
	END AS CELULAR,
C.EMAIL AS EMAIL,
U.ID_TIPO_SERVICO,
U.ID AS ID_USUARIO_TIPO_SERVICO,
S.ID_TIPO_PROTECAO,
S.NAO_TIPIFICADO,
(CASE WHEN R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL AND  R.DESCRICAO_NAO_TIPIFICADO <> '' AND TP.ID <> 3 AND S.NAO_TIPIFICADO IS NOT NULL  THEN  'Serviço não tipificado - ' + S.NOME + ' - ' + R.DESCRICAO_NAO_TIPIFICADO 
		WHEN TP.ID = 3 AND R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL THEN 'Serviço não tipificado - ' + R.DESCRICAO_NAO_TIPIFICADO 
		WHEN S.NAO_TIPIFICADO IS NOT NULL THEN 'Servico não tipificado - ' + S.NOME 
		ELSE S.NOME END)  AS TIPO_SERVICO
FROM TB_PREFEITURA P
INNER JOIN DBSEDS.DBO.TB_MUNICIPIOS M ON(M.ID = P.ID_MUNICIPIO)
INNER JOIN DBSEDS.DBO.TB_DRADS D ON (D.ID = M.ID_DRADS)
INNER JOIN TB_UNIDADE_PUBLICA UP ON(UP.ID_PREFEITURA = P.ID)
INNER JOIN TB_CRAS C ON(C.ID_UNIDADE_PUBLICA = UP.ID)
LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS R ON(R.ID_CRAS = C.ID)
LEFT JOIN TB_USUARIO_TIPO_SERVICO U ON (R.ID_USUARIO_TIPO_SERVICO = U.ID)
LEFT JOIN TB_TIPO_SERVICO AS S ON (U.ID_TIPO_SERVICO = S.ID)
INNER JOIN TB_TIPO_PROTECAO TP ON(TP.ID = S.ID_TIPO_PROTECAO)
LEFT JOIN TB_DISTRITOS_SAO_PAULO DS ON (DS.ID = C.ID_DISTRITOS_SAO_PAULO)
WHERE C.DESATIVADO = 0


UNION ALL

SELECT 
P.ID AS ID_PREFEITURA,
M.ID AS ID_MUNICIPIO,
M.ID_DRADS,
M.NOME AS MUNICIPIO,
D.NOME AS DRADS,
COALESCE(M.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
D.ID_MACRO_REGIAO,
P.ID_NIVEL_GESTAO,
(CASE WHEN P.POPULACAO <= 20000 THEN 1
   WHEN   P.POPULACAO <= 50000 THEN 2
   WHEN   P.POPULACAO <= 100000 THEN 3
   WHEN   P.POPULACAO <= 900000 THEN 4
   ELSE 5
END) AS ID_PORTE,
'Rede direta' AS TIPO_UNIDADE,
4 AS ID_TIPO_UNIDADE,
C.ID AS CODIGO_UNIDADE,
isnull(C.ID_DISTRITOS_SAO_PAULO,0) AS ID_DISTRITOS_SAO_PAULO,
DS.NOME AS DISTRITOS_SAO_PAULO,
UP.RAZAO_SOCIAL AS UNIDADE_RESPONSAVEL,
dbo.FORMATAR_CNPJ(UP.CNPJ) AS CNPJ,
C.ID AS ID_LOCAL,
C.NOME AS LOCAL_EXECUCAO,
C.COORDENADOR AS TECNICO_RESPONSAVEL_COORDENADOR,
(RTRIM(C.LOGRADOURO) + ', ' + C.NUMERO + (CASE WHEN C.COMPLEMENTO IS NOT NULL AND C.COMPLEMENTO <> ' ' THEN ' - ' + C.COMPLEMENTO ELSE '' END)) AS ENDERECO,
RTRIM(C.BAIRRO) AS BAIRRO,
dbo.FORMATAR_CEP(C.CEP) AS CEP,
C.CIDADE AS CIDADE,
CASE 
	WHEN C.TELEFONE = '' OR C.TELEFONE IS NULL THEN '' 
	ELSE DBO.FORMATAR_TELEFONE(C.TELEFONE)
	END AS TELEFONE,
CASE
	WHEN C.CELULAR= '' OR C.CELULAR IS NULL THEN ''
	ELSE DBO.FORMATAR_CELULAR(C.CELULAR) 
	END AS CELULAR,
C.EMAIL AS EMAIL,
U.ID_TIPO_SERVICO,
U.ID AS ID_USUARIO_TIPO_SERVICO,
S.ID_TIPO_PROTECAO,
S.NAO_TIPIFICADO,
(CASE WHEN R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL AND  R.DESCRICAO_NAO_TIPIFICADO <> '' AND TP.ID <> 3 AND S.NAO_TIPIFICADO IS NOT NULL  THEN  'Serviço não tipificado - ' + S.NOME + ' - ' + R.DESCRICAO_NAO_TIPIFICADO 
		WHEN TP.ID = 3 AND R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL THEN 'Serviço não tipificado - ' + R.DESCRICAO_NAO_TIPIFICADO 
		WHEN S.NAO_TIPIFICADO IS NOT NULL THEN 'Servico não tipificado - ' + S.NOME 
		ELSE S.NOME END)  AS TIPO_SERVICO
FROM TB_PREFEITURA P
INNER JOIN DBSEDS.DBO.TB_MUNICIPIOS M ON(M.ID = P.ID_MUNICIPIO)
INNER JOIN DBSEDS.DBO.TB_DRADS D ON (D.ID = M.ID_DRADS)
INNER JOIN TB_UNIDADE_PUBLICA UP ON(UP.ID_PREFEITURA = P.ID)
INNER JOIN TB_CREAS C ON(C.ID_UNIDADE_PUBLICA = UP.ID)
LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS R ON(R.ID_CREAS = C.ID)
LEFT JOIN TB_USUARIO_TIPO_SERVICO U ON (R.ID_USUARIO_TIPO_SERVICO = U.ID)
LEFT JOIN TB_TIPO_SERVICO AS S ON (U.ID_TIPO_SERVICO = S.ID)
INNER JOIN TB_TIPO_PROTECAO TP ON(TP.ID = S.ID_TIPO_PROTECAO)
LEFT JOIN TB_DISTRITOS_SAO_PAULO DS ON (DS.ID = C.ID_DISTRITOS_SAO_PAULO)
WHERE C.DESATIVADO = 0

UNION ALL

SELECT 
P.ID AS ID_PREFEITURA,
M.ID AS ID_MUNICIPIO,
M.ID_DRADS,
M.NOME AS MUNICIPIO,
D.NOME AS DRADS,
COALESCE(M.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
D.ID_MACRO_REGIAO,
P.ID_NIVEL_GESTAO,
(CASE WHEN P.POPULACAO <= 20000 THEN 1
   WHEN   P.POPULACAO <= 50000 THEN 2
   WHEN   P.POPULACAO <= 100000 THEN 3
   WHEN   P.POPULACAO <= 900000 THEN 4
   ELSE 5
END) AS ID_PORTE,
'Rede direta' AS TIPO_UNIDADE,
5 AS ID_TIPO_UNIDADE,
C.ID AS CODIGO_UNIDADE,
isnull(C.ID_DISTRITOS_SAO_PAULO,0) AS ID_DISTRITOS_SAO_PAULO,
DS.NOME AS DISTRITOS_SAO_PAULO,
UP.RAZAO_SOCIAL AS UNIDADE_RESPONSAVEL,
dbo.FORMATAR_CNPJ(UP.CNPJ) AS CNPJ,
C.ID AS ID_LOCAL,
C.NOME AS LOCAL_EXECUCAO,
C.COORDENADOR AS TECNICO_RESPONSAVEL_COORDENADOR,
(RTRIM(C.LOGRADOURO) + ', ' + C.NUMERO + (CASE WHEN C.COMPLEMENTO IS NOT NULL AND C.COMPLEMENTO <> ' ' THEN ' - ' + C.COMPLEMENTO ELSE '' END)) AS ENDERECO,
RTRIM(C.BAIRRO) AS BAIRRO,
dbo.FORMATAR_CEP(C.CEP) AS CEP,
C.CIDADE AS CIDADE,
CASE 
	WHEN C.TELEFONE = '' OR C.TELEFONE IS NULL THEN '' 
	ELSE DBO.FORMATAR_TELEFONE(C.TELEFONE)
	END AS TELEFONE,
CASE
	WHEN C.CELULAR= '' OR C.CELULAR IS NULL THEN ''
	ELSE DBO.FORMATAR_CELULAR(C.CELULAR) 
	END AS CELULAR,
C.EMAIL AS EMAIL,
U.ID_TIPO_SERVICO,
U.ID AS ID_USUARIO_TIPO_SERVICO,
S.ID_TIPO_PROTECAO,
S.NAO_TIPIFICADO,
(CASE WHEN R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL AND  R.DESCRICAO_NAO_TIPIFICADO <> '' AND TP.ID <> 3 AND S.NAO_TIPIFICADO IS NOT NULL  THEN  'Serviço não tipificado - ' + S.NOME + ' - ' + R.DESCRICAO_NAO_TIPIFICADO 
		WHEN TP.ID = 3 AND R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL THEN 'Serviço não tipificado - ' + R.DESCRICAO_NAO_TIPIFICADO 
		WHEN S.NAO_TIPIFICADO IS NOT NULL THEN 'Servico não tipificado - ' + S.NOME 
		ELSE S.NOME END)  AS TIPO_SERVICO
FROM TB_PREFEITURA P
INNER JOIN DBSEDS.DBO.TB_MUNICIPIOS M ON(M.ID = P.ID_MUNICIPIO)
INNER JOIN DBSEDS.DBO.TB_DRADS D ON (D.ID = M.ID_DRADS)
INNER JOIN TB_UNIDADE_PUBLICA UP ON(UP.ID_PREFEITURA = P.ID)
INNER JOIN TB_CENTRO_POP C ON(C.ID_UNIDADE_PUBLICA = UP.ID)
LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP R ON(R.ID_CENTRO_POP = C.ID)
LEFT JOIN TB_USUARIO_TIPO_SERVICO U ON (R.ID_USUARIO_TIPO_SERVICO = U.ID)
LEFT JOIN TB_TIPO_SERVICO AS S ON (U.ID_TIPO_SERVICO = S.ID)
INNER JOIN TB_TIPO_PROTECAO TP ON(TP.ID = S.ID_TIPO_PROTECAO)
LEFT JOIN TB_DISTRITOS_SAO_PAULO DS ON (DS.ID = C.ID_DISTRITOS_SAO_PAULO)
WHERE C.DESATIVADO = 0 
GO


