  ALTER TABLE  [DBSEDS].[dbo].[TB_MUNICIPIO_DEMOGRAFIA_TERRITORIO_INDICADORES] ADD VERSAO_SISTEMA INT NULL
  ALTER TABLE  [DBSEDS].[dbo].[TB_MUNICIPIO_POPULACAO_VULNERABILIDADE_INDICADORES] ADD VERSAO_SISTEMA INT NULL
  ALTER TABLE  [DBSEDS].[dbo].[TB_MUNICIPIO_REDE_SOCIOASSISTENCIAL_INDICADORES] ADD VERSAO_SISTEMA INT NULL

