USE [DBPMAS2016]
GO

/****** Object:  View [dbo].[VW_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO]    Script Date: 24/08/2015 10:23:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  View [dbo].[VW_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO]    Script Date: 24/08/2015 11:36:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[VW_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO]
  AS
  SELECT S.ID
		,S.ID_LOCAL_EXECUCAO_PUBLICO
		,S.ID_USUARIO_TIPO_SERVICO
		,U.NOME AS USUARIO
		,U.ID_TIPO_SERVICO
		,(CASE WHEN ID_TIPO_SERVICO_NAO_TIPIFICADO IS NOT NULL THEN ('Serviço não tipificado pela Resolução n° 109 do CNAS, de 11/11/2009 - '
		 + CASE WHEN DESCRICAO_NAO_TIPIFICADO IS NULL THEN T.NOME ELSE (
		  CASE WHEN ID_TIPO_PROTECAO = 3 THEN  DESCRICAO_NAO_TIPIFICADO ELSE( T.NOME + ' - ' + DESCRICAO_NAO_TIPIFICADO)END)END)
		 ELSE (T.NOME + (CASE WHEN DESCRICAO_NAO_TIPIFICADO IS NULL THEN '' ELSE ( + ' - ' + DESCRICAO_NAO_TIPIFICADO)END)) --(T.NOME)
		END)  AS TIPO_SERVICO
		,T.ID_TIPO_PROTECAO
		,P.NOME AS PROTECAO_SOCIAL
		,S.NUMERO_ATENDIDOS AS PREVISAO_ANUAL_NUMERO_ATENDIDOS
		,S.NUMERO_ATENDIDOS_MENSAL AS PREVISAO_MENSAL_NUMERO_ATENDIDOS
		,A.ABREVIACAO AS ABRANGENCIA
		,S.SERVICO_ESTADUALIZADO
		,COALESCE((S.VALOR_MUNICIPAL_ASSISTENCIA + S.VALOR_MUNICIPAL_FMDCA + S.VALOR_ESTADUAL_ASSISTENCIA + S.VALOR_ESTADUAL_FEDCA + S.VALOR_FEDERAL_ASSISTENCIA + S.VALOR_FEDERAL_FNDCA + ISNULL(S.VALOR_MUNICIPAL_FMI, 0.0) + ISNULL(S.VALOR_ESTADUAL_FEI, 0.0) + ISNULL(S.VALOR_FEDERAL_FNI, 0) + COALESCE(S.VALOR_ESTADUALIZADO,0)),0) AS PREVISAO_ORCAMENTARIA
		,(COALESCE(S.VALOR_ESTADUAL_ASSISTENCIA,0) + COALESCE(S.VALOR_ESTADUALIZADO,0)) AS VALOR_COFINANCIAMENTO_ESTADUAL
		,((Select Count(C.ID) FROM TB_PROGRAMA_PROJETO_COFINANCIAMENTO C 
		   where C.ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO = S.ID)
		 + (Select Count(C.ID) FROM TB_TRANSFERENCIA_RENDA_COFINANCIAMENTO C 
		 where C.ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO = S.ID)) AS TOTAL_SERVICOS_ASSOCIADOS 
  FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO S
  INNER JOIN TB_USUARIO_TIPO_SERVICO U ON (U.ID = S.ID_USUARIO_TIPO_SERVICO)
  INNER JOIN TB_TIPO_SERVICO T ON(T.ID = U.ID_TIPO_SERVICO)
  INNER JOIN TB_TIPO_PROTECAO P ON(P.ID = T.ID_TIPO_PROTECAO)
  INNER JOIN TB_ABRANGENCIA_SERVICO A ON(A.ID = S.ID_ABRANGENCIA_SERVICO)



GO
/****** Object:  View [dbo].[VW_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO]    Script Date: 24/08/2015 11:02:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--VISÃO DOS SERVIÇOS E RECURSOS FINANCEIROS PÚBLICO
  ALTER VIEW [dbo].[VW_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO]
  AS
   SELECT S.ID
		,S.ID_LOCAL_EXECUCAO_PRIVADO
		,S.ID_USUARIO_TIPO_SERVICO
		,U.NOME AS USUARIO
		,U.ID_TIPO_SERVICO
		,(CASE WHEN ID_TIPO_SERVICO_NAO_TIPIFICADO IS NOT NULL THEN ('Serviço não tipificado pela Resolução n° 109 do CNAS, de 11/11/2009 - '
		 + CASE WHEN DESCRICAO_NAO_TIPIFICADO IS NULL THEN T.NOME ELSE (
		  CASE WHEN ID_TIPO_PROTECAO = 3 THEN  DESCRICAO_NAO_TIPIFICADO ELSE( T.NOME + ' - ' + DESCRICAO_NAO_TIPIFICADO)END)END)
		 ELSE (T.NOME + (CASE WHEN DESCRICAO_NAO_TIPIFICADO IS NULL THEN '' ELSE ( + ' - ' + DESCRICAO_NAO_TIPIFICADO)END)) --(T.NOME)
		END)  AS TIPO_SERVICO
		,T.ID_TIPO_PROTECAO
		,P.NOME AS PROTECAO_SOCIAL
		,S.NUMERO_ATENDIDOS AS PREVISAO_ANUAL_NUMERO_ATENDIDOS
		,S.NUMERO_ATENDIDOS_MENSAL AS PREVISAO_MENSAL_NUMERO_ATENDIDOS
		,A.ABREVIACAO AS ABRANGENCIA
		,S.SERVICO_ESTADUALIZADO
		,COALESCE((S.VALOR_MUNICIPAL_ASSISTENCIA + S.VALOR_MUNICIPAL_FMDCA + S.VALOR_ESTADUAL_ASSISTENCIA + S.VALOR_ESTADUAL_FEDCA + S.VALOR_FEDERAL_ASSISTENCIA + S.VALOR_FEDERAL_FNDCA + COALESCE(S.VALOR_ESTADUALIZADO,0) + S.VALOR_PRIVADO_EMPRESAS + S.VALOR_PRIVADO_PESSOAS_FISICAS + s.VALOR_PRIVADO_ORGANIZACOES + S.VALOR_PRIVADO_PROPRIOS + ISNULL(S.VALOR_MUNICIPAL_FMI, 0.0) + ISNULL(S.VALOR_ESTADUAL_FEI, 0.0) + ISNULL(S.VALOR_FEDERAL_FNI, 0)),0) AS PREVISAO_ORCAMENTARIA
		,(COALESCE(S.VALOR_ESTADUAL_ASSISTENCIA,0)) AS VALOR_COFINANCIAMENTO_ESTADUAL
		,((Select Count(C.ID) FROM TB_PROGRAMA_PROJETO_COFINANCIAMENTO C 
		   where C.ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO = S.ID)
		 + (Select Count(C.ID) FROM TB_TRANSFERENCIA_RENDA_COFINANCIAMENTO C 
		 where C.ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO = S.ID)) AS TOTAL_SERVICOS_ASSOCIADOS 
  FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO S
  INNER JOIN TB_USUARIO_TIPO_SERVICO U ON (U.ID = S.ID_USUARIO_TIPO_SERVICO)
  INNER JOIN TB_TIPO_SERVICO T ON(T.ID = U.ID_TIPO_SERVICO)
  INNER JOIN TB_TIPO_PROTECAO P ON(P.ID = T.ID_TIPO_PROTECAO)
  INNER JOIN TB_ABRANGENCIA_SERVICO A ON(A.ID = S.ID_ABRANGENCIA_SERVICO)

GO


/****** Object:  View [dbo].[VW_SERVICOS_RECURSOS_FINANCEIROS_CRAS]    Script Date: 24/08/2015 11:03:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--VISÃO DOS SERVIÇOS E RECURSOS FINANCEIROS CRAS
  ALTER VIEW [dbo].[VW_SERVICOS_RECURSOS_FINANCEIROS_CRAS]
  AS
  SELECT S.ID
		,S.ID_CRAS
		,S.ID_USUARIO_TIPO_SERVICO
		,U.NOME AS USUARIO
		,U.ID_TIPO_SERVICO
		,((CASE WHEN DESCRICAO_NAO_TIPIFICADO IS NULL THEN T.NOME ELSE ('Serviço não tipificado pela Resolução nº 109 do CNAS, de 11/11/2009 - ' + T.NOME + ' - ' + DESCRICAO_NAO_TIPIFICADO)END))  AS TIPO_SERVICO
		,T.ID_TIPO_PROTECAO
		,P.NOME AS PROTECAO_SOCIAL
		,S.NUMERO_ATENDIDOS AS PREVISAO_ANUAL_NUMERO_ATENDIDOS
		,S.NUMERO_ATENDIDOS_MENSAL AS PREVISAO_MENSAL_NUMERO_ATENDIDOS
		,A.ABREVIACAO AS ABRANGENCIA
		,S.SERVICO_ESTADUALIZADO
		,COALESCE((S.VALOR_MUNICIPAL_ASSISTENCIA + S.VALOR_MUNICIPAL_FMDCA + S.VALOR_ESTADUAL_ASSISTENCIA + S.VALOR_ESTADUAL_FEDCA + S.VALOR_FEDERAL_ASSISTENCIA + S.VALOR_FEDERAL_FNDCA + ISNULL(S.VALOR_MUNICIPAL_FMI, 0.0) + ISNULL(S.VALOR_ESTADUAL_FEI, 0.0) + ISNULL(S.VALOR_FEDERAL_FNI, 0) + COALESCE(S.VALOR_ESTADUALIZADO,0)),0) AS PREVISAO_ORCAMENTARIA
		,(COALESCE(S.VALOR_ESTADUAL_ASSISTENCIA,0) + COALESCE(S.VALOR_ESTADUALIZADO,0)) AS VALOR_COFINANCIAMENTO_ESTADUAL
		,((Select Count(C.ID) FROM TB_PROGRAMA_PROJETO_COFINANCIAMENTO C 
		   where C.ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS = S.ID)
		 + (Select Count(C.ID) FROM TB_TRANSFERENCIA_RENDA_COFINANCIAMENTO C 
		 where C.ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS = S.ID)) AS TOTAL_SERVICOS_ASSOCIADOS  
  FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS S
  INNER JOIN TB_USUARIO_TIPO_SERVICO U ON (U.ID = S.ID_USUARIO_TIPO_SERVICO)
  INNER JOIN TB_TIPO_SERVICO T ON(T.ID = U.ID_TIPO_SERVICO)
  INNER JOIN TB_TIPO_PROTECAO P ON(P.ID = T.ID_TIPO_PROTECAO)
  INNER JOIN TB_ABRANGENCIA_SERVICO A ON(A.ID = S.ID_ABRANGENCIA_SERVICO)

GO

/****** Object:  View [dbo].[VW_SERVICOS_RECURSOS_FINANCEIROS_CREAS]    Script Date: 24/08/2015 11:04:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[VW_SERVICOS_RECURSOS_FINANCEIROS_CREAS]
  AS
  SELECT S.ID
		,S.ID_CREAS
		,S.ID_USUARIO_TIPO_SERVICO
		,U.NOME AS USUARIO
		,U.ID_TIPO_SERVICO
	,((CASE WHEN DESCRICAO_NAO_TIPIFICADO IS NULL THEN T.NOME ELSE ('Serviço não tipificado pela Resolução nº 109 do CNAS, de 11/11/2009 - ' + T.NOME + ' - ' + DESCRICAO_NAO_TIPIFICADO)END))  AS TIPO_SERVICO
		,T.ID_TIPO_PROTECAO
		,P.NOME AS PROTECAO_SOCIAL
		,S.NUMERO_ATENDIDOS AS PREVISAO_ANUAL_NUMERO_ATENDIDOS
		,S.NUMERO_ATENDIDOS_MENSAL AS PREVISAO_MENSAL_NUMERO_ATENDIDOS
		,A.ABREVIACAO AS ABRANGENCIA
		,S.SERVICO_ESTADUALIZADO
		,COALESCE((S.VALOR_MUNICIPAL_ASSISTENCIA + S.VALOR_MUNICIPAL_FMDCA + S.VALOR_ESTADUAL_ASSISTENCIA + S.VALOR_ESTADUAL_FEDCA + S.VALOR_FEDERAL_ASSISTENCIA + S.VALOR_FEDERAL_FNDCA + ISNULL(S.VALOR_MUNICIPAL_FMI, 0.0) + ISNULL(S.VALOR_ESTADUAL_FEI, 0.0) + ISNULL(S.VALOR_FEDERAL_FNI, 0) + COALESCE(S.VALOR_ESTADUALIZADO,0)),0) AS PREVISAO_ORCAMENTARIA
		,(COALESCE(S.VALOR_ESTADUAL_ASSISTENCIA,0) + COALESCE(S.VALOR_ESTADUALIZADO,0)) AS VALOR_COFINANCIAMENTO_ESTADUAL
	 	,((Select Count(C.ID) FROM TB_PROGRAMA_PROJETO_COFINANCIAMENTO C 
		   where C.ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS = S.ID)
		 + (Select Count(C.ID) FROM TB_TRANSFERENCIA_RENDA_COFINANCIAMENTO C 
		 where C.ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS = S.ID)) AS TOTAL_SERVICOS_ASSOCIADOS 
  FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS S
  INNER JOIN TB_USUARIO_TIPO_SERVICO U ON (U.ID = S.ID_USUARIO_TIPO_SERVICO)
  INNER JOIN TB_TIPO_SERVICO T ON(T.ID = U.ID_TIPO_SERVICO)
  INNER JOIN TB_TIPO_PROTECAO P ON(P.ID = T.ID_TIPO_PROTECAO)
  INNER JOIN TB_ABRANGENCIA_SERVICO A ON(A.ID = S.ID_ABRANGENCIA_SERVICO)

GO

/****** Object:  View [dbo].[VW_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP]    Script Date: 24/08/2015 11:05:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--VISÃO DOS SERVIÇOS E RECURSOS FINANCEIROS CENTRO_POP
  ALTER VIEW [dbo].[VW_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP]
  AS
  SELECT S.ID
		,S.ID_CENTRO_POP
		,S.ID_USUARIO_TIPO_SERVICO
		,U.NOME AS USUARIO
		,U.ID_TIPO_SERVICO
		,((CASE WHEN DESCRICAO_NAO_TIPIFICADO IS NULL THEN T.NOME ELSE ('Serviço não tipificado pela Resolução nº 109 do CNAS, de 11/11/2009 - ' + T.NOME + ' - ' + DESCRICAO_NAO_TIPIFICADO)END))  AS TIPO_SERVICO
		,T.ID_TIPO_PROTECAO
		,P.NOME AS PROTECAO_SOCIAL
		,S.NUMERO_ATENDIDOS AS PREVISAO_ANUAL_NUMERO_ATENDIDOS
		,S.NUMERO_ATENDIDOS_MENSAL AS PREVISAO_MENSAL_NUMERO_ATENDIDOS
		,A.ABREVIACAO AS ABRANGENCIA
		,S.SERVICO_ESTADUALIZADO
		,COALESCE((S.VALOR_MUNICIPAL_ASSISTENCIA + S.VALOR_MUNICIPAL_FMDCA + S.VALOR_ESTADUAL_ASSISTENCIA + S.VALOR_ESTADUAL_FEDCA + S.VALOR_FEDERAL_ASSISTENCIA + S.VALOR_FEDERAL_FNDCA + ISNULL(S.VALOR_MUNICIPAL_FMI, 0.0) + ISNULL(S.VALOR_ESTADUAL_FEI, 0.0) + ISNULL(S.VALOR_FEDERAL_FNI, 0) + COALESCE(S.VALOR_ESTADUALIZADO,0)),0) AS PREVISAO_ORCAMENTARIA
		,(COALESCE(S.VALOR_ESTADUAL_ASSISTENCIA,0) + COALESCE(S.VALOR_ESTADUALIZADO,0)) AS VALOR_COFINANCIAMENTO_ESTADUAL
	 	,((Select Count(C.ID) FROM TB_PROGRAMA_PROJETO_COFINANCIAMENTO C 
		   where C.ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP = S.ID)
		 + (Select Count(C.ID) FROM TB_TRANSFERENCIA_RENDA_COFINANCIAMENTO C 
		 where C.ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP = S.ID)) AS TOTAL_SERVICOS_ASSOCIADOS 
  FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP S
  INNER JOIN TB_USUARIO_TIPO_SERVICO U ON (U.ID = S.ID_USUARIO_TIPO_SERVICO)
  INNER JOIN TB_TIPO_SERVICO T ON(T.ID = U.ID_TIPO_SERVICO)
  INNER JOIN TB_TIPO_PROTECAO P ON(P.ID = T.ID_TIPO_PROTECAO)
  INNER JOIN TB_ABRANGENCIA_SERVICO A ON(A.ID = S.ID_ABRANGENCIA_SERVICO)


GO



	
	
	


