



ALTER VIEW [dbo].[VW_SERVICOS_RECURSOS_FINANCEIROS_CRAS]
  AS
 SELECT S.ID
		,S.ID_CRAS
		,S.ID_USUARIO_TIPO_SERVICO
		,U.NOME AS USUARIO
		,U.ID_TIPO_SERVICO
		,((CASE WHEN DESCRICAO_NAO_TIPIFICADO IS NULL THEN T.NOME ELSE ('Serviço não tipificado pela Resolução nº 109 do CNAS, de 11/11/2009 - ' + T.NOME + ' - ' + DESCRICAO_NAO_TIPIFICADO)END))  AS TIPO_SERVICO
		,T.ID_TIPO_PROTECAO
		,P.NOME AS PROTECAO_SOCIAL
		,S.NUMERO_ATENDIDOS AS PREVISAO_ANUAL_NUMERO_ATENDIDOS
		,ISNULL(s2.CAPACIDADE,0) AS PREVISAO_MENSAL_NUMERO_ATENDIDOS

		,A.ABREVIACAO AS ABRANGENCIA
		--,S.SERVICO_ESTADUALIZADO
		,COALESCE((S1.VALOR_MUNICIPAL_ASSISTENCIA + 
					S1.VALOR_MUNICIPAL_FMDCA + 
					S1.VALOR_ESTADUAL_ASSISTENCIA + 
					S1.VALOR_ESTADUAL_FEDCA + 
					S1.VALOR_FEDERAL_ASSISTENCIA + 
					S1.VALOR_FEDERAL_FNDCA 
					+ ISNULL(S1.VALOR_MUNICIPAL_FMI, 0.0) 
					+ ISNULL(S1.VALOR_ESTADUAL_FEI, 0.0) 
					+ ISNULL(S1.VALOR_FEDERAL_FNI, 0) 
					--+ COALESCE(S.VALOR_ESTADUALIZADO,0)
					),0) AS PREVISAO_ORCAMENTARIA
		,(COALESCE(S1.VALOR_ESTADUAL_ASSISTENCIA,0) 
		--+ COALESCE(S.VALOR_ESTADUALIZADO,0)
		) AS VALOR_COFINANCIAMENTO_ESTADUAL
		,S.DATA_FUNCIONAMENTO_SERVICO
		,S.DESATIVADO
		,S.DATA_REGISTRO_LOG AS DATA_EXCLUSAO_SERVICO
		,S.ID_MOTIVO_DESATIVACAO
		,M.DESCRICAO AS MOTIVO_DESATIVACAO
		,CASE when S.ID_MOTIVO_DESATIVACAO = 1 
				then S.DATA_REGISTRO_LOG 
				else  S.DATA_DESATIVACAO end 
				AS DATA_ENCERRAMENTO_SERVICO
		,S.DETALHAMENTO AS DETALHAMENTO_ENCERRAMENTO
		,((Select Count(C.ID) FROM TB_PROGRAMA_PROJETO_COFINANCIAMENTO C 
		   where C.ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS = S.ID)
		 + (Select Count(C.ID) FROM TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA C 
		 where C.ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS = S.ID)) AS TOTAL_SERVICOS_ASSOCIADOS  
		 ,S2.EXERCICIO
  
  FROM [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS] S
  LEFT join TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_CAPACIDADE s2 on s2.ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS = S.ID
  LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_CRAS S1 ON(S.ID = S1.ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS AND S1.EXERCICIO = S2.EXERCICIO)
  INNER JOIN [dbo].[TB_USUARIO_TIPO_SERVICO] U ON (U.ID = S.ID_USUARIO_TIPO_SERVICO)
  INNER JOIN [dbo].[TB_TIPO_SERVICO] T ON(T.ID = U.ID_TIPO_SERVICO)
  INNER JOIN [dbo].[TB_TIPO_PROTECAO] P ON(P.ID = T.ID_TIPO_PROTECAO)
  INNER JOIN [dbo].[TB_ABRANGENCIA_SERVICO] A ON(A.ID = S.ID_ABRANGENCIA_SERVICO)
  LEFT JOIN [dbo].[TB_MOTIVO_DESATIVACAO_SERVICO] M ON (M.ID = S.ID_MOTIVO_DESATIVACAO) 
  



GO


