/****** Object:  View [dbo].[VW_INFORMACOES_FMAS]    Script Date: 22/04/2019 17:15:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[VW_INFORMACOES_FMAS]
AS
SELECT 
P.ID AS ID_PREFEITURA,
M.ID AS ID_MUNICIPIO,
M.ID_DRADS,
M.NOME AS MUNICIPIO,
D.NOME AS DRADS,

P.ID_NIVEL_GESTAO,
(CASE WHEN POPULACAO <= 20000 THEN 1
   WHEN   POPULACAO <= 50000 THEN 2
   WHEN   POPULACAO <= 100000 THEN 3
   WHEN   POPULACAO <= 900000 THEN 4
   ELSE 5
END) AS ID_PORTE,
COALESCE(M.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
D.ID_MACRO_REGIAO,
COALESCE(F.LEI,'') AS LEI,
(CASE WHEN F.REGULAMENTA IS NULL THEN ''
WHEN F.REGULAMENTA = 1 THEN 'Sim' 
ELSE 'Não' END) AS REGULAMENTADO,
COALESCE(F.NR_DECRETO,'') AS DECRETO,
(CASE WHEN F.ORCAMENTARIA IS NULL THEN ''
WHEN F.ORCAMENTARIA = 1 THEN 'Sim' ELSE 'Não' END) AS ORCAMENTARIA,
G.NOME AS NOME_GESTOR,
T.TIPO_GESTOR,
COALESCE(LO.VALOR_RECURSOS_FMAS, '0.00') AS VALOR_RECURSOS_FMAS,
COALESCE(LO.VALOR_RECURSOS_NAO_ALOCADOS_FMAS, '0.00') AS VALOR_NAO_ALOCADOS_FMAS,
COALESCE(FMV.VALOR_FMAS, '0.00') AS VALOR_FMAS,
COALESCE(FMV.VALOR_FEAS, '0.00') AS VALOR_FEAS,
COALESCE(FMV.VALOR_FNAS, '0.00') AS VALOR_FNAS,
DBO.FORMATAR_CNPJ(F.CNPJ) AS CNPJ,
(CASE WHEN F.CNPJ IS NULL THEN NULL WHEN F.CNPJ <> P.CNPJ THEN 'Matriz' ELSE 'Filial' END) as CONDICAO_CNPJ,
FMV.EXERCICIO
FROM TB_PREFEITURA P
INNER JOIN DBSEDS.DBO.TB_MUNICIPIOS M ON(M.ID = P.ID_MUNICIPIO)
INNER JOIN DBSEDS.DBO.TB_DRADS D ON (D.ID = M.ID_DRADS)
LEFT JOIN TB_FUNDO_MUNICIPAL_VALORES FMV ON P.ID = FMV.ID_PREFEITURA 
LEFT JOIN TB_FUNDO_MUNICIPAL F ON(F.ID_PREFEITURA = P.ID)
INNER JOIN TB_GESTOR_FUNDO_MUNICIPAL G ON (G.ID_PREFEITURA = P.ID)
LEFT JOIN TB_TIPO_GESTOR T ON T.ID = G.ID_TIPO_GESTOR
LEFT JOIN TB_LEI_ORCAMENTARIA LO ON LO.ID_PREFEITURA = P.ID and LO.EXERCICIO = FMV.EXERCICIO
where G.ID_STATUS =1  
GO


