

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
BEGIN TRAN
	BEGIN TRY
		BEGIN
			--ADICIONAR AS GRANTS
			--CRIAR AS 18 TABELAS E ACERTAR EDMX
			-----------------------------------------------------------------
			-----------------------------------------------------------------
			-- TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_PSC
			-----------------------------------------------------------------
			----------------------------------------------------------------
			PRINT 'CRIANDO A TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_PSC'
			----------------------------------------------------------------
	
			IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_PSC')
			BEGIN
				CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_PSC](
									[ID] [int] IDENTITY(1,1) NOT NULL,
									[ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] [int] NOT NULL,
									[CAPACIDADE] [int] NULL,
									[EXERCICIO] [int] NULL
				 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_PSC] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY] 

				ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_PSC]  WITH CHECK 
				ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_PSC_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] 
				FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO])
				REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] ([ID])
			END

			--------------------------------------------
			-- FUNCIONAMENTO
			--------------------------------------------
			IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_PSC)
			BEGIN
				--ORIGINAL EXISTENTE: VALORES DE 2018
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_PSC(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO
								, CAPACIDADE
								, EXERCICIO )
				SELECT 
				  ID
				, NUMERO_ATENDIDOS_MENSAL_SERVICO
				, 2018
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO 
				WHERE ID_USUARIO_TIPO_SERVICO = 22

				--COPIA DA ORIGINAL EXISTENTE PARA 2019
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_PSC(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO
								, CAPACIDADE
								, EXERCICIO )
				SELECT 
				  ID
				, NUMERO_ATENDIDOS_MENSAL_SERVICO
				, 2019 -- Adicionado novo
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO 
				WHERE ID_USUARIO_TIPO_SERVICO = 22
			END


			-----------------------------------------------------------------
			-----------------------------------------------------------------
			-- TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_LA
			-----------------------------------------------------------------
			----------------------------------------------------------------
			PRINT 'CRIANDO A TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_LA'
			----------------------------------------------------------------

			IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_LA')
			BEGIN
				CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_LA](
									[ID] [int] IDENTITY(1,1) NOT NULL,
									[ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] [int] NOT NULL,
									[CAPACIDADE] [int] NULL,
									[EXERCICIO] [int] NULL
				 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_LA] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY] 

				ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_LA]  WITH CHECK 
				ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_LA_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] 
				FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO])
				REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] ([ID])
			END

			--------------------------------------------
			-- FUNCIONAMENTO
			--------------------------------------------
			IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_LA)
			BEGIN
				--ORIGINAL EXISTENTE: VALORES DE 2018
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_LA(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO
								, CAPACIDADE
								, EXERCICIO )
				SELECT 
				  ID
				, NUMERO_ATENDIDOS_MENSAL
				, 2018
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO 
				WHERE ID_USUARIO_TIPO_SERVICO = 22

				--COPIA DA ORIGINAL EXISTENTE PARA 2019
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_LA(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO
								, CAPACIDADE
								, EXERCICIO )
				SELECT 
				  ID
				, NUMERO_ATENDIDOS_MENSAL
				, 2019 -- Adicionado novo
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO 
				WHERE ID_USUARIO_TIPO_SERVICO = 22
			END


			-----------------------------------------------------------------
			-----------------------------------------------------------------
			-- TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE
			-----------------------------------------------------------------
			----------------------------------------------------------------
			PRINT 'CRIANDO A TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE'
			----------------------------------------------------------------

			IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE')
			BEGIN
				CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE](
									[ID] [int] IDENTITY(1,1) NOT NULL,
									[ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] [int] NOT NULL,
									[CAPACIDADE] [int] NULL,
									[EXERCICIO] [int] NULL
				 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY] 

				ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE]  WITH CHECK 
				ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] 
				FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO])
				REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] ([ID])
			END

			--------------------------------------------
			-- FUNCIONAMENTO
			--------------------------------------------
			IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE)
			BEGIN
				--ORIGINAL EXISTENTE: VALORES DE 2018
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO
								, CAPACIDADE
								, EXERCICIO )
				SELECT 
				  ID
				, NUMERO_ATENDIDOS_MENSAL
				, 2018
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO 
				WHERE ID_USUARIO_TIPO_SERVICO <> 22

				--COPIA DA ORIGINAL EXISTENTE PARA 2019
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO
								, CAPACIDADE
								, EXERCICIO )
				SELECT 
				  ID
				, NUMERO_ATENDIDOS_MENSAL
				, 2019 -- Adicionado novo
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO 
				WHERE ID_USUARIO_TIPO_SERVICO <> 22
			END

			-----------------------------------------------------------------
			-----------------------------------------------------------------
			-- TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL
			-----------------------------------------------------------------
			----------------------------------------------------------------
			PRINT 'CRIANDO A TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL'
			----------------------------------------------------------------


			IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL')
			BEGIN
				CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL](
									[ID] [int] IDENTITY(1,1) NOT NULL,
									[ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS] [int] NOT NULL,
									[MEDIA] [int] NULL,
									[EXERCICIO] [int] NULL
				 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY] 

				ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL]  WITH CHECK 
				ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS] 
				FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS])
				REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS] ([ID])
			END

			--------------------------------------------
			-- FUNCIONAMENTO
			--------------------------------------------
			IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL)
			BEGIN
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS
								, MEDIA
								, EXERCICIO )
				SELECT 
				  ID
				, MEDIA_MENSAL_ATENDIMENTO_2017
				, 2018
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS 
				WHERE ID_USUARIO_TIPO_SERVICO <> 22

				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS
								, MEDIA
								, EXERCICIO )
				SELECT 
				  ID
				, MEDIA_MENSAL_ATENDIMENTO_2018
				, 2019
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS 
				WHERE ID_USUARIO_TIPO_SERVICO <> 22
			END


			-----------------------------------------------------------------
			-----------------------------------------------------------------
			-- TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_PSC
			-----------------------------------------------------------------
			----------------------------------------------------------------
			PRINT 'CRIANDO A TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_PSC'
			----------------------------------------------------------------

			IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_PSC')
			BEGIN
				CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_PSC](
									[ID] [int] IDENTITY(1,1) NOT NULL,
									[ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS] [int] NOT NULL,
									[MEDIA] [int] NULL,
									[EXERCICIO] [int] NULL
				 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_PSC] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY] 

				ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_PSC]  WITH CHECK 
				ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_PSC_TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS] 
				FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS])
				REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS] ([ID])
			END

			--------------------------------------------
			-- FUNCIONAMENTO
			--------------------------------------------
			IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_PSC)
			BEGIN
	
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_PSC(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS
								, MEDIA
								, EXERCICIO )
				SELECT 
				  ID
				, MEDIA_MENSAL_ATENDIMENTO_PSC_2017
				, 2018
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS 
				WHERE ID_USUARIO_TIPO_SERVICO = 22

	
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_PSC(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS
								, MEDIA
								, EXERCICIO )
				SELECT 
				  ID
				, MEDIA_MENSAL_ATENDIMENTO_PSC_2018
				, 2019
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS 
				WHERE ID_USUARIO_TIPO_SERVICO = 22
			END


			-----------------------------------------------------------------
			-----------------------------------------------------------------
			-- TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_LA
			-----------------------------------------------------------------
			----------------------------------------------------------------
			PRINT 'CRIANDO A TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_LA'
			----------------------------------------------------------------

			IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_LA')
			BEGIN
				CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_LA](
									[ID] [int] IDENTITY(1,1) NOT NULL,
									[ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS] [int] NOT NULL,
									[MEDIA] [int] NULL,
									[EXERCICIO] [int] NULL
				 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_LA] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY] 

				ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_LA]  WITH CHECK 
				ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_LA_TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS] 
				FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS])
				REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS] ([ID])
			END

			--------------------------------------------
			-- FUNCIONAMENTO
			--------------------------------------------
			IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_LA)
			BEGIN
	
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_LA(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS
								, MEDIA
								, EXERCICIO )
				SELECT 
				  ID
				, MEDIA_MENSAL_ATENDIMENTO_2017
				, 2018
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS 
				WHERE ID_USUARIO_TIPO_SERVICO = 22

	
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_LA(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS
								, MEDIA
								, EXERCICIO )
				SELECT 
				  ID
				, MEDIA_MENSAL_ATENDIMENTO_2018
				, 2019 -- Adicionado novo
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS 
				WHERE ID_USUARIO_TIPO_SERVICO = 22
			END


			-----------------------------------------------------------------
			-----------------------------------------------------------------
			-- TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE
			-----------------------------------------------------------------
			----------------------------------------------------------------
			PRINT 'CRIANDO A TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE'
			----------------------------------------------------------------
			IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE')
			BEGIN
				CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE](
									[ID] [int] IDENTITY(1,1) NOT NULL,
									[ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS] [int] NOT NULL,
									[CAPACIDADE] [int] NULL,
									[EXERCICIO] [int] NULL
				 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY] 

				ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE]  WITH CHECK 
				ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS] 
				FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS])
				REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS] ([ID])
			END

			--------------------------------------------
			-- FUNCIONAMENTO
			--------------------------------------------
			IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE)
			BEGIN
				--ORIGINAL EXISTENTE: VALORES DE 2018
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS
								, CAPACIDADE
								, EXERCICIO )
				SELECT 
				  ID
				, NUMERO_ATENDIDOS_MENSAL
				, 2018
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS 
				WHERE ID_USUARIO_TIPO_SERVICO <> 22

				--COPIA DA ORIGINAL EXISTENTE PARA 2019
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS
								, CAPACIDADE
								, EXERCICIO )
				SELECT 
				  ID
				, NUMERO_ATENDIDOS_MENSAL
				, 2019 -- Adicionado novo
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS 
				WHERE ID_USUARIO_TIPO_SERVICO <> 22
			END



			-----------------------------------------------------------------
			-----------------------------------------------------------------
			-- TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_PSC
			-----------------------------------------------------------------
			----------------------------------------------------------------
			PRINT 'CRIANDO A TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_PSC'
			----------------------------------------------------------------

			IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_PSC')
			BEGIN
				CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_PSC](
									[ID] [int] IDENTITY(1,1) NOT NULL,
									[ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS] [int] NOT NULL,
									[CAPACIDADE] [int] NULL,
									[EXERCICIO] [int] NULL
				 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_PSC] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY] 

				ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_PSC]  WITH CHECK 
				ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_PSC_TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS] 
				FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS])
				REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS] ([ID])
			END

			--------------------------------------------
			-- FUNCIONAMENTO
			--------------------------------------------
			IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_PSC)
			BEGIN
				--ORIGINAL EXISTENTE: VALORES DE 2018
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_PSC(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS
								, CAPACIDADE
								, EXERCICIO )
				SELECT 
				  ID
				, NUMERO_ATENDIDOS_MENSAL_SERVICO
				, 2018
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS 
				WHERE ID_USUARIO_TIPO_SERVICO = 22

				--COPIA DA ORIGINAL EXISTENTE PARA 2019
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_PSC(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS
								, CAPACIDADE
								, EXERCICIO )
				SELECT 
				  ID
				, NUMERO_ATENDIDOS_MENSAL_SERVICO
				, 2019 -- Adicionado novo
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS 
				WHERE ID_USUARIO_TIPO_SERVICO = 22
			END

			-----------------------------------------------------------------
			-----------------------------------------------------------------
			-- TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_LA
			-----------------------------------------------------------------
			----------------------------------------------------------------
			PRINT 'CRIANDO A TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_LA'
			----------------------------------------------------------------
			IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_LA')
			BEGIN
				CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_LA](
									[ID] [int] IDENTITY(1,1) NOT NULL,
									[ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS] [int] NOT NULL,
									[CAPACIDADE] [int] NULL,
									[EXERCICIO] [int] NULL
				 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_LA] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY] 

				ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_LA]  WITH CHECK 
				ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_LA_TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS] 
				FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS])
				REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS] ([ID])
			END

			--------------------------------------------
			-- FUNCIONAMENTO
			--------------------------------------------
			IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_LA)
			BEGIN
				--ORIGINAL EXISTENTE: VALORES DE 2018
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_LA(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS
								, CAPACIDADE
								, EXERCICIO )
				SELECT 
				  ID
				, NUMERO_ATENDIDOS_MENSAL
				, 2018
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS 
				WHERE ID_USUARIO_TIPO_SERVICO = 22

				--COPIA DA ORIGINAL EXISTENTE PARA 2019
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_LA(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS
								, CAPACIDADE
								, EXERCICIO )
				SELECT 
				  ID
				, NUMERO_ATENDIDOS_MENSAL
				, 2019 -- Adicionado novo
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS 
				WHERE ID_USUARIO_TIPO_SERVICO = 22
			END



			-----------------------------------------------------------------
			-----------------------------------------------------------------
			-- TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_MEDIA_MENSAL
			-----------------------------------------------------------------
			----------------------------------------------------------------
			PRINT 'CRIANDO A TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_MEDIA_MENSAL'
			----------------------------------------------------------------
			IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_MEDIA_MENSAL')
			BEGIN
				CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_MEDIA_MENSAL](
									[ID] [int] IDENTITY(1,1) NOT NULL,
									[ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS] [int] NOT NULL,
									[MEDIA] [int] NULL,
									[EXERCICIO] [int] NULL
				 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_MEDIA_MENSAL] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY] 

				ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_MEDIA_MENSAL]  WITH CHECK 
				ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_MEDIA_MENSAL_TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS] 
				FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS])
				REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS] ([ID])
			END

			--------------------------------------------
			-- FUNCIONAMENTO
			--------------------------------------------
			IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_MEDIA_MENSAL)
			BEGIN
	
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_MEDIA_MENSAL(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS
								, MEDIA
								, EXERCICIO )
				SELECT 
				  ID
				, MEDIA_MENSAL_ATENDIMENTO_2017
				, 2018
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS 
				WHERE ID_USUARIO_TIPO_SERVICO <> 22

	
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_MEDIA_MENSAL(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS
								, MEDIA
								, EXERCICIO )
				SELECT 
				  ID
				, MEDIA_MENSAL_ATENDIMENTO_2018
				, 2019 -- Adicionado novo
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS 
				WHERE ID_USUARIO_TIPO_SERVICO <> 22
			END

			-----------------------------------------------------------------
			-----------------------------------------------------------------
			-- TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_CAPACIDADE
			-----------------------------------------------------------------
			----------------------------------------------------------------
			PRINT 'CRIANDO A TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_CAPACIDADE'
			----------------------------------------------------------------
			IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_CAPACIDADE')
			BEGIN
				CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_CAPACIDADE](
									[ID] [int] IDENTITY(1,1) NOT NULL,
									[ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS] [int] NOT NULL,
									[CAPACIDADE] [int] NULL,
									[EXERCICIO] [int] NULL
				 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_CAPACIDADE] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY] 

				ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_CAPACIDADE]  WITH CHECK 
				ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_CAPACIDADE_TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS] 
				FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS])
				REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS] ([ID])
			END

			--------------------------------------------
			-- FUNCIONAMENTO
			--------------------------------------------
			IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_CAPACIDADE)
			BEGIN
				--ORIGINAL EXISTENTE: VALORES DE 2018
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_CAPACIDADE(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS
								, CAPACIDADE
								, EXERCICIO )
				SELECT 
				  ID
				, NUMERO_ATENDIDOS_MENSAL
				, 2018
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS 
				WHERE ID_USUARIO_TIPO_SERVICO <> 22

				--COPIA DA ORIGINAL EXISTENTE PARA 2019
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_CAPACIDADE(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS
								, CAPACIDADE
								, EXERCICIO )
				SELECT 
				  ID
				, NUMERO_ATENDIDOS_MENSAL
				, 2019 -- Adicionado novo
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS 
				WHERE ID_USUARIO_TIPO_SERVICO <> 22
			END

			-----------------------------------------------------------------
			-----------------------------------------------------------------
			-- TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_MEDIA_MENSAL
			-----------------------------------------------------------------
			----------------------------------------------------------------
			PRINT 'CRIANDO A TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_MEDIA_MENSAL'
			----------------------------------------------------------------
			IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_MEDIA_MENSAL')
			BEGIN
				CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_MEDIA_MENSAL](
									[ID] [int] IDENTITY(1,1) NOT NULL,
									[ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP] [int] NOT NULL,
									[MEDIA] [int] NULL,
									[EXERCICIO] [int] NULL
				 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_MEDIA_MENSAL] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY] 

				ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_MEDIA_MENSAL]  WITH CHECK 
				ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_MEDIA_MENSAL_TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP] 
				FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP])
				REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP] ([ID])
			END

			--------------------------------------------
			-- FUNCIONAMENTO
			--------------------------------------------
			IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_MEDIA_MENSAL)
			BEGIN
	
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_MEDIA_MENSAL(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP
								, MEDIA
								, EXERCICIO )
				SELECT 
				  ID
				, MEDIA_MENSAL_ATENDIMENTO_2017
				, 2018
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP 
				WHERE ID_USUARIO_TIPO_SERVICO <> 22

	
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_MEDIA_MENSAL(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP
								, MEDIA
								, EXERCICIO )
				SELECT 
				  ID
				, MEDIA_MENSAL_ATENDIMENTO_2018
				, 2019 
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP 
				WHERE ID_USUARIO_TIPO_SERVICO <> 22
			END


			-----------------------------------------------------------------
			-----------------------------------------------------------------
			-- TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_CAPACIDADE
			-----------------------------------------------------------------
			----------------------------------------------------------------
			PRINT 'CRIANDO A TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_CAPACIDADE'
			----------------------------------------------------------------
			IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_CAPACIDADE')
			BEGIN
				CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_CAPACIDADE](
									[ID] [int] IDENTITY(1,1) NOT NULL,
									[ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP] [int] NOT NULL,
									[CAPACIDADE] [int] NULL,
									[EXERCICIO] [int] NULL
				 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_CAPACIDADE] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY] 

				ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_CAPACIDADE]  WITH CHECK 
				ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_CAPACIDADE_TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP] 
				FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP])
				REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP] ([ID])
			END

			--------------------------------------------
			-- FUNCIONAMENTO
			--------------------------------------------
			IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_CAPACIDADE)
			BEGIN
				--ORIGINAL EXISTENTE: VALORES DE 2018
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_CAPACIDADE(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP
								, CAPACIDADE
								, EXERCICIO )
				SELECT 
				  ID
				, NUMERO_ATENDIDOS_MENSAL
				, 2018
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP 
				WHERE ID_USUARIO_TIPO_SERVICO <> 22

				--COPIA DA ORIGINAL EXISTENTE PARA 2019
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_CAPACIDADE(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP
								, CAPACIDADE
								, EXERCICIO )
				SELECT 
				  ID
				, NUMERO_ATENDIDOS_MENSAL
				, 2019 -- Adicionado novo
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP 
				WHERE ID_USUARIO_TIPO_SERVICO <> 22
			END



			-----------------------------------------------------------------
			-----------------------------------------------------------------
			-- TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL
			-----------------------------------------------------------------
			----------------------------------------------------------------
			PRINT 'CRIANDO A TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL'
			----------------------------------------------------------------
			IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL')
			BEGIN
				CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL](
									[ID] [int] IDENTITY(1,1) NOT NULL,
									[ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] [int] NOT NULL,
									[MEDIA] [int] NULL,
									[EXERCICIO] [int] NULL
				 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY] 

				ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL]  WITH CHECK 
				ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] 
				FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO])
				REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] ([ID])
			END

			--------------------------------------------
			-- FUNCIONAMENTO
			--------------------------------------------
			IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL)
			BEGIN
				--ORIGINAL EXISTENTE: VALORES DE 2018
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO
								, MEDIA
								, EXERCICIO )
				SELECT 
				  ID
				, MEDIA_MENSAL_ATENDIMENTO_2017
				, 2018
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO 
				WHERE ID_USUARIO_TIPO_SERVICO <> 22

				--COPIA DA ORIGINAL EXISTENTE PARA 2019
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO
								, MEDIA
								, EXERCICIO )
				SELECT 
				  ID
				, MEDIA_MENSAL_ATENDIMENTO_2018
				, 2019 -- Adicionado novo
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO 
				WHERE ID_USUARIO_TIPO_SERVICO <> 22
			END


			-----------------------------------------------------------------
			-----------------------------------------------------------------
			-- TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_PSC
			-----------------------------------------------------------------
			----------------------------------------------------------------
			PRINT 'CRIANDO A TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_PSC'
			----------------------------------------------------------------
			IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_PSC')
			BEGIN
				CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_PSC](
									[ID] [int] IDENTITY(1,1) NOT NULL,
									[ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] [int] NOT NULL,
									[MEDIA] [int] NULL,
									[EXERCICIO] [int] NULL
				 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_PSC] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY] 

				ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_PSC]  WITH CHECK 
				ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_PSC_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] 
				FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO])
				REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] ([ID])
			END

			--------------------------------------------
			-- FUNCIONAMENTO
			--------------------------------------------
			IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_PSC)
			BEGIN
	
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_PSC(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO
								, MEDIA
								, EXERCICIO )
				SELECT 
				  ID
				, MEDIA_MENSAL_ATENDIMENTO_PSC_2017
				, 2018
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO 
				WHERE ID_USUARIO_TIPO_SERVICO = 22

	
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_PSC(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO
								, MEDIA
								, EXERCICIO )
				SELECT 
				  ID
				, MEDIA_MENSAL_ATENDIMENTO_PSC_2018
				, 2019 -- Adicionado novo
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO 
				WHERE ID_USUARIO_TIPO_SERVICO = 22
			END


			-----------------------------------------------------------------
			-----------------------------------------------------------------
			-- TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_LA
			-----------------------------------------------------------------
			----------------------------------------------------------------
			PRINT 'CRIANDO A TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_LA'
			----------------------------------------------------------------
			IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_LA')
			BEGIN
				CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_LA](
									[ID] [int] IDENTITY(1,1) NOT NULL,
									[ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] [int] NOT NULL,
									[MEDIA] [int] NULL,
									[EXERCICIO] [int] NULL
				 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_LA] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY] 

				ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_LA]  WITH CHECK 
				ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_LA_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] 
				FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO])
				REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] ([ID])
			END

			--------------------------------------------
			-- FUNCIONAMENTO
			--------------------------------------------
			IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_LA)
			BEGIN
	
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_LA(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO
								, MEDIA
								, EXERCICIO )
				SELECT 
				  ID
				, MEDIA_MENSAL_ATENDIMENTO_2017
				, 2018
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO 
				WHERE ID_USUARIO_TIPO_SERVICO = 22

	
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_LA(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO
								, MEDIA
								, EXERCICIO )
				SELECT 
				  ID
				, MEDIA_MENSAL_ATENDIMENTO_2018
				, 2019 -- Adicionado novo
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO 
				WHERE ID_USUARIO_TIPO_SERVICO = 22
			END




			-----------------------------------------------------------------
			-----------------------------------------------------------------
			-- TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE
			-----------------------------------------------------------------
			----------------------------------------------------------------
			PRINT 'CRIANDO A TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE'
			----------------------------------------------------------------
			IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE')
			BEGIN
				CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE](
									[ID] [int] IDENTITY(1,1) NOT NULL,
									[ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] [int] NOT NULL,
									[CAPACIDADE] [int] NULL,
									[EXERCICIO] [int] NULL
				 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY] 

				ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE]  WITH CHECK 
				ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] 
				FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO])
				REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] ([ID])
			END

			--------------------------------------------
			-- FUNCIONAMENTO
			--------------------------------------------
			IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE)
			BEGIN
				--ORIGINAL EXISTENTE: VALORES DE 2018
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO
								, CAPACIDADE
								, EXERCICIO )
				SELECT 
				  ID
				, NUMERO_ATENDIDOS_MENSAL
				, 2018
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO 
				WHERE ID_USUARIO_TIPO_SERVICO <> 22

				--COPIA DA ORIGINAL EXISTENTE PARA 2019
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO
								, CAPACIDADE
								, EXERCICIO )
				SELECT 
				  ID
				, NUMERO_ATENDIDOS_MENSAL
				, 2019 -- Adicionado novo
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO 
				WHERE ID_USUARIO_TIPO_SERVICO <> 22
			END


			-----------------------------------------------------------------
			-----------------------------------------------------------------
			-- TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_PSC
			-----------------------------------------------------------------
			----------------------------------------------------------------
			PRINT 'CRIANDO A TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_PSC'
			----------------------------------------------------------------
			IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_PSC')
			BEGIN
				CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_PSC](
									[ID] [int] IDENTITY(1,1) NOT NULL,
									[ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] [int] NOT NULL,
									[CAPACIDADE] [int] NULL,
									[EXERCICIO] [int] NULL
				 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_PSC] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY] 

				ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_PSC]  WITH CHECK 
				ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_PSC_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] 
				FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO])
				REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] ([ID])
			END

			--------------------------------------------
			-- FUNCIONAMENTO
			--------------------------------------------
			IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_PSC)
			BEGIN
				--ORIGINAL EXISTENTE: VALORES DE 2018
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_PSC(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO
								, CAPACIDADE
								, EXERCICIO )
				SELECT 
				  ID
				, NUMERO_ATENDIDOS_MENSAL_SERVICO
				, 2018
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO 
				WHERE ID_USUARIO_TIPO_SERVICO = 22

				--COPIA DA ORIGINAL EXISTENTE PARA 2019
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_PSC(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO
								, CAPACIDADE
								, EXERCICIO )
				SELECT 
				  ID
				, NUMERO_ATENDIDOS_MENSAL_SERVICO
				, 2019 -- Adicionado novo
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO 
				WHERE ID_USUARIO_TIPO_SERVICO = 22
			END


			-----------------------------------------------------------------
			-----------------------------------------------------------------
			-- TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_LA
			-----------------------------------------------------------------
			----------------------------------------------------------------
			PRINT 'CRIANDO A TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_LA'
			----------------------------------------------------------------
			IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_LA')
			BEGIN
				CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_LA](
									[ID] [int] IDENTITY(1,1) NOT NULL,
									[ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] [int] NOT NULL,
									[CAPACIDADE] [int] NULL,
									[EXERCICIO] [int] NULL
				 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_LA] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY] 

				ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_LA]  WITH CHECK 
				ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_LA_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] 
				FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO])
				REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] ([ID])
			END

			--------------------------------------------
			-- FUNCIONAMENTO
			--------------------------------------------
			IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_LA)
			BEGIN
				--ORIGINAL EXISTENTE: VALORES DE 2018
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_LA(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO
								, CAPACIDADE
								, EXERCICIO )
				SELECT 
				  ID
				, NUMERO_ATENDIDOS_MENSAL
				, 2018
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO 
				WHERE ID_USUARIO_TIPO_SERVICO = 22

				--COPIA DA ORIGINAL EXISTENTE PARA 2019
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_LA(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO
								, CAPACIDADE
								, EXERCICIO )
				SELECT 
				  ID
				, NUMERO_ATENDIDOS_MENSAL
				, 2019 -- Adicionado novo
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO 
				WHERE ID_USUARIO_TIPO_SERVICO = 22
			END

			-----------------------------------------------------------------
			-----------------------------------------------------------------
			-- TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL
			-----------------------------------------------------------------
			----------------------------------------------------------------
			PRINT 'CRIANDO A TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL'
			----------------------------------------------------------------
			IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL')
			BEGIN
				CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL](
									[ID] [int] IDENTITY(1,1) NOT NULL,
									[ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] [int] NOT NULL,
									[MEDIA] [int] NULL,
									[EXERCICIO] [int] NULL
				 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY] 

				ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL]  WITH CHECK 
				ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] 
				FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO])
				REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] ([ID])
			END

			--------------------------------------------
			-- FUNCIONAMENTO
			--------------------------------------------
			IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL)
			BEGIN
	
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO
								, MEDIA
								, EXERCICIO )
				SELECT 
				  ID
				, MEDIA_MENSAL_ATENDIMENTO_2017
				, 2018
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO 
				WHERE ID_USUARIO_TIPO_SERVICO <> 22

	
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO
								, MEDIA
								, EXERCICIO )
				SELECT 
				  ID
				, MEDIA_MENSAL_ATENDIMENTO_2018
				, 2019 
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO 
				WHERE ID_USUARIO_TIPO_SERVICO <> 22
			END



			-----------------------------------------------------------------
			-----------------------------------------------------------------
			-- TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_PSC
			-----------------------------------------------------------------
			----------------------------------------------------------------
			PRINT 'CRIANDO A TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_PSC'
			----------------------------------------------------------------
			IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_PSC')
			BEGIN
				CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_PSC](
									[ID] [int] IDENTITY(1,1) NOT NULL,
									[ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] [int] NOT NULL,
									[MEDIA] [int] NULL,
									[EXERCICIO] [int] NULL
				 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_PSC] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY] 

				ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_PSC]  WITH CHECK 
				ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_PSC_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] 
				FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO])
				REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] ([ID])
			END

			--------------------------------------------
			-- FUNCIONAMENTO
			--------------------------------------------
			IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_PSC)
			BEGIN
	
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_PSC(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO
								, MEDIA
								, EXERCICIO )
				SELECT 
				  ID
				, MEDIA_MENSAL_ATENDIMENTO_PSC_2017
				, 2018
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO 
				WHERE ID_USUARIO_TIPO_SERVICO = 22

	
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_PSC(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO
								, MEDIA
								, EXERCICIO )
				SELECT 
				  ID
				, MEDIA_MENSAL_ATENDIMENTO_PSC_2018
				, 2019 -- Adicionado novo
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO 
				WHERE ID_USUARIO_TIPO_SERVICO = 22
			END


			-----------------------------------------------------------------
			-----------------------------------------------------------------
			-- TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_LA
			-----------------------------------------------------------------
			----------------------------------------------------------------
			PRINT 'CRIANDO A TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_LA'
			----------------------------------------------------------------
			IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_LA')
			BEGIN
				CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_LA](
									[ID] [int] IDENTITY(1,1) NOT NULL,
									[ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] [int] NOT NULL,
									[MEDIA] [int] NULL,
									[EXERCICIO] [int] NULL
				 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_LA] PRIMARY KEY CLUSTERED 
				(
					[ID] ASC
				)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
				) ON [PRIMARY] 

				ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_LA]  WITH CHECK 
				ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_LA_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] 
				FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO])
				REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] ([ID])
			END

			--------------------------------------------
			-- FUNCIONAMENTO
			--------------------------------------------
			IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_LA)
			BEGIN
	
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_LA(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO
								, MEDIA
								, EXERCICIO )
				SELECT 
				  ID
				, MEDIA_MENSAL_ATENDIMENTO_2017
				, 2018
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO 
				WHERE ID_USUARIO_TIPO_SERVICO = 22

	
				INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_LA(
								  ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO
								, MEDIA
								, EXERCICIO )
				SELECT 
				  ID
				, MEDIA_MENSAL_ATENDIMENTO_2018
				, 2019 -- Adicionado novo
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO 
				WHERE ID_USUARIO_TIPO_SERVICO = 22
			END

		COMMIT TRAN
	END
	END TRY 
BEGIN CATCH 
	SELECT  
		ERROR_NUMBER() AS ErrorNumber  
		,ERROR_SEVERITY() AS ErrorSeverity  
		,ERROR_STATE() AS ErrorState  
		,ERROR_PROCEDURE() AS ErrorProcedure  
		,ERROR_LINE() AS ErrorLine  
		,ERROR_MESSAGE() AS ErrorMessage;  
	ROLLBACK TRAN
END CATCH 

