USE [Dbpmas_quadrienal_PRODUCAO_OUTUBRO_2018]
GO

/****** Object:  View [dbo].[VW_CENTRO_POP]    Script Date: 24/10/2018 19:08:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[VW_CENTRO_POP]
AS
SELECT   C.ID
		 ,C.NOME
   		 ,C.ID_UNIDADE_PUBLICA AS ID_UNIDADE
		 ,C.COORDENADOR
		 , CASE (SELECT  COUNT(B.ID)  
			 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP B
			 LEFT JOIN  TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_CENTRO_POP B1
					ON(B.ID = B1.ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP AND B1.EXERCICIO = 2018)
			WHERE (B1.VALOR_ESTADUAL_ASSISTENCIA > 0 
			--OR B.VALOR_ESTADUALIZADO > 0
			)
              AND B.ID_CENTRO_POP = C.ID)   
		   WHEN 0   
		   THEN 'Não'   
		   ELSE 'Sim'   
		   END 'COFINANCIAMENTO'
		--,COUNT(R.ID) AS TOTAL_SERVICO
		  ,COALESCE((SELECT COUNT(RP.ID) FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP RP where RP.DESATIVADO = 0 AND RP.ID_CENTRO_POP = C.ID), 0) AS TOTAL_SERVICO
		 ,COALESCE((SELECT COUNT(RP.ID) FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP RP where RP.DESATIVADO = 1 AND RP.ID_CENTRO_POP = C.ID), 0) AS TOTAL_SERVICO_DESATIVADO
		,COALESCE(SUM(R1.VALOR_MUNICIPAL_ASSISTENCIA 
		+ R1.VALOR_MUNICIPAL_FMDCA 
		+ R1.VALOR_ESTADUAL_ASSISTENCIA 
		+ R1.VALOR_ESTADUAL_FEDCA 
		+ R1.VALOR_FEDERAL_ASSISTENCIA 
		+ R1.VALOR_FEDERAL_FNDCA 
		+ ISNULL(R1.VALOR_MUNICIPAL_FMI, 0.0) 
		+ ISNULL(R1.VALOR_ESTADUAL_FEI, 0.0) 
		+ ISNULL(R1.VALOR_FEDERAL_FNI, 0) 
		--+ COALESCE(R.VALOR_ESTADUALIZADO,0)
		),0) AS PREVISAO_ORCAMENTARIA
		--,COALESCE(SUM(R.VALOR_MUNICIPAL_ASSISTENCIA + R.VALOR_MUNICIPAL_FMDCA + R.VALOR_ESTADUAL_ASSISTENCIA + R.VALOR_ESTADUAL_FEDCA + R.VALOR_FEDERAL_ASSISTENCIA + R.VALOR_FEDERAL_FNDCA + COALESCE(R.VALOR_ESTADUALIZADO,0)),0) AS PREVISAO_ORCAMENTARIA
		,COALESCE(SUM(COALESCE(R1.VALOR_ESTADUAL_ASSISTENCIA ,0) 
		--+ COALESCE(R.VALOR_ESTADUALIZADO,0)
		),0)  AS VALOR_COFINANCIAMENTO_ESTADUAL
		,COALESCE(SUM(R.NUMERO_ATENDIDOS),0) AS NUMERO_ATENDIDOS
		,C.IDCREAS
		,C.DESATIVADO
		,C.ID_MOTIVO_DESATIVACAO 
		 ,CASE when C.DESATIVADO = 'True' AND  C.ID_MOTIVO_DESATIVACAO = 22
				then C.DATA_DESATIVACAO 
				ELSE C.DATA_REGISTRO_LOG END AS DATA_ENCERRAMENTO
		,C.DETALHAMENTO
		,M.DESCRICAO AS MOTIVO_DESATIVACAO
		,C.ID_MOTIVO_ENCERRAMENTO
		,(SELECT DESCRICAO FROM TB_MOTIVO_DESATIVACAO_LOCAL M where ID = C.ID_MOTIVO_ENCERRAMENTO) MOTIVO_ENCERRAMENTO
  FROM TB_CENTRO_POP C
  LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP R ON(R.ID_CENTRO_POP = C.ID)
  LEFT JOIN  TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_CENTRO_POP R1
	ON(R.ID = R1.ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP AND R1.EXERCICIO = 2018)
     LEFT JOIN TB_MOTIVO_DESATIVACAO_LOCAL M ON (C.ID_MOTIVO_DESATIVACAO = M.ID)   
  GROUP BY C.ID_UNIDADE_PUBLICA, C.ID, C.NOME, C.COORDENADOR, C.IDCREAS, C.DESATIVADO, C.ID_MOTIVO_DESATIVACAO, C.ID_MOTIVO_ENCERRAMENTO, M.DESCRICAO, C.DETALHAMENTO, C.DATA_DESATIVACAO, C.DATA_REGISTRO_LOG


GO


