USE [Dbpmas_quadrienal_PRODUCAO_OUTUBRO_2018]
GO

/****** Object:  View [dbo].[VW_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO]    Script Date: 24/10/2018 19:35:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[VW_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO]
  AS
  SELECT S.ID
		,S.ID_LOCAL_EXECUCAO_PUBLICO
		,S.ID_USUARIO_TIPO_SERVICO
		,U.NOME AS USUARIO
		,U.ID_TIPO_SERVICO
		,(CASE WHEN ID_TIPO_SERVICO_NAO_TIPIFICADO IS NOT NULL THEN ('Serviço não tipificado pela Resolução n° 109 do CNAS, de 11/11/2009 - '
		 + CASE WHEN DESCRICAO_NAO_TIPIFICADO IS NULL THEN T.NOME ELSE (
		  CASE WHEN ID_TIPO_PROTECAO = 3 THEN  DESCRICAO_NAO_TIPIFICADO ELSE( T.NOME + ' - ' + DESCRICAO_NAO_TIPIFICADO)END)END)
		 ELSE (T.NOME + (CASE WHEN DESCRICAO_NAO_TIPIFICADO IS NULL THEN '' ELSE ( + ' - ' + DESCRICAO_NAO_TIPIFICADO)END)) --(T.NOME)
		END)  AS TIPO_SERVICO
		,T.ID_TIPO_PROTECAO
		,P.NOME AS PROTECAO_SOCIAL
		,ISNULL(S.NUMERO_ATENDIDOS, 0) + ISNULL(S.NUMERO_ATENDIDOS_SERVICO,0) AS PREVISAO_ANUAL_NUMERO_ATENDIDOS
		,ISNULL(S.NUMERO_ATENDIDOS_MENSAL, 0) + ISNULL(S.NUMERO_ATENDIDOS_MENSAL_SERVICO,0) AS PREVISAO_MENSAL_NUMERO_ATENDIDOS
		,A.ABREVIACAO AS ABRANGENCIA
		--,S.SERVICO_ESTADUALIZADO
		,COALESCE((S1.VALOR_MUNICIPAL_ASSISTENCIA + 
					S1.VALOR_MUNICIPAL_FMDCA + 
					S1.VALOR_ESTADUAL_ASSISTENCIA + 
					S1.VALOR_ESTADUAL_FEDCA + 
					S1.VALOR_FEDERAL_ASSISTENCIA + 
					S1.VALOR_FEDERAL_FNDCA 
					+ ISNULL(S1.VALOR_MUNICIPAL_FMI, 0.0) 
					+ ISNULL(S1.VALOR_ESTADUAL_FEI, 0.0) 
					+ ISNULL(S1.VALOR_FEDERAL_FNI, 0) 
					--+ COALESCE(S.VALOR_ESTADUALIZADO,0)
					),0) AS PREVISAO_ORCAMENTARIA
		,(COALESCE(S1.VALOR_ESTADUAL_ASSISTENCIA,0) 
		--+ COALESCE(S.VALOR_ESTADUALIZADO,0)
		) AS VALOR_COFINANCIAMENTO_ESTADUAL
		,S.DATA_FUNCIONAMENTO_SERVICO
		,S.DESATIVADO
		,S.DATA_REGISTRO_LOG AS DATA_EXCLUSAO_SERVICO
		,S.ID_MOTIVO_DESATIVACAO
		,M.DESCRICAO AS MOTIVO_DESATIVACAO
		,S.DATA_DESATIVACAO AS DATA_ENCERRAMENTO_SERVICO
		,S.DETALHAMENTO AS DETALHAMENTO_ENCERRAMENTO
		,((Select Count(C.ID) FROM TB_PROGRAMA_PROJETO_COFINANCIAMENTO C 
		   where C.ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO = S.ID)
		 + (Select Count(C.ID) FROM TB_TRANSFERENCIA_RENDA_COFINANCIAMENTO C 
		 where C.ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO = S.ID)) AS TOTAL_SERVICOS_ASSOCIADOS 
  FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO S
  LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_PUBLICO S1 
	ON(S.ID = S1.ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO AND S1.EXERCICIO = 2019)
  INNER JOIN TB_USUARIO_TIPO_SERVICO U ON (U.ID = S.ID_USUARIO_TIPO_SERVICO)
  INNER JOIN TB_TIPO_SERVICO T ON(T.ID = U.ID_TIPO_SERVICO)
  INNER JOIN TB_TIPO_PROTECAO P ON(P.ID = T.ID_TIPO_PROTECAO)
  INNER JOIN TB_ABRANGENCIA_SERVICO A ON(A.ID = S.ID_ABRANGENCIA_SERVICO)
  LEFT JOIN [dbo].[TB_MOTIVO_DESATIVACAO_SERVICO] M ON (M.ID = S.ID_MOTIVO_DESATIVACAO) 

GO


