USE [Dbpmas_quadrienal_PRODUCAO_OUTUBRO_2018]
GO

/****** Object:  View [dbo].[VW_UNIDADE_PRIVADA]    Script Date: 25/10/2018 17:47:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER VIEW [dbo].[VW_UNIDADE_PRIVADA]
AS    
SELECT   T.ID
		 ,RAZAO_SOCIAL
		 ,INSCRICAO_CMAS
		 ,CNPJ
		 ,ID_PREFEITURA
		 ,(select COUNT(LP.ID) from TB_LOCAL_EXECUCAO_PRIVADO LP where LP.ID_UNIDADE_PRIVADA = T.ID and DESATIVADO = 'False') AS TOTAL_LOCAIS
		  ,(select COUNT(LP.ID) from TB_LOCAL_EXECUCAO_PRIVADO LP where LP.ID_UNIDADE_PRIVADA = T.ID and DESATIVADO = 'TRUE') AS TOTAL_LOCAIS_DESATIVADOS
		,CASE (
				SELECT  COUNT(A.ID)  
				FROM TB_LOCAL_EXECUCAO_PRIVADO A
					INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO B 
						ON(A.ID = B.ID_LOCAL_EXECUCAO_PRIVADO)			             
					INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_PRIVADO B1 
						ON(B.ID = B1.ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO AND B1.EXERCICIO = 2018)
				WHERE (B1.VALOR_ESTADUAL_ASSISTENCIA > 0)
					AND A.ID_UNIDADE_PRIVADA = T.ID)   
   WHEN 0   
   THEN 'Não'   
   ELSE 'Sim'   
   END 'COFINANCIAMENTO'		
		,CASE (  SELECT COUNT(B1.SERVICO_ESTADUALIZADO)
				 FROM TB_LOCAL_EXECUCAO_PRIVADO A
			     INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO B ON A.ID = B.ID_LOCAL_EXECUCAO_PRIVADO
				 LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_PRIVADO B1 ON(B.ID = B1.ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO)
				 WHERE A.ID_UNIDADE_PRIVADA = T.ID 
				 AND B1.SERVICO_ESTADUALIZADO = 1)
		WHEN 0
		  THEN 'Não'
		  ELSE 'Sim'   
    END 'ESTADUALIZADO'  
	,(
		SELECT COALESCE(SUM(COALESCE(S1.VALOR_ESTADUAL_ASSISTENCIA ,0) ),0) 
		FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO S
		INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_PRIVADO S1 ON(S.ID = S1.ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO AND S1.EXERCICIO = 2018)
		INNER JOIN TB_LOCAL_EXECUCAO_PRIVADO L ON(L.ID = S.ID_LOCAL_EXECUCAO_PRIVADO AND L.ID_UNIDADE_PRIVADA = T.ID)) AS VALOR_COFINANCIAMENTO_ESTADUAL		
	,(
		SELECT COALESCE(SUM(S.NUMERO_ATENDIDOS),0) 
		FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO S
		INNER JOIN TB_LOCAL_EXECUCAO_PRIVADO L ON(L.ID = S.ID_LOCAL_EXECUCAO_PRIVADO AND L.ID_UNIDADE_PRIVADA = T.ID)) AS NUMERO_ATENDIDOS		
	,(
			SELECT COALESCE(
				SUM(R1.VALOR_MUNICIPAL_ASSISTENCIA + 
					R1.VALOR_MUNICIPAL_FMDCA + 
					R1.VALOR_ESTADUAL_ASSISTENCIA + 
					R1.VALOR_ESTADUAL_FEDCA + 
					R1.VALOR_FEDERAL_ASSISTENCIA + 
					R1.VALOR_FEDERAL_FNDCA 
					+ ISNULL(R1.VALOR_MUNICIPAL_FMI, 0.0) 
					+ ISNULL(R1.VALOR_ESTADUAL_FEI, 0.0) 
					+ ISNULL(R1.VALOR_FEDERAL_FNI, 0.0) 
					+ COALESCE(R1.VALOR_ESTADUALIZADO,0) + 
					R.VALOR_PRIVADO_EMPRESAS + 
					R.VALOR_PRIVADO_PESSOAS_FISICAS + 
					R.VALOR_PRIVADO_ORGANIZACOES + 
					R.VALOR_PRIVADO_PROPRIOS),0) 
			FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO R
			INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_PRIVADO R1 ON(R.ID = R1.ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO AND R1.EXERCICIO = 2018)
			INNER JOIN TB_LOCAL_EXECUCAO_PRIVADO L ON(L.ID = R.ID_LOCAL_EXECUCAO_PRIVADO AND L.ID_UNIDADE_PRIVADA = T.ID)
	  ) AS PREVISAO_ORCAMENTARIA
		, dbo.fncConcatForma_atuacao(T.ID) AS 'FORMA_ATUACAO'
		, T.[DESATIVADO]
		, T.[ID_MOTIVO_DESATIVACAO]
    , CASE when T.DESATIVADO = 'True' AND  T.ID_MOTIVO_DESATIVACAO = 1
				then T.DATA_REGISTRO_LOG 
				ELSE T.DATA_DESATIVACAO  END AS DATA_DESATIVACAO
     ,T.[DETALHAMENTO]
     ,T.[DATA_REGISTRO_LOG]
 FROM TB_UNIDADE_PRIVADA AS T
	LEFT JOIN TB_LOCAL_EXECUCAO_PRIVADO L ON(L.ID_UNIDADE_PRIVADA = T.ID)
 GROUP BY T.ID,T.RAZAO_SOCIAL,T.CNPJ,T.ID_PREFEITURA, INSCRICAO_CMAS, T.DESATIVADO,T.[ID_MOTIVO_DESATIVACAO]
     ,T.[DATA_DESATIVACAO] ,T.[DETALHAMENTO] ,T.[DATA_REGISTRO_LOG]


GO


