USE [Dbpmas_quadrienal_PRODUCAO_OUTUBRO_2018]
GO

/****** Object:  View [dbo].[VW_LOCAIS_EXECUCAO_PRIVADO]    Script Date: 25/10/2018 17:55:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[VW_LOCAIS_EXECUCAO_PRIVADO]
AS
SELECT L.ID      
	,L.ID_UNIDADE_PRIVADA AS ID_UNIDADE
	--,L.TIPO_OFERTA_ATENDIMENTO AS TIPO_OFERTA_ATENDIMENTO
    ,L.NOME 
	,L.TECNICO_RESPONSAVEL
	--,COUNT(R.ID) AS TOTAL_SERVICO
	,COALESCE((SELECT COUNT(RP.ID) FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO RP where RP.DESATIVADO = 0 AND RP.ID_LOCAL_EXECUCAO_PRIVADO = L.ID), 0) AS TOTAL_SERVICO
	,COALESCE((SELECT COUNT(RP.ID) FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO RP where RP.DESATIVADO = 1 AND RP.ID_LOCAL_EXECUCAO_PRIVADO = L.ID), 0) AS TOTAL_SERVICO_DESATIVADO
    ,COALESCE(SUM(R1.VALOR_MUNICIPAL_ASSISTENCIA + 
				R1.VALOR_MUNICIPAL_FMDCA + 
				R1.VALOR_ESTADUAL_ASSISTENCIA + 
				R1.VALOR_ESTADUAL_FEDCA + 
				R1.VALOR_FEDERAL_ASSISTENCIA + 
				R1.VALOR_FEDERAL_FNDCA + 
				COALESCE(R1.VALOR_ESTADUALIZADO,0) + 
				R.VALOR_PRIVADO_EMPRESAS + 
				R.VALOR_PRIVADO_PESSOAS_FISICAS + 
				R.VALOR_PRIVADO_ORGANIZACOES + 
				R.VALOR_PRIVADO_PROPRIOS 
				+ ISNULL(R1.VALOR_MUNICIPAL_FMI, 0.0) 
				+ ISNULL(R1.VALOR_ESTADUAL_FEI, 0.0) 
				+ ISNULL(R1.VALOR_FEDERAL_FNI, 0)),0) AS PREVISAO_ORCAMENTARIA
 				,COALESCE(SUM(COALESCE(R1.VALOR_ESTADUAL_ASSISTENCIA,0)
				),0) AS VALOR_COFINANCIAMENTO_ESTADUAL
	,L.DESATIVADO
	,L.ID_MOTIVO_DESATIVACAO
	,M.DESCRICAO
	  	,CASE when L.DESATIVADO = 'True' AND  L.ID_MOTIVO_DESATIVACAO = 1
			then L.DATA_REGISTRO_LOG 
			ELSE L.DATA_DESATIVACAO  END AS DATA_ENCERRAMENTO
	,L.DETALHAMENTO AS DETALHAMENTO_ENCERRAMENTO
FROM TB_LOCAL_EXECUCAO_PRIVADO L
LEFT JOIN TB_MOTIVO_DESATIVACAO_LOCAL M ON (L.ID_MOTIVO_DESATIVACAO = M.ID)
LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO R ON(R.ID_LOCAL_EXECUCAO_PRIVADO = L.ID)  
LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_PRIVADO R1 ON(R.ID = R1.ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO AND R1.EXERCICIO = 2018)  
GROUP BY L.ID_UNIDADE_PRIVADA, L.TIPO_OFERTA_ATENDIMENTO, L.ID, L.NOME, L.TECNICO_RESPONSAVEL
,L.DESATIVADO
	,L.ID_MOTIVO_DESATIVACAO
	,L.DATA_DESATIVACAO
	,L.DATA_REGISTRO_LOG 
	,L.DETALHAMENTO
	,M.DESCRICAO


GO


