USE [Dbpmas_quadrienal_PRODUCAO_OUTUBRO_2018]
GO

/****** Object:  View [dbo].[VW_LOCAIS_EXECUCAO_PUBLICO]    Script Date: 25/10/2018 18:42:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER VIEW [dbo].[VW_LOCAIS_EXECUCAO_PUBLICO]
AS
SELECT L.ID      
	  ,L.ID_UNIDADE_PUBLICA AS ID_UNIDADE
      ,L.NOME 
	  ,L.TECNICO_RESPONSAVEL
	  ,COALESCE(
			(
				SELECT COUNT(RP.ID) 
				FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO RP 
				WHERE RP.DESATIVADO = 0 AND RP.ID_LOCAL_EXECUCAO_PUBLICO = L.ID), 0
			) AS TOTAL_SERVICO
	  ,COALESCE(
				(
					SELECT COUNT(RP.ID) 
					FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO RP 
					WHERE RP.DESATIVADO = 1 AND RP.ID_LOCAL_EXECUCAO_PUBLICO = L.ID), 0
				) AS TOTAL_SERVICO_DESATIVADO
      ,COALESCE(
					SUM(R1.VALOR_MUNICIPAL_ASSISTENCIA 
					+ R1.VALOR_MUNICIPAL_FMDCA 
					+ R1.VALOR_ESTADUAL_ASSISTENCIA 
					+ R1.VALOR_ESTADUAL_FEDCA 
					+ R1.VALOR_FEDERAL_ASSISTENCIA 
					+ R1.VALOR_FEDERAL_FNDCA 
					+ ISNULL(R1.VALOR_MUNICIPAL_FMI, 0.0) 
					+ ISNULL(R1.VALOR_ESTADUAL_FEI, 0.0) 
					+ ISNULL(R1.VALOR_FEDERAL_FNI, 0) 
					--+ COALESCE(R.VALOR_ESTADUALIZADO,0)
					),0
				) AS PREVISAO_ORCAMENTARIA
	  ,COALESCE(
			SUM(    COALESCE(R1.VALOR_ESTADUAL_ASSISTENCIA,0) 
			      --+ COALESCE(R.VALOR_ESTADUALIZADO,0)
				),0) AS VALOR_COFINANCIAMENTO_ESTADUAL
					,L.DESATIVADO
					,L.ID_MOTIVO_DESATIVACAO
					,M.DESCRICAO
					,CASE when L.DESATIVADO = 'True' AND  L.ID_MOTIVO_DESATIVACAO = 27
							then L.DATA_REGISTRO_LOG 
							ELSE L.DATA_DESATIVACAO  END AS DATA_ENCERRAMENTO
					,L.DETALHAMENTO AS DETALHAMENTO_ENCERRAMENTO
					,L.ID_MOTIVO_ENCERRAMENTO
	  ,(
	  SELECT DESCRICAO 
	  FROM TB_MOTIVO_DESATIVACAO_LOCAL M 
	  WHERE ID = L.ID_MOTIVO_ENCERRAMENTO) MOTIVO_ENCERRAMENTO
	  FROM TB_LOCAL_EXECUCAO_PUBLICO L
			LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO R ON(R.ID_LOCAL_EXECUCAO_PUBLICO = L.ID)  
			LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_PUBLICO R1 
			ON(R.ID = R1.ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO)  
			LEFT JOIN TB_MOTIVO_DESATIVACAO_LOCAL M ON (L.ID_MOTIVO_DESATIVACAO = M.ID)
  GROUP BY L.ID_UNIDADE_PUBLICA, L.ID, L.NOME, L.TECNICO_RESPONSAVEL,L.DESATIVADO, 
  L.ID_MOTIVO_DESATIVACAO, M.DESCRICAO, L.DATA_DESATIVACAO, L.DETALHAMENTO,L.ID_MOTIVO_ENCERRAMENTO,L.DETALHAMENTO,  L.DATA_REGISTRO_LOG



GO


