USE [Dbpmas_quadrienal_PRODUCAO_OUTUBRO_2018]
GO

/****** Object:  View [dbo].[VW_CRAS]    Script Date: 24/10/2018 19:13:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[VW_CRAS]
AS
SELECT   C.ID
		 ,C.NOME
   		 ,C.ID_UNIDADE_PUBLICA AS ID_UNIDADE
		 ,C.COORDENADOR		 
		 , CASE (SELECT  COUNT(B.ID)  
				 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS B
					LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_CRAS B1  
					ON(B.ID = B1.ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS AND B1.EXERCICIO = 2018)
			WHERE (
					B1.VALOR_ESTADUAL_ASSISTENCIA > 0 
					--OR B.VALOR_ESTADUALIZADO > 0
					)
              AND B.ID_CRAS = C.ID)   
		   WHEN 0   
		   THEN 'Não'   
		   ELSE 'Sim'   
		   END 'COFINANCIAMENTO'
		--,COUNT(R.ID) AS TOTAL_SERVICO
		  ,COALESCE((SELECT COUNT(RP.ID) FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS RP where RP.DESATIVADO = 0 AND RP.ID_CRAS = C.ID), 0) AS TOTAL_SERVICO
		  ,COALESCE((SELECT COUNT(RP.ID) FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS RP where RP.DESATIVADO = 1 AND RP.ID_CRAS = C.ID), 0) AS TOTAL_SERVICO_DESATIVADO
		 ,CASE when C.DESATIVADO = 'True' AND  C.ID_MOTIVO_DESATIVACAO = 10
				then C.DATA_DESATIVACAO 
				ELSE C.DATA_REGISTRO_LOG END AS DATA_ENCERRAMENTO
		,COALESCE(SUM(R1.VALOR_MUNICIPAL_ASSISTENCIA + 
					  R1.VALOR_MUNICIPAL_FMDCA + 
					  R1.VALOR_ESTADUAL_ASSISTENCIA + 
					  R1.VALOR_ESTADUAL_FEDCA + 
					  R1.VALOR_FEDERAL_ASSISTENCIA + 
					  R1.VALOR_FEDERAL_FNDCA 
					  + ISNULL(R1.VALOR_MUNICIPAL_FMI, 0.0) 
					  + ISNULL(R1.VALOR_ESTADUAL_FEI, 0.0) 
					  + ISNULL(R1.VALOR_FEDERAL_FNI, 0) 
					  --+ COALESCE(R.VALOR_ESTADUALIZADO,0)
					  ),0) AS PREVISAO_ORCAMENTARIA
		,COALESCE(SUM(
		  COALESCE(R1.VALOR_ESTADUAL_ASSISTENCIA ,0) 
		--+ COALESCE(R.VALOR_ESTADUALIZADO,0)
		),0)  AS VALOR_COFINANCIAMENTO_ESTADUAL
		,COALESCE(SUM(R.NUMERO_ATENDIDOS),0) AS NUMERO_ATENDIDOS
		,C.IDCRAS
		,C.DESATIVADO
		,C.ID_MOTIVO_DESATIVACAO
		,M.DESCRICAO as MOTIVO_DESATIVACAO
		,C.ID_MOTIVO_ENCERRAMENTO
		,C.DETALHAMENTO
		,(SELECT DESCRICAO FROM TB_MOTIVO_DESATIVACAO_LOCAL M where ID = C.ID_MOTIVO_ENCERRAMENTO) MOTIVO_ENCERRAMENTO
  FROM TB_CRAS C
  LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS R ON(R.ID_CRAS = C.ID) 
  LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_CRAS R1 
	ON(R.ID = R1.ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS AND R1.EXERCICIO = 2018)
   LEFT JOIN TB_MOTIVO_DESATIVACAO_LOCAL M ON (C.ID_MOTIVO_DESATIVACAO = M.ID) 
  GROUP BY C.ID_UNIDADE_PUBLICA, C.ID, C.NOME, C.COORDENADOR, C.IDCRAS,
		 C.DESATIVADO, C.DATA_DESATIVACAO,C.ID_MOTIVO_DESATIVACAO, C.DATA_REGISTRO_LOG,C.ID_MOTIVO_ENCERRAMENTO , m.DESCRICAO, C.DETALHAMENTO 

GO


