USE [Dbpmas_quadrienal_PRODUCAO_OUTUBRO_2018]
GO

/****** Object:  View [dbo].[VW_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP]    Script Date: 24/10/2018 19:27:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


--VISÃO DOS SERVIÇOS E RECURSOS FINANCEIROS CENTRO_POP
  ALTER VIEW [dbo].[VW_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP]
  AS
  SELECT S.ID
		,S.ID_CENTRO_POP
		,S.ID_USUARIO_TIPO_SERVICO
		,U.NOME AS USUARIO
		,U.ID_TIPO_SERVICO
		,((CASE WHEN DESCRICAO_NAO_TIPIFICADO IS NULL THEN T.NOME ELSE ('Serviço não tipificado pela Resolução nº 109 do CNAS, de 11/11/2009 - ' + T.NOME + ' - ' + DESCRICAO_NAO_TIPIFICADO)END))  AS TIPO_SERVICO
		,T.ID_TIPO_PROTECAO
		,P.NOME AS PROTECAO_SOCIAL
		,S.NUMERO_ATENDIDOS AS PREVISAO_ANUAL_NUMERO_ATENDIDOS
		,S.NUMERO_ATENDIDOS_MENSAL AS PREVISAO_MENSAL_NUMERO_ATENDIDOS
		,A.ABREVIACAO AS ABRANGENCIA
		--,S.SERVICO_ESTADUALIZADO
		,COALESCE((S1.VALOR_MUNICIPAL_ASSISTENCIA + 
		S1.VALOR_MUNICIPAL_FMDCA + 
		S1.VALOR_ESTADUAL_ASSISTENCIA + 
		S1.VALOR_ESTADUAL_FEDCA + 
		S1.VALOR_FEDERAL_ASSISTENCIA + 
		S1.VALOR_FEDERAL_FNDCA + 
		ISNULL(S1.VALOR_MUNICIPAL_FMI, 0.0) + 
		ISNULL(S1.VALOR_ESTADUAL_FEI, 0.0) + 
		ISNULL(S1.VALOR_FEDERAL_FNI, 0) 
		--+ COALESCE(S.VALOR_ESTADUALIZADO,0)
		),0) AS PREVISAO_ORCAMENTARIA
		,(COALESCE(S1.VALOR_ESTADUAL_ASSISTENCIA,0) 
		--+ COALESCE(S.VALOR_ESTADUALIZADO,0)
		) AS VALOR_COFINANCIAMENTO_ESTADUAL
		,S.DATA_FUNCIONAMENTO_SERVICO
		,S.DESATIVADO
		,S.DATA_REGISTRO_LOG AS DATA_EXCLUSAO_SERVICO
		,S.ID_MOTIVO_DESATIVACAO
		,M.DESCRICAO AS MOTIVO_DESATIVACAO
		,CASE WHEN (S.ID_MOTIVO_DESATIVACAO = 2 or S.ID_MOTIVO_DESATIVACAO = 3)
		THEN
		S.DATA_DESATIVACAO
		ELSE S.DATA_REGISTRO_LOG END AS DATA_ENCERRAMENTO_SERVICO
		,S.DETALHAMENTO AS DETALHAMENTO_ENCERRAMENTO
	 	,((Select Count(C.ID) FROM TB_PROGRAMA_PROJETO_COFINANCIAMENTO C 
		   where C.ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP = S.ID)
		 + (Select Count(C.ID) FROM TB_TRANSFERENCIA_RENDA_COFINANCIAMENTO C 
		 where C.ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP = S.ID)) AS TOTAL_SERVICOS_ASSOCIADOS 
  FROM [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP] S
  LEFT JOIN  TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_CENTRO_POP S1
	ON(S.ID = S1.ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP AND S1.EXERCICIO = 2018)
  INNER JOIN [dbo].[TB_USUARIO_TIPO_SERVICO] U ON (U.ID = S.ID_USUARIO_TIPO_SERVICO)
  INNER JOIN [dbo].[TB_TIPO_SERVICO] T ON(T.ID = U.ID_TIPO_SERVICO)
  INNER JOIN [dbo].[TB_TIPO_PROTECAO] P ON(P.ID = T.ID_TIPO_PROTECAO)
  INNER JOIN [dbo].[TB_ABRANGENCIA_SERVICO] A ON(A.ID = S.ID_ABRANGENCIA_SERVICO)
  LEFT JOIN [dbo].[TB_MOTIVO_DESATIVACAO_SERVICO] M ON (M.ID = S.ID_MOTIVO_DESATIVACAO) 


GO


