USE [Dbpmas_quadrienal]
GO

/****** Object:  View [dbo].[VW_REDE_SERVICOS_SOCIOASSISTENCIAIS]    Script Date: 06/05/2019 12:29:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[PR_RELATORIO_REDE_SERVICOS_SOCIOASSISTENCIAIS_DETALHAMENTO]
	@DATA_IMPLANTACAO DATE
AS
--DECLARE @DATA_IMPLANTACAO DATE = '2018-01-01 00:00:00'

SELECT 
	P.ID AS ID_PREFEITURA,
	--******** 
	--******** MUNICIPIO
	--******** 
	MUN.ID AS ID_MUNICIPIO,
	MUN.ID_DRADS,
	MUN.NOME AS MUNICIPIO,
	DRA.NOME AS DRADS,
	COALESCE(MUN.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
	DRA.ID_MACRO_REGIAO,
	P.ID_NIVEL_GESTAO,

	--******** 
	--******** ID PORTE 
	--******** 
	(CASE WHEN P.POPULACAO <= 20000 THEN 1
		WHEN   P.POPULACAO <= 50000 THEN 2
		WHEN   P.POPULACAO <= 100000 THEN 3
		WHEN   P.POPULACAO <= 900000 THEN 4
		ELSE 5
	END) AS ID_PORTE,
	--******** 
	--******** PORTE 
	--******** 
	(CASE WHEN P.POPULACAO <= 20000 THEN 'Pequeno I'
		WHEN   P.POPULACAO <= 50000 THEN 'Pequeno II'
		WHEN   P.POPULACAO <= 100000 THEN 'Médio'
		WHEN   P.POPULACAO <= 900000 THEN 'Grande'
		ELSE 'Metrópole'
	END) AS PORTE,
	'Rede direta' AS TIPO_UNIDADE,
	1 AS ID_TIPO_UNIDADE,
	UN.ID AS CODIGO_UNIDADE,
	ISNULL(L.ID_DISTRITOS_SAO_PAULO,0) AS ID_DISTRITOS_SAO_PAULO,
	DS.NOME AS DISTRITOS_SAO_PAULO,
	UN.CNPJ AS CNPJ,
	UN.RAZAO_SOCIAL AS UNIDADE_RESPONSAVEL,
	CAST(L.ID AS VARCHAR) AS ID_LOCAL,
	L.NOME AS LOCAL_EXECUCAO,
	L.CIDADE AS CIDADE,
	U.NOME AS USUARIOS,
	U.ID AS ID_USUARIO_TIPO_SERVICO,
	S.NAO_TIPIFICADO,
	--******** 
	--******** TIPO DE SERVICO 
	--******** 
	(CASE WHEN R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL AND  R.DESCRICAO_NAO_TIPIFICADO <> '' AND TP.ID <> 3 AND S.NAO_TIPIFICADO IS NOT NULL  THEN  'Serviço não tipificado - ' + S.NOME + ' - ' + R.DESCRICAO_NAO_TIPIFICADO 
			WHEN TP.ID = 3 AND R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL THEN 'Serviço não tipificado - ' + R.DESCRICAO_NAO_TIPIFICADO 
			WHEN S.NAO_TIPIFICADO IS NOT NULL THEN 'Servico não tipificado - ' + S.NOME 
			ELSE S.NOME END)  AS TIPO_SERVICO,
	S.ID AS ID_TIPO_SERVICO,
	TP.NOME AS PROTECAO_SOCIAL,
	TP.ID AS ID_TIPO_PROTECAO,
	SX.ID AS ID_SEXO,
	SX.NOME AS SEXO,
	RM.ID AS ID_REGIAO_MORADIA,
	(CASE WHEN RM.ID = 3 THEN 'Zona Urbana e Rural' ELSE RM.NOME END) AS REGIAO_MORADIA,
	CT.ID AS ID_CARACTERISTICAS_TERRITORIO,
	CT.NOME AS CARACTERISTICAS_TERRITORIO,
	SE.ID_SITUACAO_ESPECIFICA,
	STE.NOME AS SITUACAO_ESPECIFICA,
	STE.ID_SITUACAO_VULNERABILIDADE,
	SV.NOME AS SITUACAO_VULNERABILIDADE,
	--******** 
	--******** RECURSOS (POR EXERCICIO)
	--******** 
	R1.VALOR_MUNICIPAL_ASSISTENCIA AS VALOR_FMAS,
	R1.VALOR_MUNICIPAL_FMDCA AS VALOR_FMDCA,
	R1.VALOR_ESTADUAL_ASSISTENCIA AS VALOR_FEAS,
	ISNULL(R1.VALOR_ESTADUAL_ASSISTENCIA_ANO_ANTERIOR, 0.0) AS VALOR_FEAS_ANO_ANTERIOR,
	R1.VALOR_ESTADUAL_FEDCA AS VALOR_FEDCA,
	R1.VALOR_FEDERAL_ASSISTENCIA AS VALOR_FNAS,
	R1.VALOR_FEDERAL_FNDCA AS VALOR_FNDCA,
	0 AS VALOR_PRIVADO,
	ISNULL(R1.VALOR_MUNICIPAL_FMI, 0.0) AS VALOR_FMI,
	ISNULL(R1.VALOR_ESTADUAL_FEI, 0.0) AS VALOR_FEI,
	ISNULL(R1.VALOR_FEDERAL_FNI, 0.0) AS VALOR_FNI,
	0 AS VALOR_ESTADUALIZADO,
	--******** 
	--******** Abrangencia
	--******** 
	A.ABREVIACAO AS ABRANGENCIA,
	A.ID AS ID_ABRANGENCIA,
	--******** 
	--******** NUMERO DE ATENDIDOS
	--******** 
	COALESCE((R.NUMERO_ATENDIDOS_MENSAL), 0) AS NUMERO_ATENDIDOS_MENSAL, 
	COALESCE((R.NUMERO_ATENDIDOS_MENSAL_SERVICO), 0) NUMERO_ATENDIDOS_SERVICO_MENSAL,
	COALESCE((R.NUMERO_ATENDIDOS), 0) AS  NUMERO_ATENDIDOS_ANUAL, 
	COALESCE((R.NUMERO_ATENDIDOS_SERVICO), 0)  AS  NUMERO_ATENDIDOS_SERVICO_ANUAL,
	R.TOTAL_FUNCIONARIOS AS TOTAL_TRABALHADORES_SERVICO,
	COALESCE((RH.SEM_ESCOLARIZACAO + RH.NIVEL_FUNDAMENTAL + RH.NIVEL_MEDIO + RH.NIVEL_SUPERIOR),0) AS TOTAL_TRABALHADORES,

	AT.ID_ATIVIDADE_SOCIOASSISTENCIAL,
	ATS.NOME AS ATIVIDADE_SOCIOASSISTENCIAL,
	COALESCE(
		(SELECT SUM(FR.[VALOR_FONTE_RECURSO]) 
		FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_FONTE_RECURSOS FR 
		WHERE FR.ID_SERVICO_RECURSO_FINANCEIRO_FUNDO_PUBLICO = R1.ID
		),0.0) AS VALOR_FONTE_RECURSO,

	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2017, 0) AS MEDIA_MENSAL_ATENDIMENTO_2017,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2018, 0) AS MEDIA_MENSAL_ATENDIMENTO_2018,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2019, 0) AS MEDIA_MENSAL_ATENDIMENTO_2019,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2020, 0) AS MEDIA_MENSAL_ATENDIMENTO_2020,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2017, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2017,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2018, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2018,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2019, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2019,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2020, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2020
	
FROM TB_PREFEITURA P
	JOIN DBSEDS.DBO.TB_MUNICIPIOS MUN (NOLOCK) ON P.ID_MUNICIPIO = MUN.ID
	JOIN DBSEDS.DBO.TB_DRADS DRA (NOLOCK) ON MUN.ID_DRADS = DRA.ID
	INNER JOIN TB_UNIDADE_PUBLICA UN ON(UN.ID_PREFEITURA = P.ID)
	INNER JOIN TB_LOCAL_EXECUCAO_PUBLICO L ON(L.ID_UNIDADE_PUBLICA = UN.ID)
	INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO R ON(R.ID_LOCAL_EXECUCAO_PUBLICO = L.ID) AND DATA_FUNCIONAMENTO_SERVICO < @DATA_IMPLANTACAO AND (R.DATA_DESATIVACAO > @DATA_IMPLANTACAO OR R.DATA_DESATIVACAO IS NULL)
	INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_PUBLICO R1 ON(R.ID = R1.ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO)
	INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_RH RH ON (RH.ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO = R.ID)
	INNER JOIN TB_ABRANGENCIA_SERVICO A ON(R.ID_ABRANGENCIA_SERVICO = A.ID)
	INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICOxSITUACAO_ESPECIFICA SE ON(SE.ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO = R.ID)
	INNER JOIN TB_SITUACAO_ESPECIFICA STE ON(STE.ID = SE.ID_SITUACAO_ESPECIFICA)
	INNER JOIN TB_SITUACAO_VULNERABILIDADE SV ON(STE.ID_SITUACAO_VULNERABILIDADE = SV.ID)
	INNER JOIN TB_USUARIO_TIPO_SERVICO U ON (R.ID_USUARIO_TIPO_SERVICO = U.ID)
	INNER JOIN TB_TIPO_SERVICO S ON (U.ID_TIPO_SERVICO = S.ID)
	INNER JOIN TB_TIPO_PROTECAO TP ON(TP.ID = S.ID_TIPO_PROTECAO)
	INNER JOIN TB_SEXO SX ON(SX.ID = R.ID_SEXO)
	INNER JOIN TB_REGIAO_MORADIA RM ON(RM.ID = R.ID_REGIAO_MORADIA)
	INNER JOIN TB_CARACTERISTICAS_TERRITORIO CT ON(CT.ID = R.ID_CARACTERISTICAS_TERRITORIO)
	INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICOxATIVIDADE_SOCIOASSISTENCIAL AT ON (AT.ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO = R.ID)
	INNER JOIN TB_ATIVIDADE_SOCIOASSISTENCIAL ATS ON (ATS.ID = AT.ID_ATIVIDADE_SOCIOASSISTENCIAL)
	LEFT JOIN TB_DISTRITOS_SAO_PAULO DS ON (DS.ID = L.ID_DISTRITOS_SAO_PAULO) 
	
	
UNION ALL

SELECT DISTINCT
	P.ID AS ID_PREFEITURA,
	--******** 
	--******** MUNICIPIO
	--******** 
	MUN.ID AS ID_MUNICIPIO,
	MUN.ID_DRADS,
	MUN.NOME AS MUNICIPIO,
	DRA.NOME AS DRADS,
	COALESCE(MUN.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
	DRA.ID_MACRO_REGIAO,
	P.ID_NIVEL_GESTAO,
	--******** 
	--******** ID PORTE
	--******** 
	(CASE WHEN P.POPULACAO <= 20000 THEN 1
		WHEN   P.POPULACAO <= 50000 THEN 2
		WHEN   P.POPULACAO <= 100000 THEN 3
		WHEN   P.POPULACAO <= 900000 THEN 4
		ELSE 5
	END) AS ID_PORTE,
	--******** 
	--******** PORTE
	--******** 
	(CASE WHEN P.POPULACAO <= 20000 THEN 'Pequeno I'
		WHEN   P.POPULACAO <= 50000 THEN 'Pequeno II'
		WHEN   P.POPULACAO <= 100000 THEN 'Médio'
		WHEN   P.POPULACAO <= 900000 THEN 'Grande'
		ELSE 'Metrópole'
	END) AS PORTE,
	'Rede indireta' AS TIPO_UNIDADE,
	2 AS ID_TIPO_UNIDADE,
	UN.ID AS CODIGO_UNIDADE,
	isnull(L.ID_DISTRITOS_SAO_PAULO,0) AS ID_DISTRITOS_SAO_PAULO,
	NULL AS DISTRITO_SAO_PAULO,
	UN.CNPJ AS CNPJ,
	UN.RAZAO_SOCIAL AS UNIDADE_RESPONSAVEL,
	CAST(L.ID AS VARCHAR) AS ID_LOCAL,
	L.NOME AS LOCAL_EXECUCAO,
	L.CIDADE AS CIDADE,
	U.NOME AS USUARIOS,
	U.ID AS ID_USUARIO_TIPO_SERVICO,
	S.NAO_TIPIFICADO,
	(CASE WHEN R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL AND  R.DESCRICAO_NAO_TIPIFICADO <> '' AND TP.ID <> 3 AND S.NAO_TIPIFICADO IS NOT NULL  THEN  'Serviço não tipificado - ' + S.NOME + ' - ' + R.DESCRICAO_NAO_TIPIFICADO 
			WHEN TP.ID = 3 AND R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL THEN 'Serviço não tipificado - ' + R.DESCRICAO_NAO_TIPIFICADO 
			WHEN S.NAO_TIPIFICADO IS NOT NULL THEN 'Servico não tipificado - ' + S.NOME 
			ELSE S.NOME END)  AS TIPO_SERVICO,

	S.ID AS ID_TIPO_SERVICO,
	TP.NOME AS PROTECAO_SOCIAL,
	TP.ID AS ID_TIPO_PROTECAO,
	SX.ID AS ID_SEXO,
	SX.NOME AS SEXO,
	RM.ID AS ID_REGIAO_MORADIA,
	(CASE WHEN RM.ID = 3 THEN 'Zona Urbana e Rural' ELSE RM.NOME END) AS REGIAO_MORADIA,
	CT.ID AS ID_CARACTERISTICAS_TERRITORIO,
	CT.NOME AS CARACTERISTICAS_TERRITORIO,
	SE.ID_SITUACAO_ESPECIFICA,
	STE.NOME AS SITUACAO_ESPECIFICA,
	STE.ID_SITUACAO_VULNERABILIDADE,
	SV.NOME AS SITUACAO_VULNERABILIDADE,
	--******** 
	--******** RECURSOS (PELO EXERCICIO)
	--******** 
	R1.VALOR_MUNICIPAL_ASSISTENCIA AS VALOR_FMAS,
	R1.VALOR_MUNICIPAL_FMDCA AS VALOR_FMDCA,
	R1.VALOR_ESTADUAL_ASSISTENCIA AS VALOR_FEAS,
	ISNULL(R1.VALOR_ESTADUAL_ASSISTENCIA_ANO_ANTERIOR, 0.0) AS VALOR_FEAS_ANO_ANTERIOR,
	R1.VALOR_ESTADUAL_FEDCA AS VALOR_FEDCA,
	R1.VALOR_FEDERAL_ASSISTENCIA AS VALOR_FNAS,
	R1.VALOR_FEDERAL_FNDCA AS VALOR_FNDCA,
	(R.VALOR_PRIVADO_EMPRESAS + R.VALOR_PRIVADO_ORGANIZACOES + R.VALOR_PRIVADO_PESSOAS_FISICAS + R.VALOR_PRIVADO_PROPRIOS) AS VALOR_PRIVADO,
	COALESCE(R1.VALOR_ESTADUALIZADO,0) AS VALOR_ESTADUALIZADO,
	isnull(R1.VALOR_MUNICIPAL_FMI, 0.0) AS VALOR_FMI,
	isnull(R1.VALOR_ESTADUAL_FEI, 0.0) AS VALOR_FEI,
	isnull(R1.VALOR_FEDERAL_FNI, 0.0) AS VALOR_FNI,
	--******** 
	--******** NUMERO ATENDIDOS
	--******** 
	A.ABREVIACAO AS ABRANGENCIA,
	A.ID AS ID_ABRANGENCIA,
	COALESCE((R.NUMERO_ATENDIDOS_MENSAL), 0) AS NUMERO_ATENDIDOS_MENSAL,
	COALESCE((R.NUMERO_ATENDIDOS_MENSAL_SERVICO), 0) AS  NUMERO_ATENDIDOS_MENSAL_SERVICO ,
	COALESCE((R.NUMERO_ATENDIDOS), 0)  AS  NUMERO_ATENDIDOS_ANUAL, 
	COALESCE((R.NUMERO_ATENDIDOS_SERVICO), 0) as NUMERO_ATENDIDOS_SERVICO_ANUAL,
	--R.NUMERO_ATENDIDOS AS NUMERO_ATENDIDOS_ANUAL,
	R.TOTAL_FUNCIONARIOS AS TOTAL_TRABALHADORES_SERVICO,
	COALESCE((RH.SEM_ESCOLARIZACAO + RH.NIVEL_FUNDAMENTAL + RH.NIVEL_MEDIO + RH.NIVEL_SUPERIOR),0) AS TOTAL_TRABALHADORES,
	
	AT.ID_ATIVIDADE_SOCIOASSISTENCIAL,
	ATS.NOME AS ATIVIDADE_SOCIOASSISTENCIAL,

	COALESCE(
			 (SELECT SUM(FR.[VALOR_FONTE_RECURSO]) 
			  FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_FONTE_RECURSOS FR 
			  WHERE FR.ID_SERVICO_RECURSO_FINANCEIRO_FUNDO_PRIVADO = R1.ID
			  )
	,0.0) AS VALOR_FONTE_RECURSO,

	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2017, 0) AS MEDIA_MENSAL_ATENDIMENTO_2017,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2018, 0) AS MEDIA_MENSAL_ATENDIMENTO_2018,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2019, 0) AS MEDIA_MENSAL_ATENDIMENTO_2019,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2020, 0) AS MEDIA_MENSAL_ATENDIMENTO_2020,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2017, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2017,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2018, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2018,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2019, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2019,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2020, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2020
	
FROM TB_PREFEITURA P
	JOIN DBSEDS.DBO.TB_MUNICIPIOS MUN (NOLOCK) ON P.ID_MUNICIPIO = MUN.ID
	JOIN DBSEDS.DBO.TB_DRADS DRA (NOLOCK) ON MUN.ID_DRADS = DRA.ID
	INNER JOIN TB_UNIDADE_PRIVADA UN ON(UN.ID_PREFEITURA = P.ID)
	INNER JOIN TB_LOCAL_EXECUCAO_PRIVADO L ON(L.ID_UNIDADE_PRIVADA = UN.ID)
	INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO R ON(R.ID_LOCAL_EXECUCAO_PRIVADO = L.ID) AND (DATA_FUNCIONAMENTO_SERVICO < @DATA_IMPLANTACAO AND (R.DATA_DESATIVACAO > @DATA_IMPLANTACAO OR R.DATA_DESATIVACAO IS NULL))
	INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_PRIVADO R1 ON(R.ID = R1.ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO)
	INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_RH RH ON (RH.ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO = R.ID)
	INNER JOIN TB_ABRANGENCIA_SERVICO A ON(R.ID_ABRANGENCIA_SERVICO = A.ID)
	INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADOxSITUACAO_ESPECIFICA SE ON(SE.ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO = R.ID)
	INNER JOIN TB_SITUACAO_ESPECIFICA STE ON(STE.ID = SE.ID_SITUACAO_ESPECIFICA)
	INNER JOIN TB_SITUACAO_VULNERABILIDADE SV ON(STE.ID_SITUACAO_VULNERABILIDADE = SV.ID)
	INNER JOIN TB_USUARIO_TIPO_SERVICO U ON (R.ID_USUARIO_TIPO_SERVICO = U.ID)
	INNER JOIN TB_TIPO_SERVICO S ON (U.ID_TIPO_SERVICO = S.ID)
	INNER JOIN TB_TIPO_PROTECAO TP ON(TP.ID = S.ID_TIPO_PROTECAO)
	INNER JOIN TB_SEXO SX ON(SX.ID = R.ID_SEXO)
	INNER JOIN TB_REGIAO_MORADIA RM ON(RM.ID = R.ID_REGIAO_MORADIA)
	INNER JOIN TB_CARACTERISTICAS_TERRITORIO CT ON(CT.ID = R.ID_CARACTERISTICAS_TERRITORIO)
	INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADOxATIVIDADE_SOCIOASSISTENCIAL AT ON (AT.ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO = R.ID)
	INNER JOIN TB_ATIVIDADE_SOCIOASSISTENCIAL ATS ON (ATS.ID = AT.ID_ATIVIDADE_SOCIOASSISTENCIAL)
	LEFT JOIN TB_DISTRITOS_SAO_PAULO DS ON (DS.ID = L.ID_DISTRITOS_SAO_PAULO)
	

UNION ALL

SELECT 
	P.ID AS ID_PREFEITURA,
	--******** 
	--******** MUNICIPIO
	--******** 
	MUN.ID AS ID_MUNICIPIO,
	MUN.ID_DRADS,
	MUN.NOME AS MUNICIPIO,
	DRA.NOME AS DRADS,
	COALESCE(MUN.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
	DRA.ID_MACRO_REGIAO,
	P.ID_NIVEL_GESTAO,
	--******** 
	--******** ID PORTE
	--******** 
	(CASE WHEN P.POPULACAO <= 20000 THEN 1
		WHEN   P.POPULACAO <= 50000 THEN 2
		WHEN   P.POPULACAO <= 100000 THEN 3
		WHEN   P.POPULACAO <= 900000 THEN 4
		ELSE 5
	END) AS ID_PORTE,
	--******** 
	--******** PORTE
	--******** 
	(CASE WHEN P.POPULACAO <= 20000 THEN 'Pequeno I'
		WHEN   P.POPULACAO <= 50000 THEN 'Pequeno II'
		WHEN   P.POPULACAO <= 100000 THEN 'Médio'
		WHEN   P.POPULACAO <= 900000 THEN 'Grande'
		ELSE 'Metrópole'
	END) AS PORTE,
	'Rede direta' AS TIPO_UNIDADE,
	3 AS ID_TIPO_UNIDADE,
	C.ID AS CODIGO_UNIDADE,
	COALESCE(C.ID_DISTRITOS_SAO_PAULO, -1) AS ID_DISTRITOS_SAO_PAULO,
	DS.NOME AS DISTRITO_SAO_PAULO,
	UP.CNPJ AS CNPJ,
	UP.RAZAO_SOCIAL AS UNIDADE_RESPONSAVEL,
	C.IDCRAS AS ID_LOCAL,
	C.NOME AS LOCAL_EXECUCAO,
	C.CIDADE AS CIDADE,
	U.NOME AS USUARIOS,
	U.ID AS ID_USUARIO_TIPO_SERVICO,
	S.NAO_TIPIFICADO,
	(CASE WHEN R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL AND  R.DESCRICAO_NAO_TIPIFICADO <> '' AND TP.ID <> 3 AND S.NAO_TIPIFICADO IS NOT NULL  THEN  'Serviço não tipificado - ' + S.NOME + ' - ' + R.DESCRICAO_NAO_TIPIFICADO 
			WHEN TP.ID = 3 AND R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL THEN 'Serviço não tipificado - ' + R.DESCRICAO_NAO_TIPIFICADO 
			WHEN S.NAO_TIPIFICADO IS NOT NULL THEN 'Servico não tipificado - ' + S.NOME 
			ELSE S.NOME END)  AS TIPO_SERVICO,
	S.ID AS ID_TIPO_SERVICO,
	TP.NOME AS PROTECAO_SOCIAL,
	TP.ID AS ID_TIPO_PROTECAO,
	SX.ID AS ID_SEXO,
	SX.NOME AS SEXO,
	RM.ID AS ID_REGIAO_MORADIA,
	(CASE WHEN RM.ID = 3 THEN 'Zona Urbana e Rural' ELSE RM.NOME END) AS REGIAO_MORADIA,
	CT.ID AS ID_CARACTERISTICAS_TERRITORIO,
	CT.NOME AS CARACTERISTICAS_TERRITORIO,
	SE.ID_SITUACAO_ESPECIFICA,
	STE.NOME AS SITUACAO_ESPECIFICA,
	STE.ID_SITUACAO_VULNERABILIDADE,
	SV.NOME AS SITUACAO_VULNERABILIDADE,
	--******** 
	--******** RECURSOS ( POE EXERCICIO)
	--******** 
	R1.VALOR_MUNICIPAL_ASSISTENCIA AS VALOR_FMAS,
	R1.VALOR_MUNICIPAL_FMDCA AS VALOR_FMDCA,
	R1.VALOR_ESTADUAL_ASSISTENCIA AS VALOR_FEAS,
	ISNULL(R1.VALOR_ESTADUAL_ASSISTENCIA_ANO_ANTERIOR, 0.0) AS VALOR_FEAS_ANO_ANTERIOR,
	R1.VALOR_ESTADUAL_FEDCA AS VALOR_FEDCA,
	R1.VALOR_FEDERAL_ASSISTENCIA AS VALOR_FNAS,
	R1.VALOR_FEDERAL_FNDCA AS VALOR_FNDCA,
	ISNULL(R1.VALOR_MUNICIPAL_FMI, 0.0) AS VALOR_FMI,
	ISNULL(R1.VALOR_ESTADUAL_FEI, 0.0) AS VALOR_FEI,
	ISNULL(R1.VALOR_FEDERAL_FNI, 0.0) AS VALOR_FNI,
	0 AS VALOR_PRIVADO,
	0 AS VALOR_ESTADUALIZADO,

	A.ABREVIACAO AS ABRANGENCIA,
	A.ID AS ID_ABRANGENCIA,
	--******** 
	--******** NUMERO ATENDIDOS
	--******** 
	COALESCE((R.NUMERO_ATENDIDOS_MENSAL), 0) AS NUMERO_ATENDIDOS_MENSAL,
	0 AS NUMERO_ATENDIDOS_SERVICO_MENSAL,
	COALESCE((R.NUMERO_ATENDIDOS), 0)  AS  NUMERO_ATENDIDOS_ANUAL,
	0 AS NUMERO_ATENDIDOS_SERVICO_ANUAL,
	R.TOTAL_FUNCIONARIOS AS TOTAL_TRABALHADORES_SERVICO,
	COALESCE((RH.SEM_ESCOLARIZACAO + RH.NIVEL_FUNDAMENTAL + RH.NIVEL_MEDIO + RH.NIVEL_SUPERIOR),0) AS TOTAL_TRABALHADORES,
	
	AT.ID_ATIVIDADE_SOCIOASSISTENCIAL,
	ATS.NOME AS ATIVIDADE_SOCIOASSISTENCIAL,

	COALESCE(
		(	SELECT SUM(FR.[VALOR_FONTE_RECURSO]) 
			FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_FONTE_RECURSOS FR 
			WHERE FR.ID_SERVICO_RECURSO_FINANCEIRO_FUNDO_CRAS = R1.ID

		),0.0) AS VALOR_FONTE_RECURSO,

	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2017, 0) AS MEDIA_MENSAL_ATENDIMENTO_2017,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2018, 0) AS MEDIA_MENSAL_ATENDIMENTO_2018,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2019, 0) AS MEDIA_MENSAL_ATENDIMENTO_2019,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2020, 0) AS MEDIA_MENSAL_ATENDIMENTO_2020,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2017, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2017,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2018, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2018,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2019, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2019,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2020, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2020
FROM TB_PREFEITURA P
	JOIN DBSEDS.DBO.TB_MUNICIPIOS MUN (NOLOCK) ON P.ID_MUNICIPIO = MUN.ID
	JOIN DBSEDS.DBO.TB_DRADS DRA (NOLOCK) ON MUN.ID_DRADS = DRA.ID
	INNER JOIN TB_UNIDADE_PUBLICA UP ON(UP.ID_PREFEITURA = P.ID)
	INNER JOIN TB_CRAS C ON(C.ID_UNIDADE_PUBLICA = UP.ID)
	INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS R ON(R.ID_CRAS = C.ID) AND (DATA_FUNCIONAMENTO_SERVICO < @DATA_IMPLANTACAO AND (R.DATA_DESATIVACAO > @DATA_IMPLANTACAO OR R.DATA_DESATIVACAO IS NULL))
	INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_CRAS R1 ON(R.ID = R1.ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS)
	INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_RH RH ON (RH.ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS = R.ID)
	INNER JOIN TB_ABRANGENCIA_SERVICO A ON(R.ID_ABRANGENCIA_SERVICO = A.ID)
	INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CRASxSITUACAO_ESPECIFICA SE ON(SE.ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS = R.ID)
	INNER JOIN TB_SITUACAO_ESPECIFICA STE ON(STE.ID = SE.ID_SITUACAO_ESPECIFICA)
	INNER JOIN TB_SITUACAO_VULNERABILIDADE SV ON(STE.ID_SITUACAO_VULNERABILIDADE = SV.ID)
	INNER JOIN TB_USUARIO_TIPO_SERVICO U ON (R.ID_USUARIO_TIPO_SERVICO = U.ID)
	INNER JOIN TB_TIPO_SERVICO S ON (U.ID_TIPO_SERVICO = S.ID)
	INNER JOIN TB_TIPO_PROTECAO TP ON(TP.ID = S.ID_TIPO_PROTECAO)
	INNER JOIN TB_SEXO SX ON(SX.ID = R.ID_SEXO)
	INNER JOIN TB_REGIAO_MORADIA RM ON(RM.ID = R.ID_REGIAO_MORADIA)
	INNER JOIN TB_CARACTERISTICAS_TERRITORIO CT ON(CT.ID = R.ID_CARACTERISTICAS_TERRITORIO)
	INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CRASxATIVIDADE_SOCIOASSISTENCIAL AT ON (AT.ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS = R.ID)
	INNER JOIN TB_ATIVIDADE_SOCIOASSISTENCIAL ATS ON (ATS.ID = AT.ID_ATIVIDADE_SOCIOASSISTENCIAL)
	LEFT JOIN TB_DISTRITOS_SAO_PAULO DS ON (DS.ID = C.ID_DISTRITOS_SAO_PAULO)
	

UNION ALL

SELECT 
	P.ID AS ID_PREFEITURA,
	--******** 
	--******** MUNICIPIO
	--******** 
	MUN.ID AS ID_MUNICIPIO,
	MUN.ID_DRADS,
	MUN.NOME AS MUNICIPIO,
	DRA.NOME AS DRADS,
	COALESCE(MUN.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
	DRA.ID_MACRO_REGIAO,
	P.ID_NIVEL_GESTAO,
	--******** 
	--******** ID PORTE
	--******** 
	(CASE WHEN P.POPULACAO <= 20000 THEN 1
		WHEN   P.POPULACAO <= 50000 THEN 2
		WHEN   P.POPULACAO <= 100000 THEN 3
		WHEN   P.POPULACAO <= 900000 THEN 4
		ELSE 5
	END) AS ID_PORTE,
	--******** 
	--******** PORTE
	--******** 
	(CASE WHEN P.POPULACAO <= 20000 THEN 'Pequeno I'
		WHEN   P.POPULACAO <= 50000 THEN 'Pequeno II'
		WHEN   P.POPULACAO <= 100000 THEN 'Médio'
		WHEN   P.POPULACAO <= 900000 THEN 'Grande'
		ELSE 'Metrópole'
	END) AS PORTE,
	'Rede direta' AS TIPO_UNIDADE,
	4 AS ID_TIPO_UNIDADE,
	C.ID AS CODIGO_UNIDADE,
	COALESCE(C.ID_DISTRITOS_SAO_PAULO, -1) AS ID_DISTRITOS_SAO_PAULO,
	DS.NOME AS DISTRITO_SAO_PAULO,
	UP.CNPJ AS CNPJ,
	UP.RAZAO_SOCIAL AS UNIDADE_RESPONSAVEL,
	C.IDCREAS AS ID_LOCAL,
	C.NOME AS LOCAL_EXECUCAO,
	C.CIDADE AS CIDADE,
	U.NOME AS USUARIOS,
	U.ID AS ID_USUARIO_TIPO_SERVICO,
	S.NAO_TIPIFICADO,
	--******** 
	--******** TIPO SERVICO
	--******** 
	(CASE WHEN R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL AND  R.DESCRICAO_NAO_TIPIFICADO <> '' AND TP.ID <> 3 AND S.NAO_TIPIFICADO IS NOT NULL  THEN  'Serviço não tipificado - ' + S.NOME + ' - ' + R.DESCRICAO_NAO_TIPIFICADO 
			WHEN TP.ID = 3 AND R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL THEN 'Serviço não tipificado - ' + R.DESCRICAO_NAO_TIPIFICADO 
			WHEN S.NAO_TIPIFICADO IS NOT NULL THEN 'Servico não tipificado - ' + S.NOME 
			ELSE S.NOME END)  AS TIPO_SERVICO,
	S.ID AS ID_TIPO_SERVICO,
	TP.NOME AS PROTECAO_SOCIAL,
	TP.ID AS ID_TIPO_PROTECAO,
	SX.ID AS ID_SEXO,
	SX.NOME AS SEXO,
	RM.ID AS ID_REGIAO_MORADIA,
	(CASE WHEN RM.ID = 3 THEN 'Zona Urbana e Rural' ELSE RM.NOME END) AS REGIAO_MORADIA,
	CT.ID AS ID_CARACTERISTICAS_TERRITORIO,
	CT.NOME AS CARACTERISTICAS_TERRITORIO,
	SE.ID_SITUACAO_ESPECIFICA,
	STE.NOME AS SITUACAO_ESPECIFICA,
	STE.ID_SITUACAO_VULNERABILIDADE,
	SV.NOME AS SITUACAO_VULNERABILIDADE,
	--******** 
	--******** RECURSOS (POR EXERCICIO)
	--******** 
	R1.VALOR_MUNICIPAL_ASSISTENCIA AS VALOR_FMAS,
	R1.VALOR_MUNICIPAL_FMDCA AS VALOR_FMDCA,
	R1.VALOR_ESTADUAL_ASSISTENCIA AS VALOR_FEAS,
	isnull(R1.VALOR_ESTADUAL_ASSISTENCIA_ANO_ANTERIOR, 0.0) AS VALOR_FEAS_ANO_ANTERIOR,
	R1.VALOR_ESTADUAL_FEDCA AS VALOR_FEDCA,
	R1.VALOR_FEDERAL_ASSISTENCIA AS VALOR_FNAS,
	R1.VALOR_FEDERAL_FNDCA AS VALOR_FNDCA,
	0 AS VALOR_PRIVADO,
	ISNULL(R1.VALOR_MUNICIPAL_FMI, 0.0) AS VALOR_FMI,
	ISNULL(R1.VALOR_ESTADUAL_FEI, 0.0) AS VALOR_FEI,
	ISNULL(R1.VALOR_FEDERAL_FNI, 0.0) AS VALOR_FNI,

	0 as VALOR_ESTADUALIZADO,
	A.ABREVIACAO AS ABRANGENCIA,
	A.ID AS ID_ABRANGENCIA,
	--******** 
	--******** NUMERO ATENDIDOS
	--******** 
	COALESCE((R.NUMERO_ATENDIDOS_MENSAL), 0)   AS NUMERO_ATENDIDOS_MENSAL, 
	COALESCE((R.NUMERO_ATENDIDOS_MENSAL_SERVICO), 0) AS NUMERO_ATENDIDOS_SERVICO_MENSAL,
	COALESCE((R.NUMERO_ATENDIDOS), 0) AS  NUMERO_ATENDIDOS_ANUAL,
	COALESCE((R.NUMERO_ATENDIDOS_SERVICO), 0) AS NUMERO_ATENDIDOS_SERVICO_ANUAL,
	R.TOTAL_FUNCIONARIOS AS TOTAL_TRABALHADORES_SERVICO,
	COALESCE((RH.SEM_ESCOLARIZACAO + RH.NIVEL_FUNDAMENTAL + RH.NIVEL_MEDIO + RH.NIVEL_SUPERIOR),0) AS TOTAL_TRABALHADORES,
	
	AT.ID_ATIVIDADE_SOCIOASSISTENCIAL,
	ATS.NOME AS ATIVIDADE_SOCIOASSISTENCIAL,
	COALESCE(
		(SELECT SUM(FR.[VALOR_FONTE_RECURSO]) 
		FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_FONTE_RECURSOS FR 
		WHERE FR.ID_SERVICO_RECURSO_FINANCEIRO_FUNDO_CREAS = R1.ID
		),0.0) AS VALOR_FONTE_RECURSO,

	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2017, 0) AS MEDIA_MENSAL_ATENDIMENTO_2017,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2018, 0) AS MEDIA_MENSAL_ATENDIMENTO_2018,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2019, 0) AS MEDIA_MENSAL_ATENDIMENTO_2019,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2020, 0) AS MEDIA_MENSAL_ATENDIMENTO_2020,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2017, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2017,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2018, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2018,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2019, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2019,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2020, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2020
FROM TB_PREFEITURA P
JOIN DBSEDS.DBO.TB_MUNICIPIOS MUN (NOLOCK) ON P.ID_MUNICIPIO = MUN.ID
JOIN DBSEDS.DBO.TB_DRADS DRA (NOLOCK) ON MUN.ID_DRADS = DRA.ID
INNER JOIN TB_UNIDADE_PUBLICA UP ON(UP.ID_PREFEITURA = P.ID)
INNER JOIN TB_CREAS C ON(C.ID_UNIDADE_PUBLICA = UP.ID)
INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS R ON(R.ID_CREAS = C.ID) AND (DATA_FUNCIONAMENTO_SERVICO < @DATA_IMPLANTACAO AND (R.DATA_DESATIVACAO > @DATA_IMPLANTACAO OR R.DATA_DESATIVACAO IS NULL))
INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_CREAS R1 ON(R.ID = R1.ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS)
INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_RH RH ON (RH.ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS = R.ID)
INNER JOIN TB_ABRANGENCIA_SERVICO A ON(R.ID_ABRANGENCIA_SERVICO = A.ID)
INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CREASxSITUACAO_ESPECIFICA SE ON(SE.ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS = R.ID)
INNER JOIN TB_SITUACAO_ESPECIFICA STE ON(STE.ID = SE.ID_SITUACAO_ESPECIFICA)
INNER JOIN TB_SITUACAO_VULNERABILIDADE SV ON(STE.ID_SITUACAO_VULNERABILIDADE = SV.ID)
INNER JOIN TB_USUARIO_TIPO_SERVICO U ON (R.ID_USUARIO_TIPO_SERVICO = U.ID)
INNER JOIN TB_TIPO_SERVICO S ON (U.ID_TIPO_SERVICO = S.ID)
INNER JOIN TB_TIPO_PROTECAO TP ON(TP.ID = S.ID_TIPO_PROTECAO)
INNER JOIN TB_SEXO SX ON(SX.ID = R.ID_SEXO)
INNER JOIN TB_REGIAO_MORADIA RM ON(RM.ID = R.ID_REGIAO_MORADIA)
INNER JOIN TB_CARACTERISTICAS_TERRITORIO CT ON(CT.ID = R.ID_CARACTERISTICAS_TERRITORIO)
INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CREASxATIVIDADE_SOCIOASSISTENCIAL AT ON (AT.ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS = R.ID)
INNER JOIN TB_ATIVIDADE_SOCIOASSISTENCIAL ATS ON (ATS.ID = AT.ID_ATIVIDADE_SOCIOASSISTENCIAL)
LEFT JOIN TB_DISTRITOS_SAO_PAULO DS  ON (DS.ID = C.ID_DISTRITOS_SAO_PAULO)


UNION ALL

SELECT 
	P.ID AS ID_PREFEITURA,
	--******** 
	--******** MUNICIPIO
	--******** 
	MUN.ID AS ID_MUNICIPIO,
	MUN.ID_DRADS,
	MUN.NOME AS MUNICIPIO,
	DRA.NOME AS DRADS,
	COALESCE(MUN.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
	DRA.ID_MACRO_REGIAO,
	P.ID_NIVEL_GESTAO,
	--******** 
	--******** ID PORTE
	--******** 
	(CASE WHEN P.POPULACAO <= 20000 THEN 1
		WHEN   P.POPULACAO <= 50000 THEN 2
		WHEN   P.POPULACAO <= 100000 THEN 3
		WHEN   P.POPULACAO <= 900000 THEN 4
		ELSE 5
	END) AS ID_PORTE,
	--******** 
	--******** PORTE
	--******** 
	(CASE WHEN P.POPULACAO <= 20000 THEN 'Pequeno I'
		WHEN   P.POPULACAO <= 50000 THEN 'Pequeno II'
		WHEN   P.POPULACAO <= 100000 THEN 'Médio'
		WHEN   P.POPULACAO <= 900000 THEN 'Grande'
		ELSE 'Metrópole'
	END) AS PORTE,
	'Rede direta' AS TIPO_UNIDADE,
	5 AS ID_TIPO_UNIDADE,
	C.ID AS CODIGO_UNIDADE,
	COALESCE(C.ID_DISTRITOS_SAO_PAULO, -1) AS ID_DISTRITOS_SAO_PAULO,
	DS.NOME AS DISTRITO_SAO_PAULO,
	UP.CNPJ AS CNPJ,
	UP.RAZAO_SOCIAL AS UNIDADE_RESPONSAVEL,
	C.IDCREAS AS ID_LOCAL,
	C.NOME AS LOCAL_EXECUCAO,
	C.CIDADE AS CIDADE,
	U.NOME AS USUARIOS,
	U.ID AS ID_USUARIO_TIPO_SERVICO,
	S.NAO_TIPIFICADO,
	(CASE WHEN R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL AND  R.DESCRICAO_NAO_TIPIFICADO <> '' AND TP.ID <> 3 AND S.NAO_TIPIFICADO IS NOT NULL  THEN  'Serviço não tipificado - ' + S.NOME + ' - ' + R.DESCRICAO_NAO_TIPIFICADO 
			WHEN TP.ID = 3 AND R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL THEN 'Serviço não tipificado - ' + R.DESCRICAO_NAO_TIPIFICADO 
			WHEN S.NAO_TIPIFICADO IS NOT NULL THEN 'Servico não tipificado - ' + S.NOME 
			ELSE S.NOME END)  AS TIPO_SERVICO,
	S.ID AS ID_TIPO_SERVICO,
	TP.NOME AS PROTECAO_SOCIAL,
	TP.ID AS ID_TIPO_PROTECAO,
	SX.ID AS ID_SEXO,
	SX.NOME AS SEXO,
	RM.ID AS ID_REGIAO_MORADIA,
	(CASE WHEN RM.ID = 3 THEN 'Zona Urbana e Rural' ELSE RM.NOME END) AS REGIAO_MORADIA,
	CT.ID AS ID_CARACTERISTICAS_TERRITORIO,
	CT.NOME AS CARACTERISTICAS_TERRITORIO,
	SE.ID_SITUACAO_ESPECIFICA,
	STE.NOME AS SITUACAO_ESPECIFICA,
	STE.ID_SITUACAO_VULNERABILIDADE,
	SV.NOME AS SITUACAO_VULNERABILIDADE,
	--******** 
	--******** RECURSOS (POR EXERCICIO)
	--******** 
	R1.VALOR_MUNICIPAL_ASSISTENCIA AS VALOR_FMAS,
	R1.VALOR_MUNICIPAL_FMDCA AS VALOR_FMDCA,
	R1.VALOR_ESTADUAL_ASSISTENCIA AS VALOR_FEAS,
	ISNULL(R1.VALOR_ESTADUAL_ASSISTENCIA_ANO_ANTERIOR, 0.0) AS VALOR_FEAS_ANO_ANTERIOR,
	R1.VALOR_ESTADUAL_FEDCA AS VALOR_FEDCA,
	R1.VALOR_FEDERAL_ASSISTENCIA AS VALOR_FNAS,
	R1.VALOR_FEDERAL_FNDCA AS VALOR_FNDCA,
	ISNULL(R1.VALOR_MUNICIPAL_FMI, 0.0) AS VALOR_FMI,
	ISNULL(R1.VALOR_ESTADUAL_FEI, 0.0) AS VALOR_FEI,
	ISNULL(R1.VALOR_FEDERAL_FNI, 0.0) AS VALOR_FNI,

	0 AS VALOR_PRIVADO,
	0 AS VALOR_ESTADUALIZADO,
	A.ABREVIACAO AS ABRANGENCIA,
	A.ID AS ID_ABRANGENCIA,
	R.NUMERO_ATENDIDOS_MENSAL,
	0 AS NUMERO_ATENDIDOS_SERVICO_MENSAL,
	R.NUMERO_ATENDIDOS AS NUMERO_ATENDIDOS_ANUAL,
	0 AS NUMERO_ATENDIDOS_SERVICO_ANUAL,
	R.TOTAL_FUNCIONARIOS AS TOTAL_TRABALHADORES_SERVICO,
	COALESCE((RH.SEM_ESCOLARIZACAO + RH.NIVEL_FUNDAMENTAL + RH.NIVEL_MEDIO + RH.NIVEL_SUPERIOR),0) AS TOTAL_TRABALHADORES,
	
	AT.ID_ATIVIDADE_SOCIOASSISTENCIAL,
	ATS.NOME AS ATIVIDADE_SOCIOASSISTENCIAL,
	COALESCE(
	(	SELECT SUM(FR.[VALOR_FONTE_RECURSO]) 
		FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_FONTE_RECURSOS FR 
		WHERE FR.ID_SERVICO_RECURSO_FINANCEIRO_FUNDO_CENTRO_POP = R1.ID)
	, 0.0) AS VALOR_FONTE_RECURSO,

	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2017, 0) AS MEDIA_MENSAL_ATENDIMENTO_2017,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2018, 0) AS MEDIA_MENSAL_ATENDIMENTO_2018,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2019, 0) AS MEDIA_MENSAL_ATENDIMENTO_2019,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2020, 0) AS MEDIA_MENSAL_ATENDIMENTO_2020,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2017, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2017,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2018, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2018,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2019, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2019,
	COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2020, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2020
FROM TB_PREFEITURA P
JOIN DBSEDS.DBO.TB_MUNICIPIOS MUN (NOLOCK) ON P.ID_MUNICIPIO = MUN.ID
JOIN DBSEDS.DBO.TB_DRADS DRA (NOLOCK) ON MUN.ID_DRADS = DRA.ID
INNER JOIN TB_UNIDADE_PUBLICA UP ON(UP.ID_PREFEITURA = P.ID)
INNER JOIN TB_CENTRO_POP C ON(C.ID_UNIDADE_PUBLICA = UP.ID)
INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP R ON(R.ID_CENTRO_POP = C.ID) AND (DATA_FUNCIONAMENTO_SERVICO < @DATA_IMPLANTACAO AND (R.DATA_DESATIVACAO > @DATA_IMPLANTACAO OR R.DATA_DESATIVACAO IS NULL))
INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_CENTRO_POP R1 ON(R.ID = R1.ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP)
INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_RH RH ON (RH.ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP= R.ID)
INNER JOIN TB_ABRANGENCIA_SERVICO A ON(R.ID_ABRANGENCIA_SERVICO = A.ID)
INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POPxSITUACAO_ESPECIFICA SE ON(SE.ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP = R.ID)
INNER JOIN TB_SITUACAO_ESPECIFICA STE ON(STE.ID = SE.ID_SITUACAO_ESPECIFICA)
INNER JOIN TB_SITUACAO_VULNERABILIDADE SV ON(STE.ID_SITUACAO_VULNERABILIDADE = SV.ID)
INNER JOIN TB_USUARIO_TIPO_SERVICO U ON (R.ID_USUARIO_TIPO_SERVICO = U.ID)
INNER JOIN TB_TIPO_SERVICO S ON (U.ID_TIPO_SERVICO = S.ID)
INNER JOIN TB_TIPO_PROTECAO TP ON(TP.ID = S.ID_TIPO_PROTECAO)
INNER JOIN TB_SEXO SX ON(SX.ID = R.ID_SEXO)
INNER JOIN TB_REGIAO_MORADIA RM ON(RM.ID = R.ID_REGIAO_MORADIA)
INNER JOIN TB_CARACTERISTICAS_TERRITORIO CT ON(CT.ID = R.ID_CARACTERISTICAS_TERRITORIO)
INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POPxATIVIDADE_SOCIOASSISTENCIAL AT ON (AT.ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP = R.ID)
INNER JOIN TB_ATIVIDADE_SOCIOASSISTENCIAL ATS ON (ATS.ID = AT.ID_ATIVIDADE_SOCIOASSISTENCIAL)
LEFT JOIN TB_DISTRITOS_SAO_PAULO DS ON (DS.ID = C.ID_DISTRITOS_SAO_PAULO)


GO


