//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seds.PMAS.Api.PerfilService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PerfilService.IPerfilService")]
    public interface IPerfilService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/GetPerfisByAplicativo", ReplyAction="http://tempuri.org/IPerfilService/GetPerfisByAplicativoResponse")]
        Seds.Seguranca.Entidades.PerfilInfo[] GetPerfisByAplicativo(int idAplicativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/GetPerfisByAplicativo", ReplyAction="http://tempuri.org/IPerfilService/GetPerfisByAplicativoResponse")]
        System.Threading.Tasks.Task<Seds.Seguranca.Entidades.PerfilInfo[]> GetPerfisByAplicativoAsync(int idAplicativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/AssociarUsuarioAoPerfil", ReplyAction="http://tempuri.org/IPerfilService/AssociarUsuarioAoPerfilResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void AssociarUsuarioAoPerfil(int idUsuario, int idPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/AssociarUsuarioAoPerfil", ReplyAction="http://tempuri.org/IPerfilService/AssociarUsuarioAoPerfilResponse")]
        System.Threading.Tasks.Task AssociarUsuarioAoPerfilAsync(int idUsuario, int idPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/GetPerfisByUsuario", ReplyAction="http://tempuri.org/IPerfilService/GetPerfisByUsuarioResponse")]
        string[] GetPerfisByUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/GetPerfisByUsuario", ReplyAction="http://tempuri.org/IPerfilService/GetPerfisByUsuarioResponse")]
        System.Threading.Tasks.Task<string[]> GetPerfisByUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/GetUsuariosByAplicativo", ReplyAction="http://tempuri.org/IPerfilService/GetUsuariosByAplicativoResponse")]
        Seds.Seguranca.Entidades.ConsultaUsuarioCadUnicoInfo[] GetUsuariosByAplicativo(int idAplicativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/GetUsuariosByAplicativo", ReplyAction="http://tempuri.org/IPerfilService/GetUsuariosByAplicativoResponse")]
        System.Threading.Tasks.Task<Seds.Seguranca.Entidades.ConsultaUsuarioCadUnicoInfo[]> GetUsuariosByAplicativoAsync(int idAplicativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/GetUsuarioById", ReplyAction="http://tempuri.org/IPerfilService/GetUsuarioByIdResponse")]
        Seds.Seguranca.Entidades.UsuarioCadUnicoInfo GetUsuarioById(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/GetUsuarioById", ReplyAction="http://tempuri.org/IPerfilService/GetUsuarioByIdResponse")]
        System.Threading.Tasks.Task<Seds.Seguranca.Entidades.UsuarioCadUnicoInfo> GetUsuarioByIdAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/GetUsuariosByAplicativoNomeRG", ReplyAction="http://tempuri.org/IPerfilService/GetUsuariosByAplicativoNomeRGResponse")]
        Seds.Seguranca.Entidades.ConsultaUsuarioCadUnicoInfo[] GetUsuariosByAplicativoNomeRG(int idAplicativo, string nome, string RG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/GetUsuariosByAplicativoNomeRG", ReplyAction="http://tempuri.org/IPerfilService/GetUsuariosByAplicativoNomeRGResponse")]
        System.Threading.Tasks.Task<Seds.Seguranca.Entidades.ConsultaUsuarioCadUnicoInfo[]> GetUsuariosByAplicativoNomeRGAsync(int idAplicativo, string nome, string RG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/InativarUsuario", ReplyAction="http://tempuri.org/IPerfilService/InativarUsuarioResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void InativarUsuario(int idUsuario, int idAplicativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/InativarUsuario", ReplyAction="http://tempuri.org/IPerfilService/InativarUsuarioResponse")]
        System.Threading.Tasks.Task InativarUsuarioAsync(int idUsuario, int idAplicativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/AtivarUsuario", ReplyAction="http://tempuri.org/IPerfilService/AtivarUsuarioResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void AtivarUsuario(int idUsuario, int idAplicativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPerfilService/AtivarUsuario", ReplyAction="http://tempuri.org/IPerfilService/AtivarUsuarioResponse")]
        System.Threading.Tasks.Task AtivarUsuarioAsync(int idUsuario, int idAplicativo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPerfilServiceChannel : Seds.PMAS.Api.PerfilService.IPerfilService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PerfilServiceClient : System.ServiceModel.ClientBase<Seds.PMAS.Api.PerfilService.IPerfilService>, Seds.PMAS.Api.PerfilService.IPerfilService {
        
        public PerfilServiceClient() {
        }
        
        public PerfilServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PerfilServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PerfilServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PerfilServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Seds.Seguranca.Entidades.PerfilInfo[] GetPerfisByAplicativo(int idAplicativo) {
            return base.Channel.GetPerfisByAplicativo(idAplicativo);
        }
        
        public System.Threading.Tasks.Task<Seds.Seguranca.Entidades.PerfilInfo[]> GetPerfisByAplicativoAsync(int idAplicativo) {
            return base.Channel.GetPerfisByAplicativoAsync(idAplicativo);
        }
        
        public void AssociarUsuarioAoPerfil(int idUsuario, int idPerfil) {
            base.Channel.AssociarUsuarioAoPerfil(idUsuario, idPerfil);
        }
        
        public System.Threading.Tasks.Task AssociarUsuarioAoPerfilAsync(int idUsuario, int idPerfil) {
            return base.Channel.AssociarUsuarioAoPerfilAsync(idUsuario, idPerfil);
        }
        
        public string[] GetPerfisByUsuario(int idUsuario) {
            return base.Channel.GetPerfisByUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<string[]> GetPerfisByUsuarioAsync(int idUsuario) {
            return base.Channel.GetPerfisByUsuarioAsync(idUsuario);
        }
        
        public Seds.Seguranca.Entidades.ConsultaUsuarioCadUnicoInfo[] GetUsuariosByAplicativo(int idAplicativo) {
            return base.Channel.GetUsuariosByAplicativo(idAplicativo);
        }
        
        public System.Threading.Tasks.Task<Seds.Seguranca.Entidades.ConsultaUsuarioCadUnicoInfo[]> GetUsuariosByAplicativoAsync(int idAplicativo) {
            return base.Channel.GetUsuariosByAplicativoAsync(idAplicativo);
        }
        
        public Seds.Seguranca.Entidades.UsuarioCadUnicoInfo GetUsuarioById(int idUsuario) {
            return base.Channel.GetUsuarioById(idUsuario);
        }
        
        public System.Threading.Tasks.Task<Seds.Seguranca.Entidades.UsuarioCadUnicoInfo> GetUsuarioByIdAsync(int idUsuario) {
            return base.Channel.GetUsuarioByIdAsync(idUsuario);
        }
        
        public Seds.Seguranca.Entidades.ConsultaUsuarioCadUnicoInfo[] GetUsuariosByAplicativoNomeRG(int idAplicativo, string nome, string RG) {
            return base.Channel.GetUsuariosByAplicativoNomeRG(idAplicativo, nome, RG);
        }
        
        public System.Threading.Tasks.Task<Seds.Seguranca.Entidades.ConsultaUsuarioCadUnicoInfo[]> GetUsuariosByAplicativoNomeRGAsync(int idAplicativo, string nome, string RG) {
            return base.Channel.GetUsuariosByAplicativoNomeRGAsync(idAplicativo, nome, RG);
        }
        
        public void InativarUsuario(int idUsuario, int idAplicativo) {
            base.Channel.InativarUsuario(idUsuario, idAplicativo);
        }
        
        public System.Threading.Tasks.Task InativarUsuarioAsync(int idUsuario, int idAplicativo) {
            return base.Channel.InativarUsuarioAsync(idUsuario, idAplicativo);
        }
        
        public void AtivarUsuario(int idUsuario, int idAplicativo) {
            base.Channel.AtivarUsuario(idUsuario, idAplicativo);
        }
        
        public System.Threading.Tasks.Task AtivarUsuarioAsync(int idUsuario, int idAplicativo) {
            return base.Channel.AtivarUsuarioAsync(idUsuario, idAplicativo);
        }
    }
}
