USE [Dbpmas_quadrienal]
GO

ALTER VIEW [dbo].[VW_QUANTIDADE_UNIDADES_LOCAIS_SERVICOS]
AS
SELECT
			PRE.ID,
			MUN.ID AS ID_MUNICIPIO,
			MUN.ID_DRADS,
			MUN.NOME AS MUNICIPIO,
			DRA.NOME AS DRADS,
			COALESCE(MUN.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
			DRA.ID_MACRO_REGIAO,
			PRE.ID_NIVEL_GESTAO,
			
			(CASE WHEN PRE.POPULACAO <= 20000 THEN 1
			   WHEN   PRE.POPULACAO <= 50000 THEN 2
			   WHEN   PRE.POPULACAO <= 100000 THEN 3
			   WHEN   PRE.POPULACAO <= 900000 THEN 4
			   ELSE 5
			END) AS ID_PORTE,
			
			(SELECT COUNT(*) FROM TB_UNIDADE_PRIVADA AS PRIVADA WHERE PRIVADA.ID_PREFEITURA = PRE.ID AND PRIVADA.DESATIVADO = 0) AS UNIDADES_PRIVADAS,
			
			(SELECT COUNT(PRIVADA.ID) FROM TB_LOCAL_EXECUCAO_PRIVADO AS PRIVADA	INNER JOIN TB_UNIDADE_PRIVADA I ON(PRIVADA.ID_UNIDADE_PRIVADA = I.ID) WHERE I.ID_PREFEITURA = PRE.ID AND PRIVADA.DESATIVADO = 0) AS LOCAIS_PRIVADAS,
			
			(SELECT COUNT(R.ID) FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO R INNER JOIN TB_LOCAL_EXECUCAO_PRIVADO AS PRIVADA ON(R.ID_LOCAL_EXECUCAO_PRIVADO = PRIVADA.ID) INNER JOIN TB_UNIDADE_PRIVADA I ON(PRIVADA.ID_UNIDADE_PRIVADA = I.ID)	WHERE I.ID_PREFEITURA = PRE.ID AND R.DESATIVADO = 0) AS SERVICOS_PRIVADAS,

			(SELECT COUNT(*) FROM TB_UNIDADE_PUBLICA AS PUBLICA WHERE PUBLICA.ID_PREFEITURA = PRE.ID AND PUBLICA.DESATIVADO = 0) AS UNIDADES_PUBLICAS,
			
			(SELECT COUNT(PUBLICA.ID) FROM TB_LOCAL_EXECUCAO_PUBLICO AS PUBLICA	INNER JOIN TB_UNIDADE_PUBLICA I ON(PUBLICA.ID_UNIDADE_PUBLICA = I.ID) WHERE I.ID_PREFEITURA = PRE.ID AND PUBLICA.DESATIVADO = 0) AS LOCAIS_PUBLICAS,

			(SELECT COUNT(R.ID) FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO R INNER JOIN TB_LOCAL_EXECUCAO_PUBLICO AS PUBLICA ON(R.ID_LOCAL_EXECUCAO_PUBLICO = PUBLICA.ID)INNER JOIN TB_UNIDADE_PUBLICA I ON(PUBLICA.ID_UNIDADE_PUBLICA = I.ID) WHERE I.ID_PREFEITURA = PRE.ID AND R.DESATIVADO = 0) AS SERVICOS_PUBLICAS,
			
			(SELECT COUNT(*) FROM TB_CRAS AS CRAS INNER JOIN TB_UNIDADE_PUBLICA UP ON (UP.ID = CRAS.ID_UNIDADE_PUBLICA)	WHERE UP.ID_PREFEITURA = PRE.ID AND CRAS.DESATIVADO = 0) AS CRAS,
			
			(SELECT COUNT(R.ID) FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS R INNER JOIN TB_CRAS AS CRAS ON(R.ID_CRAS = CRAS.ID)	INNER JOIN TB_UNIDADE_PUBLICA UP ON (UP.ID = CRAS.ID_UNIDADE_PUBLICA) WHERE UP.ID_PREFEITURA = PRE.ID AND R.DESATIVADO = 0) AS SERVICOS_CRAS,
			
			(SELECT COUNT(*) FROM TB_CREAS AS CREAS	INNER JOIN TB_UNIDADE_PUBLICA UP ON (UP.ID = CREAS.ID_UNIDADE_PUBLICA)	WHERE UP.ID_PREFEITURA = PRE.ID AND CREAS.DESATIVADO = 0) AS CREAS,
			
			(SELECT COUNT(R.ID) FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS R INNER JOIN TB_CREAS AS CREAS ON(R.ID_CREAS = CREAS.ID) INNER JOIN TB_UNIDADE_PUBLICA UP ON (UP.ID = CREAS.ID_UNIDADE_PUBLICA)	WHERE UP.ID_PREFEITURA = PRE.ID AND R.DESATIVADO = 0) AS SERVICOS_CREAS,
			
			(SELECT COUNT(*) FROM TB_CENTRO_POP AS CENTRO_POP INNER JOIN TB_UNIDADE_PUBLICA UP ON (UP.ID = CENTRO_POP.ID_UNIDADE_PUBLICA) WHERE UP.ID_PREFEITURA = PRE.ID AND CENTRO_POP.DESATIVADO = 0) AS CENTRO_POP,
			
			(SELECT COUNT(R.ID) FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP R INNER JOIN TB_CENTRO_POP AS CENTRO_POP ON(R.ID_CENTRO_POP = CENTRO_POP.ID) INNER JOIN TB_UNIDADE_PUBLICA UP ON (UP.ID = CENTRO_POP.ID_UNIDADE_PUBLICA) WHERE UP.ID_PREFEITURA = PRE.ID AND R.DESATIVADO = 0) AS SERVICOS_CENTRO_POP
	        
			FROM TB_PREFEITURA PRE (NOLOCK)
			JOIN DBSEDS.DBO.TB_MUNICIPIOS MUN (NOLOCK)
			ON PRE.ID_MUNICIPIO = MUN.ID
			JOIN DBSEDS.DBO.TB_DRADS DRA (NOLOCK)
			ON MUN.ID_DRADS = DRA.ID



GO


