use Dbpmas_quadrienal
go
--Angatuba
UPDATE TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_PUBLICO 
SET   VALOR_ESTADUAL_ASSISTENCIA = 0 
    , VALOR_FEDERAL_ASSISTENCIA = 0
WHERE ID = 2579

--Angatuba
UPDATE TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_PUBLICO 
SET   VALOR_ESTADUAL_ASSISTENCIA = 0 
    , VALOR_ESTADUAL_ASSISTENCIA_ANO_ANTERIOR = 0
WHERE ID = 2584

--Angatuba
UPDATE TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_PUBLICO 
SET   VALOR_ESTADUAL_ASSISTENCIA = 0 
    , VALOR_FEDERAL_ASSISTENCIA = 0
WHERE ID = 2576

--Angatuba
UPDATE TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_PUBLICO 
SET   VALOR_ESTADUAL_ASSISTENCIA_ANO_ANTERIOR = 30000.00
WHERE ID = 4189

--Lorena
UPDATE TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_PRIVADO 
SET VALOR_MUNICIPAL_FMDCA = 0
  , VALOR_ESTADUAL_ASSISTENCIA_ANO_ANTERIOR = 0
WHERE ID IN (10361, 10362, 10363, 10364, 10365)