--UNION ALL 
SELECT
		B.ID
		,PRE.ID AS ID_PREFEITURA
		,B.NOME		
		--B.ID AS ID_TIPO_BENEFICIO_EVENTUAL,
		,'Não' AS COFINANCIAMENTO
		,'Não' AS ESTADUALIZADO
		,COUNT(C.ID) AS TOTAL_SERVICOS
		,COALESCE((P.VALOR_FMAS + P.VALOR_FEAS + P.VALOR_FNAS + P.VALOR_FUNDO_MUNICIPAL_SOLIDARIEDADE + P.VALOR_FUNDO_ESTADUAL_SOLIDARIEDADE + P.VALOR_ORCAMENTO_MUNICIPAL)
		,0) AS PREVISAO_ORCAMENTARIA
		,COALESCE(P.BENEFICIARIO_ATENDIDO_REDE_SOCIOASSISTENCIAL,0) AS INTEGRACAO_REDE
		,(CASE WHEN P.ID IS NOT NULL THEN 1 ELSE 0 END) AS ADERIU
		,((SELECT COUNT(U.ID) FROM TB_CRAS U
		WHERE U.ID IN(SELECT A.ID_CRAS FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS A 
				INNER JOIN TB_PREFEITURA_BENEFICIO_EVENTUAL_SERVICOS C ON(C.ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS = A.ID AND C.ID_PREFEITURA_BENEFICIO_EVENTUAL = P.ID)			             
				))
		+
		(SELECT COUNT(U.ID) FROM TB_CREAS U
		WHERE U.ID IN(SELECT A.ID_CREAS FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS A 
				INNER JOIN TB_PREFEITURA_BENEFICIO_EVENTUAL_SERVICOS C ON(C.ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS = A.ID AND C.ID_PREFEITURA_BENEFICIO_EVENTUAL = P.ID)			             
				))
		+
		(SELECT COUNT(U.ID) FROM TB_CENTRO_POP U
		WHERE U.ID IN(SELECT A.ID_CENTRO_POP FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP A 
				INNER JOIN TB_PREFEITURA_BENEFICIO_EVENTUAL_SERVICOS C ON(C.ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP = A.ID AND C.ID_PREFEITURA_BENEFICIO_EVENTUAL = P.ID)			             
				))
		+
		(SELECT COUNT(U.ID) FROM TB_LOCAL_EXECUCAO_PUBLICO U
		WHERE U.ID IN(SELECT A.ID_LOCAL_EXECUCAO_PUBLICO FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO A 
				INNER JOIN TB_PREFEITURA_BENEFICIO_EVENTUAL_SERVICOS C ON(C.ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO = A.ID AND C.ID_PREFEITURA_BENEFICIO_EVENTUAL = P.ID)			             
				))
		+
		(SELECT COUNT(U.ID) FROM TB_LOCAL_EXECUCAO_PRIVADO U
		WHERE U.ID IN(SELECT A.ID_LOCAL_EXECUCAO_PRIVADO FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO A 
				INNER JOIN TB_PREFEITURA_BENEFICIO_EVENTUAL_SERVICOS C ON(C.ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO = A.ID AND C.ID_PREFEITURA_BENEFICIO_EVENTUAL = P.ID)			             
				))
		)AS TOTAL_UNIDADES	
	FROM TB_TIPO_BENEFICIO_EVENTUAL B
	INNER JOIN TB_PREFEITURA PRE ON(PRE.ID IS NOT NULL)
	LEFT JOIN TB_PREFEITURA_BENEFICIO_EVENTUAL P ON(PRE.ID = P.ID_PREFEITURA AND B.ID = P.ID_TIPO_BENEFICIO_EVENTUAL)
	LEFT JOIN TB_PREFEITURA_BENEFICIO_EVENTUAL_SERVICOS C ON(C.ID_PREFEITURA_BENEFICIO_EVENTUAL = P.ID)	
	GROUP BY P.ID, B.ID, PRE.ID, B.NOME,P.BENEFICIARIO_ATENDIDO_REDE_SOCIOASSISTENCIAL,
	P.VALOR_FMAS , P.VALOR_FEAS ,P.VALOR_FNAS , P.VALOR_FUNDO_MUNICIPAL_SOLIDARIEDADE , P.VALOR_FUNDO_ESTADUAL_SOLIDARIEDADE, P.VALOR_ORCAMENTO_MUNICIPAL