USE [DBPMAS2017]
GO

--Blocos I, IV, V, VI e VII
delete tb_analise_diagnostica

delete TB_BLOQUEIO_QUADRO_FINANCEIRO

delete TB_BLOQUEIO_QUADRO_LEI_ORCAMENTARIA

delete tb_comentario_execucao_financeira

delete TB_CONSELHO_MUNICIPAL_PRESIDENTE_ANTERIOR

delete tb_conselho_existente_prefeitura

delete tb_conselho_municipal_parecer

delete tb_conselho_municipal

delete tb_execucao_financeira

delete tb_fundo_municipal

delete tb_gestor_municipal

delete tb_lei_orcamentaria

delete tb_log

delete tb_orgao_gestor

delete tb_plano_municipal_historico

delete tb_prefeito

delete tb_prefeitura_acao_planejamento

delete TB_PREFEITURA_AVALIACAOxMOTIVOS

delete TB_PREFEITURA_AVALIACAOxOBJETIVOS

delete TB_PREFEITURA_AVALIACAOxPROCEDIMENTOS

delete TB_PREFEITURA_AVALIACAO

delete TB_PREFEITURA_BENEFICIO_EVENTUALxORGAO_RESPONSAVEL

delete TB_PREFEITURA_BENEFICIO_EVENTUAL_SERVICOS

delete TB_PREFEITURA_BENEFICIO_EVENTUALxBENEFICIOS

delete TB_PREFEITURA_BENEFICIO_EVENTUALxCRITERIOS

delete TB_PREFEITURA_BENEFICIO_EVENTUALxNECESSIDADE

delete TB_PREFEITURA_BENEFICIO_EVENTUALxUNIDADE_PRIVADA

delete TB_PREFEITURA_BENEFICIO_EVENTUAL

delete TB_PREFEITURA_MONITORAMENTO_FOCOS

delete TB_PREFEITURA_MONITORAMENTOxINSTRUMENTOS

delete TB_PREFEITURA_MONITORAMENTOxMEIOS_DIVULGACAO

delete TB_PREFEITURA_MONITORAMENTOxPROCEDIMENTOS

delete TB_PREFEITURA_MONITORAMENTO

delete TB_PREFEITURA_SITUACAO_QUADRO

delete TB_PREFEITURA_VIGILANCIA_MONITORAMENTO_AVALIACAOxAPRIMORAMENTOS

delete TB_PREFEITURA_VIGILANCIA_MONITORAMENTO_AVALIACAO_PESQUISA

delete TB_PREFEITURA_VIGILANCIA_MONITORAMENTO_AVALIACAO

delete TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxACOES

delete TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxBASE_DADOS

delete TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL



update tb_prefeitura
set id_situacao = 1,
dt_publicacao = '2000-01-01 00:00:00.000',
cidade = '',
cep = '',
logradouro = '',
numero = null,
complemento = null,
bairro = null,
tel = '',
CELULAR = null,
web_site = null,
email = null, 
bloqueada = 0,
possui_site = 0,
revisao = 0,
caracterizacao = ''

update TB_INDICE_GESTAO_DESCENTRALIZADA set
IGD_PBF = 0.0,
IGD_PBF_VALOR_MENSAL = 0.0,
IGD_SUAS = 0.0,
IGD_SUAS_VALOR_MENSAL = 0.0

update [dbo].[TB_CRONOGRAMA_DESEMBOLSO] set
      [RH_MES_1] = 0.0
      ,[RH_MES_2] = 0.0
      ,[RH_MES_3] = 0.0
      ,[RH_MES_4] = 0.0
      ,[RH_MES_5] = 0.0
      ,[RH_MES_6] = 0.0
      ,[RH_MES_7] = 0.0
      ,[RH_MES_8] = 0.0
      ,[RH_MES_9] = 0.0
      ,[RH_MES_10] = 0.0
      ,[RH_MES_11] = 0.0
      ,[RH_MES_12] = 0.0
      ,[MATERIAL_CONSUMO_MES_1] = 0.0
      ,[MATERIAL_CONSUMO_MES_2] = 0.0
      ,[MATERIAL_CONSUMO_MES_3] = 0.0
      ,[MATERIAL_CONSUMO_MES_4] = 0.0
      ,[MATERIAL_CONSUMO_MES_5] = 0.0
      ,[MATERIAL_CONSUMO_MES_6] = 0.0
      ,[MATERIAL_CONSUMO_MES_7] = 0.0
      ,[MATERIAL_CONSUMO_MES_8] = 0.0
      ,[MATERIAL_CONSUMO_MES_9] = 0.0
      ,[MATERIAL_CONSUMO_MES_10] = 0.0
      ,[MATERIAL_CONSUMO_MES_11] = 0.0
      ,[MATERIAL_CONSUMO_MES_12] = 0.0
      ,[SERVICOS_TERCEIROS_MES_1] = 0.0
      ,[SERVICOS_TERCEIROS_MES_2] = 0.0
      ,[SERVICOS_TERCEIROS_MES_3] = 0.0
      ,[SERVICOS_TERCEIROS_MES_4] = 0.0
      ,[SERVICOS_TERCEIROS_MES_5] = 0.0
      ,[SERVICOS_TERCEIROS_MES_6] = 0.0
      ,[SERVICOS_TERCEIROS_MES_7] = 0.0
      ,[SERVICOS_TERCEIROS_MES_8] = 0.0
      ,[SERVICOS_TERCEIROS_MES_9] = 0.0
      ,[SERVICOS_TERCEIROS_MES_10] = 0.0
      ,[SERVICOS_TERCEIROS_MES_11] = 0.0
      ,[SERVICOS_TERCEIROS_MES_12] = 0.0
      ,[INVESTIMENTO_MES_1] = 0.0
      ,[INVESTIMENTO_MES_2] = 0.0
      ,[INVESTIMENTO_MES_3] = 0.0
      ,[INVESTIMENTO_MES_4] = 0.0
      ,[INVESTIMENTO_MES_5] = 0.0
      ,[INVESTIMENTO_MES_6] = 0.0
      ,[INVESTIMENTO_MES_7] = 0.0
      ,[INVESTIMENTO_MES_8] = 0.0
      ,[INVESTIMENTO_MES_9] = 0.0
      ,[INVESTIMENTO_MES_10] = 0.0
      ,[INVESTIMENTO_MES_11] = 0.0
      ,[INVESTIMENTO_MES_12] = 0.0


--Bloco III
delete TB_SP_SOLIDARIO_AGENDA_FAMILIA_PARCERIAS

delete TB_SP_SOLIDARIO_PLANEJAMENTO_BENS

delete TB_SP_SOLIDARIO_PLANEJAMENTO_SERVICOS

delete TB_PROGRAMA_PROJETO_PARCERIAS

delete TB_PROGRAMA_PROJETO_COFINANCIAMENTO

delete [dbo].[TB_PLANO_ACAO]
delete TB_PROGRAMA_PROJETO where PROGRAMA_MUNICIPAL = 1

delete TB_PETI_ACAO

delete TB_TRANSFERENCIA_RENDAxACAO_SOCIOASSISTENCIAL_COMPLEMENTAR

delete TB_TRANSFERENCIA_RENDA_PARCERIAS

delete TB_TRANSFERENCIA_RENDA_COFINANCIAMENTO

delete TB_TRANSFERENCIA_RENDA where ID_TIPO_TRANSFERENCIA_RENDA = 8

UPDATE [dbo].[TB_PROGRAMA_PROJETO] set
      [ACOES] = null
      ,[ID_ABRANGENCIA_TERRITORIAL] = 1
      ,[POSSUI_PARCERIA_FORMAL] = 0
      ,[MES_INICIO] = null
      ,[ANO_INICIO] = null
      ,[MES_TERMINO] = null
      ,[ANO_TERMINO] = null
      ,[ADERENCIA_ACESSUAS] = null
      ,[META_PACTUADA] = null
      ,[BENEFICIARIO_ATENDIDO_REDE_SOCIOASSISTENCIAL] = null
      ,[VALOR_DIA_IDOSO] = null
      ,[MES_REPASSE_DIA_IDOSO] = null
      ,[ANO_REPASSE_DIA_IDOSO] = null
      ,[VALOR_CONVIVENCIA_IDOSO] = null
      ,[MES_REPASSE_CONVIVENCIA_IDOSO] = null
      ,[ANO_REPASSE_CONVIVENCIA_IDOSO] = null
      ,[FONTE_FMAS] = null
      ,[VALOR_FMAS] = null
      ,[FONTE_ORCAMENTO_MUNICIPAL] = null
      ,[VALOR_ORCAMENTO_MUNICIPAL] = null
      ,[FONTE_FUNDO_MUNICIPAL] = null
      ,[VALOR_FUNDO_MUNICIPAL] = null
      ,[FONTE_FEAS] = null
      ,[VALOR_FEAS] = null
      ,[FONTE_ORCAMENTO_ESTADUAL] = null
      ,[VALOR_ORCAMENTO_ESTADUAL] = null
      ,[FONTE_FUNDO_ESTADUAL] = null
      ,[VALOR_FUNDO_ESTADUAL] = null
      ,[FONTE_FNAS] = null
      ,[VALOR_FNAS] = null
      ,[FONTE_ORCAMENTO_FEDERAL] = null
      ,[VALOR_ORCAMENTO_FEDERAL] = null
      ,[FONTE_FUNDO_FEDERAL] = null
      ,[VALOR_FUNDO_FEDERAL] = null
      ,[FONTE_IGD_PBF] = null
      ,[VALOR_IGD_PBF] = null
      ,[FONTE_IGD_SUAS] = null
      ,[VALOR_IGD_SUAS] = null
      ,[ID_FASE_PROGRAMA_TRANSFERENCIA_RENDA_SP_SOLIDARIO] = null
      ,[SP_SOLIDARIO_META] = null
      ,[SP_SOLIDARIO_REPASSE_ANUAL] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_MES_INICIO] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_ANO_INICIO] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_MES_TERMINO] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_ORGAO_GESTOR_EXECUTA] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_CRAS_EXECUTA] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_CREAS_EXECUTA] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_UNIDADE_PRIVADA_EXECUTA] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_VALOR_FMAS] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_VALOR_ORCAMENTO_MUNICIPAL] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_VALOR_FUNDO_MUNICIPAL] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_VALOR_FEAS] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_VALOR_ORCAMENTO_ESTADUAL] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_VALOR_FUNDO_ESTADUAL] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_VALOR_FNAS] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_VALOR_ORCAMENTO_FEDERAL] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_VALOR_FUNDO_FEDERAL] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_VALOR_IGD_PBF] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_VALOR_IGD_SUAS] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_NUMERO_FAMILIAS] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_ORGAO_GESTOR_EXECUTA] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_CRAS_EXECUTA] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_CREAS_EXECUTA] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_NUMERO_FAMILIAS_2014] = null
      ,[SP_SOLIDARIO_MES_REPASSE_FEAS_BUSCA_ATIVA] = null
      ,[SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA] = null
      ,[SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014] = null
      ,[SP_SOLIDARIO_MES_REPASSE_FEAS_AGENDA_FAMILIA] = null
      ,[SP_SOLIDARIO_ANO_REPASSE_FEAS_AGENDA_FAMILIA] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_FMAS] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_ORCAMENTO_MUNICIPAL] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_FUNDO_MUNICIPAL] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_FEAS] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_ORCAMENTO_ESTADUAL] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_FUNDO_ESTADUAL] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_FNAS] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_ORCAMENTO_FEDERAL] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_FUNDO_FEDERAL] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_IGD_PBF] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_IGD_SUAS] = null
      ,[POSSUI_PARCERIA_FORMAL_SP_SOLIDARIO_AGENDA_FAMILIA] = null
      ,[VALOR_PREVISAO_ANUAL_ACESSUAS] = null
      ,[SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014_AGENDA_FAMILIA] = null
	  ,[SP_SOLIDARIO_AGENDA_FAMILIA_NUMERO_FAMILIAS_2012] = null
	  ,[SP_SOLIDARIO_POSSUI_PLANEJAMENTO_BENS] = null
	  ,[SP_SOLIDARIO_POSSUI_PLANEJAMENTO_SERVICOS] = null
	  ,[SP_SOLIDARIO_ALEM_DA_RENDA_VALOR_FMAS]= null
      ,[SP_SOLIDARIO_MES_REPASSE_FEAS_ALEM_DA_RENDA]= null
      ,[SP_SOLIDARIO_ANO_REPASSE_FEAS_ALEM_DA_RENDA]= null
      ,[SP_SOLIDARIO_ALEM_DA_RENDA_VALOR_ORCAMENTO_MUNICIPAL]= null
      ,[SP_SOLIDARIO_ALEM_DA_RENDA_VALOR_FUNDO_MUNICIPAL]= null
      ,[SP_SOLIDARIO_ALEM_DA_RENDA_VALOR_FEAS]= null
      ,[SP_SOLIDARIO_ALEM_DA_RENDA_VALOR_ORCAMENTO_ESTADUAL]= null
      ,[SP_SOLIDARIO_ALEM_DA_RENDA_VALOR_FUNDO_ESTADUAL]= null
      ,[SP_SOLIDARIO_ALEM_DA_RENDA_VALOR_FNAS]= null
      ,[SP_SOLIDARIO_ALEM_DA_RENDA__VALOR_ORCAMENTO_FEDERAL]= null
      ,[SP_SOLIDARIO_ALEM_DA_RENDA_VALOR_FUNDO_FEDERAL]= null
      ,[SP_SOLIDARIO_ALEM_DA_RENDA_VALOR_IGD_PBF]= null
      ,[SP_SOLIDARIO_ALEM_DA_RENDA_VALOR_IGD_SUAS]= null
      ,[POSSUI_PARCERIA_FORMAL_SP_SOLIDARIO_ALEM_DA_RENDA]= null
      ,[SP_SOLIDARIO_ALEM_DA_RENDA_HOUVE_PLANEJAMENTO_AQUISICAO_BENS]= null
      ,[SP_SOLIDARIO_ALEM_DA_RENDA_VALOR_CUSTEIO]= null
      ,[SP_SOLIDARIO_ALEM_DA_RENDA_VALOR_OBRAS]= null
      ,[SP_SOLIDARIO_ALEM_DA_RENDA_VALOR_EQUIPAMENTOS]= null
      ,[SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_ALEM_DA_RENDA]= null
	  ,[EXECUTA_ACAO_VIVALEITE]= null
      ,[NUMERO_REFEICOES_BOM_PRATO]= null
      ,[ADERIU_FAMILIA_PAULISTA]= null
      ,[DT_ADESAO_PROGRAMA]= null
      ,[MES_REPASSE]= null
      ,[ANO_REPASSE]= null
      ,[MES_REPASSE_SEGUNDA]= null
      ,[ANO_REPASSE_SEGUNDA]= null
      ,[VALOR_FEAS_SEGUNDA]= null
      ,[VALOR_PROGRAMADO_ANO_ATUAL]= null
      ,[VALOR_PROGRAMADO_PROXIMO_ANO] = null
	   ,[SP_SOLIDARIO_AGENDA_FAMILIA_NUMERO_FAMILIAS_2015]= null
	  ,[SP_SOLIDARIO_AGENDA_FAMILIA_NUMERO_FAMILIAS_2016]= null
      ,[NUMERO_BENEFICIARIOS_MENSAL]= null
      ,[ID_USUARIO_PROGRAMA_PROJETO]= null
      ,[POSSUI_UNIDADE_PUBLICA]= null
      ,[POSSUI_UNIDADE_PRIVADA]= null
	  ,[POSSUI_INTERLOCUTOR_MUNICIPAL] = NULL
where [PROGRAMA_ESTADUAL] = 1 or [PROGRAMA_FEDERAL] = 1

UPDATE [dbo].[TB_TRANSFERENCIA_RENDA] set
      [BPC_NUMERO_BENEFICIARIOS] = null
      ,[BOLSA_FAMILIA_ESTIMATIVA_FAMILIAS] = null
      ,[BOLSA_FAMILIA_NUMERO_FAMILIAS] = null
      ,[BOLSA_FAMILIA_REPASSE_MENSAL] = null
      ,[PETI_NUMERO_BENEFICIARIOS] = null
      ,[PETI_PREVISAO_MENSAL] = null
      ,[ACAO_RENDA_META] = null
      ,[MUNICIPAIS_NUMERO_BENEFICIARIOS] = null
      ,[RENDA_MUNICIPAIS_REPASSE] = null
      ,[POSSUI_PARCERIA_FORMAL] = 0
      ,[BENEFICIARIO_ATENDIDO_REDE_SOCIOASSISTENCIAL] = 0
      ,[ID_FASE_PROGRAMA_TRANSFERENCIA_RENDA_SP_SOLIDARIO] = null
      ,[SP_SOLIDARIO_META] = null
      ,[SP_SOLIDARIO_REPASSE_ANUAL] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_MES_INICIO] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_ANO_INICIO] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_MES_TERMINO] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_ORGAO_GESTOR_EXECUTA] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_CRAS_EXECUTA] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_CREAS_EXECUTA] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_UNIDADE_PRIVADA_EXECUTA] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_VALOR_FMAS] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_VALOR_ORCAMENTO_MUNICIPAL] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_VALOR_FEAS] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_VALOR_FNAS] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_VALOR_IGD_PBF] = null
      ,[SP_SOLIDARIO_BUSCA_ATIVA_VALOR_IGD_SUAS] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_NUMERO_FAMILIAS] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_ORGAO_GESTOR_EXECUTA] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_CRAS_EXECUTA] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_CREAS_EXECUTA] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_NUMERO_FAMILIAS_2013] = null
      ,[SP_SOLIDARIO_MES_REPASSE_FEAS_BUSCA_ATIVA] = null
      ,[SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA] = null
      ,[SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2013] = null
      ,[SP_SOLIDARIO_MES_REPASSE_FEAS_AGENDA_FAMILIA] = null
      ,[SP_SOLIDARIO_ANO_REPASSE_FEAS_AGENDA_FAMILIA] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_FMAS] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_ORCAMENTO_MUNICIPAL] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_FEAS] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_FNAS] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_IGD_PBF] = null
      ,[SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_IGD_SUAS] = null
      ,[POSSUI_PARCERIA_FORMAL_SP_SOLIDARIO_AGENDA_FAMILIA] = null
	  ,[PETI_DATA_ADESAO] = null
	  ,[PETI_NUMERO_TRABALHO_INFANTIL_CAD_UNICO] = null
	  ,[PETI_BENEFICIARIO_TRANSFERENCIA_RENDA] = null
	  ,[PETI_BENEFICIARIO_BOLSA_FAMILIA] = null
	  ,[PETI_NUMERO_BENEFICIARIO_BOLSA_FAMILIA] = null
	  ,[PETI_BENEFICIARIO_PETI_PURO] = null
	  ,[PETI_NUMERO_BENEFICIARIO_PETI_PURO_URBANO] = null
	  ,[PETI_NUMERO_BENEFICIARIO_PETI_PURO_RURAL] = null
	  ,[PETI_BENEFICIARIO_PROGRAMA_MUNICIPAL] = null
	  ,[PETI_NUMERO_BENEFICIARIO_PROGRAMA_MUNICIPAL] = null
	  ,[PETI_ADERIU_COFINANCIAMENTO_FEDERAL] = null
	  ,[PETI_ACOES_TRABALHO_INFANTIL] = null
	  ,[VALOR_FMAS] = null
	  ,[VALOR_ORCAMENTO_MUNICIPAL] = null
	  ,[VALOR_FUNDO_MUNICIPAL] = null
	  ,[VALOR_FEAS] = null
	  ,[VALOR_ORCAMENTO_ESTADUAL] = null
	  ,[VALOR_FUNDO_ESTADUAL] = null
	  ,[VALOR_FNAS] = null
	  ,[VALOR_ORCAMENTO_FEDERAL] = null
	  ,[VALOR_FUNDO_FEDERAL] = null
	  ,[VALOR_IGD_PBF] = null
	  ,[VALOR_IGD_SUAS] = null

--Bloco II
delete TB_PREVISAO_INSTALACAO_CRAS

delete TB_PREVISAO_INSTALACAO_CREAS

delete TB_PREVISAO_INSTALACAO_CENTRO_POP

delete TB_MOTIVO_NAO_INSTALACAOxCRAS

delete TB_MOTIVO_NAO_INSTALACAOxCREAS

delete TB_MOTIVO_NAO_INSTALACAOxPOP

delete TB_SERVICOS_RECURSOS_FINANCEIROS_CRASxATIVIDADE_SOCIOASSISTENCIAL

delete TB_SERVICOS_RECURSOS_FINANCEIROS_CRASxSITUACAO_ESPECIFICA

delete TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS

delete TB_CRASxACAO_SOCIOASSISTENCIAL

delete TB_SERVICOS_RECURSOS_FINANCEIROS_CREASxATIVIDADE_SOCIOASSISTENCIAL

delete TB_SERVICOS_RECURSOS_FINANCEIROS_CREASxSITUACAO_ESPECIFICA

delete TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS

delete TB_CREASxMUNICIPIOS

delete TB_CREASxACAO_SOCIOASSISTENCIAL

delete TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POPxATIVIDADE_SOCIOASSISTENCIAL

delete TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POPxSITUACAO_ESPECIFICA

delete TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP

delete TB_CENTRO_POPxACAO_SOCIOASSISTENCIAL

delete TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICOxATIVIDADE_SOCIOASSISTENCIAL

delete TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICOxSITUACAO_ESPECIFICA

delete TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO

delete TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADOxATIVIDADE_SOCIOASSISTENCIAL

delete TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADOxSITUACAO_ESPECIFICA

delete TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO

delete tb_cras

delete tb_creas

delete tb_centro_pop

delete tb_local_execucao_publico

delete tb_local_execucao_privado

delete tb_unidade_publica
delete TB_UNIDADE_PRIVADAXTB_UNIDADE_TIPO_ATENDIMENTO
delete TB_UNIDADE_PRIVADAxPROGRAMA_PROJETO

delete tb_unidade_privada

delete TB_ACAO_SOCIOASSISTENCIALxPROGRAMA_PROJETO

delete TB_ACOES_DESENVOLVIDASxPROGRAMA_PROJETO

delete TB_INTERLOCUTOR_MUNICIPAL
delete [TB_PROGRAMA_PROJETO_GRUPO_GESTOR]
delete TB_UNIDADE_PRIVADAxCARACTERIZACAO_ATIVIDADES

delete TB_IDENTIFICACAO_TERRITORIO

delete TB_UNIDADE_OFERTANTE


update tb_cronograma_desembolso set RH_MES_1 = 0
,RH_MES_2 = 0
,RH_MES_3 = 0
,RH_MES_4 = 0
,RH_MES_5 = 0
,RH_MES_6 = 0
,RH_MES_7 = 0
,RH_MES_8 = 0
,RH_MES_9 = 0
,RH_MES_10 = 0
,RH_MES_11 = 0
,RH_MES_12 = 0
,MATERIAL_CONSUMO_MES_1 = 0
,MATERIAL_CONSUMO_MES_2 = 0
,MATERIAL_CONSUMO_MES_3 = 0
,MATERIAL_CONSUMO_MES_4 = 0
,MATERIAL_CONSUMO_MES_5 = 0
,MATERIAL_CONSUMO_MES_6 = 0
,MATERIAL_CONSUMO_MES_7 = 0
,MATERIAL_CONSUMO_MES_8 = 0
,MATERIAL_CONSUMO_MES_9 = 0
,MATERIAL_CONSUMO_MES_10 = 0
,MATERIAL_CONSUMO_MES_11 = 0
,MATERIAL_CONSUMO_MES_12 = 0
,SERVICOS_TERCEIROS_MES_1 = 0
,SERVICOS_TERCEIROS_MES_2 = 0
,SERVICOS_TERCEIROS_MES_3 = 0
,SERVICOS_TERCEIROS_MES_4 = 0
,SERVICOS_TERCEIROS_MES_5 = 0
,SERVICOS_TERCEIROS_MES_6 = 0
,SERVICOS_TERCEIROS_MES_7 = 0
,SERVICOS_TERCEIROS_MES_8 = 0
,SERVICOS_TERCEIROS_MES_9 = 0
,SERVICOS_TERCEIROS_MES_10 = 0
,SERVICOS_TERCEIROS_MES_11 = 0
,SERVICOS_TERCEIROS_MES_12 = 0
,INVESTIMENTO_MES_1 = 0
,INVESTIMENTO_MES_2 = 0
,INVESTIMENTO_MES_3 = 0
,INVESTIMENTO_MES_4 = 0
,INVESTIMENTO_MES_5 = 0
,INVESTIMENTO_MES_6 = 0
,INVESTIMENTO_MES_7 = 0
,INVESTIMENTO_MES_8 = 0
,INVESTIMENTO_MES_9 = 0
,INVESTIMENTO_MES_10 = 0
,INVESTIMENTO_MES_11 = 0
,INVESTIMENTO_MES_12 = 0
,OBRAS_MES_1 = 0
,OBRAS_MES_2 = 0
,OBRAS_MES_3 = 0
,OBRAS_MES_4 = 0
,OBRAS_MES_5 = 0
,OBRAS_MES_6 = 0
,OBRAS_MES_7 = 0
,OBRAS_MES_8 = 0
,OBRAS_MES_9 = 0
,OBRAS_MES_10 = 0
,OBRAS_MES_11 = 0
,OBRAS_MES_12 = 0
,ValorOutrasDespesasCusteioMes01 = 0
,ValorOutrasDespesasCusteioMes02 = 0
, ValorOutrasDespesasCusteioMes03 = 0
,ValorOutrasDespesasCusteioMes04 = 0
, ValorOutrasDespesasCusteioMes05 = 0
,ValorOutrasDespesasCusteioMes06 = 0
,ValorOutrasDespesasCusteioMes07 = 0
,ValorOutrasDespesasCusteioMes08 = 0
,ValorOutrasDespesasCusteioMes09 = 0
,ValorOutrasDespesasCusteioMes10 = 0
,ValorOutrasDespesasCusteioMes11 = 0
,ValorOutrasDespesasCusteioMes12 = 0
go

--Script para zerar campos novos a partir de 2016 na TB_PREFEITURA
update tb_prefeitura set CARACTERIZACAO_POPULACAO = null,
CARACTERIZACAO_REDE_SOCIOASSISTENCIAL = null,
CARACTERIZACAO_ANALISE_INTERPRETACAO = null
GO

--Script para zerar os valores valor_fmas e valor_previsao_anual_acessas, pois se tiver nulos gera exception no sistema

update tb_programa_projeto set valor_fmas = 0,valor_previsao_anual_acessuas = 0
go