USE [Dbpmas_quadrienal]

ALTER VIEW [dbo].[VW_ACOES_VIGILANCIA_SOCIOASSISTENCIAL]
AS
SELECT 
	 P.ID AS ID_PREFEITURA,
	 MUN.ID AS ID_MUNICIPIO,
	 MUN.ID_DRADS,
	 MUN.NOME AS MUNICIPIO,
	 DRA.NOME AS DRADS,
	 COALESCE(MUN.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
	 DRA.ID_MACRO_REGIAO,
	 P.ID_NIVEL_GESTAO,
	 (CASE WHEN P.POPULACAO <= 20000 THEN 1
	 	WHEN   P.POPULACAO <= 50000 THEN 2
	 	WHEN   P.POPULACAO <= 100000 THEN 3
	 	WHEN   P.POPULACAO <= 900000 THEN 4
	 	ELSE 5
	 END) AS ID_PORTE,
	 (CASE WHEN V.OFERECE_VIGILANCIA = 1 THEN 'Sim' ELSE 'Não' END) AS OFERECE_VIGILANCIA,
	 (CASE WHEN ET.POSSUI_EQUIPE_VIGILANCIA_SOCIOASSISTENCIAL = 1 THEN 'Sim' ELSE 'Não' END) AS POSSUI_EQUIPE_VIGILANCIA_SOCIOASSISTENCIAL,
	 (EE.SEM_ESCOLARIDADE + EE.NIVEL_FUNDAMENTAL + EE.NIVEL_MEDIO + EE.NIVEL_SUPERIOR )  AS EQUIPE_VIGILANCIA_SOCIOASSISTENCIAL,
	 (CASE WHEN (SELECT COUNT(*) FROM TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxACOES VA WHERE VA.ID_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL = V.ID AND VA.ID_ACAO_VIGILANCIA_SOCIOASSISTENCIAL IN(3,4,5,6)) > 0 THEN 'Sim' ELSE 'Não' END) AS VIGILANCIA_RISCOS,
	 (CASE WHEN (SELECT COUNT(*) FROM TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxACOES VA WHERE VA.ID_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL = V.ID AND VA.ID_ACAO_VIGILANCIA_SOCIOASSISTENCIAL IN(7,8,9)) > 0 THEN 'Sim' ELSE 'Não' END) AS VIGILANCIA_PADROES_SERVICOS,
	 (CASE WHEN VMA.POSSUI_SISTEMA_INFORMATIZADO_PROPRIO = 1 THEN 'Sim' ELSE 'Não' END) AS POSSUI_SISTEMA_INFORMATIZADO_PROPRIO,
	 (CASE WHEN (SELECT COUNT(*) FROM TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxBASE_DADOS VBD WHERE VBD.ID_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL = V.ID AND VBD.ID_BASE_DADOS = 1) > 0 THEN 'Sim' ELSE 'Não' END) AS CAD_UNICO,
	 (CASE WHEN (SELECT COUNT(*) FROM TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxBASE_DADOS VBD WHERE VBD.ID_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL = V.ID AND VBD.ID_BASE_DADOS = 2) > 0 THEN 'Sim' ELSE 'Não' END) AS OUTROS_APLICATIVOS_SUAS,
	 (CASE WHEN (SELECT COUNT(*) FROM TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxBASE_DADOS VBD WHERE VBD.ID_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL = V.ID AND VBD.ID_BASE_DADOS = 3) > 0 THEN 'Sim' ELSE 'Não' END) AS PMAS_WEB,
	 (CASE WHEN (SELECT COUNT(*) FROM TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxBASE_DADOS VBD WHERE VBD.ID_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL = V.ID AND VBD.ID_BASE_DADOS = 4) > 0 THEN 'Sim' ELSE 'Não' END) AS SIS_PETI,
	 (CASE WHEN (SELECT COUNT(*) FROM TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxBASE_DADOS VBD WHERE VBD.ID_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL = V.ID AND VBD.ID_BASE_DADOS = 5) > 0 THEN 'Sim' ELSE 'Não' END) AS SIS_JOVEM,
	 (CASE WHEN (SELECT COUNT(*) FROM TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxBASE_DADOS VBD WHERE VBD.ID_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL = V.ID AND VBD.ID_BASE_DADOS = 6) > 0 THEN 'Sim' ELSE 'Não' END) AS OUTRA_BASE,
	 (CASE WHEN (SELECT COUNT(*) FROM TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxBASE_DADOS VBD WHERE VBD.ID_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL = V.ID AND VBD.ID_BASE_DADOS = 7) > 0 THEN 'Sim' ELSE 'Não' END) AS PRO_SOCIAL,
	 (CASE WHEN (SELECT COUNT(*) FROM TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxBASE_DADOS VBD WHERE VBD.ID_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL = V.ID AND VBD.ID_BASE_DADOS = 8) > 0 THEN 'Sim' ELSE 'Não' END) AS INSTRUMENTAIS_PROPRIOS,
	 (CASE WHEN (SELECT COUNT(*) FROM TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxBASE_DADOS VBD WHERE VBD.ID_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL = V.ID AND VBD.ID_BASE_DADOS = 9) > 0 THEN 'Sim' ELSE 'Não' END) AS SISTEMA_INFORMATIZADO_MUNICIPAL,
	 (CASE WHEN (SELECT COUNT(*) FROM TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxBASE_DADOS VBD WHERE VBD.ID_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL = V.ID AND VBD.ID_BASE_DADOS = 10) > 0 THEN 'Sim' ELSE 'Não' END) AS OUTROS_ORGAOS_MUNICIPAIS,
	 (CASE WHEN (SELECT COUNT(*) FROM TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxBASE_DADOS VBD WHERE VBD.ID_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL = V.ID AND VBD.ID_BASE_DADOS = 11) > 0 THEN 'Sim' ELSE 'Não' END) AS SEADE,
	 (CASE WHEN (SELECT COUNT(*) FROM TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxBASE_DADOS VBD WHERE VBD.ID_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL = V.ID AND VBD.ID_BASE_DADOS = 12) > 0 THEN 'Sim' ELSE 'Não' END) AS APLICATIVOS_SAGI_MDS,
	 (CASE WHEN (SELECT COUNT(*) FROM TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxBASE_DADOS VBD WHERE VBD.ID_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL = V.ID AND VBD.ID_BASE_DADOS = 13) > 0 THEN 'Sim' ELSE 'Não' END) AS APLICATIVOS_BOLSA_FAMILIA,
	 (CASE WHEN (SELECT COUNT(*) FROM TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxBASE_DADOS VBD WHERE VBD.ID_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL = V.ID AND VBD.ID_BASE_DADOS = 14) > 0 THEN 'Sim' ELSE 'Não' END) AS IBGE,
	 (CASE WHEN (SELECT COUNT(*) FROM TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxBASE_DADOS VBD WHERE VBD.ID_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL = V.ID AND VBD.ID_BASE_DADOS = 15) > 0 THEN 'Sim' ELSE 'Não' END) AS SISC,
	 (CASE WHEN (SELECT COUNT(*) FROM TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxBASE_DADOS VBD WHERE VBD.ID_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL = V.ID AND VBD.ID_BASE_DADOS = 16) > 0 THEN 'Sim' ELSE 'Não' END) AS CENSO_SUAS,
	 (CASE WHEN (SELECT COUNT(*) FROM TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxBASE_DADOS VBD WHERE VBD.ID_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL = V.ID AND VBD.ID_BASE_DADOS = 17) > 0 THEN 'Sim' ELSE 'Não' END) AS CNEAS,
	 (CASE WHEN (SELECT COUNT(*) FROM TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxBASE_DADOS VBD WHERE VBD.ID_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL = V.ID AND VBD.ID_BASE_DADOS = 18) > 0 THEN 'Sim' ELSE 'Não' END) AS CAD_SUAS,
	 (CASE WHEN (SELECT COUNT(*) FROM TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIALxBASE_DADOS VBD WHERE VBD.ID_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL = V.ID AND VBD.ID_BASE_DADOS = 19) > 0 THEN 'Sim' ELSE 'Não' END) AS RMAS
FROM TB_PREFEITURA_VIGILANCIA_SOCIOASSISTENCIAL V
	 INNER JOIN TB_PREFEITURA P ON(P.ID = V.ID_PREFEITURA)
	 INNER JOIN TB_ORGAO_GESTOR O ON(O.ID_PREFEITURA = P.ID)
	 INNER  JOIN TB_ORGAO_GESTOR_EQUIPE_ESPECIFICA_TOTAIS ET ON ET.ID_ORGAO_GESTOR  = O.ID
	 INNER  JOIN TB_ORGAO_GESTOR_EQUIPE_ESPECIFICA EE ON EE.ID_ORGAO_GESTOR = O.ID AND EE.ID_ORGAO_GESTOR_TIPO_EQUIPE = 3
	 LEFT JOIN TB_PREFEITURA_VIGILANCIA_MONITORAMENTO_AVALIACAO VMA ON(VMA.ID_PREFEITURA = P.ID)
	 JOIN DBSEDS.DBO.TB_MUNICIPIOS MUN (NOLOCK) ON P.ID_MUNICIPIO = MUN.ID
	 JOIN DBSEDS.DBO.TB_DRADS DRA (NOLOCK) ON MUN.ID_DRADS = DRA.ID
	 WHERE ET.EXERCICIO = YEAR(GETDATE()) AND EE.EXERCICIO = YEAR(GETDATE()) 

	 
GO
