
--[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_PSC]
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_PSC] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_PSC] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_PSC] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_PSC] TO usupmasreporting

--TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_LA
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_LA] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_LA] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_LA] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE_LA] TO usupmasreporting

--TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE] TO usupmasreporting

--TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL] TO usupmasreporting

--TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_PSC
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_PSC] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_PSC] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_PSC] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_PSC] TO usupmasreporting

--TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_LA
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_LA] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_LA] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_LA] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL_LA] TO usupmasreporting

--TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL] TO usupmasreporting

--TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_PSC
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_PSC] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_PSC] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_PSC] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_PSC] TO usupmasreporting

--TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_LA
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_LA] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_LA] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_LA] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL_LA] TO usupmasreporting

--TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE] TO usupmasreporting

--TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_PSC
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_PSC] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_PSC] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_PSC] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_PSC] TO usupmasreporting

--TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_LA
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_LA] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_LA] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_LA] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE_LA] TO usupmasreporting

--TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_MEDIA_MENSAL
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_MEDIA_MENSAL] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_MEDIA_MENSAL] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_MEDIA_MENSAL] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_MEDIA_MENSAL] TO usupmasreporting

--TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_CAPACIDADE
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_CAPACIDADE] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_CAPACIDADE] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_CAPACIDADE] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_CAPACIDADE] TO usupmasreporting

--TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_MEDIA_MENSAL
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_MEDIA_MENSAL] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_MEDIA_MENSAL] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_MEDIA_MENSAL] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_MEDIA_MENSAL] TO usupmasreporting

--TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_CAPACIDADE
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_CAPACIDADE] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_CAPACIDADE] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_CAPACIDADE] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_CAPACIDADE] TO usupmasreporting

--TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL] TO usupmasreporting

--TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_PSC
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_PSC] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_PSC] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_PSC] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_PSC] TO usupmasreporting

--TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_LA
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_LA] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_LA] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_LA] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL_LA] TO usupmasreporting

--TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE] TO usupmasreporting

--TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_PSC
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_PSC] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_PSC] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_PSC] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_PSC] TO usupmasreporting

--TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_LA
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_LA] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_LA] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_LA] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE_LA] TO usupmasreporting


--TB_LOGxCENTRO_POP
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_LOGxCENTRO_POP] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_LOGxCENTRO_POP] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_LOGxCENTRO_POP] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_LOGxCENTRO_POP] TO usupmasreporting

--TB_LOGxCRAS
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_LOGxCRAS] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_LOGxCRAS] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_LOGxCRAS] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_LOGxCRAS] TO usupmasreporting

--TB_LOGxCREAS
		--###############################################################
		--#		GRANT
		--###############################################################
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_LOGxCREAS] TO USERPMAS2009
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_LOGxCREAS] TO SAPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_LOGxCREAS] TO USERPROSOCIAL
		GRANT SELECT,UPDATE,INSERT,DELETE on [dbo].[TB_LOGxCREAS] TO usupmasreporting





--TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_PSC
--TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_LA
--TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_PSC
--TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_LA
--TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_PSC
--TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_LA
--TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_PSC
--TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_LA
--TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_PSC
--TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_LA
--TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_PSC
--TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_LA
