using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Seds.PMAS.QUADRIENAL.Resource
{
    public class R_TIPO_SERVICO
    {
        public static int SERVICO_PROTECAO_ATENDIMENTO_INTEGRAL_FAMILIA_PAIF = 135;
        public static int SERVICO_CONVIVENCIA_FORTALECIMENTO_VINCULOS = 136;
        public static int SERVICO_PROTECAO_SOCIAL_BASICA_DOMICILIO_PESSOAS_DEFICIENCIA_IDOSAS = 137;
        public static int SERVICO_NAO_TIPIF_RESOLUCAO_No_109_CNAS_11_11_2009_COD_138 = 138;
        public static int SERVICO_PROTECAO_ATENDIMENTO_ESPECIALIZADO_FAMILIAS_INDIVIDUOS_PAEFI = 139;
        public static int SERVICO_ESPECIALIZADO_ABORDAGEM_SOCIAL = 140;
        public static int SERVICO_PROTECAO_SOCIAL_ADOLESC_CUMPR_MEDIDA_SOCIOEDUCATIVA_LA_PSC = 141;
        public static int SERVICO_PROTECAO_SOCIAL_ADOLESC_CUMPR_MEDIDA_SOCIOEDUCATIVA_PSC = 142;
        public static int SERVICO_PROTECAO_SOCIAL_ESPECIAL_PESSOAS_DEFICIÊNCIA_IDOSAS_FAMILIAS = 143;
        public static int SERVICO_ESPECIALIZADO_PESSOAS_SITUACAO_RUA = 144;
        public static int SERVICO_NAO_TIPIF_RESOLUCAO_No_109_CNAS_11_11_2009_COD_145 = 145;
        public static int SERVICO_ACOLHIMENTO_INSTIT_ABRIGO_INSTIT = 146;
        public static int SERVICO_ACOLHIMENTO_INSTIT_CASA_LAR = 147;
        public static int SERVICO_ACOLHIMENTO_INSTIT_CASA_PASSAGEM = 148;
        public static int SERVICO_ACOLHIMENTO_INSTIT_RESIDENCIA_INCLUS = 149;
        public static int SERVICO_ACOLHIMENTO_REPUBLICA = 150;
        public static int SERVICO_ACOLHIMENTO_FAMILIA_ACOLHEDORA = 151;
        public static int SERVICO_PROTECAO_SITUACOES_CALAM_PUBLICAS_EMERGE = 152;
        public static int SERVICO_NAO_TIPIF_RESOLUCAO_No_109_CNAS_11_11_2009_COD_153 = 153;
        public static int SERVICO_ATENDIMENTO_FAMILIAS_REALIZADO_FORA_CRAS = 154;
        public static int SERVICO_EXCLUSIVO_ACOES_COMP_PROG_ESTAD_TRANSF_RENDA = 155;
        public static int OUTRO_COD_156 = 156;
        public static int SERVICO_ATEND_FAMIL_INDIV_SIT_RISCO_S_REALIZADO_FORA_CREAS = 157;
        public static int SERVICO_ATEND_ESPEC_COMPLEMENTAR_PAEFI_OFER_FORA_CREAS = 158;
        public static int OUTRO_COD_159 = 159;
        public static int SCFV_PESSOAS_DEFIC_INTELEC_ACIMA_30_ANOS_EGRESSAS = 160;

    }
}