ALTER VIEW [dbo].[VW_RH_LOCAIS_EXECUCAO]
AS
		SELECT 
				R.ID,
				P.ID AS ID_PREFEITURA,
				MUN.ID AS ID_MUNICIPIO,
				MUN.ID_DRADS,
				MUN.NOME AS MUNICIPIO,
				DRA.NOME AS DRADS,
				COALESCE(MUN.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
				DRA.ID_MACRO_REGIAO,
				P.ID_NIVEL_GESTAO,
				(CASE WHEN P.POPULACAO <= 20000 THEN 1
					WHEN   P.POPULACAO <= 50000 THEN 2
					WHEN   P.POPULACAO <= 100000 THEN 3
					WHEN   P.POPULACAO <= 900000 THEN 4
					ELSE 5
				END) AS ID_PORTE,
				'Rede direta' AS TIPO_UNIDADE,
				1 AS ID_TIPO_UNIDADE,
				UN.ID AS CODIGO_UNIDADE,
				UN.RAZAO_SOCIAL AS UNIDADE_RESPONSAVEL,
				CAST(L.ID AS VARCHAR) AS ID_LOCAL,
				L.NOME AS LOCAL_EXECUCAO,
				S.ID_TIPO_PROTECAO,
				U.ID_TIPO_SERVICO,
				S.NAO_TIPIFICADO,
				(CASE WHEN R.ID_TIPO_SERVICO_NAO_TIPIFICADO IS NOT NULL THEN ('Serviço não tipificado pela Resolução n° 109 do CNAS, de 11/11/2009 - ' + CASE WHEN DESCRICAO_NAO_TIPIFICADO IS NULL THEN S.NOME 
					  ELSE (CASE WHEN ID_TIPO_PROTECAO = 3 THEN  DESCRICAO_NAO_TIPIFICADO ELSE( S.NOME + ' - ' + DESCRICAO_NAO_TIPIFICADO)END)END)
								ELSE (S.NOME + (CASE WHEN DESCRICAO_NAO_TIPIFICADO IS NULL THEN '' ELSE ( + ' - ' + DESCRICAO_NAO_TIPIFICADO)END)) END)  AS TIPO_SERVICO,
				U.ID AS ID_USUARIO_TIPO_SERVICO,
				U.NOME AS USUARIO,
				COALESCE(RH.TOTAL_SEM_ESCOLARIZACAO,0) AS SEM_ESCOLARIZACAO,
				COALESCE(RH.TOTAL_NIVEL_FUNDAMENTAL,0) AS NIVEL_FUNDAMENTAL,
				COALESCE(RH.TOTAL_NIVEL_MEDIO,0) AS NIVEL_MEDIO,
				COALESCE(RH.TOTAL_NIVEL_SUPERIOR,0) AS NIVEL_SUPERIOR,
				COALESCE(RH.TOTAL_SERVICO_SOCIAL,0) AS SERVICO_SOCIAL,
				COALESCE(RH.TOTAL_PSICOLOGIA,0) AS PSICOLOGIA,
				COALESCE(RH.TOTAL_PEDAGOGIA,0) AS PEDAGOGIA,
				COALESCE(RH.TOTAL_SOCIOLOGIA,0) AS SOCIOLOGIA,
				COALESCE(RH.TOTAL_DIREITO,0) AS DIREITO,
				COALESCE(RH.TOTAL_TERAPIA_OCUPACIONAL,0) AS TERAPIA_OCUPACIONAL,
				COALESCE(RH.TOTAL_ANTROPOLOGIA,0) AS ANTROPOLOGIA,
				COALESCE(RH.TOTAL_MUSICOTERAPIA,0) AS MUSICOTERAPIA,
				COALESCE(RH.TOTAL_ECONOMIA,0) AS ECONOMIA,
				COALESCE(RH.TOTAL_ECONOMIA_DOMESTICA,0) AS ECONOMIA_DOMESTICA,
				COALESCE(RH.TOTAL_POS_GRADUACAO,0) AS POS_GRADUACAO,
				COALESCE(RH.TOTAL_ESTAGIARIOS,0) AS ESTAGIARIOS,
				COALESCE(RH.TOTAL_VOLUNTARIOS, 0) AS VOLUNTARIOS,
				COALESCE(RH.TOTAL_EXCLUSIVO_SERVICO, 0) AS TOTAL_EXCLUSIVO_SERVICO,
				COALESCE(RH.TOTAL_OUTROS_SERVICOS_ASSISTENCIAIS, 0) AS TOTAL_OUTROS_SERVICOS_ASSISTENCIAIS,
				COALESCE((RH.TOTAL_NIVEL_SUPERIOR - (RH.TOTAL_SERVICO_SOCIAL + RH.TOTAL_PSICOLOGIA + RH.TOTAL_PEDAGOGIA + RH.TOTAL_ANTROPOLOGIA + RH.TOTAL_ECONOMIA + RH.TOTAL_TERAPIA_OCUPACIONAL + RH.TOTAL_SOCIOLOGIA + RH.TOTAL_DIREITO + RH.TOTAL_ECONOMIA_DOMESTICA)),0) AS OUTRAS_AREAS
				FROM TB_PREFEITURA P
					JOIN DBSEDS.DBO.TB_MUNICIPIOS MUN (NOLOCK)	ON P.ID_MUNICIPIO = MUN.ID
					JOIN DBSEDS.DBO.TB_DRADS DRA (NOLOCK) ON MUN.ID_DRADS = DRA.ID
					INNER JOIN TB_UNIDADE_PUBLICA UN ON(UN.ID_PREFEITURA = P.ID)
					INNER JOIN TB_LOCAL_EXECUCAO_PUBLICO L ON(UN.ID = L.ID_UNIDADE_PUBLICA)
					INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO R ON(R.ID_LOCAL_EXECUCAO_PUBLICO = L.ID)
					LEFT JOIN TB_USUARIO_TIPO_SERVICO U ON (R.ID_USUARIO_TIPO_SERVICO = U.ID)
					LEFT JOIN TB_TIPO_SERVICO AS S ON (U.ID_TIPO_SERVICO = S.ID)
				-- RH 
				LEFT JOIN(
							SELECT 
									RH.ID_PREFEITURA,
									RH.ID_SERVICO,
									COALESCE(SUM(RH.SEM_ESCOLARIZACAO),0) AS TOTAL_SEM_ESCOLARIZACAO,
									COALESCE(SUM(RH.NIVEL_FUNDAMENTAL),0) AS TOTAL_NIVEL_FUNDAMENTAL,
									COALESCE(SUM(RH.NIVEL_MEDIO),0) AS TOTAL_NIVEL_MEDIO,
									COALESCE(SUM(RH.NIVEL_SUPERIOR),0) AS TOTAL_NIVEL_SUPERIOR,
									COALESCE(SUM(RH.SERVICO_SOCIAL),0) AS TOTAL_SERVICO_SOCIAL,
									COALESCE(SUM(RH.PSICOLOGIA),0) AS TOTAL_PSICOLOGIA,
									COALESCE(SUM(RH.PEDAGOGIA),0) AS TOTAL_PEDAGOGIA,
									COALESCE(SUM(RH.SOCIOLOGIA),0) AS TOTAL_SOCIOLOGIA,
									COALESCE(SUM(RH.TERAPIA_OCUPACIONAL),0) AS TOTAL_TERAPIA_OCUPACIONAL,
									COALESCE(SUM(RH.DIREITO),0) AS TOTAL_DIREITO,
									COALESCE(SUM(RH.ANTROPOLOGIA),0) AS TOTAL_ANTROPOLOGIA,
									COALESCE(SUM(RH.ECONOMIA),0) AS TOTAL_ECONOMIA,
									COALESCE(SUM(RH.MUSICOTERAPIA),0) AS TOTAL_MUSICOTERAPIA,
									COALESCE(SUM(RH.ECONOMIA_DOMESTICA),0) AS TOTAL_ECONOMIA_DOMESTICA,
									COALESCE(SUM(RH.POS_GRADUACAO),0) AS TOTAL_POS_GRADUACAO,
									COALESCE(SUM(RH.ESTAGIARIOS),0) AS TOTAL_ESTAGIARIOS,
									COALESCE(SUM(RH.VOLUNTARIOS),0) AS TOTAL_VOLUNTARIOS,
									COALESCE(SUM(RH.EXCLUSIVO_SERVICO),0) AS TOTAL_EXCLUSIVO_SERVICO,
									COALESCE(SUM(RH.OUTROS_SERVICOS_ASSISTENCIAIS),0) AS TOTAL_OUTROS_SERVICOS_ASSISTENCIAIS
									FROM(
											SELECT 
												 P.ID_PREFEITURA,
												 RH.ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO AS ID_SERVICO,
												 RH.SEM_ESCOLARIZACAO,
												 RH.NIVEL_FUNDAMENTAL,
												 RH.NIVEL_MEDIO,
												 RH.NIVEL_SUPERIOR,
												 RH.SERVICO_SOCIAL,
												 RH.PSICOLOGIA,
												 RH.PEDAGOGIA,
												 RH.SOCIOLOGIA,
												 RH.TERAPIA_OCUPACIONAL,
												 RH.DIREITO,
												 RH.ANTROPOLOGIA,
												 RH.ECONOMIA,
												 RH.MUSICOTERAPIA,
												 RH.ECONOMIA_DOMESTICA,
												 RH.POS_GRADUACAO,
												 RH.ESTAGIARIOS,
												 RH.VOLUNTARIOS,
												 RH.EXCLUSIVO_SERVICO,
												 RH.OUTROS_SERVICOS_ASSISTENCIAIS
												 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_RH RH
												 INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO S ON RH.ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO = S.ID
												 INNER JOIN TB_LOCAL_EXECUCAO_PUBLICO L on S.ID_LOCAL_EXECUCAO_PUBLICO = L.ID
												 INNER JOIN TB_UNIDADE_PUBLICA P ON L.ID_UNIDADE_PUBLICA = P.ID
									) RH 
									GROUP BY RH.ID_PREFEITURA, RH.ID_SERVICO) RH 
																			  ON(RH.ID_SERVICO = R.ID)

						    WHERE R.DESATIVADO <> 1
							GROUP BY
									R.ID,
									P.ID,
									S.ID,
									UN.ID, 
									MUN.ID,
									MUN.NOME,
									MUN.ID_DRADS,
									MUN.ID_REGIAO_METROPOLITANA,
									DRA.NOME,
									DRA.ID_MACRO_REGIAO,
									P.ID_NIVEL_GESTAO,
									P.POPULACAO,
									UN.RAZAO_SOCIAL,
									L.ID,
									L.NOME,
									U.NOME,
									S.NOME,
									R.DESCRICAO_NAO_TIPIFICADO,
									RH.TOTAL_SEM_ESCOLARIZACAO,
									RH.TOTAL_NIVEL_FUNDAMENTAL,
									RH.TOTAL_NIVEL_MEDIO,
									RH.TOTAL_NIVEL_SUPERIOR,
									RH.TOTAL_SERVICO_SOCIAL,
									RH.TOTAL_PSICOLOGIA,
									RH.TOTAL_PEDAGOGIA,
									RH.TOTAL_SOCIOLOGIA,
									RH.TOTAL_DIREITO,
									RH.TOTAL_TERAPIA_OCUPACIONAL,
									RH.TOTAL_ANTROPOLOGIA,
									RH.TOTAL_MUSICOTERAPIA,
									RH.TOTAL_ECONOMIA,
									RH.TOTAL_ECONOMIA_DOMESTICA,
									RH.TOTAL_POS_GRADUACAO,
									RH.TOTAL_ESTAGIARIOS,
									RH.TOTAL_VOLUNTARIOS,
									RH.TOTAL_EXCLUSIVO_SERVICO,
									RH.TOTAL_OUTROS_SERVICOS_ASSISTENCIAIS,
									U.ID_TIPO_SERVICO,
									S.NAO_TIPIFICADO,
									R.ID_TIPO_SERVICO_NAO_TIPIFICADO,
									U.ID,
									S.ID_TIPO_PROTECAO 
	   UNION ALL
				SELECT 
						R.ID,
						P.ID AS ID_PREFEITURA,
						MUN.ID AS ID_MUNICIPIO,
						MUN.ID_DRADS,
						MUN.NOME AS MUNICIPIO,
						DRA.NOME AS DRADS,
						COALESCE(MUN.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
						DRA.ID_MACRO_REGIAO,
						P.ID_NIVEL_GESTAO,
						(CASE WHEN P.POPULACAO <= 20000 THEN 1
							WHEN   P.POPULACAO <= 50000 THEN 2
							WHEN   P.POPULACAO <= 100000 THEN 3
							WHEN   P.POPULACAO <= 900000 THEN 4
							ELSE 5
						END) AS ID_PORTE,
						'Rede indireta' AS TIPO_UNIDADE,
						2 AS ID_TIPO_UNIDADE,
						UN.ID AS CODIGO_UNIDADE,
						UN.RAZAO_SOCIAL AS UNIDADE_RESPONSAVEL,
						CAST(L.ID AS VARCHAR) AS ID_LOCAL,
						L.NOME AS LOCAL_EXECUCAO,
						S.ID_TIPO_PROTECAO,
						U.ID_TIPO_SERVICO,
						S.NAO_TIPIFICADO,
						(CASE WHEN R.ID_TIPO_SERVICO_NAO_TIPIFICADO IS NOT NULL THEN ('Serviço não tipificado pela Resolução n° 109 do CNAS, de 11/11/2009 - ' + CASE WHEN DESCRICAO_NAO_TIPIFICADO IS NULL THEN S.NOME 
							  ELSE (CASE WHEN ID_TIPO_PROTECAO = 3 THEN  DESCRICAO_NAO_TIPIFICADO ELSE( S.NOME + ' - ' + DESCRICAO_NAO_TIPIFICADO)END)END)
										 ELSE (S.NOME + (CASE WHEN DESCRICAO_NAO_TIPIFICADO IS NULL THEN '' ELSE ( + ' - ' + DESCRICAO_NAO_TIPIFICADO)END)) END)  AS TIPO_SERVICO,
						U.ID AS ID_USUARIO_TIPO_SERVICO,
						U.NOME AS USUARIO,
						COALESCE(RH.TOTAL_SEM_ESCOLARIZACAO,0) AS SEM_ESCOLARIZACAO,
						COALESCE(RH.TOTAL_NIVEL_FUNDAMENTAL,0) AS NIVEL_FUNDAMENTAL,
						COALESCE(RH.TOTAL_NIVEL_MEDIO,0) AS NIVEL_MEDIO,
						COALESCE(RH.TOTAL_NIVEL_SUPERIOR,0) AS NIVEL_SUPERIOR,
						COALESCE(RH.TOTAL_SERVICO_SOCIAL,0) AS SERVICO_SOCIAL,
						COALESCE(RH.TOTAL_PSICOLOGIA,0) AS PSICOLOGIA,
						COALESCE(RH.TOTAL_PEDAGOGIA,0) AS PEDAGOGIA,
						COALESCE(RH.TOTAL_SOCIOLOGIA,0) AS SOCIOLOGIA,
						COALESCE(RH.TOTAL_DIREITO,0) AS DIREITO,
						COALESCE(RH.TOTAL_TERAPIA_OCUPACIONAL,0) AS TERAPIA_OCUPACIONAL,
						COALESCE(RH.TOTAL_ANTROPOLOGIA,0) AS ANTROPOLOGIA,
						COALESCE(RH.TOTAL_MUSICOTERAPIA,0) AS MUSICOTERAPIA,
						COALESCE(RH.TOTAL_ECONOMIA,0) AS ECONOMIA,
						COALESCE(RH.TOTAL_ECONOMIA_DOMESTICA,0) AS ECONOMIA_DOMESTICA,
						COALESCE(RH.TOTAL_POS_GRADUACAO,0) AS POS_GRADUACAO,
						COALESCE(RH.TOTAL_ESTAGIARIOS,0) AS ESTAGIARIOS,
						COALESCE(RH.TOTAL_VOLUNTARIOS, 0) AS VOLUNTARIOS,
						COALESCE(RH.TOTAL_EXCLUSIVO_SERVICO, 0) AS TOTAL_EXCLUSIVO_SERVICO,
						COALESCE(RH.TOTAL_OUTROS_SERVICOS_ASSISTENCIAIS, 0) AS TOTAL_OUTROS_SERVICOS_ASSISTENCIAIS,
						COALESCE((RH.TOTAL_NIVEL_SUPERIOR - (RH.TOTAL_SERVICO_SOCIAL + RH.TOTAL_PSICOLOGIA + RH.TOTAL_PEDAGOGIA + RH.TOTAL_ANTROPOLOGIA + RH.TOTAL_ECONOMIA + RH.TOTAL_TERAPIA_OCUPACIONAL + RH.TOTAL_SOCIOLOGIA + RH.TOTAL_DIREITO + RH.TOTAL_ECONOMIA_DOMESTICA)),0) AS OUTRAS_AREAS
						FROM TB_PREFEITURA P
							JOIN DBSEDS.DBO.TB_MUNICIPIOS MUN (NOLOCK) ON P.ID_MUNICIPIO = MUN.ID
							JOIN DBSEDS.DBO.TB_DRADS DRA (NOLOCK) ON MUN.ID_DRADS = DRA.ID
							INNER JOIN TB_UNIDADE_PRIVADA UN ON(UN.ID_PREFEITURA = P.ID)
							INNER JOIN TB_LOCAL_EXECUCAO_PRIVADO L ON(UN.ID = L.ID_UNIDADE_PRIVADA)
							INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO R ON(R.ID_LOCAL_EXECUCAO_PRIVADO = L.ID)
							LEFT JOIN TB_USUARIO_TIPO_SERVICO U ON (R.ID_USUARIO_TIPO_SERVICO = U.ID)
							LEFT JOIN TB_TIPO_SERVICO AS S ON (U.ID_TIPO_SERVICO = S.ID)
			-- RH 
				LEFT JOIN(
							SELECT 
							RH.ID_SERVICO,
							COALESCE(SUM(RH.SEM_ESCOLARIZACAO),0) AS TOTAL_SEM_ESCOLARIZACAO,
							COALESCE(SUM(RH.NIVEL_FUNDAMENTAL),0) AS TOTAL_NIVEL_FUNDAMENTAL,
							COALESCE(SUM(RH.NIVEL_MEDIO),0) AS TOTAL_NIVEL_MEDIO,
							COALESCE(SUM(RH.NIVEL_SUPERIOR),0) AS TOTAL_NIVEL_SUPERIOR,
							COALESCE(SUM(RH.SERVICO_SOCIAL),0) AS TOTAL_SERVICO_SOCIAL,
							COALESCE(SUM(RH.PSICOLOGIA),0) AS TOTAL_PSICOLOGIA,
							COALESCE(SUM(RH.PEDAGOGIA),0) AS TOTAL_PEDAGOGIA,
							COALESCE(SUM(RH.SOCIOLOGIA),0) AS TOTAL_SOCIOLOGIA,
							COALESCE(SUM(RH.TERAPIA_OCUPACIONAL),0) AS TOTAL_TERAPIA_OCUPACIONAL,
							COALESCE(SUM(RH.DIREITO),0) AS TOTAL_DIREITO,
							COALESCE(SUM(RH.ANTROPOLOGIA),0) AS TOTAL_ANTROPOLOGIA,
							COALESCE(SUM(RH.ECONOMIA),0) AS TOTAL_ECONOMIA,
							COALESCE(SUM(RH.MUSICOTERAPIA),0) AS TOTAL_MUSICOTERAPIA,
							COALESCE(SUM(RH.ECONOMIA_DOMESTICA),0) AS TOTAL_ECONOMIA_DOMESTICA,
							COALESCE(SUM(RH.POS_GRADUACAO),0) AS TOTAL_POS_GRADUACAO,
							COALESCE(SUM(RH.ESTAGIARIOS),0) AS TOTAL_ESTAGIARIOS,
							COALESCE(SUM(RH.VOLUNTARIOS),0) AS TOTAL_VOLUNTARIOS,
							COALESCE(SUM(RH.EXCLUSIVO_SERVICO),0) AS TOTAL_EXCLUSIVO_SERVICO,
							COALESCE(SUM(RH.OUTROS_SERVICOS_ASSISTENCIAIS),0) AS TOTAL_OUTROS_SERVICOS_ASSISTENCIAIS
							FROM(
									SELECT 
										 RH.ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO AS ID_SERVICO,
										 RH.SEM_ESCOLARIZACAO,
										 RH.NIVEL_FUNDAMENTAL,
										 RH.NIVEL_MEDIO,
										 RH.NIVEL_SUPERIOR,
										 RH.SERVICO_SOCIAL,
										 RH.PSICOLOGIA,
										 RH.PEDAGOGIA,
										 RH.SOCIOLOGIA,
										 RH.TERAPIA_OCUPACIONAL,
										 RH.DIREITO,
										 RH.ANTROPOLOGIA,
										 RH.ECONOMIA,
										 RH.MUSICOTERAPIA,
										 RH.ECONOMIA_DOMESTICA,
										 RH.POS_GRADUACAO,
										 RH.ESTAGIARIOS,
										 RH.VOLUNTARIOS,
										 RH.EXCLUSIVO_SERVICO,
										 RH.OUTROS_SERVICOS_ASSISTENCIAIS
										 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_RH RH
										 INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO S ON RH.ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO = S.ID
										 INNER JOIN TB_LOCAL_EXECUCAO_PRIVADO L on S.ID_LOCAL_EXECUCAO_PRIVADO = L.ID
										 INNER JOIN TB_UNIDADE_PRIVADA P ON L.ID_UNIDADE_PRIVADA = P.ID  
							) RH 
								GROUP BY RH.ID_SERVICO) RH ON(RH.ID_SERVICO = R.ID)
								WHERE R.DESATIVADO <> 1
								GROUP BY
										R.ID,
										P.ID,
										S.ID,
										UN.ID, 
										MUN.ID,
										MUN.NOME,
										MUN.ID_DRADS,
										MUN.ID_REGIAO_METROPOLITANA,
										DRA.NOME,
										DRA.ID_MACRO_REGIAO,
										P.ID_NIVEL_GESTAO,
										P.POPULACAO,
										UN.RAZAO_SOCIAL,
										L.ID,
										L.NOME,
										U.NOME,
										S.NOME,
										R.DESCRICAO_NAO_TIPIFICADO,
										RH.TOTAL_SEM_ESCOLARIZACAO,
										RH.TOTAL_NIVEL_FUNDAMENTAL,
										RH.TOTAL_NIVEL_MEDIO,
										RH.TOTAL_NIVEL_SUPERIOR,
										RH.TOTAL_SERVICO_SOCIAL,
										RH.TOTAL_PSICOLOGIA,
										RH.TOTAL_PEDAGOGIA,
										RH.TOTAL_SOCIOLOGIA,
										RH.TOTAL_DIREITO,
										RH.TOTAL_TERAPIA_OCUPACIONAL,
										RH.TOTAL_ANTROPOLOGIA,
										RH.TOTAL_MUSICOTERAPIA,
										RH.TOTAL_ECONOMIA,
										RH.TOTAL_ECONOMIA_DOMESTICA,
										RH.TOTAL_POS_GRADUACAO,
										RH.TOTAL_ESTAGIARIOS,
										RH.TOTAL_VOLUNTARIOS,
										RH.TOTAL_EXCLUSIVO_SERVICO,
										RH.TOTAL_OUTROS_SERVICOS_ASSISTENCIAIS,
										U.ID_TIPO_SERVICO,
										S.NAO_TIPIFICADO,
										R.ID_TIPO_SERVICO_NAO_TIPIFICADO,
										U.ID,
										S.ID_TIPO_PROTECAO 
			UNION ALL
				  SELECT 
						R.ID,
						P.ID AS ID_PREFEITURA,
						MUN.ID AS ID_MUNICIPIO,
						MUN.ID_DRADS,
						MUN.NOME AS MUNICIPIO,
						DRA.NOME AS DRADS,
						COALESCE(MUN.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
						DRA.ID_MACRO_REGIAO,
						P.ID_NIVEL_GESTAO,
						(CASE WHEN P.POPULACAO <= 20000 THEN 1
							WHEN   P.POPULACAO <= 50000 THEN 2
							WHEN   P.POPULACAO <= 100000 THEN 3
							WHEN   P.POPULACAO <= 900000 THEN 4
							ELSE 5
						END) AS ID_PORTE,
						'Rede direta' AS TIPO_UNIDADE,
						3 AS ID_TIPO_UNIDADE,
						C.ID AS CODIGO_UNIDADE,
						UP.RAZAO_SOCIAL AS UNIDADE_RESPONSAVEL,
						CAST(C.IDCRAS AS VARCHAR) AS ID_LOCAL,
						C.NOME AS LOCAL_EXECUCAO,
						S.ID_TIPO_PROTECAO,
						U.ID_TIPO_SERVICO,
						S.NAO_TIPIFICADO,
						((CASE WHEN DESCRICAO_NAO_TIPIFICADO IS NULL THEN S.NOME ELSE ('Serviço não tipificado pela Resolução nº 109 do CNAS, de 11/11/2009 - ' + S.NOME + ' - ' + DESCRICAO_NAO_TIPIFICADO)END))  AS TIPO_SERVICO,
						U.ID AS ID_USUARIO_TIPO_SERVICO,
						U.NOME AS USUARIO,
						COALESCE(RH.TOTAL_SEM_ESCOLARIZACAO,0) AS SEM_ESCOLARIZACAO,
						COALESCE(RH.TOTAL_NIVEL_FUNDAMENTAL,0) AS NIVEL_FUNDAMENTAL,
						COALESCE(RH.TOTAL_NIVEL_MEDIO,0) AS NIVEL_MEDIO,
						COALESCE(RH.TOTAL_NIVEL_SUPERIOR,0) AS NIVEL_SUPERIOR,
						COALESCE(RH.TOTAL_SERVICO_SOCIAL,0) AS SERVICO_SOCIAL,
						COALESCE(RH.TOTAL_PSICOLOGIA,0) AS PSICOLOGIA,
						COALESCE(RH.TOTAL_PEDAGOGIA,0) AS PEDAGOGIA,
						COALESCE(RH.TOTAL_SOCIOLOGIA,0) AS SOCIOLOGIA,
						COALESCE(RH.TOTAL_DIREITO,0) AS DIREITO,
						COALESCE(RH.TOTAL_TERAPIA_OCUPACIONAL,0) AS TERAPIA_OCUPACIONAL,
						COALESCE(RH.TOTAL_ANTROPOLOGIA,0) AS ANTROPOLOGIA,
						COALESCE(RH.TOTAL_MUSICOTERAPIA,0) AS MUSICOTERAPIA,
						COALESCE(RH.TOTAL_ECONOMIA,0) AS ECONOMIA,
						COALESCE(RH.TOTAL_ECONOMIA_DOMESTICA,0) AS ECONOMIA_DOMESTICA,
						COALESCE(RH.TOTAL_POS_GRADUACAO,0) AS POS_GRADUACAO,
						COALESCE(RH.TOTAL_ESTAGIARIOS,0) AS ESTAGIARIOS,
						COALESCE(RH.TOTAL_VOLUNTARIOS, 0) AS VOLUNTARIOS,
						COALESCE(RH.TOTAL_EXCLUSIVO_SERVICO, 0) AS TOTAL_EXCLUSIVO_SERVICO,
						COALESCE(RH.TOTAL_OUTROS_SERVICOS_ASSISTENCIAIS, 0) AS TOTAL_OUTROS_SERVICOS_ASSISTENCIAIS,
						COALESCE((RH.TOTAL_NIVEL_SUPERIOR - (RH.TOTAL_SERVICO_SOCIAL + RH.TOTAL_PSICOLOGIA + RH.TOTAL_PEDAGOGIA + RH.TOTAL_ANTROPOLOGIA + RH.TOTAL_ECONOMIA + RH.TOTAL_TERAPIA_OCUPACIONAL + RH.TOTAL_SOCIOLOGIA + RH.TOTAL_DIREITO + RH.TOTAL_ECONOMIA_DOMESTICA)),0) AS OUTRAS_AREAS
						FROM TB_PREFEITURA P
							JOIN DBSEDS.DBO.TB_MUNICIPIOS MUN (NOLOCK) ON P.ID_MUNICIPIO = MUN.ID
							JOIN DBSEDS.DBO.TB_DRADS DRA (NOLOCK) ON MUN.ID_DRADS = DRA.ID
							INNER JOIN TB_UNIDADE_PUBLICA UP ON(UP.ID_PREFEITURA = P.ID)
							INNER JOIN TB_CRAS C ON(C.ID_UNIDADE_PUBLICA = UP.ID)
							INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS R ON(R.ID_CRAS = C.ID)
							LEFT JOIN TB_USUARIO_TIPO_SERVICO U ON (R.ID_USUARIO_TIPO_SERVICO = U.ID)
							LEFT JOIN TB_TIPO_SERVICO AS S ON (U.ID_TIPO_SERVICO = S.ID)
						-- RH 
						LEFT JOIN(
									SELECT RH.ID_SERVICO,
									COALESCE(SUM(RH.SEM_ESCOLARIZACAO),0) AS TOTAL_SEM_ESCOLARIZACAO,
									COALESCE(SUM(RH.NIVEL_FUNDAMENTAL),0) AS TOTAL_NIVEL_FUNDAMENTAL,
									COALESCE(SUM(RH.NIVEL_MEDIO),0) AS TOTAL_NIVEL_MEDIO,
									COALESCE(SUM(RH.NIVEL_SUPERIOR),0) AS TOTAL_NIVEL_SUPERIOR,
									COALESCE(SUM(RH.SERVICO_SOCIAL),0) AS TOTAL_SERVICO_SOCIAL,
									COALESCE(SUM(RH.PSICOLOGIA),0) AS TOTAL_PSICOLOGIA,
									COALESCE(SUM(RH.PEDAGOGIA),0) AS TOTAL_PEDAGOGIA,
									COALESCE(SUM(RH.SOCIOLOGIA),0) AS TOTAL_SOCIOLOGIA,
									COALESCE(SUM(RH.TERAPIA_OCUPACIONAL),0) AS TOTAL_TERAPIA_OCUPACIONAL,
									COALESCE(SUM(RH.DIREITO),0) AS TOTAL_DIREITO,
									COALESCE(SUM(RH.ANTROPOLOGIA),0) AS TOTAL_ANTROPOLOGIA,
									COALESCE(SUM(RH.ECONOMIA),0) AS TOTAL_ECONOMIA,
									COALESCE(SUM(RH.MUSICOTERAPIA),0) AS TOTAL_MUSICOTERAPIA,
									COALESCE(SUM(RH.ECONOMIA_DOMESTICA),0) AS TOTAL_ECONOMIA_DOMESTICA,
									COALESCE(SUM(RH.POS_GRADUACAO),0) AS TOTAL_POS_GRADUACAO,
									COALESCE(SUM(RH.ESTAGIARIOS),0) AS TOTAL_ESTAGIARIOS,
									COALESCE(SUM(RH.VOLUNTARIOS),0) AS TOTAL_VOLUNTARIOS,
									COALESCE(SUM(RH.EXCLUSIVO_SERVICO),0) AS TOTAL_EXCLUSIVO_SERVICO,
									COALESCE(SUM(RH.OUTROS_SERVICOS_ASSISTENCIAIS),0) AS TOTAL_OUTROS_SERVICOS_ASSISTENCIAIS
									FROM(
									SELECT
										 S.ID AS ID_SERVICO,
										 P.ID_PREFEITURA,
										 RH.SEM_ESCOLARIZACAO,
										 RH.NIVEL_FUNDAMENTAL,
										 RH.NIVEL_MEDIO,
										 RH.NIVEL_SUPERIOR,
										 RH.SERVICO_SOCIAL,
										 RH.PSICOLOGIA,
										 RH.PEDAGOGIA,
										 RH.SOCIOLOGIA,
										 RH.TERAPIA_OCUPACIONAL,
										 RH.DIREITO,
										 RH.ANTROPOLOGIA,
										 RH.ECONOMIA,
										 RH.MUSICOTERAPIA,
										 RH.ECONOMIA_DOMESTICA,
										 RH.POS_GRADUACAO,
										 RH.ESTAGIARIOS,
										 RH.VOLUNTARIOS,
										 RH.EXCLUSIVO_SERVICO,
										 RH.OUTROS_SERVICOS_ASSISTENCIAIS
										 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_RH RH
										 INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS S ON RH.ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS = S.ID
										 INNER JOIN TB_CRAS L on S.ID_CRAS = L.ID
										 INNER JOIN TB_UNIDADE_PUBLICA P ON L.ID_UNIDADE_PUBLICA = P.ID
									) RH 
						GROUP BY RH.ID_SERVICO) RH ON(RH.ID_SERVICO = R.ID)
						WHERE R.DESATIVADO <> 1
						GROUP BY 
								R.ID,
								P.ID,
								S.ID,
								MUN.ID,
								MUN.NOME,
								MUN.ID_DRADS,
								MUN.ID_REGIAO_METROPOLITANA,
								DRA.NOME,
								DRA.ID_MACRO_REGIAO,
								P.ID_NIVEL_GESTAO,
								P.POPULACAO,
								C.ID,
								UP.RAZAO_SOCIAL,
								C.IDCRAS,
								C.NOME,
								U.NOME,
								S.NOME,
								R.DESCRICAO_NAO_TIPIFICADO,
								RH.TOTAL_SEM_ESCOLARIZACAO,
								RH.TOTAL_NIVEL_FUNDAMENTAL,
								RH.TOTAL_NIVEL_MEDIO,
								RH.TOTAL_NIVEL_SUPERIOR,
								RH.TOTAL_SERVICO_SOCIAL,
								RH.TOTAL_PSICOLOGIA,
								RH.TOTAL_PEDAGOGIA,
								RH.TOTAL_SOCIOLOGIA,
								RH.TOTAL_DIREITO,
								RH.TOTAL_TERAPIA_OCUPACIONAL,
								RH.TOTAL_ANTROPOLOGIA,
								RH.TOTAL_MUSICOTERAPIA,
								RH.TOTAL_ECONOMIA,
								RH.TOTAL_ECONOMIA_DOMESTICA,
								RH.TOTAL_POS_GRADUACAO,
								RH.TOTAL_ESTAGIARIOS,
								RH.TOTAL_VOLUNTARIOS,
								RH.TOTAL_EXCLUSIVO_SERVICO,
								RH.TOTAL_OUTROS_SERVICOS_ASSISTENCIAIS,
								U.ID_TIPO_SERVICO,
								S.NAO_TIPIFICADO,
								U.ID,
								S.ID_TIPO_PROTECAO


	UNION ALL
				 SELECT 
						R.ID,
						P.ID AS ID_PREFEITURA,
						MUN.ID AS ID_MUNICIPIO,
						MUN.ID_DRADS,
						MUN.NOME AS MUNICIPIO,
						DRA.NOME AS DRADS,
						COALESCE(MUN.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
						DRA.ID_MACRO_REGIAO,
						P.ID_NIVEL_GESTAO,
						(CASE WHEN P.POPULACAO <= 20000 THEN 1
							WHEN   P.POPULACAO <= 50000 THEN 2
							WHEN   P.POPULACAO <= 100000 THEN 3
							WHEN   P.POPULACAO <= 900000 THEN 4
							ELSE 5
						END) AS ID_PORTE,
						'Rede direta' AS TIPO_UNIDADE,
						4 AS ID_TIPO_UNIDADE,
						C.ID AS CODIGO_UNIDADE,
						UP.RAZAO_SOCIAL AS UNIDADE_RESPONSAVEL,
						CAST(C.IDCREAS AS VARCHAR) AS ID_LOCAL,
						C.NOME AS LOCAL_EXECUCAO,
						S.ID_TIPO_PROTECAO,
						U.ID_TIPO_SERVICO,
						S.NAO_TIPIFICADO,
						((CASE WHEN DESCRICAO_NAO_TIPIFICADO IS NULL THEN S.NOME ELSE ('Serviço não tipificado pela Resolução nº 109 do CNAS, de 11/11/2009 - ' + S.NOME + ' - ' + DESCRICAO_NAO_TIPIFICADO)END))  AS TIPO_SERVICO,
						U.ID AS ID_USUARIO_TIPO_SERVICO,
						U.NOME AS USUARIO,
						COALESCE(RH.TOTAL_SEM_ESCOLARIZACAO,0) AS SEM_ESCOLARIZACAO,
						COALESCE(RH.TOTAL_NIVEL_FUNDAMENTAL,0) AS NIVEL_FUNDAMENTAL,
						COALESCE(RH.TOTAL_NIVEL_MEDIO,0) AS NIVEL_MEDIO,
						COALESCE(RH.TOTAL_NIVEL_SUPERIOR,0) AS NIVEL_SUPERIOR,
						COALESCE(RH.TOTAL_SERVICO_SOCIAL,0) AS SERVICO_SOCIAL,
						COALESCE(RH.TOTAL_PSICOLOGIA,0) AS PSICOLOGIA,
						COALESCE(RH.TOTAL_PEDAGOGIA,0) AS PEDAGOGIA,
						COALESCE(RH.TOTAL_SOCIOLOGIA,0) AS SOCIOLOGIA,
						COALESCE(RH.TOTAL_DIREITO,0) AS DIREITO,
						COALESCE(RH.TOTAL_TERAPIA_OCUPACIONAL,0) AS TERAPIA_OCUPACIONAL,
						COALESCE(RH.TOTAL_ANTROPOLOGIA,0) AS ANTROPOLOGIA,
						COALESCE(RH.TOTAL_MUSICOTERAPIA,0) AS MUSICOTERAPIA,
						COALESCE(RH.TOTAL_ECONOMIA,0) AS ECONOMIA,
						COALESCE(RH.TOTAL_ECONOMIA_DOMESTICA,0) AS ECONOMIA_DOMESTICA,
						COALESCE(RH.TOTAL_POS_GRADUACAO,0) AS POS_GRADUACAO,
						COALESCE(RH.TOTAL_ESTAGIARIOS,0) AS ESTAGIARIOS,
						COALESCE(RH.TOTAL_VOLUNTARIOS, 0) AS VOLUNTARIOS,
						COALESCE(RH.TOTAL_EXCLUSIVO_SERVICO, 0) AS TOTAL_EXCLUSIVO_SERVICO,
						COALESCE(RH.TOTAL_OUTROS_SERVICOS_ASSISTENCIAIS, 0) AS TOTAL_OUTROS_SERVICOS_ASSISTENCIAIS,
						COALESCE((RH.TOTAL_NIVEL_SUPERIOR - (RH.TOTAL_SERVICO_SOCIAL + RH.TOTAL_PSICOLOGIA + RH.TOTAL_PEDAGOGIA + RH.TOTAL_ANTROPOLOGIA + RH.TOTAL_ECONOMIA + RH.TOTAL_TERAPIA_OCUPACIONAL + RH.TOTAL_SOCIOLOGIA + RH.TOTAL_DIREITO + RH.TOTAL_ECONOMIA_DOMESTICA)),0) AS OUTRAS_AREAS
						FROM TB_PREFEITURA P
							JOIN DBSEDS.DBO.TB_MUNICIPIOS MUN (NOLOCK) ON (P.ID_MUNICIPIO = MUN.ID)
							JOIN DBSEDS.DBO.TB_DRADS DRA (NOLOCK) ON (MUN.ID_DRADS = DRA.ID)
							INNER JOIN TB_UNIDADE_PUBLICA UP ON(UP.ID_PREFEITURA = P.ID)
							INNER JOIN TB_CREAS C ON(C.ID_UNIDADE_PUBLICA = UP.ID)
							INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS R ON (R.ID_CREAS = C.ID)
							LEFT JOIN TB_USUARIO_TIPO_SERVICO U ON (R.ID_USUARIO_TIPO_SERVICO = U.ID)
							LEFT JOIN TB_TIPO_SERVICO AS S ON (U.ID_TIPO_SERVICO = S.ID)
						-- RH 
						LEFT JOIN(
						SELECT RH.ID_SERVICO,
						COALESCE(SUM(RH.SEM_ESCOLARIZACAO),0) AS TOTAL_SEM_ESCOLARIZACAO,
						COALESCE(SUM(RH.NIVEL_FUNDAMENTAL),0) AS TOTAL_NIVEL_FUNDAMENTAL,
						COALESCE(SUM(RH.NIVEL_MEDIO),0) AS TOTAL_NIVEL_MEDIO,
						COALESCE(SUM(RH.NIVEL_SUPERIOR),0) AS TOTAL_NIVEL_SUPERIOR,
						COALESCE(SUM(RH.SERVICO_SOCIAL),0) AS TOTAL_SERVICO_SOCIAL,
						COALESCE(SUM(RH.PSICOLOGIA),0) AS TOTAL_PSICOLOGIA,
						COALESCE(SUM(RH.PEDAGOGIA),0) AS TOTAL_PEDAGOGIA,
						COALESCE(SUM(RH.SOCIOLOGIA),0) AS TOTAL_SOCIOLOGIA,
						COALESCE(SUM(RH.TERAPIA_OCUPACIONAL),0) AS TOTAL_TERAPIA_OCUPACIONAL,
						COALESCE(SUM(RH.DIREITO),0) AS TOTAL_DIREITO,
						COALESCE(SUM(RH.ANTROPOLOGIA),0) AS TOTAL_ANTROPOLOGIA,
						COALESCE(SUM(RH.ECONOMIA),0) AS TOTAL_ECONOMIA,
						COALESCE(SUM(RH.MUSICOTERAPIA),0) AS TOTAL_MUSICOTERAPIA,
						COALESCE(SUM(RH.ECONOMIA_DOMESTICA),0) AS TOTAL_ECONOMIA_DOMESTICA,
						COALESCE(SUM(RH.POS_GRADUACAO),0) AS TOTAL_POS_GRADUACAO,
						COALESCE(SUM(RH.ESTAGIARIOS),0) AS TOTAL_ESTAGIARIOS,
						COALESCE(SUM(RH.VOLUNTARIOS),0) AS TOTAL_VOLUNTARIOS,
						COALESCE(SUM(RH.EXCLUSIVO_SERVICO),0) AS TOTAL_EXCLUSIVO_SERVICO,
						COALESCE(SUM(RH.OUTROS_SERVICOS_ASSISTENCIAIS),0) AS TOTAL_OUTROS_SERVICOS_ASSISTENCIAIS
						FROM(
							SELECT 
								 S.ID as ID_SERVICO,
								 RH.SEM_ESCOLARIZACAO,
								 RH.NIVEL_FUNDAMENTAL,
								 RH.NIVEL_MEDIO,
								 RH.NIVEL_SUPERIOR,
								 RH.SERVICO_SOCIAL,
								 RH.PSICOLOGIA,
								 RH.PEDAGOGIA,
								 RH.SOCIOLOGIA,
								 RH.TERAPIA_OCUPACIONAL,
								 RH.DIREITO,
								 RH.ANTROPOLOGIA,
								 RH.ECONOMIA,
								 RH.MUSICOTERAPIA,
								 RH.ECONOMIA_DOMESTICA,
								 RH.POS_GRADUACAO,
								 RH.ESTAGIARIOS,
								 RH.VOLUNTARIOS,
								 RH.EXCLUSIVO_SERVICO,
								 RH.OUTROS_SERVICOS_ASSISTENCIAIS
								 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_RH RH
									 INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS S ON RH.ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS = S.ID
									 INNER JOIN TB_CREAS L on S.ID_CREAS = L.ID
									 INNER JOIN TB_UNIDADE_PUBLICA P ON L.ID_UNIDADE_PUBLICA = P.ID
						) RH 
						GROUP BY  RH.ID_SERVICO) RH ON( RH.ID_SERVICO = R.ID)
						WHERE R.DESATIVADO <> 1
						GROUP BY 
								R.ID,
								P.ID,
								MUN.ID,
								MUN.NOME,
								MUN.ID_DRADS,
								MUN.ID_REGIAO_METROPOLITANA,
								DRA.NOME,
								DRA.ID_MACRO_REGIAO,
								P.ID_NIVEL_GESTAO,
								P.POPULACAO,
								C.ID,
								UP.RAZAO_SOCIAL,
								C.IDCREAS,
								C.NOME,
								R.DESCRICAO_NAO_TIPIFICADO,
								S.NOME,
								U.NOME,
								RH.TOTAL_SEM_ESCOLARIZACAO,
								RH.TOTAL_NIVEL_FUNDAMENTAL,
								RH.TOTAL_NIVEL_MEDIO,
								RH.TOTAL_NIVEL_SUPERIOR,
								RH.TOTAL_SERVICO_SOCIAL,
								RH.TOTAL_PSICOLOGIA,
								RH.TOTAL_PEDAGOGIA,
								RH.TOTAL_SOCIOLOGIA,
								RH.TOTAL_DIREITO,
								RH.TOTAL_TERAPIA_OCUPACIONAL,
								RH.TOTAL_ANTROPOLOGIA,
								RH.TOTAL_MUSICOTERAPIA,
								RH.TOTAL_ECONOMIA,
								RH.TOTAL_ECONOMIA_DOMESTICA,
								RH.TOTAL_POS_GRADUACAO,
								RH.TOTAL_ESTAGIARIOS,
								RH.TOTAL_VOLUNTARIOS,
								RH.TOTAL_EXCLUSIVO_SERVICO,
								RH.TOTAL_OUTROS_SERVICOS_ASSISTENCIAIS,
								U.ID_TIPO_SERVICO,
								S.NAO_TIPIFICADO,
								U.ID,
								S.ID_TIPO_PROTECAO

		UNION ALL
				SELECT 
					R.ID,
					P.ID AS ID_PREFEITURA,
					MUN.ID AS ID_MUNICIPIO,
					MUN.ID_DRADS,
					MUN.NOME AS MUNICIPIO,
					DRA.NOME AS DRADS,
					COALESCE(MUN.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
					DRA.ID_MACRO_REGIAO,
					P.ID_NIVEL_GESTAO,
					(CASE WHEN P.POPULACAO <= 20000 THEN 1
						WHEN   P.POPULACAO <= 50000 THEN 2
						WHEN   P.POPULACAO <= 100000 THEN 3
						WHEN   P.POPULACAO <= 900000 THEN 4
						ELSE 5
					END) AS ID_PORTE,
					'Rede direta' AS TIPO_UNIDADE,
					5 AS ID_TIPO_UNIDADE,
					C.ID AS CODIGO_UNIDADE,
					UP.RAZAO_SOCIAL AS UNIDADE_RESPONSAVEL,
					CAST(IDCREAS AS VARCHAR) AS ID_LOCAL,
					c.NOME AS LOCAL_EXECUCAO,
					S.ID_TIPO_PROTECAO,
					U.ID_TIPO_SERVICO,
					S.NAO_TIPIFICADO,
					((CASE WHEN R.DESCRICAO_NAO_TIPIFICADO IS NULL THEN S.NOME ELSE ('Serviço não tipificado pela Resolução nº 109 do CNAS, de 11/11/2009 - ' + S.NOME + ' - ' + R.DESCRICAO_NAO_TIPIFICADO)END))  AS TIPO_SERVICO,
					U.ID AS ID_USUARIO_TIPO_SERVICO,
					U.NOME AS USUARIO,
					COALESCE(RH.TOTAL_SEM_ESCOLARIZACAO,0) AS SEM_ESCOLARIZACAO,
					COALESCE(RH.TOTAL_NIVEL_FUNDAMENTAL,0) AS NIVEL_FUNDAMENTAL,
					COALESCE(RH.TOTAL_NIVEL_MEDIO,0) AS NIVEL_MEDIO,
					COALESCE(RH.TOTAL_NIVEL_SUPERIOR,0) AS NIVEL_SUPERIOR,
					COALESCE(RH.TOTAL_SERVICO_SOCIAL,0) AS SERVICO_SOCIAL,
					COALESCE(RH.TOTAL_PSICOLOGIA,0) AS PSICOLOGIA,
					COALESCE(RH.TOTAL_PEDAGOGIA,0) AS PEDAGOGIA,
					COALESCE(RH.TOTAL_SOCIOLOGIA,0) AS SOCIOLOGIA,
					COALESCE(RH.TOTAL_DIREITO,0) AS DIREITO,
					COALESCE(RH.TOTAL_TERAPIA_OCUPACIONAL,0) AS TERAPIA_OCUPACIONAL,
					COALESCE(RH.TOTAL_ANTROPOLOGIA,0) AS ANTROPOLOGIA,
					COALESCE(RH.TOTAL_MUSICOTERAPIA,0) AS MUSICOTERAPIA,
					COALESCE(RH.TOTAL_ECONOMIA,0) AS ECONOMIA,
					COALESCE(RH.TOTAL_ECONOMIA_DOMESTICA,0) AS ECONOMIA_DOMESTICA,
					COALESCE(RH.TOTAL_POS_GRADUACAO,0) AS POS_GRADUACAO,
					COALESCE(RH.TOTAL_ESTAGIARIOS,0) AS ESTAGIARIOS,
					COALESCE(RH.TOTAL_VOLUNTARIOS, 0) AS VOLUNTARIOS,
					COALESCE(RH.TOTAL_EXCLUSIVO_SERVICO, 0) AS TOTAL_EXCLUSIVO_SERVICO,
					COALESCE(RH.TOTAL_OUTROS_SERVICOS_ASSISTENCIAIS, 0) AS TOTAL_OUTROS_SERVICOS_ASSISTENCIAIS,
					COALESCE((RH.TOTAL_NIVEL_SUPERIOR - (RH.TOTAL_SERVICO_SOCIAL + RH.TOTAL_PSICOLOGIA + RH.TOTAL_PEDAGOGIA + RH.TOTAL_ANTROPOLOGIA + RH.TOTAL_ECONOMIA + RH.TOTAL_TERAPIA_OCUPACIONAL + RH.TOTAL_SOCIOLOGIA + RH.TOTAL_DIREITO + RH.TOTAL_ECONOMIA_DOMESTICA)),0) AS OUTRAS_AREAS
									FROM TB_PREFEITURA P
									JOIN DBSEDS.DBO.TB_MUNICIPIOS MUN (NOLOCK)
									ON P.ID_MUNICIPIO = MUN.ID
									JOIN DBSEDS.DBO.TB_DRADS DRA (NOLOCK)
									ON MUN.ID_DRADS = DRA.ID
									INNER JOIN TB_UNIDADE_PUBLICA UP ON(UP.ID_PREFEITURA = P.ID)
									INNER JOIN TB_CENTRO_POP C ON(C.ID_UNIDADE_PUBLICA = UP.ID)
									INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP R ON(R.ID_CENTRO_POP = C.ID)
									LEFT JOIN TB_USUARIO_TIPO_SERVICO U ON (R.ID_USUARIO_TIPO_SERVICO = U.ID)
									LEFT JOIN TB_TIPO_SERVICO AS S ON (U.ID_TIPO_SERVICO = S.ID)
									-- RH 
									LEFT JOIN(
									SELECT 
									RH.ID_SERVICO,
									COALESCE(SUM(RH.SEM_ESCOLARIZACAO),0) AS TOTAL_SEM_ESCOLARIZACAO,
									COALESCE(SUM(RH.NIVEL_FUNDAMENTAL),0) AS TOTAL_NIVEL_FUNDAMENTAL,
									COALESCE(SUM(RH.NIVEL_MEDIO),0) AS TOTAL_NIVEL_MEDIO,
									COALESCE(SUM(RH.NIVEL_SUPERIOR),0) AS TOTAL_NIVEL_SUPERIOR,
									COALESCE(SUM(RH.SERVICO_SOCIAL),0) AS TOTAL_SERVICO_SOCIAL,
									COALESCE(SUM(RH.PSICOLOGIA),0) AS TOTAL_PSICOLOGIA,
									COALESCE(SUM(RH.PEDAGOGIA),0) AS TOTAL_PEDAGOGIA,
									COALESCE(SUM(RH.SOCIOLOGIA),0) AS TOTAL_SOCIOLOGIA,
									COALESCE(SUM(RH.TERAPIA_OCUPACIONAL),0) AS TOTAL_TERAPIA_OCUPACIONAL,
									COALESCE(SUM(RH.DIREITO),0) AS TOTAL_DIREITO,
									COALESCE(SUM(RH.ANTROPOLOGIA),0) AS TOTAL_ANTROPOLOGIA,
									COALESCE(SUM(RH.ECONOMIA),0) AS TOTAL_ECONOMIA,
									COALESCE(SUM(RH.MUSICOTERAPIA),0) AS TOTAL_MUSICOTERAPIA,
									COALESCE(SUM(RH.ECONOMIA_DOMESTICA),0) AS TOTAL_ECONOMIA_DOMESTICA,
									COALESCE(SUM(RH.POS_GRADUACAO),0) AS TOTAL_POS_GRADUACAO,
									COALESCE(SUM(RH.ESTAGIARIOS),0) AS TOTAL_ESTAGIARIOS,
									COALESCE(SUM(RH.VOLUNTARIOS),0) AS TOTAL_VOLUNTARIOS,
									COALESCE(SUM(RH.EXCLUSIVO_SERVICO),0) AS TOTAL_EXCLUSIVO_SERVICO,
									COALESCE(SUM(RH.OUTROS_SERVICOS_ASSISTENCIAIS),0) AS TOTAL_OUTROS_SERVICOS_ASSISTENCIAIS
									FROM(
									SELECT 
										 S.ID AS ID_SERVICO,
										 RH.SEM_ESCOLARIZACAO,
										 RH.NIVEL_FUNDAMENTAL,
										 RH.NIVEL_MEDIO,
										 RH.NIVEL_SUPERIOR,
										 RH.SERVICO_SOCIAL,
										 RH.PSICOLOGIA,
										 RH.PEDAGOGIA,
										 RH.SOCIOLOGIA,
										 RH.TERAPIA_OCUPACIONAL,
										 RH.DIREITO,
										 RH.ANTROPOLOGIA,
										 RH.ECONOMIA,
										 RH.MUSICOTERAPIA,
										 RH.ECONOMIA_DOMESTICA,
										 RH.POS_GRADUACAO,
										 RH.ESTAGIARIOS,
										 RH.VOLUNTARIOS,
										 RH.EXCLUSIVO_SERVICO,
										 RH.OUTROS_SERVICOS_ASSISTENCIAIS
										 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_RH RH
										 INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP S ON RH.ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP = S.ID
										 INNER JOIN TB_CENTRO_POP L on S.ID_CENTRO_POP = L.ID
										 INNER JOIN TB_UNIDADE_PUBLICA P ON L.ID_UNIDADE_PUBLICA = P.ID
									) RH 
									GROUP BY RH.ID_SERVICO) RH ON(RH.ID_SERVICO = R.ID)
									WHERE R.DESATIVADO <> 1
									GROUP BY
												R.ID,
												P.ID,
												MUN.ID,
												MUN.NOME,
												MUN.ID_DRADS,
												MUN.ID_REGIAO_METROPOLITANA,
												DRA.NOME,
												DRA.ID_MACRO_REGIAO,
												P.ID_NIVEL_GESTAO,
												P.POPULACAO,
												C.ID,
												UP.RAZAO_SOCIAL,
												C.IDCREAS,
												C.NOME,
												R.DESCRICAO_NAO_TIPIFICADO,
												U.NOME,
												S.NOME,
												RH.TOTAL_SEM_ESCOLARIZACAO,
												RH.TOTAL_NIVEL_FUNDAMENTAL,
												RH.TOTAL_NIVEL_MEDIO,
												RH.TOTAL_NIVEL_SUPERIOR,
												RH.TOTAL_SERVICO_SOCIAL,
												RH.TOTAL_PSICOLOGIA,
												RH.TOTAL_PEDAGOGIA,
												RH.TOTAL_SOCIOLOGIA,
												RH.TOTAL_DIREITO,
												RH.TOTAL_TERAPIA_OCUPACIONAL,
												RH.TOTAL_ANTROPOLOGIA,
												RH.TOTAL_MUSICOTERAPIA,
												RH.TOTAL_ECONOMIA,
												RH.TOTAL_ECONOMIA_DOMESTICA,
												RH.TOTAL_POS_GRADUACAO,
												RH.TOTAL_ESTAGIARIOS,
												RH.TOTAL_VOLUNTARIOS,
												RH.TOTAL_EXCLUSIVO_SERVICO,
												RH.TOTAL_OUTROS_SERVICOS_ASSISTENCIAIS,
												U.ID_TIPO_SERVICO,
												S.NAO_TIPIFICADO,
												U.ID,
												S.ID_TIPO_PROTECAO

GO


