use Dbpmas_quadrienal
go

UPDATE TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_PUBLICO 
		SET VALOR_ESTADUAL_ASSISTENCIA = 0 where ID = 2440

UPDATE TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_PRIVADO 
		SET VALOR_MUNICIPAL_ASSISTENCIA = 0
		  , VALOR_ESTADUAL_ASSISTENCIA = 0
		  , VALOR_FEDERAL_ASSISTENCIA = 0
where ID = 4773