USE [Dbpmas_quadrienal_DESENV]
GO

/****** Object:  StoredProcedure [dbo].[PR_PREFEITURA_BENEFICIO_EVENTUAL_SERVICOS]    Script Date: 13/09/2019 11:16:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[PR_PREFEITURA_BENEFICIO_EVENTUAL_SERVICOS]
	@ID_PREFEITURA_BENEFICIO_EVENTUAL  INT 
AS  
  SELECT DISTINCT BES.ID
		,BES.ID_PREFEITURA_BENEFICIO_EVENTUAL
		,L.ID AS ID_UNIDADE
		,5 AS ID_TIPO_UNIDADE
		,'Centro Pop' AS TIPO_UNIDADE
		,L.NOME AS UNIDADE
		,S.ID AS ID_SERVICOS_RECURSOS_FINANCEIROS
		,S.ID_USUARIO_TIPO_SERVICO
		,U.NOME AS USUARIO
		,U.ID_TIPO_SERVICO
		,(T.NOME + (CASE WHEN DESCRICAO_NAO_TIPIFICADO IS NULL THEN '' ELSE (' - ' + DESCRICAO_NAO_TIPIFICADO)END))  AS TIPO_SERVICO
		,T.ID_TIPO_PROTECAO
		,P.NOME AS PROTECAO_SOCIAL
		--,S.MEDIA_MENSAL_ATENDIMENTO_2017 AS NUMERO_ATENDIDOS
		,S2.MEDIA AS NUMERO_ATENDIDOS
		,S2.EXERCICIO
		,BES.NUMERO_BENEFICIARIOS
		
	 
  FROM TB_PREFEITURA_BENEFICIO_EVENTUAL_SERVICOS BES
  INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP S 
		ON(S.ID = BES.ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP AND BES.ID_PREFEITURA_BENEFICIO_EVENTUAL = @ID_PREFEITURA_BENEFICIO_EVENTUAL)

  INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_CAPACIDADE S1
		ON(S.ID = S1.ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP)
  INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_MEDIA_MENSAL S2
		ON(S.ID = S2.ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP)

  INNER JOIN TB_CENTRO_POP L ON(L.ID = S.ID_CENTRO_POP)
  INNER JOIN TB_USUARIO_TIPO_SERVICO U ON (U.ID = S.ID_USUARIO_TIPO_SERVICO)
  INNER JOIN TB_TIPO_SERVICO T ON(T.ID = U.ID_TIPO_SERVICO)
  INNER JOIN TB_TIPO_PROTECAO P ON(P.ID = T.ID_TIPO_PROTECAO)

  UNION ALL

  SELECT DISTINCT 
		C.ID
		,C.ID_PREFEITURA_BENEFICIO_EVENTUAL
		,L.ID AS ID_UNIDADE
		,4 AS ID_TIPO_UNIDADE
		,'CREAS' AS TIPO_UNIDADE
		,L.NOME AS UNIDADE
		,S.ID AS ID_SERVICOS_RECURSOS_FINANCEIROS
		,S.ID_USUARIO_TIPO_SERVICO
		,U.NOME AS USUARIO
		,U.ID_TIPO_SERVICO
		,(T.NOME + (CASE WHEN DESCRICAO_NAO_TIPIFICADO IS NULL THEN '' ELSE (' - ' + DESCRICAO_NAO_TIPIFICADO)END))  AS TIPO_SERVICO
		,T.ID_TIPO_PROTECAO
		,P.NOME AS PROTECAO_SOCIAL
		--,S.MEDIA_MENSAL_ATENDIMENTO_2017 AS NUMERO_ATENDIDOS
		,S2.MEDIA AS NUMERO_ATENDIDOS
		,S2.EXERCICIO
		,C.NUMERO_BENEFICIARIOS
	 
  FROM TB_PREFEITURA_BENEFICIO_EVENTUAL_SERVICOS C
  INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS S 
	ON(S.ID = C.ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS AND C.ID_PREFEITURA_BENEFICIO_EVENTUAL = @ID_PREFEITURA_BENEFICIO_EVENTUAL)

  INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_CAPACIDADE S1
		ON(S.ID = S1.ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS)
  INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS_MEDIA_MENSAL S2
		ON(S.ID = S2.ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS)


  INNER JOIN TB_CREAS L ON(L.ID = S.ID_CREAS)
  INNER JOIN TB_USUARIO_TIPO_SERVICO U ON (U.ID = S.ID_USUARIO_TIPO_SERVICO)
  INNER JOIN TB_TIPO_SERVICO T ON(T.ID = U.ID_TIPO_SERVICO)
  INNER JOIN TB_TIPO_PROTECAO P ON(P.ID = T.ID_TIPO_PROTECAO)

  UNION ALL

  SELECT
		DISTINCT  
		C.ID
		,C.ID_PREFEITURA_BENEFICIO_EVENTUAL
		,L.ID AS ID_UNIDADE
		,3 AS ID_TIPO_UNIDADE
		,'CRAS' AS TIPO_UNIDADE
		,L.NOME AS UNIDADE
		,S.ID AS ID_SERVICOS_RECURSOS_FINANCEIROS
		,S.ID_USUARIO_TIPO_SERVICO
		,U.NOME AS USUARIO
		,U.ID_TIPO_SERVICO
		,(T.NOME + (CASE WHEN DESCRICAO_NAO_TIPIFICADO IS NULL THEN '' ELSE (' - ' + DESCRICAO_NAO_TIPIFICADO)END))  AS TIPO_SERVICO
		,T.ID_TIPO_PROTECAO
		,P.NOME AS PROTECAO_SOCIAL
		--,S.MEDIA_MENSAL_ATENDIMENTO_2017 AS NUMERO_ATENDIDOS
		, S2.MEDIA AS NUMERO_ATENDIDOS
		,S2.EXERCICIO
		,C.NUMERO_BENEFICIARIOS
	 
  FROM TB_PREFEITURA_BENEFICIO_EVENTUAL_SERVICOS C
  INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS S 
	ON(S.ID = C.ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS AND C.ID_PREFEITURA_BENEFICIO_EVENTUAL = @ID_PREFEITURA_BENEFICIO_EVENTUAL)

  INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_CAPACIDADE S1
		ON(S.ID = S1.ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS)
  INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS_MEDIA_MENSAL S2
		ON(S.ID = S2.ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS)

  INNER JOIN TB_CRAS L ON(L.ID = S.ID_CRAS)
  INNER JOIN TB_USUARIO_TIPO_SERVICO U ON (U.ID = S.ID_USUARIO_TIPO_SERVICO)
  INNER JOIN TB_TIPO_SERVICO T ON(T.ID = U.ID_TIPO_SERVICO)
  INNER JOIN TB_TIPO_PROTECAO P ON(P.ID = T.ID_TIPO_PROTECAO)

  UNION ALL

  SELECT 
	DISTINCT 
		C.ID
		,C.ID_PREFEITURA_BENEFICIO_EVENTUAL
		,L.ID AS ID_UNIDADE
		,1 AS ID_TIPO_UNIDADE
		,'Unidade Pública' AS TIPO_UNIDADE
		,(L.RAZAO_SOCIAL + (CASE WHEN L.RAZAO_SOCIAL <> E.NOME THEN ' - ' + E.NOME ELSE '' END)) AS UNIDADE
		,S.ID AS ID_SERVICOS_RECURSOS_FINANCEIROS
		,S.ID_USUARIO_TIPO_SERVICO
		,U.NOME AS USUARIO
		,U.ID_TIPO_SERVICO
		,(T.NOME + (CASE WHEN DESCRICAO_NAO_TIPIFICADO IS NULL THEN '' ELSE (' - ' + DESCRICAO_NAO_TIPIFICADO)END))  AS TIPO_SERVICO
		,T.ID_TIPO_PROTECAO
		,P.NOME AS PROTECAO_SOCIAL
		--,S.MEDIA_MENSAL_ATENDIMENTO_2017 AS NUMERO_ATENDIDOS
		,S2.MEDIA AS NUMERO_ATENDIDOS
		,S2.EXERCICIO
		,C.NUMERO_BENEFICIARIOS
	 
  FROM TB_PREFEITURA_BENEFICIO_EVENTUAL_SERVICOS C
  INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO S 
	ON(S.ID = C.ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO AND C.ID_PREFEITURA_BENEFICIO_EVENTUAL = @ID_PREFEITURA_BENEFICIO_EVENTUAL)

  INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_CAPACIDADE S1
		ON(S.ID = S1.ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO)
  INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_MEDIA_MENSAL S2
		ON(S.ID = S2.ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO)

  INNER JOIN TB_LOCAL_EXECUCAO_PUBLICO E ON(E.ID = S.ID_LOCAL_EXECUCAO_PUBLICO)
  INNER JOIN TB_UNIDADE_PUBLICA L ON(L.ID = E.ID_UNIDADE_PUBLICA)
  INNER JOIN TB_USUARIO_TIPO_SERVICO U ON (U.ID = S.ID_USUARIO_TIPO_SERVICO)
  INNER JOIN TB_TIPO_SERVICO T ON(T.ID = U.ID_TIPO_SERVICO)
  INNER JOIN TB_TIPO_PROTECAO P ON(P.ID = T.ID_TIPO_PROTECAO)

  UNION ALL

  SELECT C.ID
		,C.ID_PREFEITURA_BENEFICIO_EVENTUAL
		,L.ID AS ID_UNIDADE
		,2 AS ID_TIPO_UNIDADE
		,'Unidade Privada' AS TIPO_UNIDADE
		,(L.RAZAO_SOCIAL + (CASE WHEN L.RAZAO_SOCIAL <> E.NOME THEN ' - ' + E.NOME ELSE '' END)) AS UNIDADE
		,S.ID AS ID_SERVICOS_RECURSOS_FINANCEIROS
		,S.ID_USUARIO_TIPO_SERVICO
		,U.NOME AS USUARIO
		,U.ID_TIPO_SERVICO
		,(T.NOME + (CASE WHEN DESCRICAO_NAO_TIPIFICADO IS NULL THEN '' ELSE (' - ' + DESCRICAO_NAO_TIPIFICADO)END))  AS TIPO_SERVICO
		,T.ID_TIPO_PROTECAO
		,P.NOME AS PROTECAO_SOCIAL
		,S2.MEDIA AS NUMERO_ATENDIDOS
		,S2.EXERCICIO
		,C.NUMERO_BENEFICIARIOS			 
  FROM TB_PREFEITURA_BENEFICIO_EVENTUAL_SERVICOS C
  INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO S 
	  ON(S.ID = C.ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO AND C.ID_PREFEITURA_BENEFICIO_EVENTUAL = @ID_PREFEITURA_BENEFICIO_EVENTUAL)


  INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_CAPACIDADE S1
		ON(S.ID = S1.ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO)
  INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_MEDIA_MENSAL S2
		ON(S.ID = S2.ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO)

  INNER JOIN TB_LOCAL_EXECUCAO_PRIVADO E ON(E.ID = S.ID_LOCAL_EXECUCAO_PRIVADO)
  INNER JOIN TB_UNIDADE_PRIVADA L ON(L.ID = E.ID_UNIDADE_PRIVADA)
  INNER JOIN TB_USUARIO_TIPO_SERVICO U ON (U.ID = S.ID_USUARIO_TIPO_SERVICO)
  INNER JOIN TB_TIPO_SERVICO T ON(T.ID = U.ID_TIPO_SERVICO)
  INNER JOIN TB_TIPO_PROTECAO P ON(P.ID = T.ID_TIPO_PROTECAO)  


GO


