USE [Dbpmas_quadrienal_DESENV]
GO

/****** Object:  View [dbo].[VW_INTEGRACAO_SERVICOS_TRANSFERENCIA_RENDA]    Script Date: 12/09/2019 15:23:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





ALTER VIEW [dbo].[VW_INTEGRACAO_SERVICOS_TRANSFERENCIA_RENDA]
AS
SELECT 
TRC.ID,
TR.ID_TIPO_TRANSFERENCIA_RENDA AS ID_TIPO_PROGRAMA,
TR.NOME AS NOME_PROGRAMA,
P.ID AS ID_PREFEITURA,
MUN.ID AS ID_MUNICIPIO,
MUN.ID_DRADS,
MUN.NOME AS MUNICIPIO,
DRA.NOME AS DRADS,
COALESCE(MUN.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
DRA.ID_MACRO_REGIAO,
P.ID_NIVEL_GESTAO,
(CASE WHEN P.POPULACAO <= 20000 THEN 1
	WHEN   P.POPULACAO <= 50000 THEN 2
	WHEN   P.POPULACAO <= 100000 THEN 3
	WHEN   P.POPULACAO <= 900000 THEN 4
	ELSE 5
END) AS ID_PORTE,
'Pública' AS TIPO_UNIDADE,
1 AS ID_TIPO_UNIDADE,
UN.ID AS CODIGO_UNIDADE,
UN.RAZAO_SOCIAL AS UNIDADE_RESPONSAVEL,
CAST(L.ID AS VARCHAR) AS ID_LOCAL,
L.NOME AS LOCAL_EXECUCAO,
U.NOME AS USUARIOS,
U.ID AS ID_USUARIO_TIPO_SERVICO,
S.NOME + (CASE WHEN R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL AND  R.DESCRICAO_NAO_TIPIFICADO <> '' THEN ' - ' + R.DESCRICAO_NAO_TIPIFICADO ELSE '' END)  AS TIPO_SERVICO,
S.ID AS ID_TIPO_SERVICO,
TP.NOME AS PROTECAO_SOCIAL,
TP.ID AS ID_TIPO_PROTECAO,
R.NUMERO_ATENDIDOS_MENSAL,
R.NUMERO_ATENDIDOS AS NUMERO_ATENDIDOS_ANUAL,
R.ID AS ID_SERVICOS_RECURSOS_FINANCEIROS,
isnull(TR.PETI_NUMERO_BENEFICIARIO_PETI_PURO_URBANO, 0) + isnull(TR.PETI_NUMERO_BENEFICIARIO_PETI_PURO_RURAL, 0) AS PETI,
TRC.NUMERO_USUARIOS AS NUMERO_ATENDIDOS_INTEGRACAO
FROM TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA TRC
LEFT JOIN TB_TRANSFERENCIA_RENDA TR ON(TR.ID = TRC.ID_TRANSFERENCIA_RENDA)
LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO R ON(R.ID = TRC.ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO)
LEFT JOIN TB_USUARIO_TIPO_SERVICO U ON (R.ID_USUARIO_TIPO_SERVICO = U.ID)
LEFT JOIN TB_TIPO_SERVICO S ON (U.ID_TIPO_SERVICO = S.ID)
LEFT JOIN TB_TIPO_PROTECAO TP ON(TP.ID = S.ID_TIPO_PROTECAO)
INNER JOIN TB_LOCAL_EXECUCAO_PUBLICO L ON(L.ID = R.ID_LOCAL_EXECUCAO_PUBLICO)
INNER JOIN TB_UNIDADE_PUBLICA UN ON(UN.ID = L.ID_UNIDADE_PUBLICA)
INNER JOIN TB_PREFEITURA P ON(P.ID = TR.ID_PREFEITURA)
JOIN DBSEDS.DBO.TB_MUNICIPIOS MUN (NOLOCK) ON P.ID_MUNICIPIO = MUN.ID
JOIN DBSEDS.DBO.TB_DRADS DRA (NOLOCK) ON MUN.ID_DRADS = DRA.ID

UNION ALL

SELECT 
TRC.ID,
TR.ID_TIPO_TRANSFERENCIA_RENDA AS ID_TIPO_PROGRAMA,
TR.NOME AS NOME_PROGRAMA,
P.ID AS ID_PREFEITURA,
MUN.ID AS ID_MUNICIPIO,
MUN.ID_DRADS,
MUN.NOME AS MUNICIPIO,
DRA.NOME AS DRADS,
COALESCE(MUN.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
DRA.ID_MACRO_REGIAO,
P.ID_NIVEL_GESTAO,
(CASE WHEN P.POPULACAO <= 20000 THEN 1
	WHEN   P.POPULACAO <= 50000 THEN 2
	WHEN   P.POPULACAO <= 100000 THEN 3
	WHEN   P.POPULACAO <= 900000 THEN 4
	ELSE 5
END) AS ID_PORTE,
'Privada' AS TIPO_UNIDADE,
2 AS ID_TIPO_UNIDADE,
UN.ID AS CODIGO_UNIDADE,
UN.RAZAO_SOCIAL AS UNIDADE_RESPONSAVEL,
CAST(L.ID AS VARCHAR) AS ID_LOCAL,
L.NOME AS LOCAL_EXECUCAO,
U.NOME AS USUARIOS,
U.ID AS ID_USUARIO_TIPO_SERVICO,
S.NOME + (CASE WHEN R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL AND  R.DESCRICAO_NAO_TIPIFICADO <> '' THEN ' - ' + R.DESCRICAO_NAO_TIPIFICADO ELSE '' END)  AS TIPO_SERVICO,
S.ID AS ID_TIPO_SERVICO,
TP.NOME AS PROTECAO_SOCIAL,
TP.ID AS ID_TIPO_PROTECAO,
R.NUMERO_ATENDIDOS_MENSAL,
R.NUMERO_ATENDIDOS AS NUMERO_ATENDIDOS_ANUAL,
R.ID AS ID_SERVICOS_RECURSOS_FINANCEIROS,
isnull(TR.PETI_NUMERO_BENEFICIARIO_PETI_PURO_URBANO, 0) + isnull(TR.PETI_NUMERO_BENEFICIARIO_PETI_PURO_RURAL, 0) AS PETI,
TRC.NUMERO_USUARIOS AS NUMERO_ATENDIDOS_INTEGRACAO
FROM TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA TRC
LEFT JOIN TB_TRANSFERENCIA_RENDA TR ON(TR.ID = TRC.ID_TRANSFERENCIA_RENDA)
LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO R ON(R.ID = TRC.ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO)
LEFT JOIN TB_USUARIO_TIPO_SERVICO U ON (R.ID_USUARIO_TIPO_SERVICO = U.ID)
LEFT JOIN TB_TIPO_SERVICO S ON (U.ID_TIPO_SERVICO = S.ID)
LEFT JOIN TB_TIPO_PROTECAO TP ON(TP.ID = S.ID_TIPO_PROTECAO)
INNER JOIN TB_LOCAL_EXECUCAO_PRIVADO L ON(L.ID = R.ID_LOCAL_EXECUCAO_PRIVADO)
INNER JOIN TB_UNIDADE_PRIVADA UN ON(UN.ID = L.ID_UNIDADE_PRIVADA)
INNER JOIN TB_PREFEITURA P ON(P.ID = TR.ID_PREFEITURA)
JOIN DBSEDS.DBO.TB_MUNICIPIOS MUN (NOLOCK) ON P.ID_MUNICIPIO = MUN.ID
JOIN DBSEDS.DBO.TB_DRADS DRA (NOLOCK) ON MUN.ID_DRADS = DRA.ID

UNION ALL

SELECT 
TRC.ID,
TR.ID_TIPO_TRANSFERENCIA_RENDA AS ID_TIPO_PROGRAMA,
TR.NOME AS NOME_PROGRAMA,
P.ID AS ID_PREFEITURA,
MUN.ID AS ID_MUNICIPIO,
MUN.ID_DRADS,
MUN.NOME AS MUNICIPIO,
DRA.NOME AS DRADS,
COALESCE(MUN.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
DRA.ID_MACRO_REGIAO,
P.ID_NIVEL_GESTAO,
(CASE WHEN P.POPULACAO <= 20000 THEN 1
	WHEN   P.POPULACAO <= 50000 THEN 2
	WHEN   P.POPULACAO <= 100000 THEN 3
	WHEN   P.POPULACAO <= 900000 THEN 4
	ELSE 5
END) AS ID_PORTE,
'Pública' AS TIPO_UNIDADE,
3 AS ID_TIPO_UNIDADE,
C.ID AS CODIGO_UNIDADE,
UN.RAZAO_SOCIAL AS UNIDADE_RESPONSAVEL,
C.IDCRAS AS ID_LOCAL,
C.NOME AS LOCAL_EXECUCAO,
U.NOME AS USUARIOS,
U.ID AS ID_USUARIO_TIPO_SERVICO,
S.NOME + (CASE WHEN R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL AND  R.DESCRICAO_NAO_TIPIFICADO <> '' THEN ' - ' + R.DESCRICAO_NAO_TIPIFICADO ELSE '' END)  AS TIPO_SERVICO,
S.ID AS ID_TIPO_SERVICO,
TP.NOME AS PROTECAO_SOCIAL,
TP.ID AS ID_TIPO_PROTECAO,
R.NUMERO_ATENDIDOS_MENSAL,
R.NUMERO_ATENDIDOS AS NUMERO_ATENDIDOS_ANUAL,
R.ID AS ID_SERVICOS_RECURSOS_FINANCEIROS,
isnull(TR.PETI_NUMERO_BENEFICIARIO_PETI_PURO_URBANO, 0) + isnull(TR.PETI_NUMERO_BENEFICIARIO_PETI_PURO_RURAL, 0) AS PETI,
TRC.NUMERO_USUARIOS AS NUMERO_ATENDIDOS_INTEGRACAO
FROM TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA TRC
LEFT JOIN TB_TRANSFERENCIA_RENDA TR ON(TR.ID = TRC.ID_TRANSFERENCIA_RENDA)
LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS R ON(R.ID = TRC.ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS)
LEFT JOIN TB_USUARIO_TIPO_SERVICO U ON (R.ID_USUARIO_TIPO_SERVICO = U.ID)
LEFT JOIN TB_TIPO_SERVICO S ON (U.ID_TIPO_SERVICO = S.ID)
LEFT JOIN TB_TIPO_PROTECAO TP ON(TP.ID = S.ID_TIPO_PROTECAO)
INNER JOIN TB_CRAS C ON(C.ID = R.ID_CRAS)
INNER JOIN TB_UNIDADE_PUBLICA UN ON (UN.ID = C.ID_UNIDADE_PUBLICA)
INNER JOIN TB_PREFEITURA P ON(P.ID = TR.ID_PREFEITURA)
JOIN DBSEDS.DBO.TB_MUNICIPIOS MUN (NOLOCK) ON P.ID_MUNICIPIO = MUN.ID
JOIN DBSEDS.DBO.TB_DRADS DRA (NOLOCK) ON MUN.ID_DRADS = DRA.ID

UNION ALL

SELECT 
TRC.ID,
TR.ID_TIPO_TRANSFERENCIA_RENDA AS ID_TIPO_PROGRAMA,
TR.NOME AS NOME_PROGRAMA,
P.ID AS ID_PREFEITURA,
MUN.ID AS ID_MUNICIPIO,
MUN.ID_DRADS,
MUN.NOME AS MUNICIPIO,
DRA.NOME AS DRADS,
COALESCE(MUN.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
DRA.ID_MACRO_REGIAO,
P.ID_NIVEL_GESTAO,
(CASE WHEN P.POPULACAO <= 20000 THEN 1
	WHEN   P.POPULACAO <= 50000 THEN 2
	WHEN   P.POPULACAO <= 100000 THEN 3
	WHEN   P.POPULACAO <= 900000 THEN 4
	ELSE 5
END) AS ID_PORTE,
'Pública' AS TIPO_UNIDADE,
4 AS ID_TIPO_UNIDADE,
C.ID AS CODIGO_UNIDADE,
UN.RAZAO_SOCIAL AS UNIDADE_RESPONSAVEL,
C.IDCREAS AS ID_LOCAL,
C.NOME AS LOCAL_EXECUCAO,
U.NOME AS USUARIOS,
U.ID AS ID_USUARIO_TIPO_SERVICO,
S.NOME + (CASE WHEN R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL AND  R.DESCRICAO_NAO_TIPIFICADO <> '' THEN ' - ' + R.DESCRICAO_NAO_TIPIFICADO ELSE '' END)  AS TIPO_SERVICO,
S.ID AS ID_TIPO_SERVICO,
TP.NOME AS PROTECAO_SOCIAL,
TP.ID AS ID_TIPO_PROTECAO,
R.NUMERO_ATENDIDOS_MENSAL,
R.NUMERO_ATENDIDOS AS NUMERO_ATENDIDOS_ANUAL,
R.ID AS ID_SERVICOS_RECURSOS_FINANCEIROS,
isnull(TR.PETI_NUMERO_BENEFICIARIO_PETI_PURO_URBANO, 0) + isnull(TR.PETI_NUMERO_BENEFICIARIO_PETI_PURO_RURAL, 0) AS PETI,
TRC.NUMERO_USUARIOS AS NUMERO_ATENDIDOS_INTEGRACAO
FROM TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA TRC
LEFT JOIN TB_TRANSFERENCIA_RENDA TR ON(TR.ID = TRC.ID_TRANSFERENCIA_RENDA)
LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS R ON(R.ID = TRC.ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS)
LEFT JOIN TB_USUARIO_TIPO_SERVICO U ON (R.ID_USUARIO_TIPO_SERVICO = U.ID)
LEFT JOIN TB_TIPO_SERVICO S ON (U.ID_TIPO_SERVICO = S.ID)
LEFT JOIN TB_TIPO_PROTECAO TP ON(TP.ID = S.ID_TIPO_PROTECAO)
INNER JOIN TB_CREAS C ON(C.ID = R.ID_CREAS)
INNER JOIN TB_UNIDADE_PUBLICA UN ON (UN.ID = C.ID_UNIDADE_PUBLICA)
INNER JOIN TB_PREFEITURA P ON(P.ID = TR.ID_PREFEITURA)
JOIN DBSEDS.DBO.TB_MUNICIPIOS MUN (NOLOCK) ON P.ID_MUNICIPIO = MUN.ID
JOIN DBSEDS.DBO.TB_DRADS DRA (NOLOCK) ON MUN.ID_DRADS = DRA.ID

UNION ALL

SELECT 
TRC.ID,
TR.ID_TIPO_TRANSFERENCIA_RENDA AS ID_TIPO_PROGRAMA,
TR.NOME AS NOME_PROGRAMA,
P.ID AS ID_PREFEITURA,
MUN.ID AS ID_MUNICIPIO,
MUN.ID_DRADS,
MUN.NOME AS MUNICIPIO,
DRA.NOME AS DRADS,
COALESCE(MUN.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
DRA.ID_MACRO_REGIAO,
P.ID_NIVEL_GESTAO,
(CASE WHEN P.POPULACAO <= 20000 THEN 1
	WHEN   P.POPULACAO <= 50000 THEN 2
	WHEN   P.POPULACAO <= 100000 THEN 3
	WHEN   P.POPULACAO <= 900000 THEN 4
	ELSE 5
END) AS ID_PORTE,
'Pública' AS TIPO_UNIDADE,
5 AS ID_TIPO_UNIDADE,
C.ID AS CODIGO_UNIDADE,
UN.RAZAO_SOCIAL AS UNIDADE_RESPONSAVEL,
C.IDCREAS AS ID_LOCAL,
C.NOME AS LOCAL_EXECUCAO,
U.NOME AS USUARIOS,
U.ID AS ID_USUARIO_TIPO_SERVICO,
S.NOME + (CASE WHEN R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL AND  R.DESCRICAO_NAO_TIPIFICADO <> '' THEN ' - ' + R.DESCRICAO_NAO_TIPIFICADO ELSE '' END)  AS TIPO_SERVICO,
S.ID AS ID_TIPO_SERVICO,
TP.NOME AS PROTECAO_SOCIAL,
TP.ID AS ID_TIPO_PROTECAO,
R.NUMERO_ATENDIDOS_MENSAL,
R.NUMERO_ATENDIDOS AS NUMERO_ATENDIDOS_ANUAL,
R.ID AS ID_SERVICOS_RECURSOS_FINANCEIROS,
isnull(TR.PETI_NUMERO_BENEFICIARIO_PETI_PURO_URBANO, 0) + isnull(TR.PETI_NUMERO_BENEFICIARIO_PETI_PURO_RURAL, 0) AS PETI,
TRC.NUMERO_USUARIOS AS NUMERO_ATENDIDOS_INTEGRACAO
FROM TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA TRC
LEFT JOIN TB_TRANSFERENCIA_RENDA TR ON(TR.ID = TRC.ID_TRANSFERENCIA_RENDA)
LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP R ON(R.ID = TRC.ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP)
LEFT JOIN TB_USUARIO_TIPO_SERVICO U ON (R.ID_USUARIO_TIPO_SERVICO = U.ID)
LEFT JOIN TB_TIPO_SERVICO S ON (U.ID_TIPO_SERVICO = S.ID)
LEFT JOIN TB_TIPO_PROTECAO TP ON(TP.ID = S.ID_TIPO_PROTECAO)
INNER JOIN TB_CENTRO_POP C ON(C.ID = R.ID_CENTRO_POP)
INNER JOIN TB_UNIDADE_PUBLICA UN ON (UN.ID = C.ID_UNIDADE_PUBLICA)
INNER JOIN TB_PREFEITURA P ON(P.ID = TR.ID_PREFEITURA)
JOIN DBSEDS.DBO.TB_MUNICIPIOS MUN (NOLOCK) ON P.ID_MUNICIPIO = MUN.ID
JOIN DBSEDS.DBO.TB_DRADS DRA (NOLOCK) ON MUN.ID_DRADS = DRA.ID


GO

