USE [Dbpmas_quadrienal_DESENV]
GO

/****** Object:  View [dbo].[VW_PROGRAMAS_TRANSFERENCIA_RENDA_MUNICIPAL]    Script Date: 12/09/2019 15:21:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[VW_PROGRAMAS_TRANSFERENCIA_RENDA_MUNICIPAL]
AS  
SELECT 
R.ID,
P.ID AS ID_PREFEITURA,
MUN.ID AS ID_MUNICIPIO,
MUN.ID_DRADS,
MUN.NOME AS MUNICIPIO,
DRA.NOME AS DRADS,
COALESCE(MUN.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
DRA.ID_MACRO_REGIAO,
P.ID_NIVEL_GESTAO,
(CASE WHEN P.POPULACAO <= 20000 THEN 1
	WHEN   P.POPULACAO <= 50000 THEN 2
	WHEN   P.POPULACAO <= 100000 THEN 3
	WHEN   P.POPULACAO <= 900000 THEN 4
	ELSE 5
END) AS ID_PORTE,
R.NOME AS NOME_PROGRAMA,
PUB.NOME AS BENEFICIARIOS,
isnull(R.MUNICIPAIS_NUMERO_BENEFICIARIOS, 0) AS NUMERO_BENEFICIARIOS,
(isnull(R.RENDA_MUNICIPAIS_REPASSE, 0.0) * 12) AS REPASSE,
(CASE WHEN R.POSSUI_PARCERIA_FORMAL > 0 THEN 'Sim' ELSE 'Não' END) AS POSSUI_PARCERIA,
(select count(*) from tb_transferencia_renda_parcerias p where p.id_transferencia_renda = r.id) AS TOTAL_PARCERIAS,
(CASE WHEN R.BENEFICIARIO_ATENDIDO_REDE_SOCIOASSISTENCIAL > 0 THEN 'Sim' ELSE 'Não' END) AS INTEGRACAO,
(select count(*) from TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA c where c.id_transferencia_renda = r.id) AS TOTAL_SERVICOS_ASSOCIADOS
FROM TB_TRANSFERENCIA_RENDA R
INNER JOIN TB_PREFEITURA P ON(P.ID = R.ID_PREFEITURA)
JOIN DBSEDS.DBO.TB_MUNICIPIOS MUN (NOLOCK)
ON P.ID_MUNICIPIO = MUN.ID
JOIN DBSEDS.DBO.TB_DRADS DRA (NOLOCK)
ON MUN.ID_DRADS = DRA.ID
INNER JOIN TB_USUARIO_TRANSFERENCIA_RENDA PUB ON(PUB.ID = R.ID_USUARIO_TRANSFERENCIA_RENDA)
WHERE R.ID_TIPO_TRANSFERENCIA_RENDA = 8

GO


