USE [Dbpmas_quadrienal_DESENV]
GO

/****** Object:  View [dbo].[VW_TRANSFERENCIA_RENDA]    Script Date: 11/09/2019 10:46:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





ALTER VIEW [dbo].[VW_TRANSFERENCIA_RENDA]
AS
SELECT	P.ID,
		P.ID_PREFEITURA,
		P.NOME,
		P.ID_TIPO_TRANSFERENCIA_RENDA,
		PVA.META_PACTUADA_2018,
		CASE
		WHEN P.ID_TIPO_TRANSFERENCIA_RENDA = 1 THEN CASE WHEN isnull(PVA.META_PACTUADA_2018, 0) > 0 THEN 1 ELSE 0 END
		WHEN P.ID_TIPO_TRANSFERENCIA_RENDA = 2 THEN CASE WHEN isnull(PVA.META_PACTUADA_2018, 0) > 0 THEN 1 ELSE 0 END
		WHEN P.ID_TIPO_TRANSFERENCIA_RENDA = 3 THEN CASE WHEN isnull(P.BOLSA_FAMILIA_ESTIMATIVA_FAMILIAS, 0) > 0 OR isnull(P.BOLSA_FAMILIA_NUMERO_FAMILIAS, 0) > 0 OR isnull(P.BOLSA_FAMILIA_REPASSE_MENSAL, 0.0) > 0.0 THEN 1 ELSE 0 END
		WHEN P.ID_TIPO_TRANSFERENCIA_RENDA = 4 THEN CASE
		WHEN  isnull(P.BENEFICIARIO_ATENDIDO_REDE_SOCIOASSISTENCIAL, 0) = 1 or isnull(P.PETI_BENEFICIARIO_TRANSFERENCIA_RENDA, 0) = 1 and ((isnull(P.PETI_NUMERO_BENEFICIARIO_BOLSA_FAMILIA, 0) + isnull(P.PETI_NUMERO_BENEFICIARIO_PETI_PURO_URBANO, 0) + isnull(P.PETI_NUMERO_BENEFICIARIO_PETI_PURO_RURAL, 0) + isnull(P.PETI_NUMERO_BENEFICIARIO_PROGRAMA_MUNICIPAL, 0)) > 0) THEN 1
		ELSE 0 END
		WHEN P.ID_TIPO_TRANSFERENCIA_RENDA = 5 THEN CASE WHEN isnull(P.ACAO_RENDA_META, 0) > 0 THEN 1 ELSE 0 END
		WHEN P.ID_TIPO_TRANSFERENCIA_RENDA = 6 THEN CASE WHEN isnull(P.ACAO_RENDA_META, 0) > 0 THEN 1 ELSE 0 END
		ELSE CASE WHEN isnull(P.MUNICIPAIS_NUMERO_BENEFICIARIOS, 0.0) > 0.0 OR isnull(P.RENDA_MUNICIPAIS_REPASSE, 0) > 0 THEN 1 ELSE 0 END
		END ADERIU,
		((SELECT COUNT(U.ID) FROM TB_CRAS U
		WHERE U.ID IN(SELECT A.ID_CRAS FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CRAS A 
				INNER JOIN TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA C ON(C.ID_SERVICOS_RECURSOS_FINANCEIROS_CRAS = A.ID AND C.ID_TRANSFERENCIA_RENDA = P.ID)			             
				))
		+
		(SELECT COUNT(U.ID) FROM TB_CREAS U
		WHERE U.ID IN(SELECT A.ID_CREAS FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CREAS A 
				INNER JOIN TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA C ON(C.ID_SERVICOS_RECURSOS_FINANCEIROS_CREAS = A.ID AND C.ID_TRANSFERENCIA_RENDA = P.ID)			             
				))
		+
		(SELECT COUNT(U.ID) FROM TB_CENTRO_POP U
		WHERE U.ID IN(SELECT A.ID_CENTRO_POP FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP A 
				INNER JOIN TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA C ON(C.ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP = A.ID AND C.ID_TRANSFERENCIA_RENDA = P.ID)			             
				))
		+
		(SELECT COUNT(U.ID) FROM TB_LOCAL_EXECUCAO_PUBLICO U
		WHERE U.ID IN(SELECT A.ID_LOCAL_EXECUCAO_PUBLICO FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO A 
				INNER JOIN TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA C ON(C.ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO = A.ID AND C.ID_TRANSFERENCIA_RENDA = P.ID)			             
				))
		+
		(SELECT COUNT(U.ID) FROM TB_LOCAL_EXECUCAO_PRIVADO U
		WHERE U.ID IN(SELECT A.ID_LOCAL_EXECUCAO_PRIVADO FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO A 
				INNER JOIN TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA C ON(C.ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO = A.ID AND C.ID_TRANSFERENCIA_RENDA = P.ID)			             
				))
		)AS TOTAL_UNIDADES		
		,COUNT(C.ID) AS TOTAL_SERVICOS
		,COALESCE((COALESCE(CAST(937 * 12 * CAST(PVA.META_PACTUADA_2018 AS BIGINT) AS BIGINT),0)
		+ COALESCE((P.BOLSA_FAMILIA_REPASSE_MENSAL * 12 ),0)		
		--+ COALESCE((P.PETI_PREVISAO_MENSAL * 12 ),0)
	    + COALESCE((P.PETI_NUMERO_BENEFICIARIO_PETI_PURO_URBANO * 40 * 12) + (P.PETI_NUMERO_BENEFICIARIO_PETI_PURO_RURAL * 70 * 12),0)
		+ COALESCE((P.ACAO_RENDA_META * 80 * 12),0)
		+ COALESCE((P.RENDA_MUNICIPAIS_REPASSE * 12),0)
		+ COALESCE((P.SP_SOLIDARIO_REPASSE_ANUAL),0)
		),0) AS PREVISAO_ANUAL_REPASSE
		,COALESCE(P.BENEFICIARIO_ATENDIDO_REDE_SOCIOASSISTENCIAL,0) AS INTEGRACAO_REDE
		,case
		when P.ID_TIPO_TRANSFERENCIA_RENDA = 1 then isnull(PVA.META_PACTUADA_2018, 0)
		when P.ID_TIPO_TRANSFERENCIA_RENDA = 2 then isnull(PVA.META_PACTUADA_2018, 0)
	   when P.ID_TIPO_TRANSFERENCIA_RENDA = 4 then isnull((isnull(P.PETI_NUMERO_BENEFICIARIO_BOLSA_FAMILIA, 0) + isnull(P.PETI_NUMERO_BENEFICIARIO_PETI_PURO_URBANO, 0) + isnull(P.PETI_NUMERO_BENEFICIARIO_PETI_PURO_RURAL, 0) + isnull(P.PETI_NUMERO_BENEFICIARIO_PROGRAMA_MUNICIPAL, 0)) , 0)
		else 0
		end NUMERO_BENEFICIARIOS
	FROM TB_TRANSFERENCIA_RENDA P
	LEFT JOIN TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA C ON(C.ID_TRANSFERENCIA_RENDA = P.ID)	
	LEFT JOIN TB_TRANSFERENCIA_RENDAXPREVISAO_ANUAL PVA ON (PVA.ID_TRANSFERENCIA_RENDA = P.ID)
	GROUP BY P.ID, P.ID_TIPO_TRANSFERENCIA_RENDA,P.NOME,P.ID_PREFEITURA,BPC_NUMERO_BENEFICIARIOS,
	BOLSA_FAMILIA_REPASSE_MENSAL,PETI_PREVISAO_MENSAL,ACAO_RENDA_META,
	RENDA_MUNICIPAIS_REPASSE,BOLSA_FAMILIA_ESTIMATIVA_FAMILIAS, BOLSA_FAMILIA_NUMERO_FAMILIAS, 
	PETI_NUMERO_BENEFICIARIOS, MUNICIPAIS_NUMERO_BENEFICIARIOS, BENEFICIARIO_ATENDIDO_REDE_SOCIOASSISTENCIAL, ID_FASE_PROGRAMA_TRANSFERENCIA_RENDA_SP_SOLIDARIO, SP_SOLIDARIO_REPASSE_ANUAL,
	PETI_BENEFICIARIO_TRANSFERENCIA_RENDA, PETI_NUMERO_BENEFICIARIO_BOLSA_FAMILIA, PETI_NUMERO_BENEFICIARIO_PETI_PURO_URBANO, PETI_NUMERO_BENEFICIARIO_PETI_PURO_RURAL,
	PETI_NUMERO_BENEFICIARIO_PROGRAMA_MUNICIPAL, META_PACTUADA_2018



GO


