USE [Dbpmas_quadrienal_HOMOLOG]
GO

/****** Object:  View [dbo].[VW_PROGRAMA_PROJETO_GERAL]    Script Date: 12/09/2019 15:38:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO







ALTER VIEW [dbo].[VW_PROGRAMA_PROJETO_GERAL]
AS  
SELECT 
R.ID,
P.ID AS ID_PREFEITURA,
MUN.ID AS ID_MUNICIPIO,
MUN.ID_DRADS,
MUN.NOME AS MUNICIPIO,
DRA.NOME AS DRADS,
COALESCE(MUN.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
DRA.ID_MACRO_REGIAO,
P.ID_NIVEL_GESTAO,
(CASE WHEN P.POPULACAO <= 20000 THEN 1
	WHEN   P.POPULACAO <= 50000 THEN 2
	WHEN   P.POPULACAO <= 100000 THEN 3
	WHEN   P.POPULACAO <= 900000 THEN 4
	ELSE 5
END) AS ID_PORTE,
R.NOME,
ISNULL(U.NOME, '') AS BENEFICIARIOS,
CASE
		WHEN R.NOME like '%acessuas%' and isnull(R.VALOR_PREVISAO_ANUAL_ACESSUAS, 0.0) > 0.0 then 1
		WHEN R.NOME like '%solidário%' and (isnull(R.SP_SOLIDARIO_BUSCA_ATIVA_MES_INICIO, 0) > 0 or isnull(R.SP_SOLIDARIO_BUSCA_ATIVA_MES_TERMINO, 0) > 0 or isnull(R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_INICIO, 0) > 0 or isnull(R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO, 0) > 0) then 1
		WHEN R.NOME like '%amigo do idoso%' and (isnull(R.META_PACTUADA, 0.0) > 0.0 or isnull(R1.VALOR_DIA_IDOSO, 0.0) > 0.0 or isnull(R1.VALOR_CONVIVENCIA_IDOSO, 0.0) > 0.0) then 1
		WHEN R.NOME like '%vivaleite%' and R.EXECUTA_ACAO_VIVALEITE = 1 then 1 
		WHEN R.NOME like '%bom prato%' and (isnull(R.NUMERO_REFEICOES_BOM_PRATO, 0.0) > 0.0 or isnull(R.NUMERO_BENEFICIARIOS_MENSAL, 0.0) > 0.0) then 1
		WHEN R.NOME like '%família paulista%' and R.ADERIU_FAMILIA_PAULISTA = 1 then 1
		ELSE 0
		END ADERIU_BENEFICIO,
CASE WHEN R.NOME = 'Bom Prato' AND R.PROGRAMA_ESTADUAL = 1  THEN ISNULL(R.NUMERO_BENEFICIARIOS_MENSAL,0) + ISNULL(R.NUMERO_REFEICOES_BOM_PRATO, 0)
	 WHEN R.NOME = 'Vivaleite' AND R.PROGRAMA_ESTADUAL = 1 THEN ISNULL(R.NUMERO_BENEFICIARIOS_MENSAL,0)
     WHEN  R.NOME LIKE '%São Paulo Solidário%' AND R.PROGRAMA_ESTADUAL = 1 THEN ISNULL(SP_SOLIDARIO_AGENDA_FAMILIA_NUMERO_FAMILIAS_2012, 0.0) + ISNULL(SP_SOLIDARIO_AGENDA_FAMILIA_NUMERO_FAMILIAS, 0.0) + ISNULL(SP_SOLIDARIO_AGENDA_FAMILIA_NUMERO_FAMILIAS_2014, 0.0) + ISNULL(SP_SOLIDARIO_AGENDA_FAMILIA_NUMERO_FAMILIAS_2015, 0.0) + ISNULL(SP_SOLIDARIO_AGENDA_FAMILIA_NUMERO_FAMILIAS_2016, 0.0)
 ELSE isnull(R.META_PACTUADA, 0) 
 END
 AS META_PACTUADA,
(CASE WHEN R.PROGRAMA_FEDERAL = 1 then 'Nacional' when R.PROGRAMA_ESTADUAL = 1 then 'Estadual' When R.PROGRAMA_MUNICIPAL = 1 then 'Municipal' else '' end) NIVEL_ABRANGENCIA,
(CASE WHEN MES_INICIO is null or ANO_INICIO is null then '' else cast(MES_INICIO as varchar) + '/' + cast(ANO_INICIO as varchar) end) DATA_INICIO,
(select count(PPC.ID) from TB_PROGRAMA_PROJETO_COFINANCIAMENTO PPC where PPC.ID_PROGRAMA_PROJETO = R.ID) TOTAL_SERVICOS_ASSOCIADOS,
(CASE WHEN R.POSSUI_PARCERIA_FORMAL = 1 then 'Sim' else 'Não' end) POSSUI_PARCERIA_FORMAL,
(select count(PPP.ID) from TB_PROGRAMA_PROJETO_PARCERIAS PPP where PPP.ID_PROGRAMA_PROJETO = R.ID) QUANTIDADE_PARCERIAS,
(CASE WHEN R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%São Paulo Solidário%' AND R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO = 2016 AND (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 OR (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 AND R.SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014 = 1)) then isnull(SP_SOLIDARIO_BUSCA_ATIVA_VALOR_FMAS, 0.0) + isnull(SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_FMAS, 0.0) else isnull(R2.VALOR_FMAS, 0.0) end) VALOR_FMAS,
(CASE WHEN R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%São Paulo Solidário%' AND R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO = 2016 AND (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 OR (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 AND R.SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014 = 1)) then isnull(SP_SOLIDARIO_BUSCA_ATIVA_VALOR_ORCAMENTO_MUNICIPAL, 0.0) + isnull(SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_ORCAMENTO_MUNICIPAL, 0.0) else isnull(R2.VALOR_ORCAMENTO_MUNICIPAL, 0.0) end) VALOR_ORCAMENTO_MUNICIPAL,
(CASE WHEN R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%São Paulo Solidário%' AND R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO = 2016 AND (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 OR (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 AND R.SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014 = 1)) then isnull(SP_SOLIDARIO_BUSCA_ATIVA_VALOR_FUNDO_MUNICIPAL, 0.0) + isnull(SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_FUNDO_MUNICIPAL, 0.0) else isnull(R2.VALOR_FUNDO_MUNICIPAL, 0.0) end) VALOR_FUNDO_MUNICIPAL,
(CASE WHEN R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%São Paulo Solidário%' AND R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO = 2016 AND (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 OR (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 AND R.SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014 = 1)) then isnull(SP_SOLIDARIO_BUSCA_ATIVA_VALOR_FEAS, 0.0) + isnull(SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_FEAS, 0.0) 
	 when R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%Família Paulista%' THEN isnull(R2.VALOR_FEAS, 0.0) + isnull(R.VALOR_FEAS_SEGUNDA, 0.0) 
	else isnull(R2.VALOR_FEAS, 0.0) end) VALOR_FEAS,
(CASE WHEN R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%São Paulo Solidário%' AND R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO = 2016 AND (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 OR (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 AND R.SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014 = 1)) then isnull(SP_SOLIDARIO_BUSCA_ATIVA_VALOR_ORCAMENTO_ESTADUAL, 0.0) + isnull(SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_ORCAMENTO_ESTADUAL, 0.0) else isnull(VALOR_ORCAMENTO_ESTADUAL, 0.0) end) VALOR_ORCAMENTO_ESTADUAL,
(CASE WHEN R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%São Paulo Solidário%' AND R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO = 2016 AND (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 OR (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 AND R.SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014 = 1)) then isnull(SP_SOLIDARIO_BUSCA_ATIVA_VALOR_FUNDO_ESTADUAL, 0.0) + isnull(SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_FUNDO_ESTADUAL, 0.0) else isnull(VALOR_FUNDO_ESTADUAL, 0.0) end) VALOR_FUNDO_ESTADUAL,
(CASE WHEN R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%São Paulo Solidário%' AND R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO = 2016 AND (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 OR (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 AND R.SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014 = 1)) then isnull(SP_SOLIDARIO_BUSCA_ATIVA_VALOR_FNAS, 0.0) + isnull(SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_FNAS, 0.0) else isnull(VALOR_FNAS, 0.0) end) VALOR_FNAS,
(CASE WHEN R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%São Paulo Solidário%' AND R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO = 2016 AND (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 OR (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 AND R.SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014 = 1)) then isnull(SP_SOLIDARIO_BUSCA_ATIVA_VALOR_ORCAMENTO_FEDERAL, 0.0) + isnull(SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_ORCAMENTO_FEDERAL, 0.0) else isnull(VALOR_ORCAMENTO_FEDERAL, 0.0) end) VALOR_ORCAMENTO_FEDERAL,
(CASE WHEN R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%São Paulo Solidário%' AND R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO = 2016 AND (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 OR (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 AND R.SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014 = 1)) then isnull(SP_SOLIDARIO_BUSCA_ATIVA_VALOR_FUNDO_FEDERAL, 0.0) + isnull(SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_FUNDO_FEDERAL, 0.0) else isnull(VALOR_FUNDO_FEDERAL, 0.0) end) VALOR_FUNDO_FEDERAL,
(CASE WHEN R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%São Paulo Solidário%' AND R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO = 2016 AND (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 OR (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 AND R.SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014 = 1)) then isnull(SP_SOLIDARIO_BUSCA_ATIVA_VALOR_IGD_PBF, 0.0) + isnull(SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_IGD_PBF, 0.0) else isnull(VALOR_IGD_PBF, 0.0) end) VALOR_IGD_PBF,
(CASE WHEN R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%São Paulo Solidário%' AND R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO = 2016 AND (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 OR (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 AND R.SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014 = 1)) then isnull(SP_SOLIDARIO_BUSCA_ATIVA_VALOR_IGD_SUAS, 0.0) + isnull(SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_IGD_SUAS, 0.0) else isnull(VALOR_IGD_SUAS, 0.0) end) VALOR_IGD_SUAS,
(
(CASE WHEN R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%São Paulo Solidário%' AND R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO = 2016 AND (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 OR (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 AND R.SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014 = 1)) then isnull(SP_SOLIDARIO_BUSCA_ATIVA_VALOR_FMAS, 0.0) + isnull(SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_FMAS, 0.0) else isnull(VALOR_FMAS, 0.0) end) +
(CASE WHEN R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%São Paulo Solidário%' AND R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO = 2016 AND (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 OR (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 AND R.SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014 = 1)) then isnull(SP_SOLIDARIO_BUSCA_ATIVA_VALOR_ORCAMENTO_MUNICIPAL, 0.0) + isnull(SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_ORCAMENTO_MUNICIPAL, 0.0) else isnull(VALOR_ORCAMENTO_MUNICIPAL, 0.0) end) +
(CASE WHEN R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%São Paulo Solidário%' AND R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO = 2016 AND (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 OR (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 AND R.SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014 = 1)) then isnull(SP_SOLIDARIO_BUSCA_ATIVA_VALOR_FUNDO_MUNICIPAL, 0.0) + isnull(SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_FUNDO_MUNICIPAL, 0.0) else isnull(VALOR_FUNDO_MUNICIPAL, 0.0) end) +
(CASE WHEN R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%São Paulo Solidário%' AND R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO = 2016 AND (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 OR (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 AND R.SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014 = 1)) then isnull(SP_SOLIDARIO_BUSCA_ATIVA_VALOR_FEAS, 0.0) + isnull(SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_FEAS, 0.0) else isnull(VALOR_FEAS, 0.0) end) +
(CASE WHEN R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%São Paulo Solidário%' AND R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO = 2016 AND (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 OR (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 AND R.SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014 = 1)) then isnull(SP_SOLIDARIO_BUSCA_ATIVA_VALOR_ORCAMENTO_ESTADUAL, 0.0) + isnull(SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_ORCAMENTO_ESTADUAL, 0.0) else isnull(VALOR_ORCAMENTO_ESTADUAL, 0.0) end) +
(CASE WHEN R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%São Paulo Solidário%' AND R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO = 2016 AND (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 OR (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 AND R.SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014 = 1)) then isnull(SP_SOLIDARIO_BUSCA_ATIVA_VALOR_FUNDO_ESTADUAL, 0.0) + isnull(SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_FUNDO_ESTADUAL, 0.0) else isnull(VALOR_FUNDO_ESTADUAL, 0.0) end) +
(CASE WHEN R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%São Paulo Solidário%' AND R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO = 2016 AND (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 OR (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 AND R.SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014 = 1)) then isnull(SP_SOLIDARIO_BUSCA_ATIVA_VALOR_FNAS, 0.0) + isnull(SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_FNAS, 0.0) else isnull(VALOR_FNAS, 0.0) end) +
(CASE WHEN R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%São Paulo Solidário%' AND R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO = 2016 AND (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 OR (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 AND R.SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014 = 1)) then isnull(SP_SOLIDARIO_BUSCA_ATIVA_VALOR_ORCAMENTO_FEDERAL, 0.0) + isnull(SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_ORCAMENTO_FEDERAL, 0.0) else isnull(VALOR_ORCAMENTO_FEDERAL, 0.0) end) +
(CASE WHEN R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%São Paulo Solidário%' AND R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO = 2016 AND (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 OR (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 AND R.SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014 = 1)) then isnull(SP_SOLIDARIO_BUSCA_ATIVA_VALOR_FUNDO_FEDERAL, 0.0) + isnull(SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_FUNDO_FEDERAL, 0.0) else isnull(VALOR_FUNDO_FEDERAL, 0.0) end) +
(CASE WHEN R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%São Paulo Solidário%' AND R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO = 2016 AND (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 OR (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 AND R.SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014 = 1)) then isnull(SP_SOLIDARIO_BUSCA_ATIVA_VALOR_IGD_PBF, 0.0) + isnull(SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_IGD_PBF, 0.0) else isnull(VALOR_IGD_PBF, 0.0) end) +
(CASE WHEN R.PROGRAMA_ESTADUAL = 1 and R.NOME like '%São Paulo Solidário%' AND R.SP_SOLIDARIO_BUSCA_ATIVA_ANO_TERMINO = 2016 AND (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 OR (R.SP_SOLIDARIO_ANO_REPASSE_FEAS_BUSCA_ATIVA = 2016 AND R.SP_SOLIDARIO_VALOR_FEAS_RETIDO_FMAS_2014 = 1)) then isnull(SP_SOLIDARIO_BUSCA_ATIVA_VALOR_IGD_SUAS, 0.0) + isnull(SP_SOLIDARIO_AGENDA_FAMILIA_VALOR_IGD_SUAS, 0.0) else isnull(VALOR_IGD_SUAS, 0.0) end)
) TOTAL_RECURSOS,
R.ATIVO
FROM TB_PROGRAMA_PROJETO R
INNER JOIN TB_PREFEITURA P ON(P.ID = R.ID_PREFEITURA)
inner join TB_PROGRAMA_PROJETO_PARCELAS R1 ON(R.ID = R1.ID_PROGRAMA_PROJETO)
inner join TB_PROGRAMA_PROJETO_RECURSOS_FINANCEIROS R2 ON(R.ID = R2.ID_PROGRAMA_PROJETO)
LEFT JOIN TB_USUARIO_TRANSFERENCIA_RENDA U ON (U.ID = R.ID_USUARIO_TRANSFERENCIA_RENDA)
INNER JOIN DBSEDS.DBO.TB_MUNICIPIOS MUN (NOLOCK) ON (MUN.ID =  P.ID_MUNICIPIO)
JOIN DBSEDS.DBO.TB_DRADS DRA (NOLOCK)
ON MUN.ID_DRADS = DRA.ID
where R.PROGRAMA_MUNICIPAL = 1 or ((R.PROGRAMA_ESTADUAL = 1 OR R.PROGRAMA_FEDERAL = 1)) 
UNION ALL
SELECT	R.ID,
		P.ID AS ID_PREFEITURA,
		MUN.ID AS ID_MUNICIPIO,
		MUN.ID_DRADS,
		MUN.NOME AS MUNICIPIO,
		DRA.NOME AS DRADS,
		COALESCE(MUN.ID_REGIAO_METROPOLITANA, -1) AS ID_REGIAO_METROPOLITANA,
		DRA.ID_MACRO_REGIAO,
		P.ID_NIVEL_GESTAO,
(CASE WHEN P.POPULACAO <= 20000 THEN 1
	WHEN   P.POPULACAO <= 50000 THEN 2
	WHEN   P.POPULACAO <= 100000 THEN 3
	WHEN   P.POPULACAO <= 900000 THEN 4
	ELSE 5
END) AS ID_PORTE,
		CASE WHEN R.NOME like '%Beneficio de Prestação Continuada - BPC Pessoas com Deficiência%' then 'BPC na escola' 
		ELSE R.NOME END AS NOME,
		ISNULL(U.NOME, '') AS BENEFICIARIOS,
		CASE
		WHEN R.ID_TIPO_TRANSFERENCIA_RENDA = 1 THEN CASE WHEN isnull(R.BPC_NUMERO_BENEFICIARIOS, 0) > 0 THEN 1 ELSE 0 END
		--WHEN P.ID_TIPO_TRANSFERENCIA_RENDA = 2 THEN CASE WHEN isnull(R.BPC_NUMERO_BENEFICIARIOS, 0) > 0
		WHEN R.ID_TIPO_TRANSFERENCIA_RENDA = 2 THEN CASE WHEN ISNULL(R.NUMERO_BENEFICIARIOS_BPC_NA_ESCOLA, 0) > 0 and ISNULL(R.ADERIU_BPC_NA_ESCOLA, 0) > 0 THEN 1 ELSE 0 END
		WHEN R.ID_TIPO_TRANSFERENCIA_RENDA = 3 THEN CASE WHEN isnull(R.BOLSA_FAMILIA_ESTIMATIVA_FAMILIAS, 0) > 0 OR isnull(R.BOLSA_FAMILIA_NUMERO_FAMILIAS, 0) > 0 OR isnull(R.BOLSA_FAMILIA_REPASSE_MENSAL, 0.0) > 0.0 THEN 1 ELSE 0 END
		WHEN R.ID_TIPO_TRANSFERENCIA_RENDA = 4 THEN CASE
		WHEN  isnull(R.BENEFICIARIO_ATENDIDO_REDE_SOCIOASSISTENCIAL, 0) = 1 or isnull(R.PETI_BENEFICIARIO_TRANSFERENCIA_RENDA, 0) = 1 and ((isnull(R.PETI_NUMERO_BENEFICIARIO_BOLSA_FAMILIA, 0) + isnull(R.PETI_NUMERO_BENEFICIARIO_PETI_PURO_URBANO, 0) + isnull(R.PETI_NUMERO_BENEFICIARIO_PETI_PURO_RURAL, 0) + isnull(R.PETI_NUMERO_BENEFICIARIO_PROGRAMA_MUNICIPAL, 0)) > 0) THEN CAST(1 AS BIT)
		ELSE 0 END
		WHEN R.ID_TIPO_TRANSFERENCIA_RENDA = 5 THEN CASE WHEN isnull(R.ACAO_RENDA_META, 0) > 0 THEN 1 ELSE 0 END
		WHEN R.ID_TIPO_TRANSFERENCIA_RENDA = 6 THEN CASE WHEN isnull(R.ACAO_RENDA_META, 0) > 0 THEN 1 ELSE 0 END
		ELSE CASE WHEN isnull(R.MUNICIPAIS_NUMERO_BENEFICIARIOS, 0.0) > 0.0 OR isnull(R.RENDA_MUNICIPAIS_REPASSE, 0) > 0 THEN 1 ELSE 0 END
		END ADERIU_BENEFICIO,
		CASE 
		WHEN (R.ID_TIPO_TRANSFERENCIA_RENDA = 3) THEN COALESCE(R.BOLSA_FAMILIA_NUMERO_FAMILIAS ,0)
		WHEN (R.ID_TIPO_TRANSFERENCIA_RENDA = 4) THEN (isnull(R.PETI_NUMERO_BENEFICIARIO_BOLSA_FAMILIA, 0) + isnull(R.PETI_NUMERO_BENEFICIARIO_PETI_PURO_URBANO, 0) + isnull(R.PETI_NUMERO_BENEFICIARIO_PETI_PURO_RURAL, 0) + isnull(R.PETI_BENEFICIARIO_TRANSFERENCIA_RENDA, 0))
		WHEN (R.ID_TIPO_TRANSFERENCIA_RENDA = 5) THEN isnull(R.ACAO_RENDA_META, 0)
		WHEN (R.ID_TIPO_TRANSFERENCIA_RENDA = 6) THEN isnull(R.ACAO_RENDA_META, 0)
		WHEN (R.ID_TIPO_TRANSFERENCIA_RENDA = 8) THEN isnull(R.MUNICIPAIS_NUMERO_BENEFICIARIOS, 0)
		ELSE
		0 END AS  META_PACTUADA,
		CASE 
		WHEN (R.ID_TIPO_TRANSFERENCIA_RENDA = 8) THEN 'Municipal' 
		WHEN R.ID_TIPO_TRANSFERENCIA_RENDA = 5 OR R.ID_TIPO_TRANSFERENCIA_RENDA = 6 OR R.ID_TIPO_TRANSFERENCIA_RENDA = 9 THEN 'Estadual'
		WHEN R.ID_TIPO_TRANSFERENCIA_RENDA = 2 OR R.ID_TIPO_TRANSFERENCIA_RENDA = 3 OR R.ID_TIPO_TRANSFERENCIA_RENDA = 4 THEN 'Nacional' 
		ELSE NULL END
		AS NIVEL_ABRANGENCIA,
		'' AS DATA_INICIO,
		(select count(PPC.ID) from TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA PPC where PPC.ID_TRANSFERENCIA_RENDA = R.ID) TOTAL_SERVICOS_ASSOCIADOS,
		'Não' As POSSUI_PARCERIA_FORMAL,
		(select count(PPP.ID) from TB_TRANSFERENCIA_RENDA_PARCERIAS PPP where PPP.ID_TRANSFERENCIA_RENDA = R.ID) QUANTIDADE_PARCERIAS,
		 CASE WHEN (R.ID_TIPO_TRANSFERENCIA_RENDA = 8) THEN COALESCE(ISNULL(R.RENDA_MUNICIPAIS_REPASSE * 12, 0),0)
		 WHEN (R.ID_TIPO_TRANSFERENCIA_RENDA = 4) THEN ISNULL(R.VALOR_FMAS, 0.0)
		 ELSE '0.00' END AS VALOR_FMAS,
		 CASE WHEN (R.ID_TIPO_TRANSFERENCIA_RENDA = 4) THEN isnull(R.VALOR_ORCAMENTO_MUNICIPAL, 0.0) ELSE '0.00' END AS VALOR_ORCAMENTO_MUNICIPAL,
		 CASE WHEN (R.ID_TIPO_TRANSFERENCIA_RENDA = 4) THEN isnull(R.VALOR_FUNDO_MUNICIPAL, 0.0) ELSE '0.00' END AS VALOR_FUNDO_MUNICIPAL ,
		 CASE WHEN (R.ID_TIPO_TRANSFERENCIA_RENDA = 4) THEN isnull(R.VALOR_FEAS, 0.0) 
			  WHEN (R.ID_TIPO_TRANSFERENCIA_RENDA = 5) THEN COALESCE((R.ACAO_RENDA_META * 80 * 12),0) 
			  WHEN (R.ID_TIPO_TRANSFERENCIA_RENDA = 6) THEN COALESCE((R.ACAO_RENDA_META * 80 * 12), 0)
		 ELSE '0.00' END AS VALOR_FEAS,
		 CASE WHEN (R.ID_TIPO_TRANSFERENCIA_RENDA = 4) THEN  isnull(R.VALOR_ORCAMENTO_ESTADUAL, 0.0) ELSE '0.00' END AS VALOR_ORCAMENTO_ESTADUAL,
		 CASE WHEN (R.ID_TIPO_TRANSFERENCIA_RENDA = 4) THEN isnull(R.VALOR_FUNDO_ESTADUAL, 0.0) ELSE '0.00'END AS VALOR_FUNDO_ESTADUAL,
		 CASE WHEN (R.ID_TIPO_TRANSFERENCIA_RENDA = 4) THEN isnull(R.VALOR_FNAS, 0.0) ELSE '0.00' END AS VALOR_FNAS,
		 CASE WHEN (R.ID_TIPO_TRANSFERENCIA_RENDA = 4) THEN isnull(R.VALOR_ORCAMENTO_FEDERAL, 0.0) ELSE '0.00' END AS VALOR_ORCAMENTO_FEDERAL,
		 CASE WHEN (R.ID_TIPO_TRANSFERENCIA_RENDA = 4) THEN isnull(R.VALOR_FUNDO_FEDERAL, 0.0) ELSE '0.00' END AS VALOR_FUNDO_FEDERAL,
		 CASE WHEN (R.ID_TIPO_TRANSFERENCIA_RENDA = 4) THEN isnull(R.VALOR_IGD_PBF, 0.0) ELSE '0.00' END AS VALOR_IGD_PBF,
		 CASE WHEN (R.ID_TIPO_TRANSFERENCIA_RENDA = 4) THEN isnull(R.VALOR_IGD_SUAS, 0.0) ELSE '0.00' END AS VALOR_IGD_SUAS,
		 isnull(R.VALOR_FMAS, 0.0) +
		 isnull(R.VALOR_ORCAMENTO_MUNICIPAL, 0.0) +
		 isnull(R.VALOR_FUNDO_MUNICIPAL, 0.0) +
		 isnull(R.VALOR_FEAS, 0.0) +
		 isnull(R.VALOR_ORCAMENTO_ESTADUAL, 0.0) +
		 isnull(R.VALOR_FUNDO_ESTADUAL, 0.0) +
		 isnull(R.VALOR_FNAS, 0.0) +
		 isnull(R.VALOR_ORCAMENTO_FEDERAL, 0.0) +
		 isnull(R.VALOR_FNAS, 0.0) +
		 isnull(R.VALOR_IGD_PBF, 0.0) +
		 isnull(R.VALOR_IGD_SUAS, 0.0)+
		 COALESCE(ISNULL(R.RENDA_MUNICIPAIS_REPASSE * 12, 0),0)+
		 COALESCE((R.ACAO_RENDA_META * 80 * 12),0)  AS TOTAL_RECURSOS,
		 R.ATIVO
	FROM TB_TRANSFERENCIA_RENDA R
	LEFT JOIN TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA C ON(C.ID_TRANSFERENCIA_RENDA = R.ID)	
	LEFT JOIN TB_USUARIO_TRANSFERENCIA_RENDA U ON (U.ID = R.ID_USUARIO_TRANSFERENCIA_RENDA)
	INNER JOIN TB_PREFEITURA P ON (P.ID = R.ID_PREFEITURA)
	JOIN DBSEDS.DBO.TB_MUNICIPIOS MUN (NOLOCK)
	ON P.ID_MUNICIPIO = MUN.ID
	JOIN DBSEDS.DBO.TB_DRADS DRA (NOLOCK)
	ON MUN.ID_DRADS = DRA.ID
	where R.ID_TIPO_TRANSFERENCIA_RENDA <> 9 and R.ID_TIPO_TRANSFERENCIA_RENDA <> 1
	GROUP BY R.ID, P.ID,  R.ID_TIPO_TRANSFERENCIA_RENDA,R.NOME, MUN.ID, MUN.ID_DRADS, MUN.NOME, DRA.NOME, MUN.ID_REGIAO_METROPOLITANA, DRA.ID_MACRO_REGIAO, P.ID_NIVEL_GESTAO, P.POPULACAO,
	 U.NOME, BPC_NUMERO_BENEFICIARIOS,BOLSA_FAMILIA_REPASSE_MENSAL, R.ID_TIPO_TRANSFERENCIA_RENDA,  PETI_PREVISAO_MENSAL,ACAO_RENDA_META, RENDA_MUNICIPAIS_REPASSE,BOLSA_FAMILIA_ESTIMATIVA_FAMILIAS, BOLSA_FAMILIA_NUMERO_FAMILIAS, 
	PETI_NUMERO_BENEFICIARIOS, MUNICIPAIS_NUMERO_BENEFICIARIOS, BENEFICIARIO_ATENDIDO_REDE_SOCIOASSISTENCIAL, ID_FASE_PROGRAMA_TRANSFERENCIA_RENDA_SP_SOLIDARIO, SP_SOLIDARIO_REPASSE_ANUAL,
	PETI_BENEFICIARIO_TRANSFERENCIA_RENDA, PETI_NUMERO_BENEFICIARIO_BOLSA_FAMILIA, PETI_NUMERO_BENEFICIARIO_PETI_PURO_URBANO, PETI_NUMERO_BENEFICIARIO_PETI_PURO_RURAL,
	PETI_NUMERO_BENEFICIARIO_PROGRAMA_MUNICIPAL, R.VALOR_FMAS,
		R.VALOR_ORCAMENTO_MUNICIPAL,
		R.VALOR_FUNDO_MUNICIPAL,
		R.VALOR_FEAS,
		R.VALOR_ORCAMENTO_ESTADUAL,
		R.VALOR_FUNDO_ESTADUAL,
		R.VALOR_FNAS,
		R.VALOR_FUNDO_FEDERAL,
		R.VALOR_ORCAMENTO_FEDERAL,
		R.VALOR_FNAS,
		R.VALOR_IGD_PBF,
		R.VALOR_IGD_SUAS,
		R.PETI_BENEFICIARIO_BOLSA_FAMILIA,
		R.PETI_BENEFICIARIO_PETI_PURO, 
		R.PETI_BENEFICIARIO_TRANSFERENCIA_RENDA,
		R.NUMERO_BENEFICIARIOS_BPC_NA_ESCOLA,
		R.ADERIU_BPC_NA_ESCOLA,
		R.ATIVO


GO


