USE [Dbpmas_quadrienal_DESENV]
GO

/****** Object:  View [dbo].[VW_RELATORIO_TRANSFERENCIA_RENDA]    Script Date: 12/09/2019 15:22:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[VW_RELATORIO_TRANSFERENCIA_RENDA]
AS
SELECT 
		P.ID AS ID_PREFEITURA,
		MUN.ID AS ID_MUNICIPIO,
		MUN.ID_DRADS,
		MUN.NOME AS MUNICIPIO,
		DRA.NOME AS DRADS,
		COALESCE(MUN.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
		DRA.ID_MACRO_REGIAO,
		P.ID_NIVEL_GESTAO,
		(CASE WHEN P.POPULACAO <= 20000 THEN 1
			WHEN   P.POPULACAO <= 50000 THEN 2
			WHEN   P.POPULACAO <= 100000 THEN 3
			WHEN   P.POPULACAO <= 900000 THEN 4
			ELSE 5
		END) AS ID_PORTE,
		CAST(COALESCE((SELECT SUM(R.ACAO_RENDA_META) FROM TB_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 5),0) AS INT) AS ACAO_JOVEM_META,
		CAST(COALESCE((SELECT SUM(R.PREVISAO_ANUAL_REPASSE) FROM VW_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 5),0)AS MONEY) AS ACAO_JOVEM_REPASSE,
		(CASE WHEN (SELECT TOP 1 R.POSSUI_PARCERIA_FORMAL FROM TB_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 5) > 0 THEN 'Sim' ELSE 'Não' END) AS PARCERIA_ACAO_JOVEM,
		(CASE WHEN (SELECT TOP 1 R.BENEFICIARIO_ATENDIDO_REDE_SOCIOASSISTENCIAL FROM TB_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 5) > 0 THEN 'Sim' ELSE 'Não' END) AS INTEGRACAO_ACAO_JOVEM,
		(SELECT count(*) FROM TB_TRANSFERENCIA_RENDA_PARCERIAS R join tb_transferencia_renda t on t.id = r.id_transferencia_renda WHERE t.ID_PREFEITURA = P.ID AND t.ID_TIPO_TRANSFERENCIA_RENDA = 5) AS TOTAL_PARCERIAS_ACAO_JOVEM,
		(SELECT count(*) FROM TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA R join tb_transferencia_renda t on t.id = r.id_transferencia_renda WHERE t.ID_PREFEITURA = P.ID AND t.ID_TIPO_TRANSFERENCIA_RENDA = 5) AS TOTAL_SERVICOS_ASSOCIADOS_ACAO_JOVEM,
		CAST(COALESCE((SELECT SUM(R.ACAO_RENDA_META) FROM TB_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 6),0) AS INT) AS RENDA_CIDADA_META,
		CAST(COALESCE((SELECT SUM(R.PREVISAO_ANUAL_REPASSE) FROM VW_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 6),0) as MONEY) AS RENDA_CIDADA_REPASSE,
		(CASE WHEN (SELECT TOP 1 R.POSSUI_PARCERIA_FORMAL FROM TB_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 6) > 0 THEN 'Sim' ELSE 'Não' END) AS PARCERIA_RENDA_CIDADA,
		(CASE WHEN (SELECT TOP 1 R.BENEFICIARIO_ATENDIDO_REDE_SOCIOASSISTENCIAL FROM TB_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 6) > 0 THEN 'Sim' ELSE 'Não' END) AS INTEGRACAO_RENDA_CIDADA,
		(SELECT count(*) FROM TB_TRANSFERENCIA_RENDA_PARCERIAS R join tb_transferencia_renda t on t.id = r.id_transferencia_renda WHERE t.ID_PREFEITURA = P.ID AND t.ID_TIPO_TRANSFERENCIA_RENDA = 6) AS TOTAL_PARCERIAS_RENDA_CIDADA,
		(SELECT count(*) FROM TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA R join tb_transferencia_renda t on t.id = r.id_transferencia_renda WHERE t.ID_PREFEITURA = P.ID AND t.ID_TIPO_TRANSFERENCIA_RENDA = 6) AS TOTAL_SERVICOS_ASSOCIADOS_RENDA_CIDADA,
		CAST(COALESCE((SELECT SUM(R.SP_SOLIDARIO_META) FROM TB_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 9),0) AS INT) AS SP_SOLIDARIO_META,
		CAST(COALESCE((SELECT SUM(R.PREVISAO_ANUAL_REPASSE) FROM VW_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 9),0) as MONEY) AS SP_SOLIDARIO_REPASSE,
		(CASE WHEN (SELECT TOP 1 R.POSSUI_PARCERIA_FORMAL FROM TB_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 9) > 0 THEN 'Sim' ELSE 'Não' END) AS PARCERIA_SP_SOLIDARIO,
		(CASE WHEN (SELECT TOP 1 R.BENEFICIARIO_ATENDIDO_REDE_SOCIOASSISTENCIAL FROM TB_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 9) > 0 THEN 'Sim' ELSE 'Não' END) AS INTEGRACAO_SP_SOLIDARIO,
		CAST(COALESCE((SELECT SUM(PA.META_PACTUADA_2018) FROM TB_TRANSFERENCIA_RENDAXPREVISAO_ANUAL PA INNER JOIN TB_TRANSFERENCIA_RENDA R ON PA.ID_TRANSFERENCIA_RENDA = R.ID  WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 1),0)AS BIGINT) AS BPC_IDOSOS_BENEFICIARIOS,
	--	CAST(COALESCE((SELECT SUM(R.BPC_NUMERO_BENEFICIARIOS) FROM TB_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 1),0)AS BIGINT) AS BPC_IDOSOS_BENEFICIARIOS,
		CAST(COALESCE((SELECT SUM(R.PREVISAO_ANUAL_REPASSE) FROM VW_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 1),0)AS MONEY) AS BPC_IDOSOS_REPASSE,
		(CASE WHEN (SELECT TOP 1 R.POSSUI_PARCERIA_FORMAL FROM TB_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 1) > 0 THEN 'Sim' ELSE 'Não' END) AS PARCERIA_BPC_IDOSOS,
		--(CASE WHEN (SELECT TOP 1 R.BENEFICIARIO_ATENDIDO_REDE_SOCIOASSISTENCIAL FROM TB_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 1) > 0 THEN 'Sim' ELSE 'Não' END) AS INTEGRACAO_BPC_IDOSOS,
		(CASE WHEN (SELECT count(*) FROM TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA R join tb_transferencia_renda t on t.id = r.id_transferencia_renda WHERE t.ID_PREFEITURA = P.ID AND t.ID_TIPO_TRANSFERENCIA_RENDA = 1) > 0 THEN 'Sim' ELSE 'Não' END) AS INTEGRACAO_BPC_IDOSOS,
		(SELECT count(*) FROM TB_TRANSFERENCIA_RENDA_PARCERIAS R join tb_transferencia_renda t on t.id = r.id_transferencia_renda WHERE t.ID_PREFEITURA = P.ID AND t.ID_TIPO_TRANSFERENCIA_RENDA = 1) AS TOTAL_PARCERIAS_BPC_IDOSOS,
		(SELECT count(*) FROM TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA R join tb_transferencia_renda t on t.id = r.id_transferencia_renda WHERE t.ID_PREFEITURA = P.ID AND t.ID_TIPO_TRANSFERENCIA_RENDA = 1) AS TOTAL_SERVICOS_ASSOCIADOS_BPC_IDOSOS,
		CAST(COALESCE((SELECT SUM(PA.META_PACTUADA_2018) FROM TB_TRANSFERENCIA_RENDAXPREVISAO_ANUAL PA INNER JOIN TB_TRANSFERENCIA_RENDA R ON PA.ID_TRANSFERENCIA_RENDA = R.ID  WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 2),0)AS BIGINT) AS BPC_PCD_BENEFICIARIOS,
		CAST(COALESCE((SELECT SUM(R.PREVISAO_ANUAL_REPASSE) FROM VW_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 2),0) AS MONEY) AS BPC_PCD_REPASSE,
		(CASE WHEN (SELECT TOP 1 R.POSSUI_PARCERIA_FORMAL FROM TB_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 2) > 0 THEN 'Sim' ELSE 'Não' END) AS PARCERIA_BPC_PCD,
		--(CASE WHEN (SELECT TOP 1 R.BENEFICIARIO_ATENDIDO_REDE_SOCIOASSISTENCIAL FROM TB_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 2) > 0 THEN 'Sim' ELSE 'Não' END) AS INTEGRACAO_BPC_PCD,
		(CASE WHEN (SELECT count(*) FROM TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA R join tb_transferencia_renda t on t.id = r.id_transferencia_renda WHERE t.ID_PREFEITURA = P.ID AND t.ID_TIPO_TRANSFERENCIA_RENDA = 2) > 0 THEN 'Sim' ELSE 'Não' END) AS INTEGRACAO_BPC_PCD,
		(SELECT count(*) FROM TB_TRANSFERENCIA_RENDA_PARCERIAS R join tb_transferencia_renda t on t.id = r.id_transferencia_renda WHERE t.ID_PREFEITURA = P.ID AND t.ID_TIPO_TRANSFERENCIA_RENDA = 2) AS TOTAL_PARCERIAS_BPC_PCD,
		(SELECT count(*) FROM TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA R join tb_transferencia_renda t on t.id = r.id_transferencia_renda WHERE t.ID_PREFEITURA = P.ID AND t.ID_TIPO_TRANSFERENCIA_RENDA = 2) AS TOTAL_SERVICOS_ASSOCIADOS_BPC_PCD,
		CAST(COALESCE((SELECT SUM(R.BOLSA_FAMILIA_ESTIMATIVA_FAMILIAS) FROM TB_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 3),0) AS INT) AS BOLSA_FAMILIA_BENEFICIARIOS,
		CAST(COALESCE((SELECT SUM(R.PREVISAO_ANUAL_REPASSE) FROM VW_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 3),0) AS MONEY) AS BOLSA_FAMILIA_REPASSE,
		(CASE WHEN (SELECT TOP 1 R.POSSUI_PARCERIA_FORMAL FROM TB_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 3) > 0 THEN 'Sim' ELSE 'Não' END) AS PARCERIA_BOLSA_FAMILIA,
		(CASE WHEN (SELECT TOP 1 R.BENEFICIARIO_ATENDIDO_REDE_SOCIOASSISTENCIAL FROM TB_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 3) > 0 THEN 'Sim' ELSE 'Não' END) AS INTEGRACAO_BOLSA_FAMILIA,
		(SELECT count(*) FROM TB_TRANSFERENCIA_RENDA_PARCERIAS R join tb_transferencia_renda t on t.id = r.id_transferencia_renda WHERE t.ID_PREFEITURA = P.ID AND t.ID_TIPO_TRANSFERENCIA_RENDA = 3) AS TOTAL_PARCERIAS_BOLSA_FAMILIA,
		(SELECT count(*) FROM TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA R join tb_transferencia_renda t on t.id = r.id_transferencia_renda WHERE t.ID_PREFEITURA = P.ID AND t.ID_TIPO_TRANSFERENCIA_RENDA = 3) AS TOTAL_SERVICOS_ASSOCIADOS_BOLSA_FAMILIA,
		CAST(COALESCE((SELECT SUM(isnull(R.PETI_NUMERO_BENEFICIARIO_BOLSA_FAMILIA, 0) + isnull(R.PETI_NUMERO_BENEFICIARIO_PETI_PURO_RURAL,0) + isnull(R.PETI_NUMERO_BENEFICIARIO_PETI_PURO_URBANO,0) + isnull(R.PETI_NUMERO_BENEFICIARIO_PROGRAMA_MUNICIPAL,0)) FROM TB_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 4),0) AS INT) AS PETI_BENEFICIARIOS,
		--CAST(COALESCE((SELECT SUM(R.PETI_NUMERO_BENEFICIARIOS) FROM TB_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 4),0) AS INT) AS PETI_BENEFICIARIOS,
		CAST(COALESCE((SELECT SUM(R.PREVISAO_ANUAL_REPASSE) FROM VW_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 4),0) AS MONEY) AS PETI_REPASSE,
		(CASE WHEN (SELECT TOP 1 R.POSSUI_PARCERIA_FORMAL FROM TB_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 4) > 0 THEN 'Sim' ELSE 'Não' END) AS PARCERIA_PETI,
		(CASE WHEN (SELECT TOP 1 R.BENEFICIARIO_ATENDIDO_REDE_SOCIOASSISTENCIAL FROM TB_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 4) > 0 THEN 'Sim' ELSE 'Não' END) AS INTEGRACAO_PETI,
		(SELECT count(*) FROM TB_TRANSFERENCIA_RENDA_PARCERIAS R join tb_transferencia_renda t on t.id = r.id_transferencia_renda WHERE t.ID_PREFEITURA = P.ID AND t.ID_TIPO_TRANSFERENCIA_RENDA = 4) AS TOTAL_PARCERIAS_PETI,
		(SELECT count(*) FROM TB_SERVICO_RECURSO_FINANCEIRO_TRANSFERENCIA_RENDA R join tb_transferencia_renda t on t.id = r.id_transferencia_renda WHERE t.ID_PREFEITURA = P.ID AND t.ID_TIPO_TRANSFERENCIA_RENDA = 4) AS TOTAL_SERVICOS_ASSOCIADOS_PETI,
		CAST(COALESCE((SELECT SUM(isnull(R.META_PACTUADA, 0)) FROM TB_PROGRAMA_PROJETO R WHERE R.ID_PREFEITURA = P.ID AND R.PROGRAMA_ESTADUAL = 1 AND R.NOME like '%Amigo do Idoso%'),0) AS INT) AS RENDA_CIDADA_IDOSO_META,
		CAST(COALESCE((SELECT SUM(isnull(R.META_PACTUADA, 0) * 12 * 100) FROM TB_PROGRAMA_PROJETO R WHERE R.ID_PREFEITURA = P.ID AND R.PROGRAMA_ESTADUAL = 1 AND R.NOME like '%Amigo do Idoso%'),0)AS MONEY) AS RENDA_CIDADA_IDOSO_REPASSE,
		(CASE WHEN (SELECT TOP 1 R.POSSUI_PARCERIA_FORMAL FROM TB_PROGRAMA_PROJETO R WHERE R.ID_PREFEITURA = P.ID AND R.PROGRAMA_ESTADUAL = 1 AND R.NOME like '%Amigo do Idoso%') > 0 THEN 'Sim' ELSE 'Não' END) AS PARCERIA_RENDA_CIDADA_IDOSO,
		(CASE WHEN (SELECT TOP 1 R.BENEFICIARIO_ATENDIDO_REDE_SOCIOASSISTENCIAL FROM TB_PROGRAMA_PROJETO R WHERE R.ID_PREFEITURA = P.ID AND R.PROGRAMA_ESTADUAL = 1 AND R.NOME like '%Amigo do Idoso%') > 0 THEN 'Sim' ELSE 'Não' END) AS INTEGRACAO_RENDA_CIDADA_IDOSO,
		(SELECT count(*) FROM TB_PROGRAMA_PROJETO_PARCERIAS R join tb_programa_projeto t on t.id = r.id_programa_projeto WHERE t.ID_PREFEITURA = P.ID AND t.PROGRAMA_ESTADUAL = 1 AND t.NOME like '%Amigo do Idoso%') AS TOTAL_PARCERIAS_RENDA_CIDADA_IDOSO,
		(SELECT count(*) FROM TB_PROGRAMA_PROJETO_COFINANCIAMENTO R join tb_programa_projeto t on t.id = r.id_programa_projeto WHERE t.ID_PREFEITURA = P.ID AND t.PROGRAMA_ESTADUAL = 1 AND t.NOME like '%Amigo do Idoso%') AS TOTAL_SERVICOS_ASSOCIADOS_RENDA_CIDADA_IDOSO,
		CAST(COALESCE((SELECT SUM(R.MUNICIPAIS_NUMERO_BENEFICIARIOS) FROM TB_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 8),0) AS INT) AS MUNICIPAIS_BENEFICIARIOS,
		CAST(COALESCE((SELECT SUM(R.PREVISAO_ANUAL_REPASSE) FROM VW_TRANSFERENCIA_RENDA R WHERE R.ID_PREFEITURA = P.ID AND R.ID_TIPO_TRANSFERENCIA_RENDA = 8),0) AS MONEY) AS MUNICIPAIS_REPASSE
		FROM TB_PREFEITURA P
		JOIN DBSEDS.DBO.TB_MUNICIPIOS MUN (NOLOCK) ON P.ID_MUNICIPIO = MUN.ID
		JOIN DBSEDS.DBO.TB_DRADS DRA (NOLOCK) ON MUN.ID_DRADS = DRA.ID
GO


