USE [Dbpmas_quadrienal_DESENV]
GO

/****** Object:  Table [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_LA]    Script Date: 19/06/2019 10:18:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_LA')
BEGIN
	CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_LA](
						[ID] [int] IDENTITY(1,1) NOT NULL,
						[ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] [int] NOT NULL,
						[MEDIA_MENSAL_ATENDIMENTO] [int] NULL,
						[PREVISAO_MENSAL_ATENDIMENTO] [int] NULL,
						[EXERCICIO] [int] NULL
	 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_LA] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY] 

	ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_LA]  WITH CHECK 
	ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_LA_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] 
	FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO])
	REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] ([ID])
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_PSC')
BEGIN
	CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_PSC](
						[ID] [int] IDENTITY(1,1) NOT NULL,
						[ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] [int] NOT NULL,
						[MEDIA_MENSAL_ATENDIMENTO] [int] NULL,
						[PREVISAO_MENSAL_ATENDIMENTO] [int] NULL,
						[EXERCICIO] [int] NULL
	 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_PSC] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY] 

	ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_PSC]  WITH CHECK 
	ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_PSC_TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] 
	FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO])
	REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO] ([ID])
END
 
--------------------------------------------
--PREVISAO LA, MEDIA ATENDIDOS LA
--------------------------------------------
IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_LA)
BEGIN
	INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_LA(ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO, PREVISAO_MENSAL_ATENDIMENTO, MEDIA_MENSAL_ATENDIMENTO, EXERCICIO)
	SELECT ID, NUMERO_ATENDIDOS_MENSAL, MEDIA_MENSAL_ATENDIMENTO_2017, 2018
	FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO WHERE ID_USUARIO_TIPO_SERVICO = 22

	INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_LA(ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO, PREVISAO_MENSAL_ATENDIMENTO, MEDIA_MENSAL_ATENDIMENTO, EXERCICIO)
	SELECT ID, NUMERO_ATENDIDOS_MENSAL, MEDIA_MENSAL_ATENDIMENTO_2018, 2019
	FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO WHERE ID_USUARIO_TIPO_SERVICO = 22

	--INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_LA(ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO, PREVISAO_MENSAL_ATENDIMENTO, MEDIA_MENSAL_ATENDIMENTO, EXERCICIO)
	--SELECT ID, NUMERO_ATENDIDOS_MENSAL, MEDIA_MENSAL_ATENDIMENTO_2019, 2019
	--FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO

	--INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_LA(ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO, PREVISAO_MENSAL_ATENDIMENTO, MEDIA_MENSAL_ATENDIMENTO, EXERCICIO)
	--SELECT ID, NUMERO_ATENDIDOS_MENSAL, MEDIA_MENSAL_ATENDIMENTO_2020, 2020
	--FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO
END

--------------------------------------------
--PREVISAO PSC, MEDIA ATENDIDOS PSC
--------------------------------------------
IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_PSC)
BEGIN
	INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_PSC(ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO, PREVISAO_MENSAL_ATENDIMENTO, MEDIA_MENSAL_ATENDIMENTO, EXERCICIO)
	SELECT ID, NUMERO_ATENDIDOS_MENSAL, MEDIA_MENSAL_ATENDIMENTO_PSC_2017, 2018
	FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO WHERE ID_USUARIO_TIPO_SERVICO = 22

	INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_PSC(ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO, PREVISAO_MENSAL_ATENDIMENTO, MEDIA_MENSAL_ATENDIMENTO, EXERCICIO)
	SELECT ID, NUMERO_ATENDIDOS_MENSAL, MEDIA_MENSAL_ATENDIMENTO_PSC_2018, 2019
	FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO WHERE ID_USUARIO_TIPO_SERVICO = 22

	--INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_PSC(ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO, PREVISAO_MENSAL_ATENDIMENTO, MEDIA_MENSAL_ATENDIMENTO, EXERCICIO)
	--SELECT ID, NUMERO_ATENDIDOS_MENSAL, MEDIA_MENSAL_ATENDIMENTO_PSC_2019, 2019
	--FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO

	--INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO_PSC(ID_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO, PREVISAO_MENSAL_ATENDIMENTO, MEDIA_MENSAL_ATENDIMENTO, EXERCICIO)
	--SELECT ID, NUMERO_ATENDIDOS_MENSAL, MEDIA_MENSAL_ATENDIMENTO_PSC_2020, 2020
	--FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PUBLICO
END

