USE [Dbpmas_quadrienal_DESENV]
GO

/****** Object:  Table [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_LA]    Script Date: 19/06/2019 10:18:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_LA')
BEGIN
	CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_LA](
						[ID] [int] IDENTITY(1,1) NOT NULL,
						[ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] [int] NOT NULL,
						[MEDIA_MENSAL_ATENDIMENTO] [int] NULL,
						[PREVISAO_MENSAL_ATENDIMENTO] [int] NULL,
						[EXERCICIO] [int] NULL
	 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_LA] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY] 

	ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_LA]  WITH CHECK 
	ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_LA_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] 
	FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO])
	REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] ([ID])
END

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_PSC')
BEGIN
	CREATE TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_PSC](
						[ID] [int] IDENTITY(1,1) NOT NULL,
						[ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] [int] NOT NULL,
						[MEDIA_MENSAL_ATENDIMENTO] [int] NULL,
						[PREVISAO_MENSAL_ATENDIMENTO] [int] NULL,
						[EXERCICIO] [int] NULL
	 CONSTRAINT [PK_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_PSC] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY] 

	ALTER TABLE [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_PSC]  WITH CHECK 
	ADD  CONSTRAINT [FK_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_PSC_TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] 
	FOREIGN KEY([ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO])
	REFERENCES [dbo].[TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO] ([ID])
END

--------------------------------------------
--PREVISAO LA, MEDIA ATENDIDOS LA
--------------------------------------------
IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_LA)
BEGIN
	INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_LA(ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO, PREVISAO_MENSAL_ATENDIMENTO, MEDIA_MENSAL_ATENDIMENTO, EXERCICIO)
	SELECT ID, NUMERO_ATENDIDOS_MENSAL, MEDIA_MENSAL_ATENDIMENTO_2017, 2018
	FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO WHERE ID_USUARIO_TIPO_SERVICO = 22

	INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_LA(ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO, PREVISAO_MENSAL_ATENDIMENTO, MEDIA_MENSAL_ATENDIMENTO, EXERCICIO)
	SELECT ID, NUMERO_ATENDIDOS_MENSAL, MEDIA_MENSAL_ATENDIMENTO_2018, 2019
	FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO WHERE ID_USUARIO_TIPO_SERVICO = 22

	--INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_LA(ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO, PREVISAO_MENSAL_ATENDIMENTO, MEDIA_MENSAL_ATENDIMENTO, EXERCICIO)
	--SELECT ID, NUMERO_ATENDIDOS_MENSAL, MEDIA_MENSAL_ATENDIMENTO_2019, 2019
	--FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO


	--INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_LA(ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO, PREVISAO_MENSAL_ATENDIMENTO, MEDIA_MENSAL_ATENDIMENTO, EXERCICIO)
	--SELECT ID, NUMERO_ATENDIDOS_MENSAL, MEDIA_MENSAL_ATENDIMENTO_2020, 2020
	--FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO
END

--------------------------------------------
--PREVISAO PSC, MEDIA ATENDIDOS PSC
--------------------------------------------
IF NOT EXISTS(select 1 FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_PSC)
BEGIN
	INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_PSC(ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO, PREVISAO_MENSAL_ATENDIMENTO, MEDIA_MENSAL_ATENDIMENTO, EXERCICIO)
	SELECT ID, NUMERO_ATENDIDOS_MENSAL, MEDIA_MENSAL_ATENDIMENTO_PSC_2017, 2018
	FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO WHERE ID_USUARIO_TIPO_SERVICO = 22

	INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_PSC(ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO, PREVISAO_MENSAL_ATENDIMENTO, MEDIA_MENSAL_ATENDIMENTO, EXERCICIO)
	SELECT ID, NUMERO_ATENDIDOS_MENSAL, MEDIA_MENSAL_ATENDIMENTO_PSC_2018, 2019
	FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO WHERE ID_USUARIO_TIPO_SERVICO = 22

	--INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_PSC(ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO, PREVISAO_MENSAL_ATENDIMENTO, MEDIA_MENSAL_ATENDIMENTO, EXERCICIO)
	--SELECT ID, NUMERO_ATENDIDOS_MENSAL, MEDIA_MENSAL_ATENDIMENTO_PSC_2019, 2019
	--FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO

	--INSERT TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO_PSC(ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO, PREVISAO_MENSAL_ATENDIMENTO, MEDIA_MENSAL_ATENDIMENTO, EXERCICIO)
	--SELECT ID, NUMERO_ATENDIDOS_MENSAL, MEDIA_MENSAL_ATENDIMENTO_PSC_2020, 2020
	--FROM TB_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO
END

