
declare @ID_EXERCICIO INT = 2019

SELECT distinct
			--------------------------------------------------------------
			-- MUNICIPIO
			--------------------------------------------------------------
			P.ID AS ID_PREFEITURA,
			MUN.ID AS ID_MUNICIPIO,
			MUN.ID_DRADS,
			MUN.NOME AS MUNICIPIO,
			DRA.NOME AS DRADS,
			COALESCE(MUN.ID_REGIAO_METROPOLITANA,-1) AS ID_REGIAO_METROPOLITANA,
			DRA.ID_MACRO_REGIAO,
			P.ID_NIVEL_GESTAO,
			--------------------------------------------------------------
			-- PORTE
			--------------------------------------------------------------
			(CASE WHEN P.POPULACAO <= 20000 THEN 1
				WHEN   P.POPULACAO <= 50000 THEN 2
				WHEN   P.POPULACAO <= 100000 THEN 3
				WHEN   P.POPULACAO <= 900000 THEN 4
				ELSE 5
			END) AS ID_PORTE,
			(CASE WHEN P.POPULACAO <= 20000 THEN 'Pequeno I'
				WHEN   P.POPULACAO <= 50000 THEN 'Pequeno II'
				WHEN   P.POPULACAO <= 100000 THEN 'Médio'
				WHEN   P.POPULACAO <= 900000 THEN 'Grande'
				ELSE 'Metrópole'
			END) AS PORTE,
			--------------------------------------------------------------
			-- REDE DIRETA - CENTRO POP
			--------------------------------------------------------------
			'Rede direta' AS TIPO_UNIDADE,
			5 AS ID_TIPO_UNIDADE,
			UP.ID AS CODIGO_UNIDADE,
			ISNULL(C.ID_DISTRITOS_SAO_PAULO,0) AS ID_DISTRITOS_SAO_PAULO,
			DS.NOME AS DISTRITO_SAO_PAULO,
			UP.CNPJ AS CNPJ,
			UP.RAZAO_SOCIAL AS UNIDADE_RESPONSAVEL,
			C.IDCREAS AS ID_LOCAL,
			C.NOME AS LOCAL_EXECUCAO,
			C.CIDADE AS CIDADE,
			U.NOME AS USUARIOS,
			U.ID AS ID_USUARIO_TIPO_SERVICO,
			--------------------------------------------------------------
			-- TIPO SERVICO - REDE DIRETA - CENTRO POP
			--------------------------------------------------------------
			S.NAO_TIPIFICADO,
			(CASE WHEN R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL AND  R.DESCRICAO_NAO_TIPIFICADO <> '' AND TP.ID <> 3 AND S.NAO_TIPIFICADO IS NOT NULL  THEN  'Serviço não tipificado - ' + S.NOME + ' - ' + R.DESCRICAO_NAO_TIPIFICADO 
					WHEN TP.ID = 3 AND R.DESCRICAO_NAO_TIPIFICADO IS NOT NULL THEN 'Serviço não tipificado - ' + R.DESCRICAO_NAO_TIPIFICADO 
					WHEN S.NAO_TIPIFICADO IS NOT NULL THEN 'Servico não tipificado - ' + S.NOME 
					ELSE S.NOME END)  AS TIPO_SERVICO,
			S.ID AS ID_TIPO_SERVICO,

			TP.NOME AS PROTECAO_SOCIAL,
			TP.ID AS ID_TIPO_PROTECAO,
			SX.ID AS ID_SEXO,
			SX.NOME AS SEXO,
			RM.ID AS ID_REGIAO_MORADIA,
			(CASE WHEN RM.ID = 3 THEN 'Zona Urbana e Rural' ELSE RM.NOME END) AS REGIAO_MORADIA,
			CT.ID AS ID_CARACTERISTICAS_TERRITORIO,
			case when CT.ID = 14 then 'Não'
			else CT.NOME End AS CARACTERISTICAS_TERRITORIO,
			--------------------------------------------------------------
			-- VALORES SERVICOS - REDE DIRETA - CENTRO POP
			--------------------------------------------------------------
			ISNULL(R1.VALOR_MUNICIPAL_ASSISTENCIA, 0.0) AS VALOR_FMAS,
			ISNULL(R1.VALOR_MUNICIPAL_FMDCA, 0.0) AS VALOR_FMDCA,
			ISNULL(R1.VALOR_ESTADUAL_ASSISTENCIA, 0.0) AS VALOR_FEAS,
			ISNULL(R1.VALOR_ESTADUAL_ASSISTENCIA_ANO_ANTERIOR, 0.0) AS VALOR_FEAS_ANO_ANTERIOR,
			ISNULL(R1.VALOR_ESTADUAL_FEDCA, 0.0) AS VALOR_FEDCA,
			ISNULL(R1.VALOR_FEDERAL_ASSISTENCIA, 0.0) AS VALOR_FNAS,
			ISNULL(R1.VALOR_FEDERAL_FNDCA, 0.0) AS VALOR_FNDCA,
			ISNULL(R1.VALOR_MUNICIPAL_FMI, 0.0) AS VALOR_FMI,
			ISNULL(R1.VALOR_ESTADUAL_FEI, 0.0) AS VALOR_FEI,
			ISNULL(R1.VALOR_FEDERAL_FNI, 0.0) AS VALOR_FNI,
			0.0 AS VALOR_PRIVADO,
			COALESCE((SELECT SUM(FR.[VALOR_FONTE_RECURSO])
					  FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_FONTE_RECURSOS AS FR
					  WHERE ( FR.ID_SERVICO_RECURSO_FINANCEIRO_FUNDO_CENTRO_POP = R1.ID )), 0.0) AS VALOR_FONTE_RECURSO,
			COALESCE(R3.VALOR_ESTADUALIZADO,0) AS VALOR_ESTADUALIZADO,

			A.ABREVIACAO AS ABRANGENCIA,
			A.ID AS ID_ABRANGENCIA,
			ISNULL(CONVERT(CHAR(10), R.DATA_FUNCIONAMENTO_SERVICO,103),'') AS DATA_FUNCIONAMENTO_SERVICO,
			
			CASE WHEN R2.ID_MOTIVO_DESATIVACAO = 1 THEN ISNULL(CONVERT(CHAR(16), R2.DATA_EXCLUSAO_SERVICO,103),'Em Funcionamento')
			WHEN R2.ID_MOTIVO_DESATIVACAO = 2 THEN ISNULL(CONVERT(CHAR(16),R2.DATA_ENCERRAMENTO_SERVICO,103),'Em Funcionamento')
			WHEN R2.ID_MOTIVO_DESATIVACAO = 3 THEN ISNULL(CONVERT(CHAR(16), R2.DATA_ENCERRAMENTO_SERVICO,103),'Em Funcionamento') 
			WHEN (R2.ID_MOTIVO_DESATIVACAO is NULL OR R2.ID_MOTIVO_DESATIVACAO = 0) THEN 'Em Funcionamento' END AS DATA_DESATIVACAO,

			--------------------------------------------------------------
			-- NUMERO ATENDIDOS - REDE DIRETA - CENTRO POP
			--------------------------------------------------------------
			COALESCE((R.NUMERO_ATENDIDOS_MENSAL), 0) AS NUMERO_ATENDIDOS_MENSAL, 
			0 AS NUMERO_ATENDIDOS_SERVICO_MENSAL,
			COALESCE((R.NUMERO_ATENDIDOS), 0) AS  NUMERO_ATENDIDOS_ANUAL, 
			0 AS  NUMERO_ATENDIDOS_SERVICO_ANUAL,
			R.TOTAL_FUNCIONARIOS AS TOTAL_TRABALHADORES_SERVICO,
			COALESCE((RH.NIVEL_FUNDAMENTAL + RH.NIVEL_MEDIO + RH.NIVEL_SUPERIOR + RH.SEM_ESCOLARIZACAO),0) AS TOTAL_TRABALHADORES,
			--------------------------------------------------------------
			-- MEDIA ATENDIDOS - REDE DIRETA - CENTRO POP
			--------------------------------------------------------------
			COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2017, 0) AS MEDIA_MENSAL_ATENDIMENTO_2017,
			COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2018, 0) AS MEDIA_MENSAL_ATENDIMENTO_2018,
			COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2019, 0) AS MEDIA_MENSAL_ATENDIMENTO_2019,
			COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_2020, 0) AS MEDIA_MENSAL_ATENDIMENTO_2020,
			COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2017, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2017,
			COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2018, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2018,
			COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2019, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2019,
			COALESCE(R.MEDIA_MENSAL_ATENDIMENTO_PSC_2020, 0) AS MEDIA_MENSAL_ATENDIMENTO_PSC_2020,
			R1.EXERCICIO
			, RH.NIVEL_FUNDAMENTAL
			, RH.NIVEL_MEDIO
			, RH.NIVEL_SUPERIOR
			,RH.SEM_ESCOLARIZACAO
			, RH.ID AS RH
			, RH.ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP
		FROM TB_PREFEITURA P
		JOIN DBSEDS.DBO.TB_MUNICIPIOS MUN (NOLOCK) ON P.ID_MUNICIPIO = MUN.ID
		JOIN DBSEDS.DBO.TB_DRADS DRA (NOLOCK) ON MUN.ID_DRADS = DRA.ID
		INNER JOIN TB_UNIDADE_PUBLICA UP ON(UP.ID_PREFEITURA = P.ID)
		INNER JOIN TB_CENTRO_POP C ON(C.ID_UNIDADE_PUBLICA = UP.ID)
		INNER JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP R ON(R.ID_CENTRO_POP = C.ID)
		LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_RH RH on (RH.ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP = R.ID )


		INNER JOIN TB_ABRANGENCIA_SERVICO A ON(R.ID_ABRANGENCIA_SERVICO = A.ID)
		INNER JOIN TB_USUARIO_TIPO_SERVICO U ON (R.ID_USUARIO_TIPO_SERVICO = U.ID)
		INNER JOIN TB_TIPO_SERVICO S ON (U.ID_TIPO_SERVICO = S.ID)

		INNER JOIN TB_TIPO_PROTECAO TP ON(TP.ID = S.ID_TIPO_PROTECAO)

		--INNER JOIN VW_SERVICOS_RECURSOS_FINANCEIROS_CRAS R2       ON (R2.ID_CRAS = C.ID       and R2.ID_TIPO_SERVICO = S.ID and R2.ID_USUARIO_TIPO_SERVICO = U.ID AND R2.EXERCICIO = @ID_EXERCICIO) 
		INNER JOIN VW_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP R2 ON (R2.ID_CENTRO_POP = C.ID and R2.ID_USUARIO_TIPO_SERVICO = U.ID and R2.ID_TIPO_SERVICO = S.ID AND R2.EXERCICIO = @ID_EXERCICIO)

		INNER JOIN TB_SEXO SX ON(SX.ID = R.ID_SEXO)
		INNER JOIN TB_REGIAO_MORADIA RM ON(RM.ID = R.ID_REGIAO_MORADIA)
		INNER JOIN TB_CARACTERISTICAS_TERRITORIO CT ON(CT.ID = R.ID_CARACTERISTICAS_TERRITORIO)
		LEFT JOIN TB_DISTRITOS_SAO_PAULO DS ON (DS.ID = C.ID_DISTRITOS_SAO_PAULO)

		INNER JOIN TB_UNIDADE_PUBLICA UN (NOLOCK) ON(UN.ID_PREFEITURA = P.ID)
		LEFT JOIN TB_LOCAL_EXECUCAO_PUBLICO L ON(L.ID_UNIDADE_PUBLICA = UN.ID)
		LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_CENTRO_POP R1 (NOLOCK)
			ON (R1.ID_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP = R.ID AND R1.EXERCICIO = @ID_EXERCICIO) 
		LEFT JOIN TB_SERVICOS_RECURSOS_FINANCEIROS_FUNDOS_PRIVADO R3 
			ON (R3.ID_SERVICOS_RECURSOS_FINANCEIROS_PRIVADO = L.ID  AND R3.EXERCICIO = @ID_EXERCICIO) 
WHERE P.ID = (select id from TB_PREFEITURA where cidade like '%catand%')
AND RH.NIVEL_FUNDAMENTAL = 1
AND RH.NIVEL_MEDIO = 2
AND RH.NIVEL_SUPERIOR = 2
AND RH.SEM_ESCOLARIZACAO = 0

 

 --update TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_RH set NIVEL_SUPERIOR = 2 where id = 101

 --DELETE FROM TB_SERVICOS_RECURSOS_FINANCEIROS_CENTRO_POP_RH WHERE ID IN (557, 612, 496, 497)

 



--ERRADO 497 (9)
	--MEDIA_MENSAL_ATENDIMENTO_2017:  263
	--MEDIA_MENSAL_ATENDIMENTO_2018 : 265
--558
	--MEDIA_MENSAL_ATENDIMENTO_2017:  263
	--MEDIA_MENSAL_ATENDIMENTO_2018 : 265
--613
	--MEDIA_MENSAL_ATENDIMENTO_2017:  263
	--MEDIA_MENSAL_ATENDIMENTO_2018 : 265
--654
	--MEDIA_MENSAL_ATENDIMENTO_2017:  263
	--MEDIA_MENSAL_ATENDIMENTO_2018 : 265
	-- Total trabalhadores 8



-- 496 
	--MEDIA_MENSAL_ATENDIMENTO_2017: 80
	--MEDIA_MENSAL_ATENDIMENTO_2018: 75
-- 557
	--MEDIA_MENSAL_ATENDIMENTO_2017: 80
	--MEDIA_MENSAL_ATENDIMENTO_2018: 75
-- 612
	--MEDIA_MENSAL_ATENDIMENTO_2017: 80
	--MEDIA_MENSAL_ATENDIMENTO_2018: 75
