USE [DBSEDS]
GO

UPDATE [dbo].[TB_MUNICIPIO_INDICADORES]
   SET 
      [AREA_TERRITORIAL_EM_KM_QUADRADO] = 
      ,[POPULACAO_NUM_HAB_2010] = 
	  ,[TOTAL_FAMILIAS_2010] = 
	  ,[DENSIDADE_DEMOGRAFICA_2010] = 
	  ,[GRAU_URBANIZACAO_PERC_2010] = 
	  ,[TOTAL_DOMICILIOS_SANEAMENTO_ADEQUADO_PERC_2010] = 
	  ,[TOTAL_PESSOAS_ABAIXO_15_ANOS_PERC_2010] = 
	  ,[TOTAL_IDOSOS_PERC_2010] = 
	  ,[TOTAL_MAES_ADOLESCENTES_PERC_2009] = 
	  ,[RENDIMENTO_MENSAL_DOMICILIAR_PER_CAPITA_ATE_70_PERC_2010] = 
 WHERE [ID_MUNICIPIO] = (select top 1 ID from [DBSEDS].[dbo].[TB_MUNICIPIOS] where NOME like )
GO

